### ISSUE TITLE
create release tags

### ISSUE THREAD

**Issue by mes5k** [fritzsedlazeck/Sniffles#1]
Hi, can you create a release tag for Sniffles?  I'd just like this for reproducibility as my users seem quite enamored with your software!

**Comment by fritzsedlazeck** [comment]
Sure. Keep in mind I have already benchmarked it over several data sets. However, I haven't benchmarked it to full extend. So please let me know if there is anything you need or recommend. 
Thank you
Fritz

**Comment by mes5k** [comment]
Cool thanks.  We understand that the software is still young and likely to change, which is why we want to be careful with which version we're using.  We'll definitely let you know if we run into any problems.  Thanks!

**Comment by fritzsedlazeck** [comment]
Release tag has been created.
