### ISSUE TITLE
Genotyping among samples

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/Sniffles#101]
Hi Fritz,

Do you plan to implement function to perform genotyping among samples?  To get missing genotypes and matches to the reference?  The way svtools does for paralel lumpy calls. Like svtools (lsort, lmerge and genotype pipeline)?

Best Regards,
Mehmet

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
There is a pipeline for this. First call SVs with sniffles for each sample. Second merge the calls with survivor merge . Third put the merged file as extra input for each sample for sniffles (--Ivcf) . Fourth merge the results again to get a fully genotyped multisample VCf.

I think that is what you want. Let me know if you have problems. I can describe it a bit more.

Also feel free to check out the wiki:
https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population


Cheers
Fritz

**Comment by MehmetGoktay** [comment]
Hi Fritz,

I didnt not know about that. Thank you very much for your detailed answer. 

Best,
Mehmet

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
yeah its a bit hidden :). 
Thanks
Fritz

**Comment by wangjiawen2013** [comment]
I notice that "This will generate one VCF file for all the samples, but we lack the information if a SV identified in one sample but not in the other is really absent". refer to this link: https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population
But what cause the missing genotypes and why the information is lack of ?
@fritzsedlazeck

**Comment by fritzsedlazeck** [comment]
In the initial calling you might have regions that are too noisy or too low on coverage to make a call.
Thus, they are ignored. The same is true for every SNP caller.. .

When you obtain additional information that there might be a variant on another sample, you want to make sure there is or isnt.
Then a genotyping is necessary to dig back into that location to see if there is any evidence. 
I hope that helps
Fritz
