### ISSUE TITLE
SVLEN calculation for translocations (SVTYPE=TRA)

### ISSUE THREAD

**Issue by biojiangke** [fritzsedlazeck/Sniffles#104]
I wonder how the SVLEN for SVTYPE=TRA is calculated. Could I leverage this value for filtering out some false positives?

**Comment by fritzsedlazeck** [comment]
Hi,
The length for translocations are not defined as the connect locations across two chromosomes. Therefore, they have a fixed value.
Thanks
Fritz

**Comment by biojiangke** [comment]
Then where do the values come from? Sizes of chromosomes involved? I've seen large and negative values, looks like some kind of combinations of chromosome sizes?

**Comment by fritzsedlazeck** [comment]
You have seen negative values ? Can you post what   you did ?
Thanks 
Fritz

**Comment by biojiangke** [comment]
Nanpore 4~5k reads from a WGS experiment, with about 100G data towards an average coverage of 20X to 30X. Aligned with NGMLR using the following command:

ngmlr -t 4 -r ref -q input.fastq -o out.sam -x ont

converted to bam and sorted, then ran sniffles as following:

sniffles -m sorted.bam -v variants.vcf

There are TRA calls like these:

CHR1 POS1 CHR2 POS2 SVLEN
1	6042691	27	END=6219480	SVLEN=-1948029593

The SVLEN is negative and way bigger than the sum of chr1 and chr27 sizes.

**Comment by fritzsedlazeck** [comment]
Is it a very large genome ? For me this sounds like a conversion error. Since it is negative. I will have a look tomorrow.
Thanks for reaching out 
Fritz

**Comment by wdecoster** [comment]
If it's 100G data with an average coverage of 20-30x then it looks like human-size.

**Comment by fritzsedlazeck** [comment]
But chr27?

**Comment by biojiangke** [comment]
It is Bovine, the genome size is about 2.6Gbp.

**Comment by fritzsedlazeck** [comment]
Can you maybe share the bam and VCf file ? My email is fritz.sedlazeck@gmail.com
Thanks
Fritz

**Comment by biojiangke** [comment]
The BAM is huge, is it OK to take a slice? But that may not reflect the called SVs in the VCF. Maybe a slice of BAM around one called TRA with negative SVLEN? Could you briefly explain how the SVLEN was calculated (guess might be related to chromosome sizes involved in this particular translocation?)? It seems I couldn't find this part from the Sniffles paper.

**Comment by fritzsedlazeck** [comment]
So for TRA there is no estimation of SVlen. there is an internal indicator that these are TRA and the length is not determined but set. So what I think happens here is some conversion or so between one data type to another. Can you maybe send me the VCF and if it is not too much work extract the reads around the breakpoints?

Thanks
Fritz

**Comment by biojiangke** [comment]
Length is set according to what information? All I'd like to know is whether SVLEN contains any useful information for filtering. For example, if the value is way off the chart (for some it is, much larger than any two/three chromosome combined, could be as large as half of the genome), does it mean this could more likely to be a false positive? 

I'll send the VCF and sliced BAM around the first TRA with negative length. I'll send more if needed. 

Thanks!

**Comment by fritzsedlazeck** [comment]
It does not contain any useful information. 

Thanks for the help.
Fritz

**Comment by fritzsedlazeck** [comment]
Ok that is totally my fault I was confused with unresolved INS, where I do report a fix number for SVLen. 

RA need to have a SVLen, however it does not mean anything. It is the distance between the two points, but including some padding stretch. 

To avoid these confusions I can try to set it to 0 and we can check it out if that causes problems for subsequent programs. The - also makes sense now since sometimes these coordinates can be flipped inside of Sniffles.

**Comment by biojiangke** [comment]
Great! I think zero would make sense, as there would be no reasonable distance across two chromosomes. Thanks for taking care of it.

**Comment by fritzsedlazeck** [comment]
Code is pushed. Please give it a try. I have to run now, but I will check it later. I only tested it on one simulated sample consisting of only TRA events. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Did you had a chance to test the new mode? No pressure just checking in :). 
Thanks
Fritz

**Comment by biojiangke** [comment]
It's working fine with a small sample test. All SVLEN values for SVTYPE=TRA are zeros.

**Comment by fritzsedlazeck** [comment]
Great thanks for reporting in. 
I am thus closing this issue. Please feel free to reach out if you have any additional questions. 
Cheers
Fritz
