### ISSUE TITLE
SVLEN for deletions should be negative

### ISSUE THREAD

**Issue by wdecoster** [fritzsedlazeck/Sniffles#105]
Hi Fritz,

As we discussed via email, according to the vcf specifications (https://samtools.github.io/hts-specs/VCFv4.3.pdf) SVLEN of deletions should be negative:

> Longer ALT alleles (e.g.  insertions) have positive values, shorter ALT alleles (e.g.
deletions) have negative values.

Cheers,
Wouter

**Comment by fritzsedlazeck** [comment]
Thanks for reporting this. I made the changes to the code. 
Cheers
Fritz
