### ISSUE TITLE
RNAMES INFO description

### ISSUE THREAD

**Issue by jts** [fritzsedlazeck/Sniffles#109]
Hi Fritz,

The VCF header INFO line for RNAMES is:

```
##INFO=<ID=RNAMES,Number=1,Type=String,Description="Names of reads supporting SVs (comma separated)">
```

should this be `Number=.` since you produce a comma-separated list of unknown length? Currently pyvcf fails to parse the full list and only returns the first entry.

Jared

**Comment by fritzsedlazeck** [comment]
Hi Jared,
thanks. I just pushed the change. These VCF header declarations are somehow tricky for me...
Cheers
Fritz

**Comment by jts** [comment]
Thanks!
