### ISSUE TITLE
No precise variant

### ISSUE THREAD

**Issue by haghshenas** [fritzsedlazeck/Sniffles#11]
Hello,

I tested Sniffles on a small sample. I used NGM-LR for mapping pacbio long reads to the reference.
Sinffles reports about 13,000 variants, but they are all imprecise.
Is this expected? Any chance that I get precise calls by changing parameters of the mapper or Sniffles?

**Comment by fritzsedlazeck** [comment]
Hi,
yes currently this is not set -> set to be imprecise following the standard. Nevertheless, the breakpoints are most often (~80%) precise depending on sequence composition (e.g. repeats). I am currently working on a method to estimate this.
I should have an improved version uploaded by tomorrow or Wednesday. 
Best

**Comment by fritzsedlazeck** [comment]
Hi,
I just put up the new release that also sets the precise/imprecise tag based on the consensus of the breakpoints of the variants. You can also see in the vcf output that I put in flags (STD_quant_start,STD_quant_stop) for the start and stop breakpoint accuracy.
Best
Fritz
