### ISSUE TITLE
--report_seq process for generating INS and DEL sequences

### ISSUE THREAD

**Issue by gbdias** [fritzsedlazeck/Sniffles#111]
Hi Fritz,

I want to do some further characterization on the Indel sequences reported by Sniffles and was wondering how are those generated. I am assuming they are a consensus of the supporting reads right? Could you give more info on that?

Thanks,
Guilherme

**Comment by fritzsedlazeck** [comment]
Hi Guilerme,
Right now they are a raw sequence from a read that best agrees with the break points.
We do have crosstich that can perform a local assembly of these variants. It uses sniffles with -n -1 parameter.

I hope that helps
Fritz

**Comment by gbdias** [comment]
Thanks for the info Fritz!
I will give CrossStitch a try and see how results compare.

Best,
Guilherme
