### ISSUE TITLE
Bug report. Tag <TRA> missed.

### ISSUE THREAD

**Issue by tjiangHIT** [fritzsedlazeck/Sniffles#112]
hi,
I run sniffles with Arabidopsis trio datasets (download from your readme). I got a .vcf like this:
**_4       13306615        10572   N       ]5:26415600]N   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.10;ZMW=19;STD_quant_start=0.000000;STD_quant_stop=0.316228;Kurtosis_quant_start=1.825507;Kurtosis_quant_stop=-1.244389;SVTYPE=BND;SUPTYPE=SR;SVLEN=0;STRANDS=--;RE=19;REF_strand=0,0;AF=1 GT:DR:DV        1/1:0:19_**

It seems like a translocation, however, with a error tag **_]5:26415600]N_**.

**Comment by fritzsedlazeck** [comment]
That is the new specification from vcf to report it like this. 
You can switch to the old representation with a parameter called something like no BND.
Sorry I am not at my laptop right now.
Cheers
Fritz
