### ISSUE TITLE
Insertions from reads with >2 alignment segments

### ISSUE THREAD

**Issue by eldariont** [fritzsedlazeck/Sniffles#114]
Hi Fritz,

I have a short question, just to make sure that I understand the Supplementary (Section 2.2.2) of the paper correctly: Does Sniffles detect insertions indicated by reads with more than two alignment segments?

Let's say we have a read spanning an Alu insertion that is not present in the reference. Then segment 1 will map left of the insertion location, segment 3 will map right of it and segment 2 might map at another location in the genome with a similar Alu element. Would Sniffles pick that up (the insertion between segment 1 and 3) or would it look only for nested SVs?

Cheers
David

**Comment by fritzsedlazeck** [comment]
Hi David,

It should be able to pick that up. We account for that if a read is supporting multiple variants close to each other.
The nested/adjecent procedure is a bit of a special case because for sniffles it looks almost like 2 breakpoints on top of each other in the same read. Thus, required a special treatment.

I hope that helps

Cheers
Fritz

**Comment by eldariont** [comment]
Thanks Fritz for your quick reply,

I'm not sure whether the scenario that I had in mind is really a nested event. Actually it's just a single retrotransposon-like insertion. I observed that Sniffles struggles to pick these up in my data.

If you like you can have a look at this bam file: https://www.dropbox.com/s/nlyjgnt8nmwomka/simulated.ngmlr.hg19.coordsorted.bam
The reads contain an 850bp insertion at chr21:46,920,354 that stems from chr22. Sniffles picks up TRA events at this position but not the insertion indicated by the reads. It would be interesting to know why if you have time to have a quick look.

Cheers
David

**Comment by fritzsedlazeck** [comment]
Ah sorry I see what you are after. Yes that is a TRA signal or a DEL/INV if the other alu is on the same chr. 
TRA indicate a connecton of a segment from a different CHR. An INS would be a complete novel sequence or e.g. a repeat extention. 

I can have a look at the bam if you like. 

Thanks and sorry for the misunderstanding. I am replying sometimes right in the morning and I seem to sometimes overread things....
Thanks
Fritz

**Comment by eldariont** [comment]
No problem at all, Fritz. Thanks for looking at it again. So it is intended to classify such an event as a TRA and not an INS. This answers my question then and there is no need to further look at the bam file.

Thanks
David
