### ISSUE TITLE
Conda package update

### ISSUE THREAD

**Issue by mpabloperez** [fritzsedlazeck/Sniffles#117]
Hi there, 

Could you please update the conda package? Thank you in advance. I need some of the features included after version 1.0.8.

Best regards,
Pablo

**Comment by fritzsedlazeck** [comment]
As far as I know the conda package should be on v10. Isnt it?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Yeah I just checked over: conda install sniffles you get sniffles:  1.0.10-hd4ff3c4_0     bioconda
I hope that helps.
Fritz
