### ISSUE TITLE
Erroneous genotype call for an insertion

### ISSUE THREAD

**Issue by AyushSaxena** [fritzsedlazeck/Sniffles#123]
I have used NGMLR mapped bam files for SV calling using Sniffles (1.0.8) using the following script -
f=MA530_230211.ngmlr.sorted.bam
sniffles \
 -s 3 \
 --max_num_splits 7 \
 --threads 16 \
 --min_length 15 \
 --minmapping_qual 20 \
 --num_reads_report 5 \
 --genotype \
 -m $f -v ${f/.sorted.bam/.vcf}

I find a homozygous variant call, which had minimal 3 read support. I'm copying the vcf information of that variant.
tig00000003     2411768 305     N       <INS>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=tig00000003;END=2411856;ZMW=3;STD_quant_start=49.913258;STD_quant_stop=32.746501;Kurtosis_quant_start=-1.117132;Kurtosis_quant_stop=-0.147269;SVTYPE=INS;RNAMES=m54030_171212_175405/24052391/0_7931,m54030_171212_175405/32178549/0_15011,m54030_171212_175405/43451226/10394_14277;SUPTYPE=AL;SVLEN=97;STRANDS=+-;RE=3;AF=1    GT:DR:DV        1/1:0:3

When I zoomed in the region with IGV, I found only one read supporting an insertion (highlighted in the image), while the other 2 reads listed in the vcf file did not have an insertion at the site (I didn't find a purple I in the region of the read). Also, as you can see in the snapshot, there are at least 30 or so reads in the region.  I would intuitively think that those reads should be counted when calculating allele frequencies.  These are the putative false positives that I am trying to remove from my analysis.  Is this a bug, or am I misinterpreting the variant call.

In the selected read, the 97 base-pair insertion can be seen.  The variant I'm referencing to is in red.

![igv_putative_false_insertion](https://user-images.githubusercontent.com/12516584/52287349-f4e37c00-2937-11e9-976f-1ff5120742c4.PNG)

**Comment by AyushSaxena** [comment]
Hi,

Thank you for your quick response.  I'm attaching the bam file of the surrounding (~50kb) region.  The variant of interest starts at 2411768 on contig "tig00000003".

1. I realize that I'm using a low value for the '-s' option.  My objective is to compare Structural Variant counts across different genotypes who happen to have different coverage.  Reducing minimum read support levels the playing field.  I'm not sure if Sniffles calls too many false positives in this range.  Is there a recommended range?

2.  The mapping quality of the other reads in the region look healthy (~50).  Does Sniffles call a read noise on the basis of mapping quality or number of mismatches?

3. This makes a lot of sense.  The other variants in the region are at low frequency (perhaps false positives, or low frequency heterozygous; the library was made from a genetically identical population of C.elegans).  If I were to exclude those other variants from my analysis by using an allele frequency filter, would the reads originally supporting those variants in the region be now called reference?  There is a low frequency ~900 bp Insertion (2411756) called in the same region (1 read supporting it).  That variant was processed 'right' by Sniffles with AF=0.05. It's only 10 or base-pairs away from the call I first reported.  Is there a way to re-calculate allele frequencies by counting that read (with the ~900bp Insertion) in favour of reference?  In other words, can we calculate allele frequencies using 'impure' reference supporting reads that support the reference in the region in question?

Lastly, the assembly was done using Canu with ~100x PacBio data.  I haven't polished it with Arrow, or Pilon yet (I have Illumina data as well).  Do you recommend, or find it necessary, for structural variant calling (I'm not interested in calling SNPs/small indels)?  I had assumed that an unpolished assembly would do just fine for large structural variant calling.

[MA530_230211.ngmlr.subset.sorted.zip](https://github.com/fritzsedlazeck/Sniffles/files/2833060/MA530_230211.ngmlr.subset.sorted.zip)

**Comment by fritzsedlazeck** [comment]
Hi,
ad 1) what seems to work well is about 1/3 of your input coverage. s 3 is kind of the lowest I would ever go. 

ad 2) Yes Sniffles takes the MQ into account. However, the filtering is more based on the average identity of reads and how frequent errors occur next to each other.

ad 3) Yeah not really. Sniffles always assesses a read in terms of supporting any variant or being too noisy. If either is the case it is not counted as reference. I realize recently that this is a disadvantage but back then I was very strickt with these things... 


Ad assembly: Yes . This could impact your frequency / GT estimation because of the above . Right now every read that is considered to be too noisy will be ignored. Meaning that even smaller errors could probably add up. However, I have not had much of experiments were I could assess the impact of non polished assembly. 

For your project you want to polish that thing anyway at some point. So I would rather do it now and check again. 

Thanks
Fritz

**Comment by AyushSaxena** [comment]
Dear Fritz,

Thank you for your response.  I should polish my assembly first now because I had overlooked noisy reads.

Ayush

**Comment by fritzsedlazeck** [comment]
Sniffles has a MQ filter build in. By default it ignores reads that have MQ<20.
Is this your question?
Cheers
Fritz

**Comment by biomichal** [comment]
Yes, it is convenient if filter the low quality alignment automatically. I planned to filter from SAM file. 

Thanks a lot. 
Meng

**Comment by fritzsedlazeck** [comment]
I try to make my customers happy :)
