### ISSUE TITLE
max_diff_per_window

### ISSUE THREAD

**Issue by JohnUrban** [fritzsedlazeck/Sniffles#124]
Hi,

Sniffles is great. I'm messing around with parameters at the moment.

I was hoping to get a better idea of what `max_diff_per_window` does.

The description is:
`Maximum differences per 100bp.`

What is Sniffles doing with this?
What happens if there are more or fewer differences found than the given int (e.g. default of 50)?
What does the word "difference" mean in this context?

Many thanks!

John

**Comment by fritzsedlazeck** [comment]
Hi John.
thanks. 
This parameter is used to estimate if there are "too noisy" regions in the alignments that potentially mask SVs. That was needed eg. for BWA mem alignments. 
Cheers
Fritz
