### ISSUE TITLE
how to built a new genome based on the SV result?

### ISSUE THREAD

**Issue by yplee614** [fritzsedlazeck/Sniffles#127]
how to built a new genome based on the SV result? now, i got a vcf file

**Comment by fritzsedlazeck** [comment]
You can check out crosstich.

**Comment by yplee614** [comment]
thanks, but my organism is not human, it is a plant species, so how can i get a consensus sequence?

**Comment by fritzsedlazeck** [comment]
Doesn't matter. Go and look at the tool.

**Comment by yplee614** [comment]
The corssstitch.sh only supported for human, and i without phased_snps.vcf file
![image](https://user-images.githubusercontent.com/9695765/53315020-3abeaf00-38fc-11e9-8f6d-95029021a4d1.png)

**Comment by yplee614** [comment]
And crossStitch need to defined the gender.

**Comment by fritzsedlazeck** [comment]
The gender is just for the sex chromosomes, but yeah I forgot about that part. It's the only tool that I know that converts a list of SVs to a sequence.

**Comment by yplee614** [comment]
Can you add a script to sniffles which can do it?

**Comment by fritzsedlazeck** [comment]
Sorry that is not so trivial to do. That is why we developed crosstich..

**Comment by yplee614** [comment]
How can i get consensus sequence by crossitch?

**Comment by fritzsedlazeck** [comment]
mhm without phased snps I dont know. I would go ahead and post on their github to seek help. 
This is outside of what Sniffles is meant to be.

**Comment by yplee614** [comment]
Thanks.
