### ISSUE TITLE
Detecting SV in a whole genome with enriched regions

### ISSUE THREAD

**Issue by fanavarro** [fritzsedlazeck/Sniffles#129]
Hello,

Our group is interested in structural variations affecting a concrete gene, and we found very promising the use of long reads that Oxford Nanopore Technology can obtain. We have performed some experiments sequencing the whole patient genome, and we got long reads, but the coverage was poor. Our laboratory colleagues are treating to solve this coverage problem by enriching the gene in which we are interested. This provokes a great coverage on this gene, but a lack of reads on other regions. We have used minimap2 to map the obtained reads to the whole reference genome and then, Sniffles to detect structural variants. We are wondering if the irregular distribution of reads along the genome would affect the accuracy of Sniffles. In that case, is it possible to establish a concrete genome region to analyze?

I'm attaching a figure in order to illustrate our case, in which you can see that many reads cover SERPINC1 gene, while other regions do not have coverage:

![imagen](https://user-images.githubusercontent.com/11376639/53640460-8a6ae680-3c2c-11e9-990b-0a4dc9d15575.png)

Thanks for your time. Regards,
Fran.

**Comment by fritzsedlazeck** [comment]
Dear Fran,
that should not be a problem. We have already analyzed capture sequencing data sets using Sniffles over ONT and Pacbio. So it should work fine.
For the 2nd question about filtering / focusing option in Sniffles: This is currently is not supported. However, you can easily filter (e.g. bedtools) the vcf from Sniffles or filter the bam file before Snifles (e.g. samtools view).
I hope that helps. 
Cheers
Fritz

**Comment by fanavarro** [comment]
Thanks for your answer @fritzsedlazeck, I'll filter it before sniffles.

Regards,
Fran
