### ISSUE TITLE
STD_quant_start  and STD_quant_stop

### ISSUE THREAD

**Issue by bluesea2017** [fritzsedlazeck/Sniffles#13]
Hi,
 First, how much value of STD_quant_start  and STD_quant_stop is precise and how much value of    STD_quant_start  and STD_quant_stop is imprecise.
 Second: use bam(ngm-lr) to caculate depth(samtools),depth is very low,less than 2x, raw data 60x, how difference the pacbio bam and the illumina bam?how do you caculate depth?
Thanks.

**Comment by fritzsedlazeck** [comment]
Hi,
ad 1: right now it is defined as that both start and stop has to be below 10. 

ad 2: Can you compute the number of mapped reads? (samtools view -c -F0x004 mapped.bam)
Samtools depth gives you a coverage per position. I guess you used that for the average mapped coverage?
Furthermore, I don't know if samtools depth takes the secondary alignments into account. There are some posts online that discuss this. As you know we report split reads and only on part of the splits should be a primary alignment. (BWA-MEM does not do that by default, but marks them only by using -M.)

Thanks
Fritz
