### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by biomichal** [fritzsedlazeck/Sniffles#130]

**Comment by biomichal** [comment]
Dear Fritz,
When I am running Sniffles to call SV, I find a lot of false positives. One type is as the following image: 

The VCF information is: 

chr10	5321168	11069_2	N	<DEL>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr10;END=5322496;STD_quant_start=3.464102;STD_quant_stop=2.886751;Kurtosis_quant_start=0.000000;Kurtosis_quant_stop=-1.382400;SVTYPE=DEL;RNAMES=1082168;SUPTYPE=SR;SVLEN=-1328;STRANDS=+-;STRANDS2=3,0,3,0;RE=3;REF_strand=3,3;AF=0.333333	GT:DR:DV	0/1:6:3

Obvisouy, the SV (a deletion) region (in the red rectangle) is a mistake. This region have a lower depth compared to its flanking regions. This is because of the a repeat region in the flanking region, but not a deletion which caused the lower depth.

![2019-03-07_134954](https://user-images.githubusercontent.com/5409656/53935059-f8595700-40df-11e9-91c9-7fffd84399b7.png)


However, in the real Deletion region as the following figure, Sniffles showed no result in this region.

![2019-03-07_133906](https://user-images.githubusercontent.com/5409656/53935288-b54bb380-40e0-11e9-8e5d-423916a7326f.png)

There are a lot of these cases, so how could I avoid this kind of results?

Thank you.

Meng

**Comment by fritzsedlazeck** [comment]
Hi Meg,
Sniffles does not care about coverage. So there has to be at least 3 reads that are split and indicating this deletion in your first example.

Is this simulated data? 
It is strange that Sniffles doesn't indicate the second deletion. Could you share the reads from this location?
Thanks
Fritz

**Comment by biomichal** [comment]
Hi Fritz,
Both of two cases are the real data. 
In the first example, all reads aligned across the identified DEL region, as shown in the first ten reads in the figure. For the following reads in flanking region, reads are clipped in this region, not splitted. 
Because this is the real data, not published, I can just send you the data to your private email; sorry for this, can you send me a private adress.
My email box is yangmeng2019@gmail.com
Thank you.
Meng  



 
From: Fritz Sedlazeck
Date: 2019-03-07 20:49
To: fritzsedlazeck/Sniffles
CC: Meng Yang; Author
Subject: Re: [fritzsedlazeck/Sniffles] Problem (#130)
Hi Meg,
Sniffles does not care about coverage. So there has to be at least 3 reads that are split and indicating this deletion in your first example.
Is this simulated data?
It is strange that Sniffles doesn't indicate the second deletion. Could you share the reads from this location?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Just note to my self. I just sent an email.
thanks
Fritz

**Comment by fritzsedlazeck** [comment]
The problem was some miscommunication to interpret split vs. alignment events in IGV.
Was resolved over email.
Thanks Meng for reaching out..
Fritz
