### ISSUE TITLE
Problems replicating results on sim ref and real reads

### ISSUE THREAD

**Issue by LeaveYeah** [fritzsedlazeck/Sniffles#131]
Hi, I tried to replicate the results of the paper on sim ref and read reads. I downloaded the NA12878_PacBio_MtSinai bam file from GIAB and transform it to fastq. And I simulated a reference using SURVIVOR from hg38 with 140 indels, 140 inversions and 140 balanced translocations with length ranging from 100 to 3k bp. Then I align the fastq to simulated ref using NGMLR with default params. I get the vcf using sniffles with -l 100. But the final evaluation using SURVIVOR eval gives results as below 
560 39/0/51/163/19 47/0/89/117/35 2492/543/103/174/2809 0.485714 0.957453.

The sensitivity is only 48.6%, not as good as the paper declares. Could you point out which steps may be problematic? Are different parameters were used during your experiments? Thank you very much!

**Comment by fritzsedlazeck** [comment]
Yes because the bam files also include SVs naturally present in the genome of NA12878 compared to the reference. 

The main bulk of our simulated analysis was simulated reads against the human reference. For the analysis where we simulated the reference and aligned real reads we focused only on the SVs that were simulated. Since we cannot know if a potential false positve is not a true variant in e.g. NA12878.

I hope that helps.
Fritz

**Comment by LeaveYeah** [comment]
Thanks. I understand. I only calculated the sensitivity for the SVs simulated, i.e. (true positives)/(true positives + false negatives). And it is only 48.6%

**Comment by fritzsedlazeck** [comment]
You are right sorry, its been a while. Can you send me your parameter file for the simulation and the output?
I will try to reproduce and see what is happening.
thanks
Fritz

**Comment by fritzsedlazeck** [comment]
If the files are too large please send me an email: fritz.sedlazeck@gmail.com.
Thanks for reaching out.
Fritz

**Comment by LeaveYeah** [comment]
[files.zip](https://github.com/fritzsedlazeck/Sniffles/files/2954952/files.zip)
Thanks a lot. Please check the parameter file, simulated bed and called vcf. 
Best regards,
Alex

**Comment by fritzsedlazeck** [comment]
Hi Alex,
can you also share your simulated reference? Then I can remap the NA12878 data and see what is going on. 
Thanks
Fritz

**Comment by LeaveYeah** [comment]
Hi Fritz,
Please download the reference here https://github.com/LeaveYeah/StructuralVaraintAnalysis/blob/master/simulated.fasta.gz

Thank you very much.
Alex

**Comment by fritzsedlazeck** [comment]
Thanks. I just did. It will take me a bit to reproduce the mapping etc. 
Cheers
Fritz

**Comment by LeaveYeah** [comment]
Thanks for your prompt reply. Appreciate it.

Alex

**Comment by LeaveYeah** [comment]
Hi Fritz,

I found out that it is a problem from my side. Sorry for the trouble. 

Best, Alex

**Comment by fritzsedlazeck** [comment]
Ah even better. Thanks for letting me know.
Cheers
Fritz
