### ISSUE TITLE
VCF output contains no variants

### ISSUE THREAD

**Issue by PhilPalmer** [fritzsedlazeck/Sniffles#133]
Hi,

I have tried running sniffles, however, the VCF file produced contains no variants.

When I run the following command:
```bash
sniffles --mapped_reads giab.hg002.2D.bam --vcf giab.hg002.2D.vcf --threads 4
```

The following output & a VCF file is produced:
```
Estimating parameter...
	Max dist between aln events: 3
	Max diff in window: 50
	Min score ratio: 2
	Avg DEL ratio: 0.129177
	Avg INS ratio: 0.033356
Start parsing... chr1
	Switch Chr chr2
	Switch Chr chr3
	...
	Switch Chr chr18
	Switch Chr chr20
	Switch Chr chrY
	Switch Chr chr19
	Switch Chr chr22
	Switch Chr chr21
	Switch Chr chr6_dbb_hap3
	Switch Chr chrUn_gl000225
	Switch Chr chr4_gl000194_random
	Switch Chr chrUn_gl000224
	Switch Chr chrUn_gl000219
	Switch Chr chr17_gl000205_random
	Switch Chr chrUn_gl000216
	Switch Chr chr9_gl000199_random
	Switch Chr chrUn_gl000220
	Switch Chr chrUn_gl000214
	Switch Chr chrUn_gl000232
	Switch Chr chrM
Finalizing  ..
```

However, the VCF file produced contains the header only and no variants. 

I am using sniffles `v1.0.11` installed via conda. To generate the BAM file I download the following file `s3://giab/data/AshkenazimTrio/HG002_NA24385_son/CORNELL_Oxford_Nanopore/giab.hg002.2D.fastq` before aligning it to the hg19 reference genome using minimap2. I then then sorted & indexed it before marking duplicates. I also had to recompute the MD string using samtools.

Do you think everything is working correctly or is there a problem with my data/commands used? Why might no structural variants have been found?

Thanks in advance, any help would be much appreciated

**Comment by fritzsedlazeck** [comment]
Hi,
Thanks for reaching out. 
You said the md string was recomputed? That is good.
I would also check how much coverage this file has. By default Sniffles reports only svs that are supported by 10 reads (-s is the parameter)
Thanks
Fritz

**Comment by PhilPalmer** [comment]
Hi Fritz,

Thanks for responding so fast. 

Yes, I think its a problem with the coverage. If I lower the min_support parameter then there are variants in the VCF file produced. 

Thanks again for your help
