### ISSUE TITLE
Why the genotype is "./."

### ISSUE THREAD

**Issue by biomichal** [fritzsedlazeck/Sniffles#134]
Hi, Fritz,

`chr1	1074252	65	N	<DEL>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr1;END=1099389;STD_quant_start=0.632456;STD_quant_stop=0.632456;Kurtosis_quant_start=-0.500000;Kurtosis_quant_stop=-0.500000;SVTYPE=DEL;RNAMES=1723761;SUPTYPE=SR;SVLEN=-25137;STRANDS=+-;STRANDS2=3,2,3,2;RE=5	GT:DR:DV	./.:.:5`

**why the genotype is "./.:." ?**

my command is:
`sniffles -m sample.sort.bam -v sample.vcf -s 5 -t 10 -l 30 -n 1 --report_BND --report_seq --report_read_strands --ignore_sd --tmp_file tmpfile --cluster --cluster_support 1 --genotype 
`
I used the version 1.0.11.

**Comment by fritzsedlazeck** [comment]
Thanks do you have the command line output? It should say that the genotype function has been called towards the end.
Thanks
Fritz

**Comment by biomichal** [comment]
Do you mean the log file? I can not find "the genotype function has been called towards the end" in the log file. 
I run sniffles simultaneously for 10 samples using the same parameters, surprisingly, the genotype is normal the program is finished, and this unnormal phenomenon is found when sniffles is running.

**Comment by fritzsedlazeck** [comment]
Yes the log file. It's a short line towards the end. Sorry I am traveling right now and don't remember the exact phrase.

So what you are saying is you are looking at the temporary output before the program finishes?

This is expected. Sniffles first finishes the scanning and subsequently assess the genotype.

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Yes. Sniffles writes out the found svs in a vcf files. Once this is all done it goes back and insert the gt value.
So all is fine.
I hope that helps.
Fritz

**Comment by biomichal** [comment]
I got it. Maybe I shoud leave the computer for a while, until it is done.

Thanks
