### ISSUE TITLE
Sniffles installation: Could NOT find OpenMP_C

### ISSUE THREAD

**Issue by francoiskroll** [fritzsedlazeck/Sniffles#136]
I don't have a lot of experience installing packages without a manager and I could use some help. I could install sniffles with conda but I need the latest release (I am on macOS).

Here is what I did:
- Installed cmake with homebrew (`brew install cmake`)
- Downloaded the `.tar.gz` from the release page.
- Unzipped it
- `cd Sniffles-master/`
- `mkdir -p build/`
- `cd build/`
- `cmake ..`

> Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.14.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/Cellar/cmake/3.14.0/share/cmake/Modules/FindOpenMP.cmake:474 (find_package_handle_standard_args)
>   CMakeLists.txt:27 (FIND_PACKAGE)

I have also tried manually setting the paths in the `cmake` command as you suggest for macOS:
`cmake -D CMAKE_C_COMPILER=/usr/bin/gcc -D CMAKE_CXX_COMPILER=/usr/bin/g++ ..`
It throws the same error.

**Comment by fritzsedlazeck** [comment]
Sorry about this more complicated way for Mac.
I think last time I followed something similar than the answer in this post.
https://stackoverflow.com/questions/35134681/installing-openmp-on-mac-os-x-10-11

It is basically a special version of gcc that you need to get to have openmp included. 
I know it sounds complicated, but it's just a few steps.
Thanks for trying.
Fritz

**Comment by francoiskroll** [comment]
Great, solved! Thank you.

For anyone with the same issue (or if you want to update the README): I don't understand every detail, but there is something about `cmake` using another version of gcc compilers that are on macOS per default.

- Install gcc with homebrew: `brew install gcc` (`--without-multilib` mentioned in the StackOverflow post does not exist anymore apparently).
- Homebrew should put gcc in `/usr/local/bin/` and have appended the version (currently gcc-8) so it does not conflict with the macOS default one.
- Do all the same as the installation instructions in the [README.md](https://github.com/fritzsedlazeck/Sniffles), except at the `cmake` step, manually tell it to use the gcc you just installed with:
`cmake -D CMAKE_C_COMPILER=/usr/local/bin/gcc-8 -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-8 ..`.
- Sniffles is in `Sniffles-master/bin/sniffles-core-1.0.11/`. Use it with `./sniffles` while in this directory or add an entry to your `$PATH`.

**Comment by mschatz** [comment]
brew is up to gcc-9. Here are the current steps:

1.  `brew install gcc`
2. `mkdir build && cd build`
3. `cmake -D CMAKE_C_COMPILER=/usr/local/bin/gcc-9 -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-9 ..`
4. `make`

Good luck!

Mike
