### ISSUE TITLE
Segmentation Fault on Test File

### ISSUE THREAD

**Issue by mcfarland-k** [fritzsedlazeck/Sniffles#138]
Hi Fritz,
I am getting a segmentation fault when running the test case on my cluster. 

I compiled with gcc/g++ version 4.8.5. 

When running the test case `sniffles -m reads_region.bam -v test.`, I get the following 
```
Estimating parameter...

	Max dist between aln events: 4

	Max diff in window: 50

	Min score ratio: 2

	Avg DEL ratio: 0.0432235

	Avg INS ratio: 0.0740733`

Start parsing... 21

	Switch Chr 21

Finalizing  ..

Segmentation fault
```

I've tried recompiling with newer versions of GNU compilers (v5 and 6), but haven't been successful.

Any help would be much appreciated. 

Kevin McFarland
Johns Hopkins University
Chemical & Biomolecular Engineering

**Comment by fritzsedlazeck** [comment]
I dont think it has something to do with the compiling. 
Can you check if you have permission to write the output file?
Thanks for reaching out.
Fritz

**Comment by mcfarland-k** [comment]
Not completely clear on what you mean for permission to write the output file, but I checked my permissions for the folder, and I have write access. Just to be sure, I used chmod 777 for the files, and also attempted to copy the files and run them outside of the test folder. Both of them gave me the same output I posted above. 
Kevin

**Comment by fritzsedlazeck** [comment]
Mhm this is tricky. 
Usually, you get that kind of an error when Sniffles tries to write something out and fails to do so. 
I just tried it again with the test case and the newest code: 
![Screen Shot 2019-04-02 at 11 36 06 AM](https://user-images.githubusercontent.com/2081951/55420138-eed6d980-553b-11e9-9b33-aa6ef3cece07.png)


Is it on Marc or is it on a different environment?
Thanks
Fritz

**Comment by mcfarland-k** [comment]
I see, not sure why it would be doing it for me. Yes, it's on marcc.
Best,
Kevin

**Comment by fritzsedlazeck** [comment]
can you go to wherever you start sniffles from and do a` touch test` ?

**Comment by fritzsedlazeck** [comment]
I also assumbed you cloned the code from the git?

**Comment by mcfarland-k** [comment]
Touch test worked, and I indeed cloned from git.

**Comment by fritzsedlazeck** [comment]
Mhm let me think about this a bit....
I pinged a friend at JHU if he can have a look... I am running out of ideas.
Thanks
Fritz

**Comment by mcfarland-k** [comment]
Okay, thank you very much for your help and responsiveness!

**Comment by malonge** [comment]
You can email me at malonge11@gmail.com

Perhaps I can test things out on MARCC

**Comment by ttian627** [comment]
I have the same problem. Has it been solved?

**Comment by fritzsedlazeck** [comment]
No it hasnt. My problem is that I cannot reproduce it. I will try on different machines, but so far I was not lucky...

**Comment by fritzsedlazeck** [comment]
@ttian627 can you post your command line output?

**Comment by ttian627** [comment]
This is my command line output
[ttian@localhost test_set]$ ../bin/sniffles-core-1.0.11/sniffles -m reads_region.bam -v test.vcf
Estimating parameter...
	Max dist between aln events: 4
	Max diff in window: 50
	Min score ratio: 2
	Avg DEL ratio: 0.0432235
	Avg INS ratio: 0.0740733
Start parsing... 21
	Switch Chr 21
Finalizing  ..
Segmentation fault (core dumped)

**Comment by fritzsedlazeck** [comment]
Ok I think I found something that I recently changed at this location, which could effect this. 
Could someone clone the code again, rebuild and test?
Thanks
Fritz

**Comment by ttian627** [comment]
It works, thank you very much!

**Comment by fritzsedlazeck** [comment]
Awesome. Thanks to everyone and sorry that it took so long.

**Comment by mcfarland-k** [comment]
Thanks again for your help Fritz!

Kevin
