### ISSUE TITLE
Merge population calls and -d 

### ISSUE THREAD

**Issue by CWYuan08** [fritzsedlazeck/Sniffles#139]
Hi Fritz,
I am wondering whether it is necessary to use the -d option for collapsing nearby SVs, given that the population calls is going to be merged.

Thank you 
Best 
Ulrika

**Comment by fritzsedlazeck** [comment]
the -d parameter is set as default to 1kbp but its the maximum. sniffles self determines other thresholds as a ratio of the -d specified value to merge or not signals for smaller events.

the -d is not directly for merging SVs but rather to cluster noisy signals together. So for example, if there is a smaller indel in a low complexity region. 

In doubt, I would leave it as the default value. 
Does that answer your question?
Thanks
Fritz
