### ISSUE TITLE
Randomly chosen reads number for parameter estimation

### ISSUE THREAD

**Issue by hanyue36** [fritzsedlazeck/Sniffles#140]
The supplementary note mentions _Sniffles scans 10000 randomly chosen reads_ for parameter estimation before calling variations. But line 722 in file Detect_Breakpoints.cpp shows only it only choses 1000 reads, is it a spell mistake or something else? Do you think it may have bias for further analysis ?

**Comment by fritzsedlazeck** [comment]
Thanks for digging in :).
We reduced the number later on as we saw it doesnt improve much.
