### ISSUE TITLE
VCF missing some known structural variance

### ISSUE THREAD

**Issue by isardi** [fritzsedlazeck/Sniffles#142]
Hello,

I am using SNIFFLES as an additional tool to confirm genetic changes done through engineering and making sure that there is not unwanted changes.  Unfortunately, I am finding that there are some structural variance that I have confirmed by looking at my bam file through IGV but there aren't come up in the vcf file. 

First, let me tell you my pipeline in case I am missing something:

#Mapping and sorting
minimap2 -ax map-ont -t 32 -Y --MD my_reference.fasta nanoporeData.fastq > output.sam

samtools view -bS output.sam > output.bam

 samtools sort output.bam > output_sorted.bam

samtools index out_sorted.bam

#Running Sniffles
sniffles -t 10 -s 10 -r 2000 -q 20 -d 1000 --genotype -l 1000 -m output_sorted.bam -v sniffles.vcf

Now, there are confirmed deletions that are not showing up in the vcf and for the one that shows up it says it is a haploid deletion while I know it is a clean deletion.  I am wondering if having deletion of a gene, which is replaced by a new construct is causing Sniffles to get confused.  

Below is an example of a SNIFFLE output that shows a haploid deletion, while it is a diploid deletion/insertion.  Picture of clean deletion attached.  

![Capture-1](https://user-images.githubusercontent.com/32888126/56392221-7720d400-61f6-11e9-84d6-470df085758d.PNG)

Thanks in advanced for your input.
Best, 

Isabel

**Comment by fritzsedlazeck** [comment]
Hi Isabel,
what are the sizes for the deletions? You require that they are at least 1kbp long. This might be a problem. However, I see that this deletion is larger. Would it be possible to send me this region? The easiest way to extract it is:
`samtools view -h my.bam chr1L:3440850-352239 > new.bam `
Then just send me that new.bam via email: fritz.sedlazeck@gmail.com

I have just recently (2 weeks ago) fixed a potential problem that could lead to the het vs. homozygous error. If you like please clone the code again from github and build the project: https://github.com/fritzsedlazeck/Sniffles#how-to-build-sniffles

Thank you
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Isabel,
any update if you can or cannot send me some sub sample data?
Thanks
Fritz

**Comment by isardi** [comment]
Hi Fritz,
Unfortunately I can’t send you the data. I am planning to make a mock file to see if I can get the same type of error.  I am out of town right now so I expect to work on that next week. Thanks again for reaching out! Best, Isabel

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ythuang0522** [comment]
We have similar issues in terms of missing translocations.
https://github.com/fritzsedlazeck/Sniffles/issues/143#issuecomment-486665788
Would be grateful if you can assist. We can send the data if needed.

**Comment by fritzsedlazeck** [comment]
Dear @ythuang0522,
did I solve the problem or is this still remaining? 
Thanks
Fritz
