### ISSUE TITLE
TRA analysis

### ISSUE THREAD

**Issue by HJTsai** [fritzsedlazeck/Sniffles#143]
Hi,

Whether the inter-chromosome translocation (translocation occurs at different chromosomes) could be reported by sniffles? Or only intra-chromosome translocation (translocation occurs at same chromosome) could be reported by sniffles?

**Comment by fritzsedlazeck** [comment]
Hi,
Between chromosomes are reported directly as tra/ bnd events.
Within chromosomes can be found as very long deletions or inversion depending on who the molecule is put together.

I hope that helps
Fritz

**Comment by HJTsai** [comment]
Thank you.

**Comment by HJTsai** [comment]
Hello,

I am finding that there are some breakpoint reads (inter-chromosome translocation reads) that I have confirmed by looking at my bam file through IGV but there aren't come up in the vcf file.

The IGV figure and pipeline listed below:

minimap2 -ax map-ont --MD -t 12 reference.fasta nanopore.fastq | samtools sort -o output_sorted.bam -T reads.tmp

samtools index output_sorted.bam

sniffles -t 12 -m output.bam.bam --min_support 5 -v output.sniffles.vcf

![IGV_01](https://user-images.githubusercontent.com/49969700/56738015-46184480-679e-11e9-8114-349fc949b21c.jpg)

![IGV_02](https://user-images.githubusercontent.com/49969700/56738031-4d3f5280-679e-11e9-8e81-e6efa7e8c2e6.jpg)

Could you give me a help to figure out?

Best regards,

HJTsai

**Comment by fritzsedlazeck** [comment]
Hi HJTsai,
thanks for reaching out 
I can have a look next week to see why Snifles is not calling this translocation.
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
my email: fritz.sedlazeck@gmail.com
Thanks
Fritz
