### ISSUE TITLE
Allele frequency calculation

### ISSUE THREAD

**Issue by gbdias** [fritzsedlazeck/Sniffles#145]
Hi Fritz,

I have two questions about the allele frequency calculation done by Sniffles.

1. Does it use ZMW information to prevent overrepresentation of sequences?
2. Is the ratio calculated solely from the number of reads that support a SV vs the ones that don't, or is there also some regional depth information incorporated?

Thanks!
Guilherme

**Comment by fritzsedlazeck** [comment]
Hi Guilherme,

Ad 1: No
Ad 2: Its the ratio of reads that support the SV vs. any read that does not support the SV and is of high quality.

I hope that helps
Cheers
Fritz

**Comment by gbdias** [comment]
Thanks for clarifying!

Cheers,
Guilherme
