### ISSUE TITLE
Exit status of 0 for "./sniffles -m nonexistent_file -v output.vcf"

### ISSUE THREAD

**Issue by wtwhite** [fritzsedlazeck/Sniffles#146]
Running `./sniffles -m nonexistent_file -v output.vcf` gives the error message "BAM Parser: could not open file: nonexistent_file", but the program still returns an exit status of 0 to the operating system, which is a problem if you are running Sniffles inside a script and want to break out at the first failing step.

I noticed that other conditions that should cause a nonzero exit status do so, though they return different ones: e.g. `./sniffles -m existing_file.bam` gives 255, while `./sniffles -v output.vcf` gives 1.

**Comment by fritzsedlazeck** [comment]
Thanks for pointing this out. I will correct this. 
Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
I just checked the bam parser is now throwing the EXIT_FAILURE flag. I hope that fixes it.
