### ISSUE TITLE
Alt allele sequence for Insertions

### ISSUE THREAD

**Issue by hd00ljy** [fritzsedlazeck/Sniffles#147]
Hi Fritz,

  How does Sniffles infer Alt allele sequence in VCF for insertions?

  I could not find sections describing this in GitHub or in the paper.

  1. Is the sequence from one of the reads supporting and spanning the insertion?

  2. Is the sequence the consensus from the supporting reads?
      - In that case, what assembler do you use for making consensus sequence?

Thank you for always kindly answering my questions.
Jinyoung

**Comment by fritzsedlazeck** [comment]
Hi Jinyoung,
sorry for the late reply somehow this slipped through as I was traveling. At the moment Sniffles reports the sequence from the read best representing the inserted sequence. 

I hope that helps
Fritz

**Comment by fritzsedlazeck** [comment]
FYI check out crosstich to compute an assembly on top..

**Comment by hd00ljy** [comment]
Thank you for the reply and the suggestion!

I'll try using crosstich

Thank you again
Jinyoung.
