### ISSUE TITLE
Sniffles VCF report does not make sense

### ISSUE THREAD

**Issue by HJTsai** [fritzsedlazeck/Sniffles#148]
Hello,

We got the MAPQ>=2 and MAPQ>=45 bam flies then run sniffles, one of data (RE=52) was removed in the output.minimap2_all_q2_S15.vcf but reported in the output.minimap2_all_q45_S15.vcf.

![Q2_Q45_VCF](https://user-images.githubusercontent.com/49969700/57741394-3c279880-76ef-11e9-9fea-e7c6fc284445.jpg)

The bam files were checked by IGV.

![Q2_Q45](https://user-images.githubusercontent.com/49969700/57741400-434ea680-76ef-11e9-9b66-8de276add4fb.jpg)

It is very strange.

Could you help me to figure out ?

The pipeline listed below:

samtools view -bq 2 minimap2_reads.sorted_all.bam > minimap2_reads.sorted_all_q2.bam

samtools index minimap2_reads.sorted_all_q2.bam

sniffles -t 12 -m minimap2_reads.sorted_all_q2.bam --min_support 15 --genotype --report_BND -v output.minimap2_all_q2_S15.vcf

samtools view -bq 45 minimap2_reads.sorted_all.bam > minimap2_reads.sorted_all_q45.bam

samtools index minimap2_reads.sorted_all_q45.bam

sniffles -t 12 -m minimap2_reads.sorted_all_q45.bam --min_support 15 --genotype --report_BND -v output.minimap2_all_q45_S15.vcf

**Comment by fritzsedlazeck** [comment]
I can only speculate. Sniffles has a statistic mode included that filters out variations if they are too noisy. And I think that happens here. for MQ>=2 the reads show a too noisy pattern and thus the variant is not reported. For MQ>=45 the remaining reads are cleaner and thus it gets reported. 
I am not 100% sure I understand your question, but I think that this is it, right?

Thanks
Fritz

**Comment by HJTsai** [comment]
The average reads is 20 in minimap2_reads.sorted_all_q45.bam, but the reads support (RE=52) for chr15:chr9 TRA in the output.minimap2_all_q45_S15.vcf. 
Dose this make sense?

Thanks
HJTsai

**Comment by fritzsedlazeck** [comment]
I dont fully get the question. Sorry... 
You mean if it makes sense that the average coverage is 20 but then you see a variant with 52 reads supporting? That might be an indication of a misalignment... but I dont know. 
Thanks
Fritz

**Comment by HJTsai** [comment]
Sorry, I describe again.
A structural variant was reported by sniffles with 52 reads supporting. I checked this structural variant by IGV and saw only 20 reads supporting in bam file. Where the other 32 reads come from? If the answer is misalignment, how to dissolve it?

Thanks

HJTsai

**Comment by HJTsai** [comment]
Sorry, I describe again.
A structural variant was reported by sniffles with 52 reads supporting. I checked this structural variant by IGV and saw only 20 reads supporting in bam file. Where the other 32 reads come from? If the answer is misalignment, how to dissolve it?

Thanks

HJTsai

**Comment by fritzsedlazeck** [comment]
Oh I would check the preferences in IGV. IGV has (depending on the version you are using) several parameters preset that do not display all the long reads. 
Please let me know if this helps
Thanks,
Fritz

**Comment by fritzsedlazeck** [comment]
Dear HJTsai,
did you got a chance to check this?
Thanks
Fritz
