### ISSUE TITLE
no MD string detected

### ISSUE THREAD

**Issue by yiwanniantaijiu** [fritzsedlazeck/Sniffles#149]
hello
I'm using NGS sequenceing data to call SVs. The aligner I used is minimap2.
My command line is :
     sniffles -m input.sorted.bam -v output.vcf
And the output.vcf is :
     ##......
    ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
    ##FORMAT=<ID=DR,Number=1,Type=Integer,Description="# high-quality reference reads">
    ##FORMAT=<ID=DV,Number=1,Type=Integer,Description="# high-quality variant reads">
    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  output.sorted.bam
the error message is:
    Estimating parameter...
    No MD string detected! Check bam file! Otherwise generate using e.g. samtools.
    MD: TESTc700778e-2df6-46c1-a44d-bd16eff806c4
I use another sorted.bam to call SVs again with same command line ,the error message is same with different MD.
Combined with above-mentioned informations ,can you please give me some suggestions?
looking forward your reply,and thank you!

**Comment by fritzsedlazeck** [comment]
Your bam files dont have an MD tag.
As the error suggest. You can generate one with samtools or rerun minimap2 with the appropriate parameters.
Thanks
Fritz

**Comment by yiwanniantaijiu** [comment]
thank you very much

**Comment by dKlee99** [comment]
Hello, @yiwanniantaijiu 
I have encountered the same problem. Could you please share how you managed to solve it?

Thanks,
DK

**Comment by fritzsedlazeck** [comment]
Good morning @dKlee99 

Sniffles requires an MD tag. You can either use the appropriate parameter during mapping since almost all aligner support these or use samtools calmd to generate it.

Hope that helps
Fritz
