### ISSUE TITLE
Segmentation fault when giving invalid output vcf file

### ISSUE THREAD

**Issue by eldariont** [fritzsedlazeck/Sniffles#15]
Hi Fritz,

on my machine, Sniffles crashes with a segfault when given an invalid path to the output vcf file:
`sniffles -m input.bam -v non_exisiting_directory/output.vcf`
`Segmentation fault` 
I noticed this when I forgot to create the output directory ("non_exisiting_directory") before running Sniffles. Although this was my fault of course, it would be great if Sniffles would give a proper error message ;-) 

Cheers
David

**Comment by fritzsedlazeck** [comment]
Hi David,
I of course assumed that you guys are infallible. :) I just uploaded the fix on the code base.
Thanks for pointing it out.
Cheers
Fritz

**Comment by eldariont** [comment]
Thanks for the quick fix! I get a beautiful error message now :)

**Comment by sathishkumarRamaswamy** [comment]
Following error I am getting when I run sniflles 1.0.3
Finalizing  ..
Start genotype calling
Segmentation fault (core dumped)

**Comment by fritzsedlazeck** [comment]
Hi,
can you try if the error also occurs when you clone the code directly? I fixed a similar issue recently and did not create a new release.

just do a:
 `git clone  https://github.com/fritzsedlazeck/Sniffles.git`

and then follow the install instructions.
Thanks
Fritz
