### ISSUE TITLE
Dose different thread cause different output of structural variant number?

### ISSUE THREAD

**Issue by HJTsai** [fritzsedlazeck/Sniffles#151]
Hi,

Recently, we used different thread to run sniffles and got different output of structural variant number.
Dose anyone have same situation and how to dissolve it ?

![sniffles_thread](https://user-images.githubusercontent.com/49969700/57977861-96986000-7a33-11e9-8e6c-8f263fc22fad.jpg)

Thanks

HJTsai

**Comment by fritzsedlazeck** [comment]
This is quite strange. The only difference that could make sense is that Sniffles performs a parameter test, in the beginning, to estimate which regions could be noise etc. These estimated parameters are reported in the beginning.  These parameters are also used to filter out reads. 

Do you have the graphical/terminal output?

The number of threads cannot have an impact because the code doesn' work that way and it also does not scale larger than 5 threads. 

Thanks
Fritz

**Comment by HJTsai** [comment]
Hi,

We rerun Sniffles with -t 1, the output of SV number is still different.
![t1](https://user-images.githubusercontent.com/49969700/58080703-431a4380-7be6-11e9-96dc-6cf3b65b2513.jpg)
![1558418553143](https://user-images.githubusercontent.com/49969700/58080751-5a593100-7be6-11e9-9e55-d71b30eb4216.jpg)
![1558418818524](https://user-images.githubusercontent.com/49969700/58080770-62b16c00-7be6-11e9-8feb-b145d698b28b.jpg)

Thanks
HUTsai

**Comment by fritzsedlazeck** [comment]
Hi HJTsai,
first of all sorry for the confusion and thanks for reporting. I agree that this behavior is not ideal and I haven't seen it before. 

What I meant was that the only thing that could make sense to me is that this is due to the parameter estimation. You could try to avoid this by using: --skip_parameter_estimation 

May I ask of what coverage and sequencing technology the data is?
Again thanks for reporting this.
Fritz

**Comment by fritzsedlazeck** [comment]
Oh and what organism and if that is aligned to a reference genome or a draft assembly?
Thanks
Fritz

**Comment by HJTsai** [comment]
Hi Fritz,

Whether the bam file from Minimap2 is not compatible with Sniffles?

Information was listed as below:
Organism: Human cancer cell line
Sequencing technology: Nanopore, WGS　
Coverage: ~16X
Our data is aligned to reference genome hg19

Thanks
HJTsai

**Comment by HJTsai** [comment]
Hi Fritz,

We try --skip_parameter_estimation but the output of SV number is still different.
![--skip](https://user-images.githubusercontent.com/49969700/58158010-247e8000-7cac-11e9-872f-e773c513a5a1.jpg)

**Comment by fritzsedlazeck** [comment]
The output of minimap2 is compatible. You just need to select certain parameters for minimap2 such as 
`minimap2 --cs --MD -y -L  -a` and the tag of the seq tech.

About the changing numbers. I will need to look at this. I havent seen that on my test data...
Thanks
Fritz

**Comment by HJTsai** [comment]
Hi Fritz,

We still obtained different structural variant number from same input.
Could you help us to debug our problem?
We will appreciate your help with this situation and provide the bam file for you.

Thanks
HJTsai

**Comment by HJTsai** [comment]
Hi Fritz,

We have a question about the below parameter.
-q <int>,  --minmapping_qual <int> Minimum Mapping Quality. [20]
Dose the parameter remove Minimum Mapping Quality alignment only for primary alignment, or secondary alignment, or both? 

Thanks
HJTsai

**Comment by fritzsedlazeck** [comment]
Hi that should remove both. 
Sorry i am traveling this week. So earliest I can help is next week. I will have to see if I can reporduce the problem.. can you tell me which sequencing technology?

Thanks
Fritz

**Comment by HJTsai** [comment]
Hi Fritz,

Thanks for your help
We will sent the bam file to you.

Thanks
HJTsai

**Comment by HJTsai** [comment]
Hi Fritz,

Thanks for your help again.
You can download the bam file in the link below.
https://drive.google.com/drive/folders/1NDeIJuGxgsKEN6AU1bVxyBst50Xgid8b?usp=sharing

The data information and command line was tested and listed below:
Organism: Human cancer cell line
Sequencing technology: We performed whole-genome library prep using an LSK-108 kit, sequencing using GridIon (oxford nanopore technologies)
Coverage: ~16X
Our data is aligned to reference genome hg19

minimap2 -ax map-ont --MD -t 12 /home/gits/ref/hg19.fa.gz combined_all.fastq | samtools sort -o minimap2_reads.sorted_all.bam -T reads.tmp

sniffles -t 12 -m minimap2_reads.sorted_all.bam --min_support 10 --genotype --report_BND -v output.minimap2_S10.vcf

We also tested the parameters of -t 1 and --skip_parameter_estimation.


Thanks

HJTsai

________________________________
寄件者: Fritz Sedlazeck <notifications@github.com>
寄件日期: 2019年5月28日 上午 10:10
收件者: fritzsedlazeck/Sniffles
副本: HJTsai; Author
主旨: Re: [fritzsedlazeck/Sniffles] Dose different thread cause different output of structural variant number? (#151)


Hi that should remove both.
Sorry i am traveling this week. So earliest I can help is next week. I will have to see if I can reporduce the problem.. can you tell me which sequencing technology?

Thanks
Fritz

**Comment by HJTsai** [comment]
Hi Fritz,

After sniffles analysis, the different SV results were reported at the deletion regions of chr2 (76299373-76301767) and chr3 (102564930-102565268). The consistent part was indicated by green rectangle and the different part was indicated by red rectangle.
![large DEL miss](https://user-images.githubusercontent.com/49969700/62371494-93f3d400-b567-11e9-810f-58e51c96d0f4.png)
![large DEL miss 2](https://user-images.githubusercontent.com/49969700/62371507-99511e80-b567-11e9-838c-cbecebf8f1f4.png)

We pick up reads that align to the deletion region of chr2 and chr3 (chr2_chr3_target_sorted.bam、chr2_chr3_target_sorted.bam.bai) and run sniffles again. In contrast to the result of chr3 deletion was 100% reported, the result of chr2 deletion was 50% reported.

Could you help us to debug our problem?
We will appreciate your help with this situation and provide the bam file for you.

Thanks
HJTsai

**Comment by fritzsedlazeck** [comment]
Hi HJTsai,
I can only debug it if I have access to the data.  Can you send me the two VCF Files? fritz.sedlazeck@gmail.com
Thanks

**Comment by HJTsai** [comment]
Hi Fritz,

I sent files for you and thank you for your help.

Thanks
HJTsai

**Comment by HJTsai** [comment]
Hi Fritz,

How’s the procedure of debug going?
Should we provide further information?

Thanks
HJTsai

**Comment by fritzsedlazeck** [comment]
Hi HJTsai,
I am on it. I just pushed an improvement on the genotyper. Now I will check out whats on with this. Over my smaller test cases I did not see this effect.. 
Cheers
Fritz
