### ISSUE TITLE
After second run of Sniffles

### ISSUE THREAD

**Issue by UlrikaYuan** [fritzsedlazeck/Sniffles#152]
Hi Fritz,

I am wondering for population variant calling, after second run of Sniffles, the vcf for all the samples contain the same number of SVs (seems to be combined from all samples, and most SVs have reads between 0-10), I guess these are the evidence for Survivor. However, how could I obtain the individual file, i.e. second Sniffles outputs only SVs specific to the sample? ( want this file because the raw Sniffles vcf has calls not merged, and I want to study the individual file of the samples) 

Thank you 
Best 
Ulrika

**Comment by fritzsedlazeck** [comment]
Hi Ulrika,
so you called SVs with Sniffles per sample, then merged and then used that merged vcf file as input for Sniffles (--Ivcf)?
In that case Sniffles provides a new output file with these SVs and the information it could obtain  for each of the input SVs. 
Is that what you are asking?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Ulrika,
any chance to check that out?
Thanks
Fritz

**Comment by CWYuan08** [comment]
@fritzsedlazeck, sorry for the late reply
thank you very much for your help!
Best 
Ulrika

**Comment by UlrikaYuan** [comment]
@fritzsedlazeck, sorry for the late reply
thank you very much for your help!
Best
Ulrika

**Comment by qy152** [comment]
sniffles -m /work/home/yuxing/Qianyang_Dir/HIFI/sniffles/Rbie.srt.merged.bam -v Rbie-genotype.vcf --genotype -n -1 --Ivcf /work/home/yuxing/Qianyang_Dir/HIFI/graphtyper/four-species.merge.vcf，对分别进行基因分型的vcf文件合并后对单个样本进行基因分型，是否可行
