### ISSUE TITLE
segmentation fault error with --Ivcf

### ISSUE THREAD

**Issue by hd00ljy** [fritzsedlazeck/Sniffles#153]
Hi Fritz

  I posted this for the segmentation fault error with regard to --Ivcf option.

  I'm trying to merge SVs following the wiki.
  (https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population)

  I merged VCFs using SURVIVOR. (2nd section)

  And then forces calling all SVs again by Sniffles. (3rd section)

  But , segmentation fault occurred during reference allele update within genotyping step.

  This error did not show up when I excluded --Ivcf option.

  I read other segmentation fault issues but they were slightly different from mine.

With regards,
Jinyoung

sniffles version : 1.0.11 (I installed it last week)
cmake version : 3.2.2
RAM : 251GM
CPU : 28 cores

Command (wihtout --tmp_file : according to #83 )
```
sniffles --Ivcf NT-merge1_1000.vcf --report_BND -s 4 -n -1 -t 2 -m sorted.bam -v sorted.NT-merge1_1000.vcf --max_distance 1000 --minmapping_qual 30 --genotype --cluster --report_seq --report_read_strands
```

stderr - all error messages that can be redirected show up at the beginning of running sniffles.
```
Automatically enabling genotype mode
        Invalid types found skipping 0 entries.
```

stdout & seg fault error
```
...(skip)...
        Switch Chr chrUn_JTFH01001998v1_decoy
Finalizing  ..
Start phasing:
        Cleaning tmp files
Start genotype calling:
        Construct tree
                Read in SV: 5000
                Read in SV: 10000
                Read in SV: 15000
                Read in SV: 20000
                Read in SV: 25000
        Update reference alleles
                Scanning CHR chr1
                Scanning CHR chr9
                Scanning CHR chr1
...(skip)...
                Scanning CHR chr2
                Scanning CHR chr1
./code20190521_SURVIVOR: line 32:  8179 Segmentation fault      (core dumped) ${SNIFFLES} --Ivcf ${mergevcf1} --report_BND -s $th -n -1 -t $thread -m $BAM_filt -v ${output} --max_distance ${dist_option} --minmapping_qual $mapqualth --genotype --cluster --report_seq --report_read_strands
merging entries: 26728
merging entries: 26728

```

I also tried removing minimum support read threshold option according to  #103 
but the same error occurred at the same point

**Comment by hd00ljy** [comment]
To see if there is any problematic line in the input merged VCF or the number of lines of VCF is the issue,

I used header + first 5 entry of input merged VCF

And segmentation fault did not occur.

**Comment by fritzsedlazeck** [comment]
Thanks. Just to make sure the seg fault is in sniffles not in survivor...

Can you maybe share the vcf file? Fritz.sedlazeck@gmail.com

Thanks

**Comment by hd00ljy** [comment]
Yes, the seg fault is in Sniffles.

I will send the VCF shortly!

Thank you!

**Comment by fritzsedlazeck** [comment]
Thanks got it.
Fritz

**Comment by MehmetGoktay** [comment]
Hi Fritz,

Unfortunately same here. I have called SVs using sniffles for 8 samples and performed genotyping.

Then I followed this pipeline, https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population

4 out of 8 samples threw segmentation fault.

This is one example : 

./script.sh: line 3: 25444 Segmentation fault      sniffles -m sample.sorted.bam -v sample.gt.vcf --Ivcf merged_SURVIVOR_1kbpdist_typesave.vcf
Automatically enabling genotype mode
Force calling SVs
Estimating parameter...
	Max dist between aln events: 8
	Max diff in window: 50
	Min score ratio: 2
	Avg DEL ratio: 0.0490211
	Avg INS ratio: 0.0237165
Construct Tree...
		1377 SVs found in input.
	Invalid types found skipping 0 entries.
Start parsing: Chr Chr1
		# Processed reads: 10000
		# Processed reads: 20000
		# Processed reads: 30000
		# Processed reads: 40000
		# Processed reads: 50000
		# Processed reads: 60000
	Switch Chr Chr2
		# Processed reads: 70000
		# Processed reads: 80000
		# Processed reads: 90000
		# Processed reads: 100000
	Switch Chr Chr3
		# Processed reads: 110000
		# Processed reads: 120000
		# Processed reads: 130000
		# Processed reads: 140000
		# Processed reads: 150000
		# Processed reads: 160000
		# Processed reads: 170000
	Switch Chr Chr4
		# Processed reads: 180000
		# Processed reads: 190000
		# Processed reads: 200000
	Switch Chr Chr5
		# Processed reads: 210000
		# Processed reads: 220000
		# Processed reads: 230000
		# Processed reads: 240000
		# Processed reads: 250000
Finalizing  ..
Start genotype calling:
	Construct tree
	Update reference alleles
		Scanning CHR Chr1

Best,
Mehmet

**Comment by fritzsedlazeck** [comment]
sorry guys. I am stretched thin right now.. I will try to get to this over this week. 
Thanks for reaching out. 
Fritz

**Comment by hd00ljy** [comment]
Hi Fritz

 I split my merged VCF file into single-SV VCF files and ran the sniffles with --Ivcf option .

  I was able to pinpoint the specific SVs that are throwing the segmentation faults.

  And I also found that the seg faults arise in a sample specific manner.
  That is, for the same SV, the seg fault arise for BAM of sample 1 but not for BAM of sample 2.
  Some SVs show issues only in sample1, the other SVs show issues only in sample2.

  I will send you the problematic SVs through e-mail shortly

With regards,

Jinyoung

**Comment by fritzsedlazeck** [comment]
Hi Jinyoung,
thanks for checking this. Very interesting. What type of SV caused the seg fault?
Thanks
Fritz

**Comment by hd00ljy** [comment]
Um... various types of SVs were involved

These are the types of SVs that are causing the seg fault.

![image](https://user-images.githubusercontent.com/13775022/59208968-3eddb680-8be5-11e9-9f38-7c2206c6834f.png)

**Comment by fritzsedlazeck** [comment]
Thanks. Then it has to be something in the backbone. I will check asap. 
Thanks for the debugging. 
Fritz

**Comment by hd00ljy** [comment]
For SV1, run with sample1 threw seg fault but run with sample2 succeeded.
For SV2, run with sample1 succeeded but run with sample2 threw seg fault.

![image](https://user-images.githubusercontent.com/13775022/59210632-fe803780-8be8-11e9-9716-aa5a4457af7f.png)

**Comment by fritzsedlazeck** [comment]
Just for me: I think I fixed the issue. Please pull the new code and test it out.
Thanks
Fritz

**Comment by hd00ljy** [comment]
Hi Fritz!

  I pulled the updated code and the run ended successfully.

  No tmp file remained.

  Ref read depth and Alt read depth were shown with matching genotypes!

Thank you for the updates!

With regards,

Jinyoung

**Comment by fritzsedlazeck** [comment]
Awesome. 
Thanks for letting me know 
Fritz

**Comment by Teklu67** [comment]
Hello Fritz,
I combined individual vcf files using SURVIVOR v1.0.3 following the wiki as indicated above. Then when I try to force call SV using the combined vcf as input to sniffles v1.0.12b I get the following error. This error is somewhat similar to hd00ljy but in my case it is aborted. Any help please. I generated individual vcf files using the same version of Sniffles but without the --Ivcf option. 

Force calling mode enabled. Setting parameter accordingly
Automatically enabling genotype mode
Force calling SVs resetting parameters
Estimating parameter...
        Max dist between aln events: 4
        Max diff in window: 50
        Min score ratio: 2
        Avg DEL ratio: 0.05887
        Avg INS ratio: 0.0499182
        Construct Tree...
                259978 SVs found in input.
                Invalid types found skipping 0 entries.
Start parsing: Chr Chr1A
BUG: split read ins! 46551 264 fd2dc596-578b-495d-993a-00a7171e11b5
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 44388) > this->size() (which is 264)
Aborted
