### ISSUE TITLE
--report_seq is default ?

### ISSUE THREAD

**Issue by Litterlemon** [fritzsedlazeck/Sniffles#154]
Hi Fritz,
when i run ''`sniffles-1.0.11 --report_BND --ignore_sd -q 0 -n  -1 -t 8 -l 50 -s 1 --genotype -m input.bam -v out.vcf ` ,but still report sequences for indels in out.vcf,so --report_seq is default ?

**Comment by fritzsedlazeck** [comment]
Hi,
yes sorry, I didnt document it. I apparently thought that most people using it and thus set it true anyways. I just push code that you can deactivate it again.  

Thanks for pinging me. 
Fritz
