### ISSUE TITLE
the INV sv length is too long?

### ISSUE THREAD

**Issue by ttian627** [fritzsedlazeck/Sniffles#156]
This is the vcf out file, the sv length is  234M which is similar with the length of the chromsome. Is it right?  Please help me.
2	398126	9685	N	<INV>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=2;END=235077688;ZMW=13;STD_quant_start=0.707107;STD_quant_stop=0.447214;Kurtosis_quant_start=-0.105888;Kurtosis_quant_stop=6.985140;SVTYPE=INV;SUPTYPE=SR;SVLEN=234679562;STRANDS=++;RE=14	GT:DR:DV	./.:.:14

**Comment by fritzsedlazeck** [comment]
Hi @ttian627,
We saw these very large events before, most of the time these indicate some connections, which do not always have to reflect the actual alleles. For example that could be a transposon jump or something else related. Another example that I see is a DUP called for a circular DNA. 

Thanks
Fritz
