### ISSUE TITLE
Segmentation fault with --genotype

### ISSUE THREAD

**Issue by nathanhaigh** [fritzsedlazeck/Sniffles#157]
I've generated BAM files from aligning PacBio reads with `minimap2`. For some of these files I get segmentation faults after the `Update reference alleles` message when the `--genotype` argument is provided.

Minimap2 alignment command:

```bash
minimap2 \
  --MD \
  -ax map-pb \
  -t {threads} \
  -R "@RG\\tID:rg\\tLB:lb\\tPL:pl\\tPU:pu\\tSM:sm" \
  my.fastq.gz.mmi \
  my.fasta.gz \
| samtools sort -T /tmp --threads 12 -m 5G \
> my.bam
```

Sniffles command:

```bash
sniffles \
  --threads 12 \
  --mapped_reads my.bam \
  --min_support 5 \
  --genotype \
  --bedpe my.genotype.bed
```

Error:

```bash
Finalizing  ..
        processing merged TRA
Start genotype calling:
        Construct tree
        Update reference alleles
bash: line 1:  8601 Segmentation fault      sniffles --threads 16 --mapped_reads my.bam --min_support 5 --genotype --bedpe my.genotype.bed
```

Any thought's on what might be happening here? BTW, I'm executing this on a cluster using Snakemake.

**Comment by fritzsedlazeck** [comment]
Hi,
thanks for reporting this. 
Can you maybe try if that also happens with a vcf file output?
I can have a look later this week to check with the bedpe format. I sadly rarely update it and focus more on the vcf format.
Thanks
Fritz

**Comment by nathanhaigh** [comment]
The VCF output worked fine.

What are the pros/cons of each of these formats for SV's?

**Comment by fritzsedlazeck** [comment]
The vcf holds more information and I think more people are using it.... 
Thanks for letting me know.
Fritz
