### ISSUE TITLE
SV type changes after population genotyping

### ISSUE THREAD

**Issue by ricardovialle** [fritzsedlazeck/Sniffles#159]
Hi Fritz,

I'm using Sniffles in combination with SURVIVOR like you suggested here: https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population

However, I'm having some issues. All SVs that were initially classified as **duplications** were changed to **INVs** after the Sniffles second run (using --Ivcf).

See an example:

**Before**
`17	44436952	143	N	<DUP>	.	PASS	SUPP=1;SUPP_VEC=000000000000000000000100;SVLEN=217912;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.6;CHR2=17;END=44654855;CIPOS=0,942;CIEND=0,960;STRANDS=-+	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:217921:11,11:-+:.:DUP:153:NA:NA:17_44437894-17_446558150/0:NA:217903:181,13:-+:.:DUP:143:NA:NA:17_44436952-17_44654855	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN`

**After**
`17	44436952	INV_148	N	<INV>	.	PASS	SUPP=6;SUPP_VEC=000010001100001001100000;SVLEN=217912;SVTYPE=INV;SVMETHOD=SURVIVOR1.0.6;CHR2=17;END=44654855;CIPOS=0,0;CIEND=0,0;STRANDS=--	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	0/0:NA:217912:3,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:1,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:4,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:2,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/1:NA:217912:1,2:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:0,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:7,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:1,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	1/1:NA:217912:0,1:--:.:INV:510:NA:NA:17_44436952-17_44654855	1/1:NA:217912:0,2:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:5,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:2,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:4,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:6,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/1:NA:217912:5,4:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:1,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:3,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/1:NA:217912:1,1:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/1:NA:217912:2,1:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:1,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:1,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:2,0:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:3,1:--:.:INV:510:NA:NA:17_44436952-17_44654855	0/0:NA:217912:1,0:--:.:INV:510:NA:NA:17_44436952-17_44654855`

I'm using Snifflesv1.0.8 and SURVIVOR1.0.6

Any idea why is this happening?

Thanks!

**Comment by fritzsedlazeck** [comment]
Hi Ricardo,
thanks for reaching out. 
I know it sounds stupid, but could you update Sniffles? The current version is 11 for Sniffles. 

There has been a lot of recent changes especially for the force calling step and the genotyping. I am also testing right now an improved genotyping step but I will need some more tests before I can push it.

Please keep me posted. 
Thanks
Fritz

**Comment by ricardovialle** [comment]
Hi Fritz, thanks for your reply. 
I just run with v1.0.11 and I got the same issue, DUPs becoming INVs. 

**Original call**
`17      44554806        347     N       <DUP>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=17;END=44772492;ZMW=12;STD_quant_start=428.560264;STD_quant_stop=443.810320;Kurtosis_quant_start=-0.836216;Kurtosis_quant_stop=-0.902074;SVTYPE=DUP;SUPTYPE=SR;SVLEN=217686;STRANDS=-+;RE=12;AF=0.923077        GT:DR:DV        1/1:1:12`

**After force genotyping**
`17      44554806        737     N       <INV>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=17;END=44772492;SVTYPE=INV;SUPTYPE=input;SVLEN=217634;STRANDS=-+;SEQ=;RE=1;REF_strand=0,0;AF=1  GT:DR:DV        1/1:0:1`

**Comment by fritzsedlazeck** [comment]
Thanks.
Can you send me the vcf file?
fritz.sedlazeck@gmail.com

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
If possible both :)

**Comment by fritzsedlazeck** [comment]
Dear Ricardo,
I just pushed a bug fix for this. Can you clone the code and give it a try?
Sorry for the stupid mistake
Fritz

**Comment by ricardovialle** [comment]
I can see DUPs now :)
Thank you very much, Fritz!

Best,
Ricardo

**Comment by fritzsedlazeck** [comment]
Thanks for reporting!
Fritz
