### ISSUE TITLE
Separate calling and re-genotyping of SVs

### ISSUE THREAD

**Issue by holtgrewe** [fritzsedlazeck/Sniffles#16]
Hi, first of all, thanks for this great tool!

I wonder whether it would be possible to add a feature for allowing regenotyping of SVs?

One of the great features of the new Delly2 (for Illumina data SV detection) is that you can first call variants independently in all individuals of a family/cohort, then merge the site-list and regenotype in all individuals.

Also, this would make it easier to decide whether an SV is present in a child's parent beyond interval overlaps...

**Comment by fritzsedlazeck** [comment]
Hi, yes that is a great idea. I was thinking of that some weeks ago when I was using Delly for that on short reads ;).
Unfortunately it will take some time until I can provide this. So leave that issue open and I try to get it done. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Its been a while but I finally pushed a first version of the forced calling. 
you can enable it by "--Ivcf" and providing a vcf file. The output is still specified by -v. 
Let me know if you have any problems. 
Thanks
Fritz
