### ISSUE TITLE
Complex structural variants

### ISSUE THREAD

**Issue by jiadong324** [fritzsedlazeck/Sniffles#160]
I am trying to use NGLMR and Sniffle to discovery complex SVs, such as inverted-duplication and deletion associated with inversion mentioned in the paper. However, the final output dose not contain those complex SVs. Is there any special settings for the discovering?

Btw, the data is from 1000GP, previous study has shown the existence of complex SVs. We further validated some of them through long reads sequence dotplot and Sanger sequencing.

Thanks!

**Comment by fritzsedlazeck** [comment]
Invdup are reported directly if identified. Otherwise you need to check the variant id to identify more complex events as they are split in the individual svs. I choose to do that to stick as closely to the Standart types as possible.
Hope that helps
Fritz

**Comment by jiadong324** [comment]
For example, I found variant ID of the format "99_0" and "99_1". Is that mean these two separately recorded events might belong to a complex event?

Thanks!

**Comment by fritzsedlazeck** [comment]
Yes. Close to each other likely on the same read.
Cheers
Fritz
