### ISSUE TITLE
User sample names as column names for genotyping information

### ISSUE THREAD

**Issue by SHuang-Broad** [fritzsedlazeck/Sniffles#163]
I've noticed that the "sample names" columns are [currently](https://github.com/fritzsedlazeck/Sniffles/blob/111e5e2906a2b392a0058a511745e8bedfdcb1f0/src/print/VCFPrinter.cpp#L74) named with the input bam that are used for calling SVs.

It shouldn't be difficult to change that line a bit (I could be wrong) to get the actual sample name in the BAM's header (`SM`).

This would greatly help downstream applications.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved. 
Use --sample-id
