### ISSUE TITLE
1nt offset in POS field

### ISSUE THREAD

**Issue by MaestSi** [fritzsedlazeck/Sniffles#164]
Hi Fritz,
I am running Sniffles on a bam file obtained mapping ONT reads from an amplicon, and after that I am running `bcftools consensus` to obtain the alternative allele, introducing the variant (this time a DEL) in the reference. However, bcftools consensus complains that the fasta sequence does not match the REF allele at chrname:POS. At a closer inspection in IGV, I realised that the REF allele represents the sequence starting at POS+1 and not at POS. Adding 1 to the POS value in the vcf file, bcftools consensus is working as expected. Do you think this is an issue, or am I missing something? As an alternative, do you know of any other tools that may due the job and that you have tested with Sniffles output?
Thanks in advance,
Simone

**Comment by fritzsedlazeck** [comment]
Dear @Simone,
thanks for reporting this. I believe I have fixed this, but I need to test. Its been a while. 

Also sorry for the very late reply.
Thanks
Fritz

**Comment by MaestSi** [comment]
Perfect, I won't test it immediately, as I am not working on that anymore, but thanks, I'll close the issue!
Simone
