### ISSUE TITLE
--cluster output not as expected

### ISSUE THREAD

**Issue by jadams8** [fritzsedlazeck/Sniffles#165]
Hi Fritz,

Great work on creating this long-read SV caller!

I'm having some issues with the `--cluster` option.
I read in a closed issue that phase is indicated in the variant ID using _1, _2 etc. However, when I run this none of the variant IDs have an _ in them.

I ran the following command:

`sniffles -t 28 -n -1 --genotype --cluster -m <sorted.bam> -v <output.vcf> `

using sniffles version 1.0.11.
the bam file was created using NGMLR (version 0.2.7)

Parsing the RNAMES info tag I saw that 13% of the reads support more than one variant, so I hoped to obtain at least a few phased variants.

Have I missed something in the command or has the output format changed? If so it would be great if you could let me know.​

Thanks,
Jes

**Comment by fritzsedlazeck** [comment]
Dear Jes,
yes but I am ignoring homozygous variations and also filter conflicting information for this clustering step. Clearly, this step can be improved and we are working on it.
Thanks for the feedback. 
Fritz
