### ISSUE TITLE
Is it suitable for microbial genomes sv detection?

### ISSUE THREAD

**Issue by pigraul** [fritzsedlazeck/Sniffles#166]
Hi Fritz,

Is Sniffles suitable for microbial genomes sv detection?
What should I pay attention to if i use it for microbial genomes?

Thanks,
Raulee

**Comment by fritzsedlazeck** [comment]
Dear Raulee,
yes it is. People have already used it. I would check if the zygosity of the variant prediction makes sense or not depending on the organism of course. 

Cheers
Fritz
