### ISSUE TITLE
Overlapping inversions, duplications and deletions?

### ISSUE THREAD

**Issue by smehra97** [fritzsedlazeck/Sniffles#169]
Hello,

I've been using Sniffles (with NGMLR) to detect SVs for Oxford Nanopore data. There's a ~5,500bp region on one chromosome, however, that's showing overlapping inversions, duplications and deletions. I've tried running Sniffles in --genotyping --cluster mode, and there are overlapping duplications, deletions and inversions even within phased groups. I suspect this is a marker for more complex variation, but I was wondering if you might know how to interpret this? I've included a snippet of the VCF file below.

`Pf3D7_13_v3	2265810	241_0	N	<DEL>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2267164;STD_quant_start=13.397761;STD_quant_stop=2.323790;Kurtosis_quant_start=1.238785;Kurtosis_quant_stop=0.692757;SVTYPE=DEL;SUPTYPE=SR;SVLEN=-1354;STRANDS=+-;RE=21;REF_strand=71,60;AF=0.138158	GT:DR:DV	0/0:131:21
Pf3D7_13_v3	2267162	241_1	N	<INV>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2268885;STD_quant_start=1.707412;STD_quant_stop=1.000000;Kurtosis_quant_start=29.210977;Kurtosis_quant_stop=2.261287;SVTYPE=INV;SUPTYPE=SR;SVLEN=1723;STRANDS=++;RE=119;REF_strand=9,8;AF=0.875	GT:DR:DV	1/1:17:119
Pf3D7_13_v3	2265808	241_1	N	<INV>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2270336;STD_quant_start=39.434156;STD_quant_stop=43.513458;Kurtosis_quant_start=-1.635125;Kurtosis_quant_stop=0.312232;SVTYPE=INV;SUPTYPE=SR;SVLEN=4528;STRANDS=--;RE=39;REF_strand=71,60;AF=0.229412	GT:DR:DV	0/0:131:39
Pf3D7_13_v3	2268885	241_2	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2270338;STD_quant_start=0.365148;STD_quant_stop=317.148861;Kurtosis_quant_start=2.829696;Kurtosis_quant_stop=-2.046354;SVTYPE=DUP;SUPTYPE=SR;SVLEN=1453;STRANDS=-+;RE=30;REF_strand=10,6;AF=0.652174	GT:DR:DV	0/1:16:30
Pf3D7_13_v3	2265809	242_1	N	<INV>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2268887;STD_quant_start=477.977057;STD_quant_stop=4.647580;Kurtosis_quant_start=-2.210635;Kurtosis_quant_stop=-1.104046;SVTYPE=INV;SUPTYPE=SR;SVLEN=3078;STRANDS=++;RE=61;REF_strand=10,6;AF=0.792208	GT:DR:DV	0/1:16:61
Pf3D7_13_v3	2268888	242_2	N	<DEL>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2269920;STD_quant_start=1.479020;STD_quant_stop=197.781445;Kurtosis_quant_start=2.860915;Kurtosis_quant_stop=-1.964694;SVTYPE=DEL;SUPTYPE=SR;SVLEN=-1032;STRANDS=+-;RE=32;REF_strand=25,28;AF=0.376471	GT:DR:DV	0/1:53:32
Pf3D7_13_v3	2265808	242_0	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2267162;STD_quant_start=55.453584;STD_quant_stop=2.190890;Kurtosis_quant_start=0.421726;Kurtosis_quant_stop=0.897518;SVTYPE=DUP;SUPTYPE=SR;SVLEN=1354;STRANDS=-+;RE=16;REF_strand=71,60;AF=0.108844	GT:DR:DV	0/0:131:16
Pf3D7_13_v3	2266417	245_0	N	<DEL>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2267168;STD_quant_start=213.033565;STD_quant_stop=70.651964;Kurtosis_quant_start=-0.905421;Kurtosis_quant_stop=3.334230;SVTYPE=DEL;SUPTYPE=SR;SVLEN=-751;STRANDS=+-;RE=12;REF_strand=4,6;AF=0.545455	GT:DR:DV	0/1:10:12
Pf3D7_13_v3	2266897	243_1	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pf3D7_13_v3;END=2267162;STD_quant_start=77.122099;STD_quant_stop=0.522233;Kurtosis_quant_start=-1.181824;Kurtosis_quant_stop=4.045121;SVTYPE=DUP;SUPTYPE=SR;SVLEN=265;STRANDS=-+;RE=22;REF_strand=9,8;AF=0.564103	GT:DR:DV	0/1:17:22
`

Thanks in advance!

**Comment by fritzsedlazeck** [comment]
Sorry for the late reply.. seems to have slipped in my inbox.
You could try to look at the reads in e.g. ribbon.  May I ask what organisms, ployidy it has?

Thanks
Fritz
