### ISSUE TITLE
predicted_length - what is it?

### ISSUE THREAD

**Issue by JohnUrban** [fritzsedlazeck/Sniffles#17]
Hi,

As usual - thanks for the great tool.

In the BEDPE output, the header specifies the columns as:
```
#Chrom	start	stop	chrom2	start2	stop2	variant_name/ID	score (smaller is better)	strand1	strand2	type	number_of_split_reads	best_chrom	best_pos	best_chrom2	best_pos2	predicted_length
```

The last column is called ```predicted_length```. I naively assumed this was the predicted length of the SV -- e.g. of a deletion. However, I recently noticed that the ```predicted_length``` column always has the same value as the ```number_of_split_reads``` column. For example:
```
11 11
17 17
15 15
11 11
11 11
12 12
23 23
11 11
12 12
13 13
```

So my question is -- is that intentional (that both columns have the same value)? If so, is it safe to say that ```predicted_length``` is meaningless for now?

Best,

John

**Comment by fritzsedlazeck** [comment]
Sorry, yes it is meaningless. I should better maintain the bedpe output. I will fix this soon. I am just moving to another state.. 
Thanks for pointing that out.
Fritz

**Comment by JohnUrban** [comment]
Thanks for getting back to me so quick.

**Comment by fritzsedlazeck** [comment]
I just pushed a fix on the code base. Please clone the repository and try. 
In general I provide much more information in the vcf file. 
Thanks for letting me know
Fritz
