### ISSUE TITLE
What's the 'Kurtosis_quant_start/stop'?

### ISSUE THREAD

**Issue by LinXialab** [fritzsedlazeck/Sniffles#170]
Excuse me, could you please tell us what is the meaning of 'Kurtosis_quant_start/stop'?

**Comment by fritzsedlazeck** [comment]
Kurtosis is a measurement of the shape to f the distribution. Here I am using it for the distribution of the read breakpoints. You can find more information in the supplement.

It's sometimes usefull for filtering, but requires a  higher coverage.
Hope that helps
Fritz
