### ISSUE TITLE
Supporting Read No. Force Calling

### ISSUE THREAD

**Issue by vollrath-p** [fritzsedlazeck/Sniffles#171]
Hello Fritz,
I just noticed that Sniffles seems to not consider the default number of supporting reads when doing force calling across many samples. I repeated the force calling by setting a supporting read number ('-s 7'). But still I have e.g. 1/1 calls with RE=1 in the vcf output. Could you comment on this? 
Many thanks in advance,
Paul

**Comment by fritzsedlazeck** [comment]
Yes, that is true. The idea here is even if it finds any evidence it uses it. While the default method is calling SVs only that are "trustworthy" .  I dont want to change this behavior. 
If you like you could try SURVIVOR filter as a subsequent step.

I hope that helps
Fritz
