### ISSUE TITLE
The meaning of  "-1 -1 -1" parameters

### ISSUE THREAD

**Issue by biomichal** [fritzsedlazeck/Sniffles#172]
Hi, Fritz, 

I noticed the "-1 -1 -1" parameters in the following command for population SV calling. I can not find the explansion in the SURVIVOR wiki. How to explain it?
`./SURVIVOR merge vcf_files_raw_calls.txt 1000 1 1 -1 -1 -1 merged_SURVIVOR_1kbpdist_typesave.vcf`

Thanks

**Comment by fritzsedlazeck** [comment]
if you call ./SURVIVOR merge it shows what these parameters are. 
-1 just means to ignore these filters during the merge.

Cheers
Fritz
