### ISSUE TITLE
Unusual entries in Test.vcf 

### ISSUE THREAD

**Issue by RY-T** [fritzsedlazeck/Sniffles#174]
Hi

I've recently ran sniffles and was looking into deletion, however I noticed a few problems the SVLEN has a neagtive value and instead of <DEL> in the ALT field, it is a string of nucleotide sequence

Thus, I tried to reproduce Test.vcf  to check it it was an installation issue, while in general most of the stuff are in order the problems that I described were present

I initially installed sniffles via bioconda, but subsequently compiled it from the tar package, still the problem persists

Do you have any advice on what should I do next, are there any dependencies I am missing?

The following is the output I received with the problems mentioned 

Thanks
Best regards

##fileformat=VCFv4.1
##source=Sniffles
##fileDate=20191219
...
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	reads_region.bam
21	21492142	0	**AAAATATGTTTTAAATTGTTGATGATTTCAAATATTACAGGAATAGAAACTTTAACTTAACACAGAATGATTATCTGGCTTCCTTCTGTAAAATATCTTAAAGGTTAATGTGGATTTGAATTGCACAACATTCCAAATGCTTCTCCCCCTTTAAAAAGAATAGTCTTATCTTTTAAAAAGAATACTCATATCTTTTATTTTTCTTATGCAAGAGCAAAAATAAGGAAAAAATATATTATTCAGGAGAATCATGGCAACAATTTAAGGAAGACAAAACCAGTCTTTAGCAACCAGTATACATATATATCATCTTTTTTTCTGCTTTAGGGTAGGTTGCTTCTATCACCAACCTGTTCCAAATCCTCCTCTTACATGCACCATTAAAACATACTCTTTCAAAAACGAGGTGATAAAATCACAAATATCAATCTATCGTTCAGAAGAAGGTACCTTTATTTTACCTTAAAGGAATTTGATATATAATGGAGAAAAGAAAATTACTTTCT**	N	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=21;END=21492648;STD_quant_start=0.000000;STD_quant_stop=0.000000;Kurtosis_quant_start=0.572582;Kurtosis_quant_stop=1.417662;SVTYPE=DEL;SUPTYPE=AL,SR;**SVLEN=-506**;STRANDS=+-;RE=48;REF_strand=48;AF=1	GT:DR:DV	1/1:0:48

**Comment by wdecoster** [comment]
> SVLEN has a neagtive value

That's according to the specifications for deletions.

**Comment by fritzsedlazeck** [comment]
Yes as @wdecoster pointed out its according to the specification of a VCF file. I belive they introduced that like 1-2 years back. 

Thanks for reaching out and checking it.
Fritz
