### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by Wuxy96** [fritzsedlazeck/Sniffles#176]
Hi,

I downloaded Sniffles on June 15, 2019. The version is 1.0.11.
And on Oct 20, 2019, I downloaded Sniffles as guided, the version is the same.
sniffles --help
the former shows 
Advanced:
    --report_seq
       Report sequences for indels in vcf output. (Beta version!)  [false]

the latter shows
Advanced:
    --not_report_seq
       Dont report sequences for indels in vcf output. (Beta version!)  [false]

Why default parameter is different as they are the same version? Is there any other difference between them?

Thanks

**Comment by fritzsedlazeck** [comment]
The github main page always holds the current development. So there can be slight changes. Every now and then I make a fix release that are then stored in the release page. 
I hope that this change did not cause major problems. I changed it as it becomes standard to report the sequences if available.
Thanks
Fritz
