### ISSUE TITLE
TRA calls on a de novo assembly

### ISSUE THREAD

**Issue by JohnUrban** [fritzsedlazeck/Sniffles#18]
Hi again,

Yesterday, I git cloned the latest version (1.0.3) -- I had been using 1.0.0.

I noticed it called more SVs given the same data. Most of the additional SV calls were of the type: ```TRA```. I assume this means "translocation". ((edit: were there TRA calls in 1.0.0 -- or is this a newer feature since then?))

I am running this on a de novo assembly and also observed that the majority of the TRA calls (if not all) strictly map to the ends of separate contigs (different contig pairs for each TRA call) -- i.e. potentially scaffolding them. Have you explored using this information for scaffolding de novo assemblies? If so, any thoughts?

Best,

  John

**Comment by fritzsedlazeck** [comment]
Hi,
yes these could represent potential scaffolding information. However, there could be e.g. conflicting information and that is why the assembler might initially did not put the two contigs/scaffolds together.
I have not explored this. I would guess if you see enough read support for that connection you might want to go ahead and join the contigs. 

Thanks
Fritz

**Comment by JohnUrban** [comment]
Thanks. When I get the chance, I will explore this a little more.

**Comment by fritzsedlazeck** [comment]
Hi John,
did you had a chance to look at that? Otherwise I will just close this. 
Thanks
Fritz

**Comment by JohnUrban** [comment]
Wow - I cannot believe it has been almost a year. Actually I have not done much with this. Closing it is fine. (((As always, sniffles is great - thanks for it!)))
