### ISSUE TITLE
Calculating how many number of reads supports the SV calls

### ISSUE THREAD

**Issue by ghausiabegum** [fritzsedlazeck/Sniffles#180]
Hi,

I am beginner in bioinformatics and I am trying to understand the output I got from Sniffles.
So we aligned our files using NGLMR and then ran sniffles. From what I understand the --min_support is by default 10 and since I  didnt change it, all my variants are supported by 10 or above reads. 
My question is how many reads exactly are supporting each of my calls, I think the word I am looking for is read depth. Can sniffles give me that information or is there any other software that I should use prior or post sniffles?

Please let me know!

Thank you!

**Comment by fritzsedlazeck** [comment]
Hi,
That information is in the info field. Look at the tag RE= and also in the genotype field tag dv

I hope that helps.
Cheers
Fritz
