### ISSUE TITLE
Reads that not support the SV

### ISSUE THREAD

**Issue by Mmark94** [fritzsedlazeck/Sniffles#185]
Hi, I am using Sniffles to call the SVs from my mapping with ngmlr, this is an example of script that I used:
sniffles -m sample-ID_ngmlr_sort.bam -s 5 -b sample-ID"-5.bedpe -t 8

In the output bedpe file there is a column that shows the number of reads that support each SV. However, I am also interested in knowing also the number of reads that do not support the SV. Something like total number of reads minus the reads that support the SV. 
Is there a way to know this using Sniffles?

**Comment by fritzsedlazeck** [comment]
Hi ,
yes just switch to the VCF output (-v instead of -b). This will include much more information including the number of reads that support the reference allele and the GT estimation.
Cheers
Fritz
