### ISSUE TITLE
translocation length

### ISSUE THREAD

**Issue by liufy11** [fritzsedlazeck/Sniffles#186]
Sniffle offer the translocation breakponit,  but I dont know the start and stop of the translocation segment. so I can't count the translocation length . Is that right ? thanks for your reply in advance.

**Comment by fritzsedlazeck** [comment]
Yes you have the points of connections for this event. This was done with cancer genomes in mind where you have novel connections between chromosomes represented by different molecules. 
Hope that helps
Fritz
