### ISSUE TITLE
Output VCF field 5 from sniffles changed without addition of the --report_seq parameter, is this suppose to happen?

### ISSUE THREAD

**Issue by Sandman2127** [fritzsedlazeck/Sniffles#187]
Hi Fritz, 
I'm using Sniffles 1.0.11 and I performed an SV analysis for testing purpose using the default parameters:

sniffles -m my.bam -v output.vcf

 I did <strong>not</strong> engage --report_seq 

and I found the output.vcf changed from your previous version. I.e. the 5th column which indicates the type of mutation detected went from the <TYPE> to an actual sequence (ATCTA..). 

From the help menu, I don't think Sniffles was suppose to do that (since --report_seq says its a beta and it should be false by default), and since I wrote some methods for plotting these awesome outputs based on the previous versions vcf (1st vcf snippet below) it would be really nice if the original vcf output was still possible. 

original vcf file: all_reads.fa.giab_h002_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_noalts.vcf

1	724845	0_0  N  <strong> \<DUP\></strong>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.3;CHR2=1;END=224202174;STD_quant_start=275.695847;STD_quant_stop=289.122984;Kurtosis_quant_start=0.233584;Kurtosis_quant_stop=-0.193920;SVTYPE=DUP;SUPTYPE=SR;SVLEN=223477329;STRANDS=-+;STRANDS2=8,3,8,3;RE=11;AF=0.323529	GT:DR:DV	0/1:23:11
1	756262	1_0	N   <strong>\<INS\></strong>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.3;CHR2=1;END=756267;STD_quant_start=10.548589;STD_quant_stop=8.268231;Kurtosis_quant_start=6.854795;Kurtosis_quant_stop=4.867317;SVTYPE=INS;SUPTYPE=AL;SVLEN=253;STRANDS=+-;STRANDS2=17,24,17,24;RE=23;AF=0.851852	GT:DR:DV	1/1:4:23

new file output:

1	10901	0	N	<strong>GTGAGGCGTGGCACAGGCGCAGAGACATGCCAGCGCGCCCAGGGA</strong>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=1;END=10944;STD_quant_start=12.727922;STD_quant_stop=9.132360;Kurtosis_quant_start=-0.961525;Kurtosis_quant_stop=0.172053;SVTYPE=INS;SUPTYPE=AL;SVLEN=40;STRANDS=+-;RE=18	GT:DR:DV	./.:.:18
1	54713	1    N  <strong>TTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTC</strong>	N	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=1;END=54748;STD_quant_start=1.264911;STD_quant_stop=2.213594;Kurtosis_quant_start=0.590389;Kurtosis_quant_stop=1.555428;SVTYPE=DEL;SUPTYPE=AL;SVLEN=-35;STRANDS=+-;RE=16	GT:DR:DV	./.:.:16

Am I missing something, or is this the new method of output permanently?

**Comment by fritzsedlazeck** [comment]
Dear @Sandman2127,
yes I switched this and the genotyping recently since I got more and more reports that people are running it like this. I hope its not too much of a problem. You should be able to disable it given the --report-seq flag. 

I hope that helps and thanks for developing on top! 
Cheers
Fritz

**Comment by Sandman2127** [comment]
Hi Fritz,
Thanks for the prompt reply, I did some testing yesterday using that --report_seq flag and it doesn't appear to have affected anything. 

I still get the sequence reported (instead of the <del> <ins>) with or without that flag. I'm rerunning it using a controlled shell script to ensure I did it correct, but from what I see the flag doesn't seem to alter the output...

**Comment by fritzsedlazeck** [comment]
sorry about the confusion on my side. Please try --not_report_seq . 
Thanks
Fritz

**Comment by Sandman2127** [comment]
Ahh, excellent, I'll report back!

**Comment by Sandman2127** [comment]
sniffles --not_report_seq -m ultra-long-ont.sorted.bam -v out3.vcf

I just keep getting back:

Error:
         Couldn't find match for argument

Short usage:
       sniffles [options] -m <sorted.bam> -v <output.vcf> 
Version: 1.0.11
Contact: fritz.sedlazeck@gmail.com

Am I using too new of a version? Perhaps that option used to exist and no longer does, its not in the help menu... If its something silly and stupid let me know but this is actually alright, I'm having to rewrite a lot of my plotting program to accommodate other SV callers as well (SVIM etc), so I can probably handle the change to the new output, I just have some really crazy regex doing the parsing and I was just hoping it might be an easy solve if I could get the original file format. Let me know either way and I'll proceed!

**Comment by Sandman2127** [comment]
Hi Fritz,
I've managed to write my way around it the differences in output. Thanks for all the help and sorry to bug you about this!

**Comment by fritzsedlazeck** [comment]
Sorry for the delay. Been on phonecalls the entire day.. I will make that an enhancement and modify the code. 
Thanks
Fritz
