### ISSUE TITLE
Found strange subjects on the reads which support INV

### ISSUE THREAD

**Issue by LinXialab** [fritzsedlazeck/Sniffles#188]
Hi,

When I check reads supported INV sniffles identified, I found major of reads had multi-alignments:
![image](https://user-images.githubusercontent.com/40595816/80170381-5dd91180-861a-11ea-8630-d02754650cf2.png)
![image](https://user-images.githubusercontent.com/40595816/80170610-ed7ec000-861a-11ea-98a7-3251ff09672f.png)

Rmapped_start means the start index of the read sequence aligned to the reference; Rmapped_end means the end index of the read sequence aligned to the reference.

The figures show a part of the read aligned to different regions on the different stands of chr1. Please tell me how do sniffles identify INV from these kinds of reads?   Why do these multi-alignments generate?

More reads:
![Uploading image.png…]()

Looking forward to your reply!
Best wishes.

**Comment by fritzsedlazeck** [comment]
Hi @LinXialab ,
looks like normal split reads to me. This is when two segments of a read are aligned to two regions. This is expected especially for INV.  Its important to know that these are not the same segment of the read aligned twice, but different regions of the read. 

We recently published a review about SV calling: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1828-7 
I hope Fig1 explains it in greater detail.

Thanks
Fritz

**Comment by LinXialab** [comment]
Thanks, Fritz.

Please check the table I show in my first message. The first segment and second segment have overlap sequence of the read: the first segment is from the 28th base to 2186th base of the read, while the second segment is from the 203rd base to 12089th base. It suggested the 203rd base to 2186th base of the read were both mapped to two strands of the reference. (I used pysam to extract the information of alignment from bam file) 

To be honest, I still doubt whether it is commonly held...

Looking forward to your kind reply.
Best wishes.

**Comment by fritzsedlazeck** [comment]
Oh I overlook that. What mapper did you use?
Seems like there must be a repetative region. A little overlap sometimes happens...
Thanks
Fritz

**Comment by LinXialab** [comment]
Thanks, Fritz,

We used NGMLR to do the mapping. So do you suggest us to remove INVs found by sniffles which overlapped repeat regions?  

Best wishes!

**Comment by fritzsedlazeck** [comment]
Mhm I don't think its wrong. You probably need a PCR or so to be certain. For an INV its on the smaller side, but there is clearly a signal.
The reads do overlap partially but that doesn't mean the signal is wrong.. 
Hope that helps
Fritz

**Comment by LinXialab** [comment]
Thanks for your kind suggestion.
Sincerely.

Lin
