### ISSUE TITLE
Using Sniffles with minimap2

### ISSUE THREAD

**Issue by fffletcher** [fritzsedlazeck/Sniffles#189]
Hi there.

I am having some issues with using Sniffles with minimap2, the output is a vcf file with no variants called. I have also tried generating the bam file using --MD to output the MD tag as I red in another issue that this could be the problem. But I am getting the same results. 

When I use Sniffles on my ngmlr aligned bam file it is detecting a very minimal number of SVs (I think 8, and all on one chromosome).

I initially has aligned using ngmlr, but after viewing on IGV the read pileup is very low compared to when I align with minimap2. Ideally I would like to use Sniffles to call SVs in my minimap2 aligned file if this is possible. Could you help me out?

I am a PhD student, and very new to bioinformatics. Any help you could give would be greatly appreciated. Thank you!

**Comment by fritzsedlazeck** [comment]
What's your coverage? Sniffles just calls svs by default if it finds 10 supporting reads. You can lower this with the -s parameter.

Cheers
Fritz

**Comment by fffletcher** [comment]
Hi Fritz, thanks for getting back to me. 

I think the issue is with the minimap2 alignment specifically. I performed an alignment with BWA MEM and the two look very similar coverage wise. When I put the bwa aligned file through Sniffles it was able to call many variants with no modification of the -s parameter. But when I put through the minimap2 file there were no variants called. I'm wondering if there is some difference in the output bam files of bwa mem and minimap2 that means one doesn't work with Sniffles?

Thanks

**Comment by fritzsedlazeck** [comment]
yes bwa mem aligns the reads very differently than miniamp2 and ngmlr do. 
You need to check your coverage.

**Comment by fffletcher** [comment]
Hi again

Using samtools depth I tried to check my coverage, and the coverage at each position is coming back as 1. Is this maybe the issue?

Thanks

**Comment by fritzsedlazeck** [comment]
Is the coverage only at the start of the chr ? Or really across all? 

samtools depth my.bam | awk '{ sum += $3; n++ } END { if (n > 0) print sum / n; }’ 
that should give you the mean bp coverage without 0.

**Comment by fffletcher** [comment]
That is giving me an output of

0.849292

**Comment by oneillkza** [comment]
An average coverage of just under 1X will mean most regions aren't covered at all, and very few will have more than a handful of reads covering them. Doing any kind of variant analysis on such low-coverage data is going to be a frustrating and likely futile exercise.

**Comment by fritzsedlazeck** [comment]
Agree. The last thing you should check is if the # raw reads and genome size also gets you to that coverage level or if there is something off in the mapping. 
Cheers
Fritz

**Comment by kizzb** [comment]
Hi.
I have the same question about the result of Sniffles with minimap2, and use samtools depth, I get the result is also less than 1, just 0.940454. I think this may due to using two assembly to do the mapping with minimap2 , so, the average coverage less than 1, could you give some advice?
thanks

**Comment by fritzsedlazeck** [comment]
@kizzb can you elaborate on the pipeline?

**Comment by kizzb** [comment]
@fritzsedlazeck This is my pipeline by Snakemake. 

rule minimap2:
	message:"Aligning query to target"
	input:
		"{ref}.fa",
		"{que}.fa"
	output:
		"{ref}-{que}-minimap2.sam"
	shell:
		"""
		minimap2 -ax asm20 -A 80 {input} > {output}
		"""
		
rule samtools_sorted:
	message:"Sorted the bam file"
	input:
		"{ref}-{que}-minimap2.sam"
	output:
		"{ref}-{que}-minimap2.sorted.bam"
	shell:
		"""
		samtools sort {input} > {output} 
		"""		
		
rule samtools_calmd:
	input:
		"{ref}-{que}-minimap2.sorted.bam",
		"{ref}.fa"
	output:
		"{ref}-{que}-minimap2.sorted.baq.bam"
	shell:
		"""
		samtools calmd -bAr {input[0]} {input[1]} > {output}
		"""
		
rule sniffles:
	message:"Call SV"
	input:
		"{ref}-{que}-minimap2.sorted.baq.bam"
	output:
		"{ref}-{que}-minimap2.vcf"
	shell:
		"""
		sniffles --min_support 1 -m {input} -v {output}
		"""

the ref.fa and que.fa are two different assembly genome, and their sequence divergence is less than 5%. Then, after I added the arguments " --min_support 1 " in the Sniffles command, I got some SVs in the result rather than 0 that I said yesterday. But, there is another question, the number of SVs is too small, probably 4000, however I can get nearly 250000 SVs by using smartie-sv(blasr + printgaps) and nearly 500000 SVs by using minima2 + printgaps. Why there are so different among the results?

thanks

**Comment by fritzsedlazeck** [comment]
Thanks,
for the MD: you can get that with -MD on minimap2. 

I think samtools sort requires a bam file not a sam file. 

How much is the coverage after the minimap2 mapping?
What organisms is it?

Thanks
Fritz

**Comment by kizzb** [comment]
About these question:
I ues samtools sort to convert sam file to bam file,

the coverage is 0.999252

the ref is human, the que is chimpanzee

Thanks

**Comment by fritzsedlazeck** [comment]
Are you aligning 2 assemblies or a read set to the human reference? 

Thanks
Fritz

**Comment by kizzb** [comment]
I use 1 assembly  to the human reference.
Thanks


| |
Bin Zhou
Master Degree Candidate
|
|
Kunming Institute of Zoology (KIZ)
+86-18810912783
kizzhoub@163.com
32 Jiaochang East Road, Kunming.
650223
|
签名由网易邮箱大师定制
On 5/13/2020 21:12，Fritz Sedlazeck<notifications@github.com> wrote：

Are you aligning 2 assemblies or a read set to the human reference?

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
so you compare 1 assembly to the human reference right ? Yeah that is not what Sniffles is primary designed for. That explains why you see these different results. Sniffles if primary there for analyzing the reads mapped to a sample and show the difference of the sample in this regard. 
Thanks
Fritz

**Comment by kizzb** [comment]
Hi, Fritz


First of all, thank you for your help.If I merge two or more assemblies into a read set, does that work for Sniffles? If not, do you think there are another tool could do this? 


thanks
bin


| |
Bin Zhou
Master Degree Candidate
|
|
Kunming Institute of Zoology (KIZ)
+86-18810912783
kizzhoub@163.com
32 Jiaochang East Road, Kunming.
650223
|
签名由网易邮箱大师定制
On 5/13/2020 22:09，周斌<kizzhoub@163.com> wrote：
I use 1 assembly  to the human reference.
Thanks


| |
Bin Zhou
Master Degree Candidate
|
|
Kunming Institute of Zoology (KIZ)
+86-18810912783
kizzhoub@163.com
32 Jiaochang East Road, Kunming.
650223
|
签名由网易邮箱大师定制
On 5/13/2020 21:12，Fritz Sedlazeck<notifications@github.com> wrote：

Are you aligning 2 assemblies or a read set to the human reference?

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
You could try to use paftools from minimap2.
Cheers
Fritz

**Comment by kizzb** [comment]
OK, I will try. Thanks.


| |
Bin Zhou
Master Degree Candidate
|
|
Kunming Institute of Zoology (KIZ)
+86-18810912783
kizzhoub@163.com
32 Jiaochang East Road, Kunming.
650223
|
签名由网易邮箱大师定制
On 5/14/2020 10:33，Fritz Sedlazeck<notifications@github.com> wrote：

You could try to use paftools from minimap2.
Cheers
Fritz
