### ISSUE TITLE
--genotype does not output genotypes

### ISSUE THREAD

**Issue by dantaki** [fritzsedlazeck/Sniffles#19]
I aligned Oxford Nanopore (ONP) samples using [ngmlr](https://github.com/philres/ngmlr) with this command

```
ngmlr -t 4 -r <FASTA> -q <ONP_FASTQ> -o <out.sam> -x ont
```
I ran Sniffles with the following command

```
sniffles --genotype -m <sorted.bam> -s 5 -v <sniffles_sv.vcf> 
```

The output VCF I get does not have genotypes. The sites appear as such

> ./.:.:13

I notice get only `.` for the DR format field as well. 

To iterate, every site gets a `./.` genotype and `.` DR value. 

Running `sniffles --version` returns

```
sniffles  version: 1.0.3
```

Is genotyping currently supported for this version? Also can you run `sniffles` jointly with multiple samples? I tried `sniffles -m <1.bam> <2.bam> ..` and `sniffles -m <1.bam> -m <2.bam> .. ` and got error messages. 

Thanks for any help!

**Comment by fritzsedlazeck** [comment]
Thanks for letting me know. Version 1.3 had sometimes a seg. fault in the genotyping/ finalization. 
Could you try the newest version? I just updated to version 1.5
Also just in case: please use NGM-LR version 2.3

The multi sample calling is currently not supported. I am working on this and the recalling. 
If you like you can use e.g. SURVIVOR to combine the different samples. I often use SURVIVOR option 5 to do that. 
https://github.com/fritzsedlazeck/SURVIVOR

Thanks
Fritz

**Comment by dantaki** [comment]
Thank you for the speedy response. I downloaded the newest version and will update once the results are ready. 

The version of ngmlr is 

> ngmlr 0.2.3 (build: Mar 29 2017 16:26:30, start: 2017-04-29.18:10:57)

So I think that's the correct one.

**Comment by fritzsedlazeck** [comment]
Np. please keep me posted. 
Thanks
Fritz

**Comment by dantaki** [comment]
Updating `sniffles` to the newest version fixed the problem. Thanks for all the help.
