### ISSUE TITLE
Strange result

### ISSUE THREAD

**Issue by daeh0ng** [fritzsedlazeck/Sniffles#191]
Hi Fritz,

I have called SVs using Sniffles with NGMLR and 
got some strange results that a variant covers the whole chromosome.

For example, even though the length of chr5 is 104,526,007 bp, 
there were some variants as follow : 
```
5   4355    13688   N   <DUP>   .   PASS    PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=5;END=104507977;ZMW=28;STD_quant_start=0.462910;STD_quant_stop=0.000000;Kurtosis_quant_start=0.656683;Kurtosis_quant_stop=0.510958;SVTYPE=DUP;SUPTYPE=SR;SVLEN=104503622;STRANDS=-+;RE=29;REF_strand=29;AF=1  GT:DR:DV    1/1:0:29
5   9756    13689   N   <DUP>   .   PASS    PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=5;END=104517215;ZMW=12;STD_quant_start=7.078135;STD_quant_stop=3.286335;Kurtosis_quant_start=0.250713;Kurtosis_quant_stop=0.385215;SVTYPE=DUP;SUPTYPE=SR;SVLEN=104507459;STRANDS=-+;RE=14;REF_strand=14;AF=1  GT:DR:DV    1/1:0:14  
```
The read coverage for chr5 and all chromosomes was 62.55x and 60.32x, respectively.
The coverage for the regions not covered the SVs in chr5 was rather 33.75x. 
Could you comment on this pattern?

Sniffles command that I used is
`Sniffles-master/bin/sniffles-core-1.0.11/sniffles  -s 10 -l 50 -t 30 -v varinats.vcf -m merge.subreads.bam`

Many thanks in advance,

Daehong Kwon

**Comment by fritzsedlazeck** [comment]
Hi Deahong, 
is that human data? Apparently there are like 29 and 14 reads each supporting this. I usually only observe that in MT where this shows circularization. 

Its probably a mismapping of the reads. 
Thanks
Fritz
