### ISSUE TITLE
[Question] Sniffles to compare genomes

### ISSUE THREAD

**Issue by aderzelle** [fritzsedlazeck/Sniffles#192]
Hello,

I was just wondering how Sniffles would handle the following case: 
Let's say we have 2 genome assemblies and we want to compare them, would Sniffles perform reasonably well? (I am aware I would probably need to tweak some parameters such as the minimum number of supporting reads). I would align the 2 genomes with ngmlr. 

Have a good day.

**Comment by fritzsedlazeck** [comment]
Dear @aderzelle ,
Sniffles was not designed for this. However, I know that some people have already used it in this way. 
I would recommend to align the two genomes with minimap2 or some other tool. NGMLR is designed for long noisy reads and will considerably slow down with a good de Novo assembly. 

I hope that helps
Fritz
