### ISSUE TITLE
Output the same result in vcf

### ISSUE THREAD

**Issue by yuntwang** [fritzsedlazeck/Sniffles#193]
Hi
when I use Sniffles(the lastest version) to detect sv ,I get strange result:
Pp02	**20182978**	7673_0	N	<INV>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pp02;END=**20242690**;STD_quant_start=0.000000;STD_quant_stop=0.738549;Kurtosis_quant_start=6.194185;Kurtosis_quant_stop=5.820590;SVTYPE=INV;SUPTYPE=SR;SVLEN=59712;STRANDS=--;RE=67;REF_strand=0,0;AF=1	GT:DR:DV	1/1:0:67
Pp02	**20182978**	10516_0	N	<INV>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Pp02;END=**20242690**;STD_quant_start=0.316228;STD_quant_stop=3.974921;Kurtosis_quant_start=1.518824;Kurtosis_quant_stop=-0.039870;SVTYPE=INV;SUPTYPE=SR;SVLEN=59712;STRANDS=--;RE=13;REF_strand=0,0;AF=1	GT:DR:DV	1/1:0:13
The START and END  is consistent!
why?

**Comment by fritzsedlazeck** [comment]
That occured in the same VCF file?
Are you able to share the bam file for that chromosome?

**Comment by yuntwang** [comment]
@fritzsedlazeck 
Storage path: ftp://65.49.217.161/
username:yuanzw
passwd:123.bmk

**Comment by fritzsedlazeck** [comment]
I am not sure if I can reach this by just opening this link. Is this a sftp or something? 
Thanks
Fritz

**Comment by yuntwang** [comment]
@fritzsedlazeck 

The IP address is invalid, just replace it with this link ftp://yuanzw.top/
username:yuanzw
passwd:123.bmk
