### ISSUE TITLE
minimap2

### ISSUE THREAD

**Issue by woodoo46** [fritzsedlazeck/Sniffles#196]
Hi there,

I have read some post about minimap2 and sniffles; and I had set up --MD when I ran minimap2, but the results for sniffles are still different for minimap2 and ngmlr in terms of number of calls.  Any other parameters I need to pay attention? My current run is:

${minimap2} --MD -ax map-pb ${genome} ${query} -R '.....'

Thank you!

**Comment by fritzsedlazeck** [comment]
You will not get the same results for minimap2 and ngmlr. There are differences in their results and thus also in the sniffles results.
Cheers
Fritz
