### ISSUE TITLE
Support For CRAM Files

### ISSUE THREAD

**Issue by maegsul** [fritzsedlazeck/Sniffles#198]
Hi,

First of all, thanks a lot for developing this amazing tool!

I am mainly interested in looking at SVs in a WES dataset of ~450 samples. I know that WES data is usually not so suitable for SVs, but this attempt is very exploratory, let's say.

SV calls (at sample-level) were done with Manta on CRAM files previously, and I used [this pipeline](https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population) for generating a multi-sample VCF containing SVs:

`SURVIVOR merge vcf_files_raw_calls.txt 1000 1 1 -1 -1 -1 450samples_SURVIVOR_1kbdist_typesave.vcf`

Of note, vcf_files_raw_calls.txt contains Manta VCFs on single sample level. 

This worked very well (at least compared to my previous experience with bcftools merge by ID), and I ended up with 51413 SVs (171 of these non-singleton). Nevertheless, the next step for "Force call all the SVs across all the samples" that I want to use for filling ./. genotype information with reference genotypes if possible, I have an error:

`sniffles -m sample1.cram -v gt.sample1.vcf --Ivcf 450samples_SURVIVOR_1kbdist_typesave.vcf --threads 40 --genotype`

**Error** -> `BAM Parser: could not open file: sample1.cram`.

I believe this means sniffles does not support the usage of CRAM files. 

Because of storage issues and the way that the data was prepared, I have no option to convert all CRAMs to BAMs at this time. I would like to ask if there are any plans to add support for CRAM files? (though I am not sure how difficult it would be to add this feature)

Best,
Fahri

**Comment by fritzsedlazeck** [comment]
Dear @maegsul ,
Sniffles is designed for long reads. Not WES. 
As you said Sniffles is currently only supporting sorted bam files. Its a good suggestion to support CRAM files. 

Thanks
Fritz

**Comment by maegsul** [comment]
Thanks @fritzsedlazeck!

Indeed, Sniffles is designed for long reads and I also use it exclusively for long reads usually; but here I only wanted to try to use its ./. genotyping function on VCFs generated by Manta.

**Comment by fritzsedlazeck** [comment]
For genotyping SV we did recently published a benchmarked  but it was for short read WGS data:  https://academic.oup.com/gigascience/article/8/9/giz110/5565134 

Maybe you find some help in there.. 

Cheers
Fritz

**Comment by maegsul** [comment]
Thanks a lot @fritzsedlazeck , this looks great. I will have a look into this as soon as possible.
