### ISSUE TITLE
variant coordinates

### ISSUE THREAD

**Issue by jdmontenegro** [fritzsedlazeck/Sniffles#199]
Dear Fritz,

Thank you for a really useful tool. I have been playing with it and getting some great results in really complex regions of plant genomes.
One issue tough, the coordinates of the variants seem to be written using 0-based indexing, when the current VCF4.2 format uses 1-based indexing. Thus, when extracting the regions of interest I am getting 1bp off target sequences. This also prevents the use downstream tools like VG tools.
Although this could be done manually, I ave not double checked if the problem persists in other BND join points.
It would be very useful to correct the coordinates in the final VCF file and double check the join coordinates of the BND SVs.
All the best,
Juan D Montenegro

**Comment by fritzsedlazeck** [comment]
Dear Juan,
thanks for the issue. I have updated that and committed the changes. 
Please check it out.
Thanks
Fritz
