### ISSUE TITLE
IGV throws error on sniffles vcf

### ISSUE THREAD

**Issue by lexnederbragt** [fritzsedlazeck/Sniffles#2]
IGV 2.3.68 throws an error on a vcf file I created with sniffles: 

>Unable to parse header with error: Your input file has a malformed header: Unexpected tag "SUPTYPE" in line /path/to/file.vcf

At first I thought it was a typo, but changing SUPTYPE to SUBTYPE gave a similar error.

**Comment by fritzsedlazeck** [comment]
Hi Lex Nederbragt,
thanks for letting me know. 
If you erase these lines in your vcf file you can load it in IGV. 
##INFO=<ID=SUPTYPE,Number=1,Type=String,Description="What supports the SV.">
##INFO=<SUPTYPE=SP,Description="SV supported by split reads">
##INFO=<SUPTYPE=MD,Description="SV supported by MD string">
##INFO=<SUPTYPE=CI,Description="SV supported by Cigar string">

I commented them now also out in the src, just so others don't have that same issue. 

It is clearly no ideal solution but it seems to work. I will work on that issue for the next release. 
Let me know if it works for you.
Thanks,
Fritz

**Comment by lexnederbragt** [comment]
Yep, that solves it. Thanks!

**Comment by fritzsedlazeck** [comment]
Np. Let me know if there is any other issue/ question. 
I hope to provide an improved version soon. I am currently testing it.
