### ISSUE TITLE
question about "Clustering/phasing and genotyping" options

### ISSUE THREAD

**Issue by aseetharam** [fritzsedlazeck/Sniffles#202]
In the help page for SNIFFLES, there are options for allele frequency in the "Clustering/phasing and genotyping" section. Can you please tell me what exactly these options do?

``` 
    -f <float>,  --allelefreq <float>
        Threshold on allele frequency (0-1).  [0]
    --min_homo_af <float>
        Threshold on allele frequency (0-1).  [0.8]
    --min_het_af <float>
        Threshold on allele frequency (0-1).  [0.3]
```
Thanks very much!

**Comment by fritzsedlazeck** [comment]
Sure, sorry for not beeing clear. 
-f is used for filtering the candidate SV based on their frequency between reads that support the event and the total coverage 

The other 2 options are being used to change the behaviour when Sniffles reports an allele heterozygous vs. homozygous. 


Hope that helps
Cheers
Fritz

**Comment by aseetharam** [comment]
Thank you for the reply! Yes, it is very helpful!
