### ISSUE TITLE
long sv length larger than 100K is error?

### ISSUE THREAD

**Issue by holiday10** [fritzsedlazeck/Sniffles#203]
i found the SVlenth is larger than 100k, like 99999999, i know it was uncertain length, but for exact length sv bigger than 100k (Pacbio or ont long reads are shorter than 100k), so is those SV are error?

**Comment by fritzsedlazeck** [comment]
if its labeled as unresolved then the length is unknown. Given the VCF standard I need to put a number in there. Thus, I am using an arbitrary number for this event. 
Hope that helps
Thanks
Fritz
