### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by GokuAK** [fritzsedlazeck/Sniffles#204]
Hi,

I got a similar error trying to run sniffles on one human genome nanopore data (11 Gb), mapped using minimap2. 

sniffles -m /bam file/ -v /vcf file/ -s 2 -t 4 
resulted in this error:

Estimating parameter...
        Max dist between aln events: 9
        Max diff in window: 50
        Min score ratio: 2
        Avg DEL ratio: 0.0388139
        Avg INS ratio: 0.0288268
Start parsing... chr1
BUG: split read ins! 9159 5855 a472e554-5071-4459-861a-93c9aa8f9ce8
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 8249) > this->size() (which is 5855)
Aborted (core dumped)

will be thankful if you can advise what should I do to overcome the error?

Thanks

_Originally posted by @yusmiatiliau in https://github.com/fritzsedlazeck/Sniffles/issues/200#issuecomment-644528729_

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
