### ISSUE TITLE
SVLen qusetions about long long SV

### ISSUE THREAD

**Issue by holiday10** [fritzsedlazeck/Sniffles#205]
I feel confused about SVlenth larger than 10Kb or 100Kb (not 99999999), these SV larger than 3rd reads length. Are these long SVs truly believable  Variant length? @fritzsedlazeck

**Comment by fritzsedlazeck** [comment]
They are often real signials. It sometimes is a bit trickier in the interpretation.

A long deletion/INV (like 1Mbp+) can be a long lost segment or indicate that two regions are joint on a molecule (e.g. in cancer genomes)

I tried to differentiate these two but there is no signal that is generalizable. 
Thanks
Fritz

**Comment by yuntwang** [comment]
@fritzsedlazeck  I encounter many long long  length SV in single chromosom，like this：

CHR1 | POS1 | CHR2 | POS2 | SV | LEN
NC_037285.1 | 3434170 | NC_037285.1 | 49967311 | INV | 46533141
NC_037285.1 | 2634926 | NC_037285.1 | 46963338 | INV | 44328412
NC_037285.1 | 2126753 | NC_037285.1 | 42680354 | DEL | 40553601
NC_037285.1 | 5928472 | NC_037285.1 | 46084246 | INV | 40155774
NC_037285.1 | 7508128 | NC_037285.1 | 47625757 | DUP | 40117629
NC_037285.1 | 7508135 | NC_037285.1 | 47620788 | DEL | 40112653
NC_037285.1 | 2147940 | NC_037285.1 | 40745475 | INV | 38597535
NC_037285.1 | 3121690 | NC_037285.1 | 40630537 | DEL | 37508847

my command:
sniffles-core-1.0.11/sniffles -m  AA.sort.bam -v AA.vcf --genotype -s 10 --max_num_splits 7 -d 10000 -t 50 -l 50 -q 20 --cluster

WHY

**Comment by fritzsedlazeck** [comment]
Dear @yuntwang ,
It depends on your sample and organism. These events are often representing connections of the individual regions (meaning that reads are split by the mapper and aligned between them.). I have studied this back then and try to decipher if these are indeed long e.g. deletions or just connections (e.g. in cancer). There is currently no way to differentiate them in Sniffles. Thus the only way around I would have had was to set an arbitrary size cutoff that would not help either. 

I would investigate if (I think its a plant?) has some amplifications or large rearrangements.

**Comment by yuntwang** [comment]
@fritzsedlazeck  Its a plant.

**Comment by fritzsedlazeck** [comment]
so since its plant.. I think you should check if these are LTR sites. 
Otherwise its hard to interpret them sadly.. If they are not artifacts from the mapping they are likely some transposon events (would be my guess).

Thanks
Fritz
