### ISSUE TITLE
Preparing sniffles output for truvari processing

### ISSUE THREAD

**Issue by cjain7** [fritzsedlazeck/Sniffles#206]
Hi Frtiz,

I'm running a mapping + sniffles SV calling pipeline on HG002 ONT data, and would like to test it using truvari against the GIAB benchmark.

I got the sniffles vcf output and post-processed it using the recipe described here:
https://github.com/PacificBiosciences/sv-benchmark

However, I'm unable to run truvari, it seems like it is not liking the vcf format. I've also opened [an issue on truvari github page](https://github.com/spiralgenetics/truvari/issues/54). I'm sure you would have run NGMLR + sniffles on HG002 sample too; Is there a set of suggested commands to prepare sniffles SV calls for Truvari benchmarking? I'm running sniffles with parameters `-t 8 -n -1 -s 5`.

I'm following the [GIAB readme file](http://ftp-trace.ncbi.nlm.nih.gov/README_SV_v0.6.txt) on how to run truvari.

Thanks,
Chirag

**Comment by MeHelmy** [comment]
Hi!
Can you please try to run `sed -i 's/REF_strand,Number=2/REF_strand,Number=./g' yout.input.vcf` and rerun Truvari?

**Comment by fritzsedlazeck** [comment]
Hi Chirag,
this is a very old file.. I just checked on the github code and there the headers are fine. I think I fixed that recently as IGV never complained. 

Thanks
Fritz
