### ISSUE TITLE
STRANDBIAS not defined in header

### ISSUE THREAD

**Issue by proinde** [fritzsedlazeck/Sniffles#209]
Just as the title says. 

[W::vcf_parse] FILTER 'STRANDBIAS' is not defined in the header

**Comment by jaesvi** [comment]
I came to comment this same issue. It would be good to know how STRANDBIAS is defined.
Thanks.

**Comment by fritzsedlazeck** [comment]
Thanks for pointing this out. I will resolve it this week, just got slammed... 
Thanks
fritz

**Comment by ddrichel** [comment]
Just ran into the same issue with sniffles 1.0.12. Is there a solution or workaround available?

**Comment by fritzsedlazeck** [comment]
sorry for the late response (teaching + grant writing). I added the header line for the filter. Please check out the latest code. 
Thanks
Fritz

**Comment by ddrichel** [comment]
Thanks, the fix works and we can close the issue.

However, I would like to note that I consider the filter p<0.01 to be too strict.
Lets say we want to control for family-wise error rate (FWER) at significance threshold alpha 0.05 corrected for multiple testing.
I am using the HG002 ultra-long reads from GIAB consortium as an example. I get 36766 variants for which strand bias is tested.
The conservative Bonferroni threshold post-multiple testing is:
alpha=0.05/36766=1.36x10^-6
167 variants get filtered using this threshold, but
718 variants get filtered using p<0.01

This means 551 variants (~1.5%) get filtered as strand-biased, although their p-values are just what we expect under null hypothesis (no strand bias).

Something to keep in mind for now.
Thanks for the quick fix!

Dmitriy

**Comment by fritzsedlazeck** [comment]
Thanks Dimitriy I see your point. 
I made it conservative to account for coverage and to be honest that I can see how good/bad this measurement works. Its just to tag certain SV and the p-value is also reported in the end of the INFO field. 

Thanks
Fritz

**Comment by Akazhiel** [comment]
Hello!
Sorry to reopen this issue but when trying to sort the VCF file using `bcftools sort` it complained about the `STRANDBIAS` filter not being in the header.

`[W::vcf_parse_filter] FILTER 'STRANDBIAS' is not defined in the header`

Cheers!
