### ISSUE TITLE
Detection on Pooled Samples

### ISSUE THREAD

**Issue by shaldenby** [fritzsedlazeck/Sniffles#21]
Hi Fritz,

I was wondering if Sniffles is suitable for calling variants on pooled sample data, i.e. where there might be quite low frequency SVs? Or is it best suited to data from individuals?

Thanks very much in advance, and best wishes!

Sam

**Comment by fritzsedlazeck** [comment]
You would need to lower the default min support (-s) and be carful about it. I have never done that, but there is no point in the program where it assumes the data is a single diploid individual apart from the genotyping that you dont have to run.

Just to make sure: you have pooled Pacbio/ Nanopore data, right?

**Comment by shaldenby** [comment]
Thanks very much for the super fast response, and that's great news! Also, that's correct, we'll have PacBio data for this.

**Comment by fritzsedlazeck** [comment]
Cool. Just wanted to check.
Let me know if you need anything else. 
Fritz
