### ISSUE TITLE
Segmentation fault in Finalizing step

### ISSUE THREAD

**Issue by Jingwen7** [fritzsedlazeck/Sniffles#210]
Hi  @fritzsedlazeck

I'm running ngmlr and sniffles to call SVs. But a segmentation fault (core dump) shows in the finalizing step when run sniffles. Here are the commands I use: ngmlr -t 16 -x ont -r human_hs37d5.fasta  -q HG002.fastq -o HG002.ONT.ngmlr.sam; sniffles -t 32 --tmp_file /scratch2/jingwenr/TMP/  -m HG002.ONT.ngmlr.bam  -v human_hs37d5.HG002.sniffles.ngmlr.vcf. 
And this is the error:      Finalizing  ..
/var/spool/slurm/slurmd/spool/job7875864/slurm_script: line 25: 126227 Segmentation fault      (core dumped) sniffles -t 32 --tmp_file /scratch2/jingwenr/TMP/ -m HG002.ONT.ngmlr.bam -v human_hs37d5.HG002.sniffles.ngmlr.vcf
Do you know what might be the problem? Thank you very much!

**Comment by fritzsedlazeck** [comment]
Hi @Jingwen7 
Can you give me the last lines of what Sniffles writes to std out? So of the log file?

I am not 100% certain but I think its the tmp_file... I expect a filename not a directory maybe. This is probably on my side, but maybe give it a try and please let me know if that is the fix. 

The top file is not large and is usually written to the output file with a postfix and is cleared afterwards. 

Also 32 threads are not needed for Sniffles. 3 threads are sufficient. The rest is usually bound by the speed of the harddrive. 

Thanks
fritz

**Comment by Jingwen7** [comment]
Yes, it is the tmp_file. I just removed --tmp_file and then it worked! Thank you!!

**Comment by fritzsedlazeck** [comment]
perfect. No problem I should add a better error message. 
Thanks
Fritz

**Comment by Krannich479** [comment]
> Yes, it is the tmp_file. I just removed --tmp_file and then it worked! Thank you!!

I can confirm this solved the same issue for me.
