### ISSUE TITLE
Better format of the VCF output

### ISSUE THREAD

**Issue by biozzq** [fritzsedlazeck/Sniffles#211]
Dear @fritzsedlazeck 

I have some questions about the VCF generated by Sniffles. Hope you can take some time to help me. Thank you.
1, the sample name, Sniffles used the BAM input as the sample name, if possible, can use the SM: tag in BAM file.
2, For the PRECISE deletion, the first base of the REF allele was not identical with the reference sequence allele at that POS.
3, For the insertion, in my mind, the END tag should be the same with POS, however, they are different in the Sniffles VCF.
4, For the insertion sequences, how to generate the consensus from the supporting reads?

Sincerely,
Zheng Zhuqing

**Comment by malonge** [comment]
For point 4, you can use [Iris](https://github.com/mkirsche/Iris).

**Comment by fritzsedlazeck** [comment]
@1: yeah I can look into that. Not all bam files have that defined, but it would be good if I carry that forward if it is. 
@2: I am currently not fetching that as I am not using a reference. I want to fix that in a new version.
@3: That is the case, but I wanted to highlight if there is descrepency in the alignments. So Start and END POS highlights the range where the ins should occur. 
@4: yes as Mike said. 
Hope that helps.
Fritz

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
