### ISSUE TITLE
Bug report of forcing calling for latest Sniffles

### ISSUE THREAD

**Issue by qiuyixmm** [fritzsedlazeck/Sniffles#214]
According to the [issue 213](https://github.com/fritzsedlazeck/Sniffles/issues/213) , I download the latest sniffles (Sniffles-1.0.12a) to get a correct genotype for called SVs. When I do force calling for all the SVs across all the samples using below command:
 ./sniffles -m my_sample.bam -v my_sample_gt.vcf --Ivcf merged_SURVIVOR_1kbpdist_typesave.vcf

A error was reported and the error message was :
     Automatically enabling genotype mode
     Too few reads detected in my_sample.bam

Thanks!

**Comment by biozzq** [comment]
Hi，
You can try the latest pushed version (https://github.com/fritzsedlazeck/Sniffles/archive/master.zip).
For @fritzsedlazeck, if you have finished checking the header of VCF, I think it's better to creat a release tag with github.

Thanks,
Zheng Zhuqing

**Comment by qiuyixmm** [comment]
> Hi，
> You can try the latest pushed version (https://github.com/fritzsedlazeck/Sniffles/archive/master.zip).
> For @fritzsedlazeck, if you have finished checking the header of VCF, I think it's better to creat a release tag with github.
> 
> Thanks,
> Zheng Zhuqing

Hello，
    Thanks for your kind suggestion! I also tried the Sniffles of latest pushed version that you mentioned above. However, same error message, such as too few reads detected in my_sample.bam, was reported.

**Comment by proinde** [comment]
I am having the same issue with forced calling on the most recent push.

**Comment by fritzsedlazeck** [comment]
Sorry guys! I needed a break this month.. I hope you understand. 
Thanks all for reporting! 
Cheers
Fritz

**Comment by proinde** [comment]
I think this error has now been fixed with the latest commit 55220741139726dedd36763b647c859337031efa (Changed typsafe conversion for MQ to Forcecalling), yes? I'm trying it this morning and it seems not to have broken so far.

**Comment by qiuyixmm** [comment]
> I think this error has now been fixed with the latest commit [5522074](https://github.com/fritzsedlazeck/Sniffles/commit/55220741139726dedd36763b647c859337031efa) (Changed typsafe conversion for MQ to Forcecalling), yes? I'm trying it this morning and it seems not to have broken so far.

yes, it can run well.

**Comment by fritzsedlazeck** [comment]
Thanks everyone for checking and patiens. 
Cheers
Fritz
