### ISSUE TITLE
Segfault after calling

### ISSUE THREAD

**Issue by TomHarrop** [fritzsedlazeck/Sniffles#216]
Hi,

I'm getting a segfault running sniffles from commit 53b7500 on Ubuntu 20.04 with the following command:

```bash
sniffles \
    -m path/to/sorted.bam \
    -v path/to/sniffles.vcf \
    --tmp_file /path/to/tmp/tmpn81h96mu \
    -t 64 \
    &> logs/sniffles.log
```

I mapped the reads with `minimap2` using the `--MD` flag. 

Calling seems to finish but then sniffles segfaults. I can't see any problems in the output VCF and there's no error in the stdout/stderr. The final message is:

```
	Finalizing  ..
```

I've pasted the full output [here](https://gist.github.com/TomHarrop/961dd7347012d32fc0f42788bc3f7c43#file-sniffles-log-L47).

Thanks!

**Comment by wdecoster** [comment]
Does the 'logs' directory exist?

**Comment by TomHarrop** [comment]
Yeah, it does. The content of sniffles.log is what I posted in the link above. Sorry if I made it confusing where I snipped the paths.

**Comment by fritzsedlazeck** [comment]
Hi Tim,
can you leave out the tmp parameter and give that a try ? I think I saw that before that it causes problems. 

Thanks
Fritz

**Comment by TomHarrop** [comment]
Hi Fritz, yep, it does finish if I don't specify `--tmp_file`. Thanks for the help.

**Comment by fritzsedlazeck** [comment]
Thanks for the confirmation. The temp file is not large... So I never use that option :).
Thanks for letting me know
