### ISSUE TITLE
Discrepancies Between SVLEN and ALT Sequence Length

### ISSUE THREAD

**Issue by CharlesARoy** [fritzsedlazeck/Sniffles#217]
Hello Fritz,

I recently became aware that the SVLEN reported by Sniffles is often different than the sequence length occasionally listed under the ALT field. From what I can tell, this occurs quite frequently for all SV types. Do you know what's going on here? 

Here's an example DEL:
chr1    180869  6_0     **CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTAAC**     N       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr1;END=180956;STD_quant_start=43.2435;STD_quant_stop=36.5541;Kurtosis_quant_start=-0.496824;Kurtosis_quant_stop=-0.1426;**SVTYPE=DEL**;SUPTYPE=AL;**SVLEN=-87**;STRANDS=+-;RE=12;REF_strand=505;AF=0.0237624  GT:DR:DV        0/0:493:12

The actual length of the sequence is 107 bases, but Sniffles calls an SVLEN of -87. 

Here's an example INS:
chr1    136962  2       N       **GGCCGGTGTTTGAGGCAAGGGCCACGGCTGACCTCTGTCTGCGTGGGAGGGCGGTGTGAGACAATGGGGCTCGGGCTGACTCTCTCAGCGTGGGAGGCCGGTTGTGAGGCAAGGGGCTCGGGCTTGACCTCTCTCAGCGTGGGAGGGGCCAGTGTGAGGCAAGGCTCACACTGACCCTCTCAGCATTGGGAAGGGGCCGGTGTTGCAGACAAGGGCTCGGCTGACCTCTCTCAGCGTGGGA**       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr1;END=136974;STD_quant_start=18.0891;STD_quant_stop=46.8691;Kurtosis_quant_start=3.05857;Kurtosis_quant_stop=1.59888;**SVTYPE=INS**;SUPTYPE=AL;**SVLEN=178**;STRANDS=+-;RE=28;REF_strand=48;AF=0.583333      GT:DR:DV        0/1:20:28

The actual length of the sequence is 241 bases, but Sniffles calls an SVLEN of 178. 

Somewhat related to this, what are these sequences that Sniffles provides? Are they some kind of consensus generated from all the reads that support the existence of the SV?

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
