### ISSUE TITLE
Problem installing Sniffles on Mac OSX

### ISSUE THREAD

**Issue by CristianRiccio** [fritzsedlazeck/Sniffles#22]
Hi,
I tried installing Sniffles on my Mac, without success. I was wondering whether you could help me, please?

I have followed these steps:

wget https://github.com/fritzsedlazeck/Sniffles/archive/master.tar.gz -O Sniffles.tar.gz
tar xzvf Sniffles.tar.gz
cd Sniffles-master/
mkdir -p build/
cd build/

Then, for Mac, you suggest this: cmake -D CMAKE_C_COMPILER=/opt/local/bin/gcc-mp-4.7 -D CMAKE_CXX_COMPILER=/opt/local/bin/g++-mp-4.7 .. 

However, I don't have a 'local' folder in 'opt', only a 'X11' folder. However, in my '/usr/bin
', I have 'gcc' and 'g++'. So I tried the following command:

cmake -D CMAKE_C_COMPILER=/usr/bin/gcc -D CMAKE_CXX_COMPILER=/usr/bin/g++ .. 

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /opt/local/bin/gcc-mp-4.7 
Build flags: 
Id flags: -c 

The output was:
No such file or directory

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /opt/local/bin/gcc-mp-4.7 
Build flags: 
Id flags: -Aa 

The output was:
No such file or directory

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /opt/local/bin/gcc-mp-4.7 
Build flags: 
Id flags: -D__CLASSIC_C__ 

The output was:
No such file or directory

etc.

It seems that I do need to get '/opt/local/bin/gcc-mp-4.7' and '/opt/local/bin/g++-mp-4.7'. Do you know how I could do this?

Thanks.

Best wishes,

Cristian.

**Comment by fritzsedlazeck** [comment]
Hi Cristian,
I think you need to set up the gcc in a proper way:
http://www.ficksworkshop.com/blog/post/installing-gcc-on-mac

and then this should work out of the build directory. Please delete and create the directory again.
cmake -D CMAKE_C_COMPILER=/opt/local/bin/gcc-mp-4.7 -D CMAKE_CXX_COMPILER=/opt/local/bin/g++-mp-4.7 ..

Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
It might be also easy to check out bioconda for installing:
https://bioconda.github.io/recipes/sniffles/README.html
Cheers
Fritz

**Comment by CristianRiccio** [comment]
Hi Fritz,
Thank you for answering my questions. I tried installing gcc with macports and then use the cmake command but that did not work. I tried 'conda install sniffles' but that also failed. But then, taking inspiration from my NGM-LR installation, I used 'conda install --channel https://conda.anaconda.org/bioconda sniffles' and it seems to have worked. 
Best wishes,
Cristian.

**Comment by fritzsedlazeck** [comment]
Hi Cristian,
awesome that it worked.
Thanks
Fritz
