### ISSUE TITLE
sniffles failed detect SV on minimap2 aligments

### ISSUE THREAD

**Issue by malaria123** [fritzsedlazeck/Sniffles#221]
Hi Fritz,
I am having issues when using sniffles to analyze minimap2 alignments. Thought here maybe a better place to ask you than email you directly.
Sniffles still runs with my data but the VCF generated is not valid.
here is my code
(base) flprntst:~ xuzhang$ sniffles -m g91minimap_sorted.bam -v g91minimap2.vcf
Estimating parameter...
	Max dist between aln events: 13
	Max diff in window: 50
	Min score ratio: 2
	Avg DEL ratio: nan
	Avg INS ratio: nan
Start parsing...
		# Processed reads: 10000
		# Processed reads: 20000
		# Processed reads: 30000
		# Processed reads: 40000
		# Processed reads: 50000
		# Processed reads: 60000
		# Processed reads: 70000
		# Processed reads: 80000
		# Processed reads: 90000
		# Processed reads: 100000
		# Processed reads: 110000
		# Processed reads: 120000
		# Processed reads: 130000
		# Processed reads: 140000
Finalizing  ..

Thanks a ton in advance.

**Comment by fritzsedlazeck** [comment]
Can you elaborate on the VCF file ?

**Comment by fritzsedlazeck** [comment]
Is that capture data or something ? Human?

**Comment by malaria123** [comment]
it is nanopore data on malaria parasites

**Comment by malaria123** [comment]
minimap2 --MD -a reference.fasta reads.fastq > output.sam
samtools generated bam and sorted bam

**Comment by fritzsedlazeck** [comment]
Ah makes sense looking at your username :). 
Looks good. 

So what is wrong with the VCF file ?
And if you could check what version of Sniffles you are using. 

Thanks
Fritz

**Comment by malaria123** [comment]
the size of VCF is really small and IGV could not read it.
Thanks,
Xu

**Comment by fritzsedlazeck** [comment]
Can you send it to me so I can take a look? fritz.sedlazeck@gmail.com 
Thanks
Fritz

**Comment by malaria123** [comment]
sent

**Comment by fritzsedlazeck** [comment]
Thanks yeah you dont have calls in that VCF file. Do you know how much coverage you have ? 
You probably need to reduce the default threshold (-s 3) . 

Also can you confirm that you didn't get any error from Sniffles when you ran it?
Thanks
Fritz

**Comment by malaria123** [comment]
When I use ngmlr the sniffles worked. The coverage it more than 90%
The code I sent on the github is exactly what it generated, I don’t  think there any error


Xu Zhang PhD
Postdoctoral Associate,
Department of Microbiology and Immunology
Weill Cornell Medicine
1300 York Avenue, Box 62
New York, NY 10065
Telephone: (212) 746-4971

**Comment by fritzsedlazeck** [comment]
Would it be possible to share the bam file with me? 
The only thing that is left to check is if your per bp coverage is low in which case you can run the -s 3 and see if you find SV in your VCF file. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Thanks for sending the bam file. Just to make sure, the one you sent me was not sorted. I have sorted it now and Sniffles seems to run normal. 

I think the one you ran was also not sorted, because the AvgDEL was nan and your output was much smaller. 
Cheers
Fritz
