### ISSUE TITLE
Genotyper Error 

### ISSUE THREAD

**Issue by mariamurach** [fritzsedlazeck/Sniffles#228]
I got this error on Sniffles version cloned today: 

Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!
Warning @Genotyper:refrence coverage. Please report this!

Is there a workaround for this issue? 

Btw - typo in "refrence".

**Comment by GerardGH** [comment]
Same warning here, Sniffles version 1.0.12

**Comment by javiercguard** [comment]
Hi, this warning persists with a version built on March, 5th, 2021. Variants appear to be correctly genotyped, though. 
Since is just a warning, can it be ignored?

**Comment by elcortegano** [comment]
Just had the exact same error with version 1.0.12.

**Comment by genotyper** [comment]
Hi.  I am not the author of 'genotyper' software, which I think you are referring to.  'genotyper' is my username.  Best wishes.

**Comment by fritzsedlazeck** [comment]
@genotyper sorry coincidence.

**Comment by fritzsedlazeck** [comment]
I have a solution. I am just tracking down some other details over the next few days . 
Thanks everyone for their patience. 
Cheers
Fritz

**Comment by junmiee** [comment]
> I have a solution. I am just tracking down some other details over the next few days .
> Thanks everyone for their patience.
> Cheers
> Fritz

HI,I have the same warning.I was wondering what's the reason for this report.Have you figured out the solution?
Greets
Junmiee.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
