### ISSUE TITLE
extremely long SVs detected (>20Mb)

### ISSUE THREAD

**Issue by eldariont** [fritzsedlazeck/Sniffles#23]
Hi Fritz,

I applied Sniffles (1.0.6) on one simulated dataset of mine (100 deletions simulated in hg19, chr21+chr22). Sniffles detected many deletions correctly but also outputted several super-large (and in my opinion incorrect) SVs. See the IGV screenshot below (top row: implanted deletions, bottom row: detected SVs from Sniffles)

![screenshot](https://user-images.githubusercontent.com/6477692/29172723-204076ea-7de1-11e7-9395-50453d4d17b9.png)

Two examples from the VCF output:
`chr21	11004164	7	N	<DEL>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.6;CHR2=chr21;END=32799278;STD_quant_start=0.935414;STD_quant_stop=0.707107;Kurtosis_quant_start=0.102041;Kurtosis_quant_stop=-1.000000;SVTYPE=DEL;SUPTYPE=SR;SVLEN=21795114;STRANDS=+-;RE=8	GT:DR:DV	./.:.:8`
`chr21	11142297	11	N	<DUP>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.6;CHR2=chr21;END=31923593;STD_quant_start=5.196152;STD_quant_stop=1.154701;Kurtosis_quant_start=0.000000;Kurtosis_quant_stop=0.000000;SVTYPE=DUP;SUPTYPE=SR;SVLEN=20781296;STRANDS=-+;RE=3	GT:DR:DV	./.:.:3`

I probably made some mistake here but cannot find it. Have you seen something similar before?

This is my pipeline:
1. mapping reads with ngm-lr onto hg19
2. samtools sort (query-sort) on bam
3. sniffles -s 5 -t 5 -v VCF (-s 2 gives similar result)

**Comment by fritzsedlazeck** [comment]
Hi,
thanks for pointing this out. 
the -s defines the minimum number of reads supporting an event before it is called. Thus -s2 should give the same results then -s 5. 

I usually use -s 10 to get a robust set of SV calls. Apart from that everything looks good. Would you mind sharing the bam file such that I can take a look and also check if there is something going on with NGMLR?

What might interest you is also the -n parameter. This gives you the read names that support the deletion. I often use this to check strange SV in IGV.

Thanks,
Fritz

**Comment by eldariont** [comment]
Hi,
sure, here are:

- the BAM file: https://ws.molgen.mpg.de/ws/493381/ngmlr.chained2.sorted.bam
- the location of the simulated deletions (the insertions in the file are regions that have been moved to a different region so that they are, for this purpose, deletions, too): https://ws.molgen.mpg.de/ws/005664/deletions_and_insertions_from.bed
- the Sniffles calls: https://ws.molgen.mpg.de/ws/263535/sniffles.ngmlr.s5.vcf

Thanks for the hint with the -n parameter! It turns out that (at least for one big detected deletion I have looked at) there are reads that map to both sides of the SV. That would be all fine if the two mapping locations wouldn't be so far apart. But maybe you can find out more with the files :)

Cheers, David

**Comment by fritzsedlazeck** [comment]
Hi David,
yes, I was more expecting an alignment artifact. NGMLR improves things a lot, but we still see sometimes noisy events... Thats why I keep the -s to 10 (default) most of the time...

Thanks for the files.
Fritz

**Comment by eldariont** [comment]
Hi Fritz,

I would like to hear your opinion on the following scenario: Let's say there is an intra-chromosomal duplication (e.g. a LINE) that copied the sequence of chr1:44,000,000-44,007,000 to another place in that same chromosome (e.g. at chr1:100,000). And let's say there is a read covering that insertion location such that the two read tails map left and right of the insertion location but the middle part maps to the source region of the duplication. Would Sniffles call a deletion between chr1:100,000-44,000,000?

I'm asking because I think this might be behind some of the very large deletion calls described above. I'm seeing this not only for simulated data: From the NA12878 PacBio data, Sniffles (with -s 10) reports 175 deletions >1Mb with the largest having a size of 78 Mb.

Cheers
David

**Comment by fritzsedlazeck** [comment]
Hi David,
thanks for reaching out. Yes that is indeed a problem. I looked into this for a long time and did not find a satisfying solution. The DEL or INV if they are very large can indicate exactly this. 

The problem is that there is no difference in the signal for me apart from the length. Thus, I did not want to set an arbitrary threshold. 

I hope that helps
Fritz
