### ISSUE TITLE
end is smaller than start in vcf files

### ISSUE THREAD

**Issue by Jingwen7** [fritzsedlazeck/Sniffles#231]
Hi Fritz, 

Here is a INS entry from the vcf file generated by sniffles. But the end pos is smaller than the start pos. Is this a bug? I notice there are a few such entries in the vcf, not just one. Thank you in advance!

2       **158189**  2467    N       CCTCCTTTCCGCTGCTTGGAGAGGGCATAATTGTGGAAATATTGGCACCCATTGGTTCATGTTTACACCCTTTTTCAATCTTCTTTTGGACCATTTGGTTGAAGCGGGGGGGTCCCTAATTAGTTTGAAGAAGTCGGGGGGCATGCTGGATTAGGGGTTAGACTCTGAGGTCACCTGTAGGGCATAAATCACGACTGTTTACATAATGCGAGTTGTCCCTCTAAAATGAAAGGAGTTTTGTACATATGGCACTTCACTCCATTTTGCATTCTTTTTCTACAAAAGAGATCTAGCTGTAAGATGGTGGTTAAAATTAATCTTCCTCAGGAGCCCAGGTTTCTCCCCCTAGAAGGATATCATGGCCAGGAGGTACTGCAGAAGAATATAAGTCATTCTTTCTTAAGTCTGATGGTCAATATTGGTCTCAATTCTCCAGAATACATCTTAGGGTGTTTTTTTGCCTTGGGGGGAACATTTCCATCCTTAAAAAAGAACATAGGGATCCAGCACCCCTAGTCATTTCCAATGAGATTAGTCCTATGCATCCTCACATGGTCCCCTAATGCATATTCTTTCCAGGGTGCAAAACCACCCACGGAACCACTGCTTATCGAT .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=2;**END=158188;**ZMW=25;STD_quant_start=1.000000;STD_quant_stop=6.239277;Kurtosis_quant_start=9.961837;Kurtosis_quant_stop=8.589612;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=617;STRANDS=+-;STRANDS2=14,15,14,15;RE=29;REF_strand=80,74;Strandbias_pval=0.839969;AF=0.188312    GT:DR:DV        0/0:125:29

**Comment by Jingwen7** [comment]
FYI, the  "**"  around END==158188 is just highlighting.

**Comment by fritzsedlazeck** [comment]
Thansk for reaching out. 
What version of Sniffles did you use ? You are right it should be the same position or maybe a bit larger since its an INS. I am just thinking I took care of this already in an older version. Please let me know. 

Thanks
Fritz

**Comment by probalica19** [comment]
Hi @Jingwen7 , @fritzsedlazeck , 

I am experiencing a similar problem. I am using Sniffles 1.0.12, and seeing these errors:

1. The end pos is smaller than the start pos:

```
1	73641001	1287	N	]17:34796976]N	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=17;END=34796976;STD_quant_start=389.715281;STD_quant_stop=19.192012;Kurtosis_quant_start=-0.000119;Kurtosis_quant_stop=-0.407579;SVTYPE=BND;SUPTYPE=SR;SVLEN=1;STRANDS=-+;STRANDS2=1,2,1,2;RE=3;REF_strand=0,1;Strandbias_pval=1;AF=1	GT:DR:DV	1/1:0:3
```

2. `STRANDBIAS` filter sometimes gets merged to the `INFO` column, and when later I try to parse that record, I get errors. Here is an example of such a record:

```
14	106214609	1316	N	]KI270726.1:25354]N	.	STRANDBIAS;AF=1	GT:DR:DV	1/1:0:18
```

3. `STRANDBIAS` filter also sometime ends up in the `CHROM` column, and later when I try to pare this record, I get the error that that contig is not defined in the header, e.g. : 

```
KI270728.1STRANDBIAS	1257	N	<INV>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=KI270728.1;END=1183908;STD_quant_start=6.046119;STD_quant_stop=4.068852;Kurtosis_quant_start=2.041167;Kurtosis_quant_stop=0.699158;SVTYPE=INV;SUPTYPE=SR;SVLEN=33;STRANDS=--;STRANDS2=0,9,9,0;RE=9;REF_strand=9,0;Strandbias_pval=4.11353e-05;AF=1	GT:DR:DV	1/1:0:9
```

This is the command I used to generate this VCF file:

```
/opt/Sniffles-1.0.12b/bin/sniffles-core-1.0.12/sniffles --mapped_reads /path/to/sample.sorted.bam --vcf sample..vcf --min_support 3 --minmapping_qual 20 --min_seq_size 1000
```

Thanks!
probalica

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
