### ISSUE TITLE
 Interpretation of SV event Interpretation(./.:0:0 )

### ISSUE THREAD

**Issue by samll-rookie** [fritzsedlazeck/Sniffles#232]
1、I run the following command：
sniffles-core-1.0.11/sniffles --mapped_reads 400.bam --vcf 400.vcf --min_support 2 --threads 4

２、I get my  following results :
Chr01   1       1       N       N[Chr14:21016695[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=-+;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0
Chr01   1       2       N       N[Chr07:12872244[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=-+;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0
Chr01   1       3       N       N[Chr06:41919152[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=--;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0
Chr01   1       4       N       N[Chr07:27279913[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=--;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0
Chr01   5       5       N       N[Chr05:12789427[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=-+;SEQ=;RE=1;REF_strand=0;AF=1      GT:DR:DV        ./.:0:1
Chr01   6       6       N       N[scaffold_99:331[      .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=-+;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0
Chr01   6       7       N       N[Chr16:18946428[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=--;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0
Chr01   6       8       N       N[Chr10:13421205[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=-+;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0
Chr01   10      9       N       N[Chr13:45873015[       .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;SVTYPE=BND;SUPTYPE=input;SVLEN=0;STRANDS=--;SEQ=;RE=0;REF_strand=0;AF=0      GT:DR:DV        ./.:0:0

３、./.:0:0 ;  ./. :Missing SV event
　    I want to know why this SV was reported without reads support(0:0)
       Or  there is a mistake in my understanding

**Comment by wdecoster** [comment]
Try running with `--genotype`

**Comment by fritzsedlazeck** [comment]
Thanks for reaching out. Could you try the latest code ? It is hard for me to guess what is going on in an old version.
Thanks
Fritz

**Comment by samll-rookie** [comment]
> Thanks for reaching out. Could you try the latest code ? It is hard for me to guess what is going on in an old version.
> Thanks
> Fritz

OＫ，Thank you.
Besides, I have another question.I found that the RE of an SV event is negative.What is the reason
E.g : Chr04	33843509	506505	N	<INS>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=Chr04;END=33843509;SVTYPE=INS;SUPTYPE=input;SVLEN=889;STRANDS=+-;SEQ=;RE=-31937;REF_strand=0;AF=0	GT:DR:DV	./.:0:-31937

**Comment by fritzsedlazeck** [comment]
that I have never seen before. What version are you using ? and what coverage do you have ? 
Thx
Fritz

**Comment by samll-rookie** [comment]
> that I have never seen before. What version are you using ? and what coverage do you have ?
> Thx
> Fritz
The version I used for analysis is sniffles-core-1.0.11；Sample coverage is close to 45X.(genome size:1G;fastq data:45G)

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
