### ISSUE TITLE
BAM Parser: could not open file:file.bam

### ISSUE THREAD

**Issue by ashajacob29** [fritzsedlazeck/Sniffles#233]
Hi,

I have used sniffles on a different dataset which worked fine and I get the following error, when running the same command on different set of BAMs. Initially it said MD tag was not present so, I created BAMs with MS tags using samtools. But sniffles keep giving me the error.

Command:
sniffles -m MDtag_bams/R-HT96-P0_DEDUPED_REALIGNED_MD.bam -v R-HT96-P0_DEDUPED_REALIGNED.vcf

Error:
BAM Parser: could not open file: MDtag_bams/R-HT96-P0_DEDUPED_REALIGNED_MD.bam

I do have access to BAM files and can view them perfectly fine through samtools.

I also tried piping it through samtools like this: samtools view -h MDtag_bams/R-HT96-P0_DEDUPED_REALIGNED_MD.bam | sniffles -m - -v R-HT96-P0_DEDUPED_REALIGNED.vcf

Error:
BAM Parser: could not open file: -

Am I missing anything here? Kindly help.

Thanks,
Asha

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
