### ISSUE TITLE
--report_seq ; Couldn't find match for argument

### ISSUE THREAD

**Issue by WeijiaSu** [fritzsedlazeck/Sniffles#236]
Hi @fritzsedlazeck 
I am trying to use Sniffles, I got the error when I set --report_seq option, it shows "Couldn't find match for argument".  It could run once this "--report_seq" option is removed.  I wonder how can I get the seq reported with the options?
Thanks
Weijia

**Comment by fritzsedlazeck** [comment]
Its now reported by default. 
Thanks
Fritz

**Comment by WeijiaSu** [comment]
Hi, Thanks for your reply.  I thought by default, the vcf infor column should report the sequence, as explained in the wiki. "SEQ= | If reportable shows the sequence of the indels."  However, for the insertions, I always get output like this:
3R	16081445	21587	N	GCCAGCACAGAATGGGTAGGCGAAAGGTAACAGGTCGCGGCCA	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=3R;END=16081445;STD_quant_start=0.000000;STD_quant_stop=0.000000;Kurtosis_quant_start=-nan;Kurtosis_quant_stop=-nan;SVTYPE=INS;RNAMES=ed345872-6847-449b-a39d-77a289427d77;SUPTYPE=AL;SVLEN=43;STRANDS=+-;STRANDS2=0,1,0,1;RE=1;REF_strand=17,24;Strandbias_pval=1;AF=0.0238095	GT:DR:DV	0/0:41:1

Is the inserted sequence represented as column #5 ? Since there is no SEQ= in the info column.  
Thanks

**Comment by fritzsedlazeck** [comment]
yeah the VCF standards say you should put it in that column depending what it is. 
Thanks
Fritz
