### ISSUE TITLE
Large negative transversion values

### ISSUE THREAD

**Issue by signor-molevol** [fritzsedlazeck/Sniffles#238]
Hello,

I am running sniffles on several genotypes using -b as output and I am consistently getting an issue with large negative values for a transversion, as follows: 

Scf_2L	0	-1721995088	TT00_mitochondrion	-739636762	0	17188	-1	-	-	TRA	23	Scf_NODE_105063	1	Scf_NODE_71522	1	10546656	PRECISE
Scf_2L	0	-1721995088	TT00_mitochondrion	-441672594	0	17191	-1	+	-	TRA	17	Scf_NODE_109412	8248	Scf_NODE_49804	50	7411655	PRECISE
Scf_2L	0	-1721995088	Scf_2L	272	0	17192	-1	-	+	TRA	22	Scf_NODE_110248	1	Scf_NODE_14939	205	2307728	PRECISE
Scf_2L	0	-1721995088	TT00_mitochondrion	-441672594	0	17198	-1	+	-	TRA	20	Scf_NODE_11432	1689	Scf_NODE_48475	65	6799396	IMPRECISE
Scf_2L	0	-1721995088	TT00_mitochondrion	-441672594	0	17204	-1	+	-	TRA	16	Scf_NODE_11900	742	Scf_NODE_60358	1	7936443	PRECISE
Scf_2L	0	-1721995088	TT00_mitochondrion	-441672594	0	17211	-1	-	-	TRA	27	Scf_NODE_13173	1	Scf_NODE_80707	1	9464367	PRECISE

I am a bit flummoxed as to how to interpret this output. If you have any guidance it would be appreciated.

**Comment by fritzsedlazeck** [comment]
Oh can you try the VCF output? I have abandoned the bedpe output...  I can check it out later. 

Thanks
Fritz

**Comment by signor-molevol** [comment]
Ok, sure, thanks for the heads up. No worries then about looking into it.
