### ISSUE TITLE
Problem while running code for Sniffles

### ISSUE THREAD

**Issue by agnibhat** [fritzsedlazeck/Sniffles#239]
Hi, 

I was able to install Sniffles successfully, but encountered a problem when running the code on the terminal of MacOS. I used the following code

./sniffles -m S1_sorted.bam -v S1.vcf --report_BND --report_seq

When I run this, I get the following message: 

-bash: ./sniffles: No such file or directory

Could you help and tell where I am going wrong? Thanks!

**Comment by fritzsedlazeck** [comment]
./ means you are starting it from the current folder. and the error msg means that this file is not in your current folder. 
Cheers
Fritz

**Comment by agnibhat** [comment]
Thanks Fritz!
