### ISSUE TITLE
Can I run Sniffles for detecting somatic SV?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [fritzsedlazeck/Sniffles#240]
Hi,
I am wondering that can I run Sniffles for paired control-tumor sample, and obtain the somatic SV through the subtraction of normal sample and tumor sample?
Is Sniffles designed for germline SV detection?

Thanks,
Charlie

**Comment by fritzsedlazeck** [comment]
The way you would need to do this is to run Sniffles independently for each sample and then merge the results with eg. SURVIVOR. 
Subsequently, you could re-genotype the merged VCF file with Sniffles to make sure a potential unique SV is indeed not found in the other sample. 

So yes it is possible. :)  
Fritz

**Comment by Akazhiel** [comment]
Hello!

Just asking since I'm also interested in calling somatic SV. How do I re-genotype de Tumor-Control merged VCF file using Sniffles?

Cheers!

**Comment by fritzsedlazeck** [comment]
check out the option --Ivcf and provide the merged VCF file.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
