### ISSUE TITLE
genotype problems

### ISSUE THREAD

**Issue by dong571** [fritzsedlazeck/Sniffles#241]
accroding this (https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population) :
the second round of sniffles: SURVIVOR merge   results:

all 15 samples are Support,  
![图片](https://user-images.githubusercontent.com/69720384/100234672-60ac3400-2f66-11eb-9b72-b259f68423ef.png)

However,why genotype  are 0/0, in my view of point ,should it all be 0/1?
![图片](https://user-images.githubusercontent.com/69720384/100234883-a963ed00-2f66-11eb-8ccd-2302110d3d67.png)
Thank you .

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
