### ISSUE TITLE
Difference of Sniffles on pbmm2 and NGMLR

### ISSUE THREAD

**Issue by jiadong324** [fritzsedlazeck/Sniffles#242]
Hi Fritz,

I am using Sniffles for SV calling based on pbmm2 and ngmlr. I found significant different between calls (see example in IGV), where the green and red boxes were calls made by Sniffles. Afterwards, I noticed that the difference might come from the format of CIGAR string, where pbmm2 uses '=/x' for 'M' in the alignment. 

![image](https://user-images.githubusercontent.com/6951612/100958598-9e592000-3557-11eb-9994-a73520e194b6.png)

**Comment by jiadong324** [comment]
@fritzsedlazeck I have used calmd to add MD tag to pbmm2 aligned BAM, but I do not know if samtools can recompute the CIGAR string. Btw, pbmm2 actually fixed parameter --eqx in minimap2 to enable '=/x' in CIGAR string.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
