### ISSUE TITLE
Discrepancy between deleted sequence in REF field and actual reference sequence

### ISSUE THREAD

**Issue by malemay** [fritzsedlazeck/Sniffles#243]
Hi,

My issue is somewhat related to issue #217.

I have noted that there is often an offset of a few nucleotides between the sequence reported in the REF field for deletions and the actual reference sequence starting at POS.

My main concern is to know which is right: the positions reported in the POS and INFO fields, or the sequence reported in the REF field? My assumption is that the deleted sequence was inferred from the reads somehow (although I wonder how if the sequence is deleted?) and not from the reference sequence, and therefore the positions in POS and INFO fields are right. This would make sense given that Sniffles does not even take the reference genome as input, and thus would have no way to query the missing sequence.

I have also noted the issue reported in #217, namely that there is a mismatch between the length of the sequence in the ALT field and the length reported in the INFO field for insertions.

Thank you,

Marc-André

**Comment by clairemerot** [comment]
Hello I encounter the same issue with the output of Sniffles. Has there been any progress on that matter to understand why that happens and how to solve it? 
The difference of a few nucleotides is not always the same between SVs and it creates some uncertainty when trying to extract alternative sequence and flanking sequences, as well as to run genome-graph programs such as vg.
Thanks!
Claire

**Comment by kpalanikannan** [comment]
The same issue noticed.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
