### ISSUE TITLE
Sniffles reports non-zero SVLEN for inversions

### ISSUE THREAD

**Issue by ielis** [fritzsedlazeck/Sniffles#245]
Dear dr. Sedlazeck,

I was running Sniffles v1.0.12 and I noticed that the inversion calls contain non-zero value in `SVLEN` field. I think that this might not be in line with VCF specs, where `SVLEN` is described as _Difference in length between REF and ALT alleles_. Since simple inversions are balanced rearrangements, there should be no difference in length between alleles.

All the best,
Daniel

**Comment by fritzsedlazeck** [comment]
Dear @ielis 
This is at least intended from Sniffles. So its for sure not a bug. I think and see also other variant caller report it this way. 
So I think it is fine. 
Thanks for reaching out. 
Fritz
