### ISSUE TITLE
END tag conflicts with vcf spec and bcftools in case of interchromosomal BND

### ISSUE THREAD

**Issue by johannesgeibel** [fritzsedlazeck/Sniffles#247]
Hi Fritz,
I did run across this problem quite frequently for a series of SV related tools, that's why I report it. Bcftools is quite strict with END tags since some time and fails indexing vcf.gz files when END is smaller than POS even if it is an interchromosomal BND. The VCF specifications actually seem to state that the END tag is not valid in case of interchromosomal BNDs and they therefore want to keep this behavior:
https://github.com/samtools/bcftools/issues/1153
https://github.com/samtools/bcftools/issues/1154
For my use cases, I've written a short awk script which corrects for this problem, but it could hurt others, too.
Hope this helps improving your tools,
Johannes

**Comment by fritzsedlazeck** [comment]
Hi Johannes,
thanks for that. I just checked : at some stage I must have commented that condition out when printing BND... I just pushed th e correction. Maybe you can check it out, but if your scritp already works it might not be worth the hussle.

Thanks
Fritz

**Comment by johannesgeibel** [comment]
Hi,
thanks for the fast response. It seems to work now.
