### ISSUE TITLE
what is the recommended annotation tools after SV calling?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [fritzsedlazeck/Sniffles#248]
Hi,

I am wondering the recommended gene annotation tools after SV calling, to estimate the SV effect on human genes mutation.

**Comment by Mmark94** [comment]
Are there any updates on this topic?

**Comment by fritzsedlazeck** [comment]
I am often using vcfanno. That's for overlapping sv with gene annotation. There are now a few tools that also allow to use population information. I wasn't happy with these results, but maybe they have improved. ( Eg pathogenic annotation from high support over 1000genome data. )

**Comment by Mmark94** [comment]
Thanks for the answer, I will try to use vcfanno.

**Comment by hd00ljy** [comment]
AnnotSV is quite convenient for human SV annotation, especially for germ-line variants

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.

**Comment by charliechen912ilovbash** [comment]
Thanks!!
I couldn't install the new version with `conda install sniffles`. I installed it successfully with `pip install sniffles`.

**Comment by fritzsedlazeck** [comment]
Thanks yes, the conda package is commited but seems not to be released yet... that's some difficulties on the conda side. 
Cheers
Fritz
