### ISSUE TITLE
-l parameter : minimum sv length to be reported. 

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/Sniffles#25]
Hi Fritz,

I would like to get even one single nucleotide deletions or insertions. When I set -l parameter to 1. It gets so slow. 15 hours was not enough even to process couple of thousands reads. 

Normally if -l is higher than 5 it takes 20 min.

Is it normal?  

Best,
Mehmet

**Comment by mschatz** [comment]
Yes, PacBio reads typically have a 10% to 15% error rate, which means an
indel every 6 to 10bp. If you set -l to 1, Sniffles will have to consider
millions and millions of potential variants, most of which are not real. We
have successfully tested Sniffles with variants as low as 10bp but do not
recommend going below that threshold. We have had some success using
freebayes or samtools for variants below this, but this will be a future
research project to fully flush out these ideas.

Cheers,

Mike

**Comment by MehmetGoktay** [comment]
Thank you very much Mike.
