### ISSUE TITLE
Position starts at "0"

### ISSUE THREAD

**Issue by lukaslee1127** [fritzsedlazeck/Sniffles#250]
Hello.
 When I used sniffles, some vcf files' position starts at "0" instead of 1. Therefore, I can't use the bedtools and bcftools.
Should I erase that kind of Structural variants or modify position 0 to 1? 

![image](https://user-images.githubusercontent.com/50225750/105891998-4383f800-5fdf-11eb-90f2-0b575c04075b.png)

![image](https://user-images.githubusercontent.com/50225750/105892185-7d54fe80-5fdf-11eb-9d12-885d44721642.png)

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
