### ISSUE TITLE
The difference between the results of running sniffles with and without -n 1 parameter

### ISSUE THREAD

**Issue by minjinhan** [fritzsedlazeck/Sniffles#251]
Hello, when we used jasmine with Iris parameter to merge the SVs of different samples, we encountered an error because we did not add the -n 1 parameter when running Sniffles to call SVs.  If we use sniffles with -n 1 parameter to recall SVs from the bam files, it will be very time-consuming. 

We have compared the difference between the results of running sniffles with -n 1 parameter and without -n 1 parameter. We found that each SV called by sniffles with -n 1 parameter has one more RNAMES information, such as "RNAMES=057da8f6-93d2-4866-b24a-e2bdbbf974f4"  between SVTPYE and SUPTYPE.  Can you tell me how the string of alphanumerics “057da8f6-93d2-4866-b24a-e2bdbbf974f4” is generated? Is it randomly generated? Can we directly add a randomly RNAMES information to each SV called by  sniffles without -n 1 parameter? 

Thanks!

**Comment by wdecoster** [comment]
Those strings are the read names of the reads supporting the structural variant.

> Can we directly add a randomly RNAMES information to each SV called by sniffles without -n 1 parameter?

No

**Comment by minjinhan** [comment]
Thanks for your reply!
