### ISSUE TITLE
Inconsistent parameter estimation errors with --Icvf usage

### ISSUE THREAD

**Issue by javiercguard** [fritzsedlazeck/Sniffles#252]
Hi,

I have found some strange behaviour when using the Ivcf option of Sniffles 1.0.12 (the conda installation). I encounter the `Too few reads detected in <bam_file>` during parameter estimation, and then the process is terminated.

This only happens with certain alignment files (I elaborate below).

I am using both minimap2 and ngmlr alignments (on separate Sniffles runs). The --Ivcf works just fine with the ngmlr alignment:
```sniffles -m ngmlrAlignment.bam --min_support 1 --Ivcf inputVcf.vcf -v forceCallingOutput.vcf```

The same command doesn't work with a minimap2 alignment:
```sniffles -m minimapAlignment.bam --min_support 1 --Ivcf inputVcf.vcf -v forceCallingOutput.vcf```

I am reporting this here because the minimap alignment works without the force calling option:
```sniffles -m minimapAlignment.bam --min_support 1 -v output.vcf```.

Only the combination of minimap2 and --Ivcf stops.

This is similar to the input VCF I'm using (I've checked that this does -and doesn't- work in the way I've said):

```
##fileformat=VCFv4.1
##source=someSource
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Length of the structural variant">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr1	245000000	0	N	<DEL>	.	.	END=248000000;SVLEN=3000000;SVTYPE=DEL;
chr4	55000000	2	N	<DUP>	.	.	END=55200000;SVLEN=200000;SVTYPE=DUP;
chr6	10000000	3	N	<DEL>	.	.	END=11000000;SVLEN=1000000;SVTYPE=DEL;
chr14	123456789	8	N	<DUP>	.	.	END=124456789;SVLEN=1000000;SVTYPE=DUP;
``` 
It mimics SURVIVOR output. I've tried a longer header with all the contigs in hg38, removing SVTYPE from the INFO field, and changing ALT to N (while keeping the type in SVTYPE), with the same results.

Thanks for your attention.

**Comment by fritzsedlazeck** [comment]
Hi , 
thanks for reporting. I think I had recently solved a similar issue was a conversion of two different values for parsing... So I just want to check if you could maybe check again wiht the current code or if you have used a previous version/ conda version? 

Thanks
Fritz

**Comment by javiercguard** [comment]
Yes, I rebuilt sniffles from the repository and it works now.

Thanks for your answer.

I'm not sure if I should open a different issue, because a I have another kind of problem (probably not a bug): regardless of aligning tool, with an input file like shown above, i get this log:
```
Construct Tree...
		4 SVs found in input.
	Invalid types found skipping 0 entries.
```
It definitely doesn't skip them, and call the variants, and the VCF is "SURVIVOR-like" (the wiki section of force calling is built around survivor usage). Is there a particular format of SV that does not not trigger the "Invalid types" warning?

**Comment by fritzsedlazeck** [comment]
Great. 
So this shows that 0 SV were skipped !   So should be all good. 

As you know there can be multiple ways people report SV.. so that is why I built this in initially as debug but then kept it. 
Cheers
Fritz

**Comment by javiercguard** [comment]
All is good, then. 

Thanks again for your answers.
