### ISSUE TITLE
The sequences are missing for some INS variations

### ISSUE THREAD

**Issue by minjinhan** [fritzsedlazeck/Sniffles#253]
Dear Fritz,
SVs have been called by Sniffles with --min_support 2 --min_homo_af 0.7 -n -1. Then we want to annotate the SV sequence. We found that some SV sequences are not showed in the vcf file.  An example is as follows.

Chr6	15978743	58822	N	<INS>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=Chr6;END=15978743;STD_quant_start=0.000000;STD_quant_stop=3054.779981;Kurtosis_quant_start=15.273597;Kurtosis_quant_stop=-2.068987;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=7690;STRANDS=+-;STRANDS2=68,30,68,30;RE=98;REF_strand=86,73;Strandbias_pval=0.0182655;AF=0.616352	GT:DR:DV	0/1:61:98

Can you help me to fix this problem? 
Thanks!

**Comment by fritzsedlazeck** [comment]
Thanks @minjinhan ,
Sniffles handles some SV very naively. It can estimate the presence but don't find a single read that overlaps it nicely to extract the sequence.  I assume this is the case here with this 7.7kbp insertion. 
We are working on improving this , but in the meantime you might want to check out Iris https://github.com/mkirsche/Iris . This was built to run after Sniffles, you only need the -n -1 parameter. 

If the sequence is not as important for you and you just wanted to check if all is as expected: it is. 

Thanks
Fritz
