### ISSUE TITLE
SV calling for a population (cuteSV， pbSV etc.)

### ISSUE THREAD

**Issue by Chenglin20170390** [fritzsedlazeck/Sniffles#254]
Dear Fritz Sedlazeck,

    Thank you very much for developing such a useful tool.
    For population SV calling, can I use other SV caller results (vcf) as input for --Ivcf rather than sniffles? does it work normally? Because I want to integrate the results of different sv software such as sniffles， cuteSV, pbSV etc. ，and then do  sv calling for population.
    Do you have any suggestions?

**Comment by fritzsedlazeck** [comment]
Dear @Chenglin20170390 , 

This should work. Clearly, I am biased :) but maybe watch out for the SV that were initially not called by Sniffles .. I dont know how these will be genotyped. Like if they get any support or not. I assume that depends also on the reason why it wasnt called in the first place. 
Thanks
Fritz

**Comment by Chenglin20170390** [comment]
OK， many thanks for your help~
