### ISSUE TITLE
how to interpret the INFO marked with‘IMPRECISE’ 

### ISSUE THREAD

**Issue by minjinhan** [fritzsedlazeck/Sniffles#255]
Hi ,Fritz

When we use sniffles call SVs, we found that some SV sites are marked as IMPRECISE in INFO column. But we found that the depth of ONTraeds and alt reads at this site are quite high. We don't know how  the ‘IMPRECISE’ is defined. So we are not sure whether to discard these IMPORECISE sites in further analysis.

We would be very grateful for any suggestions.

An example is as follows:

INFO:

IMPRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=Chr1;END=290452;STD_quant_start=0.707107;STD_quant_stop=19.205545;Kurtosis_quant_start=30.308720;Kurtosis_quant_stop=-1.716733;SVTYPE=INS;RNAMES=00e03c7b-3ece-472b-a66f-3e9f88051430,0bb6a2e0-4bfe-4d9c-b182-50ca7bf7e3fd,1d422113-1d29-4205-9295-b3d4fef4b09a,21f71884-2f2f-4c4f-abb8-17da369bafb0,26607ecc-4c12-4703-b528-dca4b9a0cba8,26a5542a-43d2-4fb5-a794-6fc7779c7aec,26fb0fa1-7a79-4d94-8fb1-0b386fc1f864,2a0a13f3-8f28-43a1-950d-8849356575d8,31451489-1112-4c1e-a1ae-d0fbb4059b51,3b208c13-e567-4028-99b3-e9bc4e4d0fde,3d7bd31e-8226-42c3-9bba-9e466cb488a8,40822f07-279a-48aa-b631-bc3dd93caca4,4107936e-8f6a-4683-a512-c7d52a6ff96f,46d8c58d-1343-48ed-b8e9-7dfcd9f14760,4752fa0a-0fa5-405f-a46c-0eb3f2514251,4f710e9f-6e2b-4942-82d0-6d44a08f01f9,54d872e7-054b-4501-8d76-7f610cbf56d0,61f87fe4-65f3-46c1-af5e-703bc0fe8c19,628d2817-b973-46ec-9ba8-4b51b43f89a2,64eea8c7-6b2a-42a7-9d2d-17a3acb6be20,652f6760-725d-486f-befa-b610c712da35,72bb718b-6280-4671-8f9b-44e7f8d8c580,73d92d54-d4af-4ec8-8244-ff48bd5388b8,7469b8c1-5ec8-495a-9c61-94c52d453df5,74b6925f-93d8-4894-b09d-306a4113d075,774174b9-1205-4a3a-a1b7-2f4a096dd908,7a02ef60-977c-4128-b828-08ab8384e778,7a4cea0d-2ed8-4207-99dd-b3ddad8c52ba,7cb3df07-b958-4d97-8635-029f7dc56510,8439b1aa-2d16-4480-b60b-fd0670faae18,87938819-a02a-44ba-9716-718414ef8241,8aa468b4-90ac-49c7-bff1-f65a1799bff2,8d32ebd9-3623-43c2-84dc-3ad53c65d96b,8d55230b-1d92-4616-9f21-3a5856668089,8e99cd0b-eebd-4fb4-a627-9b31794aa000,9688c719-26d4-4ce2-9b87-62f91d7f4c49,96ad9228-0d9c-4050-815a-77154debfa91,98002808-ec89-44f2-a8c0-e3d100c49e7a,9f952cdd-0b90-41b7-bc48-91a4414aec41,a4e170f8-80d2-400c-9bf8-2ee49c9d7dfd,a7a2732d-3246-489b-b00e-4f7ccd4f40e9,a8297216-9461-456b-80af-6c7462f5cb97,abf79d49-c295-4f56-ae51-7adc96fa1220,af5350d0-20b4-4683-b19a-b5530fc13b51,b1a1eeb9-56e0-412b-88da-6d853be28b5d,b86ea319-611d-4c88-bc9c-30ca27d8f325,bb687895-8a6b-45ad-bd06-41c6be4d8a3b,bba8d69b-eba3-4120-871c-55802ab3b136,be147ab7-4d15-4db4-a5d9-100fe63f790b,be96fb83-7006-4e66-9066-e277a617ee86,c4e2d57d-dfa7-4957-9494-4f598c5ca1f2,c56c47eb-97f3-49d4-aec3-443f5e453306,c97d7114-2d32-4092-9c34-2a6ba86ada5b,ca4cd0a3-b87c-49f7-996d-6cd0f1602f53,cb768c66-619c-484c-81d2-3d4bf074916f,cc2bf967-e3a5-4a4a-b591-124806c0fe8a,d104458b-df6b-4af6-8d3a-d8dd3323607b,d4b1a4b2-85e7-4e90-bc43-623be72a059b,d86aff92-3a61-493b-8cef-cf02d54becc8,db3aaa61-5a7f-4c12-ada4-94e7aa78eafd,de114684-ced3-4358-827b-945571731bd3,e1635b20-5d60-4d32-9438-bb0eb15293ad,ea617116-b38d-4862-a1a2-6777d1c3e163,eb3321a2-e283-499b-ab67-9508ad8fff27,ebbeb721-392d-4446-a69e-7abf5693579d,ec9e500f-3f97-478d-8608-26deb4bbf486,f7d6f47a-f020-47ff-b42a-a8b8502acbed,fac62780-d066-4039-8729-81b94d916832,fc233c20-eed3-462d-b87a-dd555241a370;SUPTYPE=AL,SR;SVLEN=1559;STRANDS=+-;STRANDS2=35,34,35,34;RE=69;REF_strand=34,42;Strandbias_pval=0.508225;AF=0.907895

GT:DR:DV=1/1:7:69

**Comment by fritzsedlazeck** [comment]
Dear @minjinhan 
So Sniffles measures the agreement of the breakpoints among the individual reads. If the standard deviation of these reads are larger than 5 it reflects this as IMPRECISE. You can see in the info field (STD_quant_start=0.707107;STD_quant_stop=19.205545. ) that this was triggered mainly from your stop breakpoint. It does not necassarily related to false positives, but rather with the likely imprecision of the breakpoint. 

I hope that helps
Cheers
Fritz

**Comment by minjinhan** [comment]
Thanks， I get it.
