### ISSUE TITLE
Interpreting ./. genotypes

### ISSUE THREAD

**Issue by BrianSanderson** [fritzsedlazeck/Sniffles#256]
I'm having some trouble interpreting what it means for a site to have a ./. genotype when there appears to be information present in the call (SVTYPE, SVLEN, DV > 10). Here's an example from a single sample from sniffles v1.0.11 with default parameters based on an ngmlr alignment:

`chr2	120429710	16950	TATATATATATACATATATACTTATATATAGTGTATATATATATATATACA	N	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr2;END=120429755;ZMW=13;STD_quant_start=1.183216;STD_quant_stop=3.987480;Kurtosis_quant_start=-0.461548;Kurtosis_quant_stop=-1.285229;SVTYPE=DEL;SUPTYPE=AL;SVLEN=-45;STRANDS=+-;RE=14	GT:DR:DV	./.:.:14`

This shows up as a "1" in the SUPP_VEC for merged SURVIVOR results, and so I'm just wrestling with how to interpret whether this actually constitutes support for the presence of a deletion at this site, and if so why the genotype is set to ./.

This is a nearby site from pbsv from the same sample (which I think would represent the same SV), for the sake of comparison:

`chr2	120429722	pbsv.DEL.65338	ACATATATACTTATATATAGTGTATATATATATATATACACTATATATGTATTATTCAATCAA	A	.	PASS	SVTYPE=DEL;END=120429784;SVLEN=-62;SVANN=TANDEM	GT:AD:DP:SAC	1/1:2,22:24:1,1,15,7`

Thank you for any insight you can provide!

**Comment by fritzsedlazeck** [comment]
Thanks
So ./. means that the GT was not computed/ reported by Sniffles. However, you can see that the SV is supported by 14 reads. 

For SURVIVOR: this is a bit tricky and I agree that its confusing (sorry). So many programs report ./. (e.g. short read SV caller). Thus if SURVIVOR sees an entry it assumes the SV is present. The SUPP_VEC vector only takes into account the presence (1) vs. absence (0). Also the SUPP= will be counted by +1 for this. 

A newer version of Sniffles reports the genotype or you can invoke genotype calling in the older versions with --genotype (or a similar parameter). 

Hope that helps
Fritz

**Comment by BrianSanderson** [comment]
This is very helpful context, thank you! I will check out the new version of Sniffles.
