### ISSUE TITLE
Tree node not found

### ISSUE THREAD

**Issue by ctxchris** [fritzsedlazeck/Sniffles#257]
Hi,

I have sniffles Version: 1.0.12 installed from Conda.
I mapped PacBio Sequel reads with minimap2 against a reference with `minimap2 --MD -x map-pb --cs` and sorted the BAM file with `samtools sort `.  Sniffles was called like that: `sniffles -m align.sorted.bam  -b align.sorted.bedpe -t 10 -s 6` 
The log file shows:

> Finalizing
> Error in GT: Tree node not found. Exiting

The output file is empty.
Do you have an idea what the issue could be?

Thanks,
Chris

**Comment by olechnwin** [comment]
I'm having the same "`Error in GT: Tree node not found. Exiting`".
@ctxchris, did you find how to fix this?

**Comment by ctxchris** [comment]
HI @olechnwin, I run it at second time with the same parameters on the same data and it worked. I don't know why I didn't work the first time.

**Comment by olechnwin** [comment]
Hi @ctxchris, thanks for replying. I'm gonna try to re-run it again. Hoping it'll work out.
