### ISSUE TITLE
VCF BND format?

### ISSUE THREAD

**Issue by imielinski** [fritzsedlazeck/Sniffles#258]
Hi Fritz- any support for this?   tried --report_BND flag but doesn't look like it does the trick.

If not, what is the behavior for complex regions? will the junctions just be reported as a mix of dup / del / inv / tra?  

Thanks!

**Comment by fritzsedlazeck** [comment]
Yeah they are reported overlapping. e.g. INV DEL (inversion flanked with 1-2 deletions) will be reported adjacent and INVDUP will be reported overlapping. 

Hope that helps
Fritz

**Comment by imielinski** [comment]
ok will give it a try, thanks
