### ISSUE TITLE
Version flag does not output anything

### ISSUE THREAD

**Issue by Schmytzi** [fritzsedlazeck/Sniffles#259]
#### Description
Calling `sniffles --version` does not produce any output and returns with exit code 0.

#### Expected Behavior
Sniffles should either report its version or terminate with an error message, as it does when passing unrecognized parameters.

**Comment by fritzsedlazeck** [comment]
You are right.. havent tested that in a while. i made the changes in my code and this will be fixed in a future release. 
Thanks for pointing that out
Fritz

**Comment by fritzsedlazeck** [comment]
Just to mention the version is listed when you just look at the help output.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
