### ISSUE TITLE
Sniffles reports SVs only if the parameter --min_support 1 is set

### ISSUE THREAD

**Issue by Mestizia** [fritzsedlazeck/Sniffles#260]
Hello there,

I am trying to detect rearrangements between two closely-related fungal genomes using nanopore reads. I am mapping ont corrected reads from strain B onto genome A using both minimap2 and ngmlr.
However, I only manage to detect any rearrangements when setting the -s parameter to 1. I can easily detect many events by eye when loading the bam file in IGV [see attachment]. 
This happens regardless of whether I use minimap2 or ngmlr for the mapping step.

Quick recap of the commands used:

**Mapping**
`ngmlr -x ont -r assembly/genome_A.fasta.masked -q reads/genome_B_correctedreads.fasta.gz -o ont_rA_qB.sam` 

[I also tried minimap2 with multiple settings with no significant change in results]

`samtools view -Sb ont_rA_qB.sam >  ont_rA_qB.bam`
`samtools sort  ont_rA_qB.bam >  ont_rA_qB.sorted.bam`

**SV detection**
`sniffles --report_BND -m ont_rA_qB.sorted.bam --genotype -v rA_qB.vcf`

However, if I don't add the argument -s 1 to sniffles the vcf file contains no SV [ends after the header]
Here are examples of some SV which I can detect by eye using IGV:

This seems like a large translocation
![Screenshot from 2021-03-16 19-43-21](https://user-images.githubusercontent.com/8880988/111373680-8176d180-869c-11eb-9118-579963746092.png)

This is an insertion/deletion
![Screenshot from 2021-03-16 19-47-00](https://user-images.githubusercontent.com/8880988/111373682-82a7fe80-869c-11eb-9a6e-6127e9b73a85.png)

Notably, these events are actually detected correctly in the vcf file but exclusively if I use the -s 1 flag. However, from what I can see in IGV there are plenty of reads (more than the default 10) that would support those SV events. Additionally, I have mummer/nucmer evidence from genome to genome alignment that supports multiple rearrangements between those two genomes. Do you have any idea of what could be causing this behavior?

Many thanks,
Vittorio

**Comment by Mestizia** [comment]
I found the origin of the problem. The reads I was using had not properly formatted headers [each read started with genome name+space+readID] which resulted in samfiles with identical QNAME fields. Apparently, sniffles uses that field to calculate the support of each SV. Therefore, regardless of the actual support all SV had support =1.

I hope this helps someone else :)

**Comment by fritzsedlazeck** [comment]
Thanks @Mestizia !
