### ISSUE TITLE
BUG: split read ins! （when calling the SV in lots of samples）

### ISSUE THREAD

**Issue by Huangyizhong** [fritzsedlazeck/Sniffles#262]
Hi, there.
   Thanks for the kind softwares to detect the SVs in the ONT files. I have runned the sniffles successfully with the bam files aligned by the minimap2 (about 80 samples). Then I conducted the sv calling for them. The codes used listed as follows:
ls *sample.vcf > vcf_files_raw_calls.txt
./SURVIVOR merge vcf_files_raw_calls.txt 1000 1 1 -1 -1 -1 merged_SURVIVOR_1kbpdist_typesave.vcf
${sniffles} -m /home/data/SeGtexData/tmpDat/ONT-minimap/files1_blign.bam -v files1_second.vcf --Ivcf ${output1}/merged_SURVIVOR_1kbpdist_typesave.vcf
How to deal with it ? This problems also discussed in the https://github.com/fritzsedlazeck/Sniffles/issues/200, but I still do not how to deal with it ? The version os the sniffles is latest! Need helps!
![image](https://user-images.githubusercontent.com/31943359/116204448-5e494280-a76f-11eb-8d86-6ac6b054bc8b.png)
Thanks so much!
Sincerely
Yizhong Huang

**Comment by fritzsedlazeck** [comment]
I think something must have gone wrong. Sniffles cannot interpret 6161 entries!
Also starting at Chr 10 is strange. 
Please make sure that the bam file is sorted and that the VCF file is valid (ie. merging done successfully) 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
