### ISSUE TITLE
Genotype contradiction(?)

### ISSUE THREAD

**Issue by mariesaitou** [fritzsedlazeck/Sniffles#263]
Hi, I used IGV on Bam files to check some SV loci identified inSniffle output (through the latest Princess as of 28 April 2021 ). 
For example, This locus under looks like all heterozygous in six individuals, but in IGV, the Bam files look like del/del in one and ref/ref in another.
How can we interpret it? Am I misinterpreting the VCF result? This locus is not a particularly odd locus. In my brief manual inspection, I could not find clean and non-contradicting sites so far.
 

```{bash,eval=FALSE}
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1	2	3	4	5	6
chr01	139041651	0_24650	N	<DEL>	.	PASS	PRECISE;SVMETHOD=JASMINE;CHR2=ssa01;END=139043334;STD_quant_start=3.33542;STD_quant_stop=8.2991;Kurtosis_quant_start=1.31966;Kurtosis_quant_stop=2.30177;SVTYPE=DEL;RNAMES=4250ef10-dff4-4c5c-9c75-8ad085dcf7a9,43cd9070-cfef-48e3-af31-9ab39d2b93e7,49e571b9-1c82-405c-907e-f019f88f37de,8ba13242-89a8-46b0-8bbe-9ded59f71356,9674455c-0317-4798-9419-cb9e3c6db356,969e1d1e-d696-4d44-8c07-892fbfa14bd7,f6d1babd-83a1-4876-859b-0bff91cad0ce,f7a73e18-1dd5-4032-ac7e-55f61225e5c8;SUPTYPE=SR;SVLEN=-1683;STRANDS=+-;RE=8;REF_strand=1,1;AF=0.8;CONFLICT=0;OLDTYPE=DEL;IS_SPECIFIC=0;STARTVARIANCE=-4.000000;ENDVARIANCE=0.000000;AVG_LEN=-1683.000000;AVG_START=139041651.000000;AVG_END=139043334.000000;SUPP_VEC_EXT=111111;IDLIST_EXT=24650,24650,24650,24650,24650,24650;SUPP_EXT=6;SUPP_VEC=111111;SUPP=6;IDLIST=24650,24650,24650,24650,24650,24650;REFINEDALT=.	GT:IS:OT:OS:DV:DR	0|1:0:DEL:.:8:2	0|1:0:DEL:.:8:2	0|1:0:DEL:.:8:2	0|1:0:DEL:.:8:2	0|1:0:DEL:.:8:2	0|1:0:DEL:.:8:2
```

![IGV](https://user-images.githubusercontent.com/41928205/116776899-6f45cc80-aa6b-11eb-898a-3ab3b787a5a6.jpeg)

Thank you very much.

**Comment by zahrahaider** [comment]
I had the same issue of discrepancy of genotype between the bam files and vcf files. A variant reported as 0/1 by sniffles had a homozygous phenotype as manually inspected by IGV. It would be great to know how sniffles estimates genotype and why there is a discrepancy.

**Comment by mariesaitou** [comment]
Were you able to run Sniffles on the Princess result bam files?

**Comment by Akazhiel** [comment]
Hello! Maybe this doesn't make much sense and I may be mistaken since I'm more of a novice in this field but, aren't the BAM files in the screenshot phased? It says *hap* in the name so I guess each BAM is one haplotype that is why sniffles is calling the variant as heterozygous, since the deletion is only observed in one of the haplotypes.

**Comment by fritzsedlazeck** [comment]
Dear @mariesaitou was that related to Jasmin ? or did Sniffles report this? I remember we looked at this together right ?

**Comment by mariesaitou** [comment]
Hi, Jasmine developer said it may be a Jasmine issue. 
Now I am trying Jasmine (it is running for days and I have not got the results yet)
