### ISSUE TITLE
STRANDBIAS flag

### ISSUE THREAD

**Issue by gchevignon** [fritzsedlazeck/Sniffles#264]
Hello, does this type of output a bug or not ? if not what is it ? Thanks

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	wocg_10_longest_MD_CIGAR.bam.sort.bam
OsHV-1_microVar-A_KY242785_C.gSTRANDBIAS	0	N	<INV>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=OsHV-1_microVar-A_KY242785_C.gigas;END=171608;STD_quant_start=0.000000;STD_quant_stop=0.108465;Kurtosis_quant_start=74.643551;Kurtosis_quant_stop=71.873540;SVTYPE=INV;SUPTYPE=SR;SVLEN=171607;STRANDS=--;STRANDS2=0,170,170,0;RE=170;REF_strand=975,1079;Strandbias_pval=1.21875e-45;AF=0.0764388	GT:DR:DV	0/0:2054:170

**Comment by fritzsedlazeck** [comment]
Looks like part of the VCF entry. What is your concern?

**Comment by gchevignon** [comment]
on other line of the vcf is more like this :  

OsHV-1_microVar-A_KY242785_C.gigas	2	2	N	<DUP>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=OsHV-1_microVar-A_KY242785_C.gigas;END=203379;STD_quant_start=0.774597;STD_quant_stop=1.140175;Kurtosis_quant_start=5.388325;Kurtosis_quant_stop=5.887095;SVTYPE=DUP;SUPTYPE=SR;SVLEN=203377;STRANDS=-+;STRANDS2=11,3,11,3;RE=14;REF_strand=130,149;Strandbias_pval=0.0264239;AF=0.0477816	GT:DR:DV	0/0:279:14

**Comment by fritzsedlazeck** [comment]
you have to point out what is your concern. These are two different entries. Of course they are different.

**Comment by gchevignon** [comment]
Sorry ...
in the first line 
#CHROM = OsHV-1_microVar-A_KY242785_C.gSTRANDBIAS
with "STRANDBIAS" at the end of the name without any position 
in the second line
#CHROM = OsHV-1_microVar-A_KY242785_C.gigas
this is the right name of my chrom
My question is : why the chrom name is truncated and flagged with a "STRANDBIAS" missing base position in the vcf line ?
Is that a bug in the VCF output or not ?
If not what does it means because there is no explanation about "strandbias" anywhere  ...

**Comment by fritzsedlazeck** [comment]
Aaah I see. Yeah, that's likely on my side. Sorry for this. I will mark this as being fixed in the next release.

**Comment by gchevignon** [comment]
OK thanks !
Best

**Comment by ErminZ** [comment]
Hi there! I have a similar issue: The header of the Sniffle output .vcf file only contains 1 chrome.  ##contig=<ID=Ad-ED---MV-Luc>.  However, in the context, Ad-ED---STRANDBIAS, a new CHROM name ending with STRANDBIAS is generated, **without position (POS) information**, and causes problems using IGV. Once I delete all the lines containing STRANDBIAS, the vcf can be loaded to IGV for visualization. 

Does the .vcf file lose a lot of information if about 20 lines with CHROM Ad-ED---STRANDBIAS are deleted? 

Thanks

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
