### ISSUE TITLE
REF and ALT alleles

### ISSUE THREAD

**Issue by Akazhiel** [fritzsedlazeck/Sniffles#265]
Hello!

I'm unsure if this is a weird behaviour or the documentation is old and wasn't updated. But in the documentation it says the REF alleles is always an `N` but in my case sometimes I have an `N` and others I have the sequence that has been deleted I'd guess. The same happens with the ALT allele, sometimes it has an `N`, others have a sequence and in some events it just has the tag of the SV as in `<DEL>` and I'm unsure as to how interpret all this if you could share your insights.

Best regards,

Jonatan

**Comment by zqliugithub** [comment]
Hello, I have the same question.

**Comment by fritzsedlazeck** [comment]
The documentation is just a bit outdated. I didn't see the need to update it for this :)

**Comment by fritzsedlazeck** [comment]
I just changed that in the wiki. 
thanks for pointing this out. 
Fritz
