### ISSUE TITLE
Length of the inserted/deleted sequence does not match SVLEN – why?

### ISSUE THREAD

**Issue by francoiskroll** [fritzsedlazeck/Sniffles#267]
I just noticed that the length of the deleted (in REF column of the output VCF) or inserted (in ALT column) does not always match the SVLEN. I cannot explain this. What am I missing?

Or in other words – how is the SVLEN calculated if not from the length of the inserted/deleted sequence?

Here is an example

```
chr20	4699380	0	N	GGTGGTGGCAGGGCGGCCTCATGGTGGTGGCTGGGGGCAGCCTCAT	.	STRANDBIAS	PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=chr20;END=4699404;STD_quant_start=3.558142;STD_quant_stop=7.716681;Kurtosis_quant_start=1.043092;Kurtosis_quant_stop=1.528971;SVTYPE=INS;SUPTYPE=AL;SVLEN=21;STRANDS=+-;STRANDS2=37,69,37,69;RE=106;REF_strand=6462,6730;Strandbias_pval=0.00447258;AF=0.00803517	GT:DR:DV	0/0:13086:106
```
SVLEN is +21, but length of the inserted sequence (GGT...CAT) is 46 bp.

I had a look at the previous questions but didn't find anything about this. Feel free to link me if I missed it.

**Comment by fritzsedlazeck** [comment]
The length is calculated based on the breakpoint support from many reads. The sequence is right now only taken from one read.  This will get improved over the next version.

**Comment by francoiskroll** [comment]
I see. Thanks for the swift reply.

Is there a logic to which read gets picked as the 'representative' one? I'm still a bit suprised in my case that reads so different gets grouped together as the same SV call. In the case above, I'm inclined to believe SV length is ~ 46 bp (at least for that read) from the context of my research (it is a tandem repeat GGTGGT...CCTCAT, then again GGTGGT...CCTCAT, which is not unexpected for my sample). I do not think it should be grouped with reads that have a ~ 21 bp insertion. But I might be missing something about how the breakpoints are calculated.

**Comment by francoiskroll** [comment]
Probably a better way to formulate my question:

If one sample has 2 (or more) independent SVs starting at the same breakpoint. Say a 21 bp and a 46 bp insertion to take my example here. How would Sniffles behave? It looks here like it might be tempted to group them together in one call?

**Comment by fritzsedlazeck** [comment]
so Sniffles assesses the reads and determines the best supporting breakpoint individually. Later on, it chooses the read that best represents this choice of breakpoints. This can sometimes deviate (e.g. in very repetitive regions ).

So for merging if two SV are the same.. Sniffles makes the choice based on the potential SV predicted length.  If you like you can set this range by -d (e.g. 50 ?) .  The default is 1kbp.

**Comment by francoiskroll** [comment]
Ah, sounds interesting. Thanks for the suggestion!

Sorry, just so I understand:

from the Wiki:

> -d/--max_distance:
> Maximum distance to group SV together. Sniffles estimates this parameter during runtime to group together SVs reported by different reads. Default: 1kb

That sounds like distance between the start breakpoints? But then your comment sounds more like length of the SV?

So in my example, say 10% of the reads have a 21 bp insertion and another 10% have a 46 bp insertion. Both start at the exact same breakpoint. How do I tell Sniffles to _not_ merge them (i.e. I want two separate calls)?

Would `-d 20` do this?

**Comment by fritzsedlazeck** [comment]
So Sniffles uses the positions of the two breakpoints (start and stop) to see if SV across two reads are the same or not .. 
This is where the distance come in ie. the allowed space between the start of the SV across two or more reads and also stop for that manner. 

Default is 1kbp but a ratio is applied based on the size of the predicted SV.. so smaller SV less tolerance. 
So I would not go too low , but maybe -d 50 is a start.

**Comment by mschatz** [comment]
We looked at this pretty carefully in the Jasmine paper and found -d 50 to
be pretty much ideal (Especially Figure 2e):
https://www.biorxiv.org/content/10.1101/2021.05.27.445886v1

Cheers

Mike

**Comment by francoiskroll** [comment]
Brilliant. Thank you very much both
