### ISSUE TITLE
STRANDBIAS flag missing from header

### ISSUE THREAD

**Issue by Akazhiel** [fritzsedlazeck/Sniffles#268]
Hello!
When trying to sort the VCF file using bcftools sort it complained about the STRANDBIAS filter not being in the header.

`[W::vcf_parse_filter] FILTER 'STRANDBIAS' is not defined in the header`

Cheers!

**Comment by dKlee99** [comment]
Hi, 
I'm using picard liftover and they are complaining about the same issue,
Any updates on this issue?

`Exception in thread "main" java.lang.IllegalStateException: Key STRANDBIAS found in VariantContext field FILTER at chr1:16396442 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.`

Thanks!

**Comment by Akazhiel** [comment]
I sort of fixed it by just adding this flag to the header when parsing the VCF `##FILTER=<ID=STRANDBIAS,Description="Strand is biased.">` But would be good for it to just be in the header by default.
