### ISSUE TITLE
multiple samples as input bam

### ISSUE THREAD

**Issue by Jennie17** [fritzsedlazeck/Sniffles#27]
Hi, thanks for developing such a nice tool. It's also very easy to use.

Just wondering whether it is possible to call SV using multiple samples?

For example
./sniffles -m sample1.bam sample2.bam -v output.vcf

Thanks again!

**Comment by fritzsedlazeck** [comment]
Hi Jennie,
sorry that is currently not supported, but on my todo list. 
What I am currently doing is to call each sample separately and then merge/compare the vcfs using SURVIVOR (option 5) https://github.com/fritzsedlazeck/SURVIVOR . This way you get a multisample VCF file, but there is no recalling on the sites involved. 
I hope this helps for now.
Thanks
Fritz

**Comment by Jennie17** [comment]
Hi Fritz,

Thank you very much!

Yes, get a multisample VCF file will be enough for now.

Jennie

**Comment by fritzsedlazeck** [comment]
Hi Jennie,
let me know if you have other questions. I am working on a more inbuilt solution and I will keep you posted. 
Cheers
Fritz

**Comment by Jennie17** [comment]
Hi Fritz,

Thanks for the updates.

When I use SURVIVOR, I found a little bug on the wiki help page.

Following sample_files, there should be 6 parameters (wiki page only 5, Estimate distance based on the size of SV is missing, which won't run). 

After I changed it to sth. like this, it works.
./SURVIVOR 5 sample_files 1000 1 2 2 1 30 sample_merged.vcf

Tab file with names
max distance between breakpoints
Minimum number of supporting caller
Take the type into account (1==yes, else no)
Take the strands of SVs into account (1==yes, else no)
Estimate distance based on the size of SV (1==yes, else no).
Minimum size of SVs to be taken into account.
Output prefix

**Comment by fritzsedlazeck** [comment]
Yes sorry I am terribly behind the documentation on SURVIVOR. 
Most of the time I use it like this:
./SURVIVOR 5 sample_files 1000 1 2 2 2 30 sample_merged.vcf
The estimate distance is still a bit experimental, but should work fine.
Cheers
Fritz

**Comment by Jennie17** [comment]
Hi Fritz,

How to open  sample_merged.vcf_venn?

Is it a figure?

**Comment by fritzsedlazeck** [comment]
Its a tab separated text file. You can load it into R for plotting a venn diagram. 
The main output file is the vcf file that you specified.
Note the filtering is not applied on the venn diagram.

I can also upload code tomorrow that can summarize this into a pairwise comparison matrix across all samples used. 
Option 13 should also give you a summary over sizes and types of SVs in the vcf file. 
Cheers
Fritz

**Comment by Jennie17** [comment]
I see. Thanks a lot.

**Comment by Jennie17** [comment]
From venn file: There is one insertion (INS007SUR) for each sample
IdentifierW104tow64r13.vcf      W53tow64r13.vcf Length
INS007SUR       1       1       150.000000

But from merged.vcf file , the genotype is ./. for the first sample, which indicates  no data available?
Why it is inconsistent between these 2 files?

000000F_013\|arrow | 261549 | INS007SUR | N | <INS> | . | PASS | SUPP=1;SUPP_VEC=01;AVGLEN=184;SVTYPE=INS;SVMETHOD=SURVIVORv2;CHR2=000000F_013\|arrow;END=261585;STRANDS=+- | GT:LN:DR:ST:TY:CO | ./.:0:0,0:--:NaN:NaN | 1/1:184:0,12:+-:INS:000000F_013\|arrow_261549-000000F_013\|arrow_261585
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by fritzsedlazeck** [comment]
One possibility is that in the first file the insertion was below the 30bp threshold. Could you check?
The venn file is written without thresholds. I should maybe change that, but back then I needed it that way.

**Comment by fritzsedlazeck** [comment]
Another think that can be is that you ran Sniffles with --genotype and it reported the insertion with a low allele frequency (./.). 
So keep in mind that "./.:0:0,0:--:NaN:NaN" this means its not recorded in the input files. I hope this is clearer.

**Comment by Jennie17** [comment]
The original file for this sample:
000000F_013\|arrow | 137691 | 445 | N | <INS> | . | PASS | IMPRECISE;SVMETHOD=Snifflesv1.0.6;CHR2=000000F_013\|arrow;END=137700;STD_quant_start=52.564246;STD_quant_stop=52.720437;Kurtosis_quant_start=0.734151;Kurtosis_quant_stop=41.046299;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=86;STRANDS=+-;RE=54;AF=0.981818 | GT:DR:DV | 1/1:1:54
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

A related question:
pos: 137691 refers to the start pos of the SV?
END=137700 refers to the end pos of the SV?
But how comes SVLEN=86? 137700-137691 = 9?

**Comment by Jennie17** [comment]
BTW, the above is the only insertion on the chr for that sample.
There is no SV close to 000000F_013\|arrow | 261549 |  in the single output vcf file.

**Comment by Jennie17** [comment]
Oh, there is a deletion close by for this sample
000000F_013\|arrow | 255790 | 446 | N | <DEL> | . | PASS | PRECISE;SVMETHOD=Snifflesv1.0.6;CHR2=000000F_013\|arrow;END=255932;STD_quant_start=4.000000;STD_quant_stop=3.049590;Kurtosis_quant_start=1.314063;Kurtosis_quant_stop=-0.700312;SVTYPE=DEL;SUPTYPE=AL;SVLEN=142;STRANDS=+-;RE=10;AF=0.909091 | GT:DR:DV | 1/1:1:10
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by fritzsedlazeck** [comment]
For insertions its the rule to report the position of the insertion. It is quite common that we cannot be 100% certain about the single position so that is why we report a range of ~8bp. The length refers to the sequence that got inserted.

**Comment by Jennie17** [comment]
Thanks for the explanation!

It looks like the merged vcf is right to give ./. as there is really nothing there in the corresponding single sample vcf file.

Just not sure why venn gives "1" for it.

**Comment by fritzsedlazeck** [comment]
Yeah I will look at this tomorrow. Thanks for finding it. 
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Jennie,
I have put up a code for force calling using Sniffles. This means you can get a multi sample file all genotyped. 
1. Call SV per sample using Sniffles
2. Merge SV call sets using SURVIVOR
3. Call merged SV per sample using force calling from Sniffles
4. Merge all of them (SURVIVOR).

This may sound a bit stupid, but its the most direct way. I have not put up a script to do that, but maybe in the future. 
If you try it, please let me know if there are any issues. I am trying to test everything, but the force calling is still in a early stage.
Thanks
Fritz

**Comment by Jennie17** [comment]
Hi Fritz,

Many thanks for the updates.

Do I need to clone Sniffles again for the force calling code?

Regarding step 3, how to call merged SV using force calling from Sniffles?

**Comment by fritzsedlazeck** [comment]
Hi Jennie,
after merging take the resulting vcf (e.g. my_merged.vcf):
./sniffles -m mysample.bam --Ivcf my_merged.vcf -v my_new.vcf

the my_new.vcf will just include the previous specified SVs. Let me know how it goes.
Thanks,
Fritz

**Comment by fritzsedlazeck** [comment]
Oh and yes you need to clone the code again.

**Comment by Jennie17** [comment]
Thanks. Running now, will update you when I get the results.

**Comment by Jennie17** [comment]
seems Ven still cannot summarize correctly:
A record from w53w104tow64r13_new_merged.vcf, one genotype not available, one is present
000000F_002\|arrow | 3616 | TRA002SUR | N | <TRA> | . | PASS | SUPP=1;SUPP_VEC=01;AVGLEN=100000;SVTYPE=TRA;SVMETHOD=SURVIVORv2;CHR2=000000F_080\|arrow;END=778870;STRANDS=+- | GT:LN:DR:ST:TY:CO | ./.:0:0,0:--:NaN:NaN | 1/1:6507834:0,15:+-:TRA:000000F_002\|arrow_3616-000000F_080\|arrow_778870
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
But venn shows both samples have this event
[jiwu2573@login4 ngmlr-0.2.6]$ head w53w104tow64r13_new_merged.vcf_venn
IdentifierW53tow64r13_new.vcf   W104tow64r13_new.vcf    Length
TRA002SUR       1       1       100000

**Comment by fritzsedlazeck** [comment]
Sorry I forgot to look at that. Let me copy past it into the SURVIVOR github.

**Comment by Jennie17** [comment]
Can you explain what's the main purpose of the 2nd round of calling vcf and merge again? Looks like the results from 2nd merged vcf different from 1st merged. For example:
1st merge:

#CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | W104tow64r13.vcf | W53tow64r13.vcf
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
000000F_002\|arrow | 0 | TRA000SUR | N | <TRA> | . | PASS | SUPP=1;SUPP_VEC=10;AVGLEN=100000;SVTYPE=TRA;SVMETHOD=SURVIVORv2;CHR2=000000F_080\|arrow;END=783558;STRANDS=-+ | GT:LN:DR:ST:TY:CO | 1/1:6516138:0,59:-+:TRA:000000F_002\|arrow_0-000000F_080\|arrow_783558 | ./.:0:0,0:--:NaN:NaN

2nd merge:

#CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | W53tow64r13_new.vcf | W104tow64r13_new.vcf
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
000000F_002\|arrow | 17 | TRA000SUR | N | <TRA> | . | PASS | SUPP=2;SUPP_VEC=11;AVGLEN=100000;SVTYPE=TRA;SVMETHOD=SURVIVORv2;CHR2=000000F_080\|arrow;END=783015;STRANDS=-+ | GT:LN:DR:ST:TY:CO | 1/1:6515578:0,4:-+:TRA:000000F_002\|arrow_17-000000F_080\|arrow_783015 | 1/1:6515618:0,43:-+:TRA:000000F_002\|arrow_0-000000F_080\|arrow_783038

**Comment by fritzsedlazeck** [comment]
Yes I allow the position to vary a bit to reflect the variant in the sample.
So when you do the initial calling and then merging, you dont know for some samples if the SV was not called because of some threshold or if it is really not preset. That can be resolved by the force calling. 
Does that help?

**Comment by fritzsedlazeck** [comment]
Oh and I just saw you did it a bit wrong.
so the merge is just for one time. With the result of the merge you would need to rerun Sniffles over each file. 

1. Call SV per sample using Sniffles
2. Merge SV call sets using SURVIVOR
3. Call merged SV per sample using force calling from Sniffles
4. Merge all of the new forced called events by Sniffles  (SURVIVOR).

**Comment by Jennie17** [comment]
Can you point out what I have done wrong? What I did:
1. call SV for each sample
2. Carried out the 1st merge using SURVIVOR
3. Using the generated merged vcf with each sample bam file to generate a new vcf for each sample
4. Using all the new vcfs to get a new merged vcf using SURVIVOR

**Comment by Jennie17** [comment]
Based on your comments: 
"So when you do the initial calling and then merging, you dont know for some samples if the SV was not called because of some threshold or if it is really not preset. That can be resolved by the force calling."

I assume that the 2nd round merged vcf based on forced calling is more accurate than the 1st merged vcf?

**Comment by fritzsedlazeck** [comment]
Sorry its been along day.. You did it correctly. 
I got confused over the second merge output. 

The 2nd round just adds information for those samples where the variant wasnt called before. 
Please keep in mind that the option is still a bit experimental.

**Comment by Jennie17** [comment]
Thank you very much!

I think it is a smart way.

It looks like that the first merged vcf gives out the specified range of SVs and then the second round vcf calling based on bam and the specified events can give more definite answers regarding whether there is a real event in the sequencing data.

**Comment by fritzsedlazeck** [comment]
Yes and the re genotyping. I am continuing the tests to proof that. 
Thanks
Fritz
