### ISSUE TITLE
Read sequence is shorter than expected. Please check your bam file if the read sequence is reported!

### ISSUE THREAD

**Issue by dolittle007** [fritzsedlazeck/Sniffles#271]
Dear Sniffles creators,

I encountered a problem when I used Sniffles to call SVs using PacBio Iso-Seq data and ONT directRNA data.
It showed "Read sequence is shorter than expected. Please check your bam file if the read sequence is reported!".
What were Sniffles expected reads length?

If possible, please fix this problem.
Thank you so much.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
