### ISSUE TITLE
New version query

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#273]
Hi,

I was wondering when will the new version of Sniffles will release so that the VCF files can be parsed using bcftools without any errors or issues? I am aware that a lot of issues have been resolved related to VCF intactness since the last release. I am currently using v1.0.12b.

Regards,
Prasun

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
