### ISSUE TITLE
Question: construct contig that minimizes SVs

### ISSUE THREAD

**Issue by JohnUrban** [fritzsedlazeck/Sniffles#274]
Hi @fritzsedlazeck and others,

It's been a while since I've posted here. As usual, thanks for the great tool.

Let's say you have some contig, X, and a list of SVs from Sniffles internal to X (i.e. no inter-contig TRA stuff). Could you then construct a new contig, X prime, that resolves or minimizes that list of SVs?

In other words, are there any tools that would take a sniffles output file describing SVs internal to a single sequence (e.g. VCF or BEDPE, or any filetype that can be converted to from those) and output an updated version of the sequence that minimizes the number of listed SVs?

It seems like a graph-based problem that I assume has already been solved. It would minimally involve breaking up the contig into unit blocks and shuffling them around and reverse complementing as needed to minimize SV signals.

Best,

John

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
