### ISSUE TITLE
GT:DR:DV abnormal display

### ISSUE THREAD

**Issue by minjinhan** [fritzsedlazeck/Sniffles#276]
Hi,
We found that GT:DR of all variation sites show "./.:.", 

For example:
Chr1       800185  270     N       GACAAAAGAAAATAAATTTGACCCAATTACACGAATGCTTACCCAGTCTGCAAATCAGATTCACGACGCTTGG       .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=Chr1;END=800187;STD_quant_start=0.000000;STD_quant_stop=1.435270;Kurtosis_quant_start=3.815255;Kurtosis_quant_stop=-0.815276;SVTYPE=INS;SUPTYPE=AL;SVLEN=68;STRANDS=+-;STRANDS2=47,54,47,54;RE=101   GT:DR:DV        ./.:.:101
Chr1       788074  260     TCAAAACTATATATACTGGTGGTAGGACCTCTTGTTAGTCCGCGCGGGTAGGTACCACCACCCTGCCTATTTCAGCCGTGAAGCAGTAATGCGTGTCGGTTTGAAAGGTGGGGCAGCCGTTGTA
ACTATACTGAGACCTTAGAACTTATCTCAAGGTGGGTGGCGCATTTGCGTCGTAGATGTCTATGGGCTCCAGTAACCACTTAACACCAGGTGGGCTGTGAGCTCGTCCACCCATTTAAGCTATAAATAAATAAATAAATAAAAAAAACTA      
N       .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=Chr1;END=788348;STD_quant_start=0.000000;STD_quant_stop=0.000000;Kurtosis_quant_start=6.3
95053;Kurtosis_quant_stop=1.977280;SVTYPE=DEL;SUPTYPE=AL;SVLEN=-274;STRANDS=+-;STRANDS2=75,82,75,82;RE=157  GT:D
R:DV        ./.:.:157
Chr1       786278  259     N       CATTATCCTGCCCTTCTCCCACCGGGGTCGGCGCACATGTTTTCCTTCCATACTCTTCTATCATATACCATTTCTTCTGCCCTCCCCTTGTTTTTCTAAGTGTTATT     .
       PASS    PRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=Chr1;END=786278;STD_quant_start=0.960769;STD_quant_stop=3.230464;Kurtosis_quant_start=2.052126;Kur
tosis_quant_stop=0.753273;SVTYPE=INS;SUPTYPE=AL;SVLEN=118;STRANDS=+-;STRANDS2=76,81,76,81;RE=157   GT:DR:DV
        ./.:.:157

The Sniffles version is v1.0.12 and long-reads coverage >100x. 

Can you help me to fix this problem?

Thanks!

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
