### ISSUE TITLE
A problem about the start and end position of insertions, and the orientation of sv?

### ISSUE THREAD

**Issue by wangqling** [fritzsedlazeck/Sniffles#279]
Hi,I just noticed that the end position of some insertions are smaller that the start position. It was invalid record for me to annotate the insertions. I don't know how to deal with this problem. Does it related with the orientation of structural variation. Here is an examples:
chr10 | 264875 | 2273 | N | GTTGACTCACAGCTGTAGGGTACAGGGCATGGGGTACGGTGTCCAGTGTATGTCACTAGGTTGACTCATAACTGTAGGGTACAGGGCATGGAGTACGGCATCCGTGCATGTCACCAGATTGACTCAACTGTAGGGTACAGGGTATGGGGTAAGGTGTCTGGTGCATGTCACTAGGTTGACTCACAGCTGTAGGCAGGGCATGGGGTAAGGTGTCTGGTGCATGTCACAA | . | PASS | IMPRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=chr10;END=264874;STD_quant_start=19.884667;STD_quant_stop=35.695938;Kurtosis_quant_start=-1.843150;Kurtosis_quant_stop=-1.301134;SVTYPE=INS;RNAMES=11aedd77-406d-4564-b350-e93d34592640,25e9cb4d-212b-442a-b0b2-761be19de9a9,4054f320-b5fb-462b-9293-6d504340c677,40b0a307-6d21-4730-bd01-0422766d62d0,43d9db54-0e44-421e-ae5b-c10905d2e4f6,48964309-4523-4d2e-90ed-0734bd560e44,4cb96b60-4ab1-48aa-8468-38928463ea93,53fa11b2-9955-4351-a03e-c0fbbf6deccc,7c6b6a76-c20c-4ec4-bd63-be5d5fae5f52,80ed23f7-d3bd-488e-96a4-751173de1419,9a87fbc5-4db5-4f34-930e-8a8ce506698f,a2812ec4-9974-4023-a592-98ab998eb646,a85f7f26-d85b-4174-a291-e1cc437ee8aa,ad1dcf97-895a-4c7d-abd0-2ec8894605e8,b4afa993-d9bb-44bc-8dc1-2378d1ffad03,e8e09cf6-3ce3-4ffc-b6d6-9ce93f014596,ea10c574-c6c4-4c9c-82ef-5795fa83f793,fed617c3-7e71-4b03-8263-2a7c7194847f;SUPTYPE=AL;SVLEN=233;STRANDS=+-;STRANDS2=9,9,9,9;RE=18;REF_strand=9,11;Strandbias_pval=1;AF=0.473684 | GT:DR:DV | 0/1:20:18 |

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
