### ISSUE TITLE
Is it possible to separate into chromosome ?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [fritzsedlazeck/Sniffles#282]
Is it possible to detect BND event with BAM file separated into each chromosome ? (e.g. chr1.bam, chr2.bam,...)
Will it be the same with a BAM contain all chromosomes?

**Comment by fritzsedlazeck** [comment]
It is, however the supporting counts might not be correct. Some reads will be reported on chr1 and some on chr2 so you would need to merge and collapse the reads later.

**Comment by charliechen912ilovbash** [comment]
Thank you very much, I understood.
Can I merge the vcf outputs with `bcftools merge` ? 
and how could I collapse the reads?

**Comment by fritzsedlazeck** [comment]
Well if you need to do it, which i would not recommend, i would use survivor merge.
It will not automatically adjust the read support etc. However will produce a merged VCF file that should make it easy.

**Comment by charliechen912ilovbash** [comment]
I see. I am calling SV with Sniffles on a large BAM(~140 Gb), it has stoped during genotyping probably because of not enough memory.
I don't need the genotyping (--genotype) but I'm not sure if it can be turned off.
That's why I tried to separate it into small BAMs.
In the folder, it contains three files:
sample.vcf
sample.vcf_tmp
sample.vcf_tmp_genotype

If I don't need the genotype data, only need the SV positions, can I just use the sample.vcf file?

**Comment by fritzsedlazeck** [comment]
The VCF fike gets written before the genotype part. So you might have your calls already.

We will be releasing a new version of sniffles soon (2-3 weeks). That's why I wouldn't like to debug this rigt now.

**Comment by charliechen912ilovbash** [comment]
I see! Thanks for answering.
Looking forward of the new version!
