### ISSUE TITLE
Are pbmm2-aligned PacBio subread bam files suitable for Sniffles inputs?

### ISSUE THREAD

**Issue by JiaweiShen1116** [fritzsedlazeck/Sniffles#283]
Hi,

I am currently performing some SV analysis on my PacBio subreads bam files by using different PacBio SV callers (pbsv, Sniffles, etc.). I am now using the pbmm2/pbsv workflow to first align my subreads bam files to the reference using pbmm2 and then call the SVs using pbsv. Therefore I am wondering if the pbmm2-aligned subread bam files are suitable for Sniffles inputs since on the wiki page it says that inputs for Sniffles need to be either NGM-LR- or BWA-MEM-aligned. I also used the --median-filter option, which selects only one subread with the median subread length per ZMW cell for alignment to minimize false positive SV calls from pbsv, when using pbmm2. Please let me know. Thank you very much.

Best,
Jiawei Shen

**Comment by fritzsedlazeck** [comment]
Hey Jiawei,
right now it would cause some problems as pbmm2 has a nonstandard/particular way to report alignments. (non standard is maybe a bit too much). anyways. We are short before releasing a major update in Feb and this will help you.
Stay tune
Cheers
Fritz
