### ISSUE TITLE
How to extract read names that support the structural variants using the vcf file

### ISSUE THREAD

**Issue by ErminZ** [fritzsedlazeck/Sniffles#284]
For example, there are about 80 support reads for a structural variant call in the .vcf file, I want to get the names of these 80 support reads and to check how does the SV Inversion happen. But in vcf files generated from Sniffle, NO information about the reads names that support the SV. And there are no other output files that contain the names of support reads. 

How to get the 80 read names that support the SV from the vcf file? So I can extract the sequence reads from bam or even Nanopore fastq files? Thanks!

**Comment by wdecoster** [comment]
Per the [documentation](https://github.com/fritzsedlazeck/Sniffles/wiki/Parameter) (and also the help on the command line)
```
-n/--num_reads_report
```

Use `-n -1` to report all read ids that support a variant
