### ISSUE TITLE
Impossible calls in unknown chromosomes 

### ISSUE THREAD

**Issue by zhemingfan** [fritzsedlazeck/Sniffles#285]
Hi @fritzsedlazeck , 

While running Sniffles in some of our samples I noticed one of the outputs being:

`chr22_KI270736v1_random 175682  40115_1 N       GTGGAGTGGAGTTGAATGGAGTGGGGTTGAGTGGAATGGAATGGAATGAAATTGAATGCAGTGGTGAAATGAAATGTGAGGTGATATTGTGCCACCGAACTCCAGCCTGCGTGACAGAGTGAGATCATCTCAAAGAAAGGAATGGAATGGAATGGAGTGCAATGGAATTGAATGGAATGCAGTGGAGTGGAGTGGAGAAGAGTGGAACGGAATGTGATGAGTGGAATGGAATGGAGTGGAGTGGAGTTTAGTTGAGTGGGTTGGAGT .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr22_KI270737v1_random;END=175682;STD_quant_start=19.97;STD_quant_stop=237.996;Kurtosis_quant_start=-0.151955;Kurtosis_quant_stop=1.88208;SVTYPE=INS;RNAMES=15db9395-df0c-40a5-a9a8-3020316fbe19,3c299ff4-c92c-47a8-b724-1a3dcbb3664d,a8b956cc-d67c-4ffc-8d93-428e741cbc7a,f739457f-631a-4ccd-a12a-0ac6619d3560,faf5bc4c-3d10-4a0c-a6f0-81e48ecbe99b;SUPTYPE=SR;SVLEN=7313;STRANDS=+-;RE=5;REF_strand=0,0;AF=1 GT:DR:DV        1/1:0:5`

Should there be some sort of check to make sure that INS/DEL calls have to be on the same chromosome?

**Comment by fritzsedlazeck** [comment]
Thanks for pointing this out. We will soon release a major update.

cheers
Fritz

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
