### ISSUE TITLE
query about 0/0

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#286]
Hi,

Thanks for releasing the new version. On first usage, I can see a huge number of improvements and additions. Thanks for this. I just have a small question. Why is a homozygous reference reported as a genotype even for a single sample calling? It may be possible for a site to get a 0/0 if there are very few alternate reads with rest of the reads supporting the reference allele, but just want to know why they are kept in the vcf output. Should they be removed from the raw output? 

Regards,
Prasun

**Comment by fritzsedlazeck** [comment]
Dear Prasun,
yes that is exactly the case. We can find some reads, but they are very low numbers compared to the overall coverage. Thus they are labeled as 0/0. Depending on your experiment and organism you might be interested in those or not.. 

Hope that helps
Fritz

**Comment by prasundutta87** [comment]
Thanks for your help, Fritz!

**Comment by ymcki** [comment]
So what is the allele frequency cutoff to call 0/0 instead of 0/1?

**Comment by fritzsedlazeck** [comment]
Sorry its not a 100% clear threshold but dependeent on a stats model. However, after ~25% or lower VAF it will very likely be a 0/0

**Comment by fritzsedlazeck** [comment]
Its a statistical model.. so there is no direct treshold on AF..
