### ISSUE TITLE
Non-germline mode

### ISSUE THREAD

**Issue by Akazhiel** [fritzsedlazeck/Sniffles#287]
Hello!

I'd like to know more about how the non-germline mode works to call somatic variants without actually using a normal sample as reference to account for the variants also present in this normal tissue.

Best regards!

**Comment by smolkmo** [comment]
Hi Akazhiel,

we detect putative somatic variants based on the read support level as well as regional and local sequencing coverage. When an SV has a read support level in relation to coverage that is too low for a germline variant, it will be assigned a 0/0 genotype (putatively somatic). The germline variants will still be output, but have a heterozygous / homozygous variant genotype (0/1 or 1/1) assigned.

Hope this helps and best regards

**Comment by Akazhiel** [comment]
Hi smolkmo,

So in reality is not actual somatic calls but putative calls that may turn out to be real if I understood correctly? Could it be possible to detect true somatic variants calling in non-germline mode on the tumor sample and on default mode on normal sample and then do a multi-sample calling using the snf files and retrieving only the ones that have support on tumor but not on normal? Also I've noticed the STD_DEV on the vcf generated by the multi-sample calling is present in the header but not on the info field.

Best regards.

**Comment by fritzsedlazeck** [comment]
Hi @Akazhiel 
so the non germline mode is to identify variants with low support which means that they are only present in a fraction of the cells that were sequenced. Thus, we refer to them as likely somatic. 

For your question: Yes. I ideally if you have tumor / normal pairs sequenced you could run the two in default settings and then merge using Sniffles2. This would give you a fully genotyped VCF file from where you could derive that. 

If you don't have both sequenced you could detect SV with non germline mode on cancer only sample and based on their support frequency estimate which are germline. Clearly this is a bit more tricky... but saves a ton of money :)

**Comment by waltergallegog** [comment]
Hello @fritzsedlazeck 
Sorry for replying to a closed issue but it seems to me the most appropriate for the following questions.

I'm also interested in somatic sv detection using  paired tumor / control samples, and I want some clarification regarding the use of sniffles and survivor.

 - In this post, you advice to use sniffles2 in default settings for each sample, and then sniffles2 for merging. In the past, the approach you recommended was using SURVIVOR for merging, which is now replaced by sniffles2 merging. Is my understanding correct?

 - If I already have two vcf files resulting from running cuteSV on the tumor and normal sample independently, can I run sniffles2 merging on them? I suppose no, as sniffles2 expects the snf files. In this case I should use SURVIVOR for merging, as done in the [preprint](https://www.biorxiv.org/content/10.1101/2022.04.04.487055v1). Is this correct?

 - The output of sniffles2  merge is already genotyped, while for the output of SURVIVOR I would have to genotype it using sniffles2, correct?

Thanks a lot for your help and best regards.

**Comment by fritzsedlazeck** [comment]
No problem. 

1. Sniffles merge can make use of the --snf generated files. This produces a fully genotyped VCF file. The merging strategy is similar to SURVIVOR but not identical. So the benefits is that you get a fully genotyped VCF file. 
2. Yes that is correct. The sniffles merge is designed for the snf files not to arbitrary VCF files.  So SURVIVOR could do that comparison for you. Note that the resulting VCF file is not going to be fully genotyped. 
3. Exactly. 


Hope that helps
Fritz
