### ISSUE TITLE
--num_reads_report in Sniffles 2

### ISSUE THREAD

**Issue by tuannguyen8390** [fritzsedlazeck/Sniffles#288]
Hi there !

Did a quick installation via Conda & do a test run, seems all good at the moment. Congrats for the debut of version 2 !

However, I was wondering if the ```--num_reads_report -1 ``` option in Sniffles is the same as ```--output-rnames``` ? LongPhase (https://github.com/twolinin/longphase) seems to require Sniffles to have that option enabled.

Cheers,

Tuan

**Comment by smolkmo** [comment]
Hi there,

thank you for the nice feedback & exactly, `--output-rnames` will lead to the same behaviour that LongPhase requires (output read names of all supporting reads for each SV in the VCF).

Hope this was able to answer your question!

Cheers,
Moritz
