### ISSUE TITLE
why INS REF is ‘N’

### ISSUE THREAD

**Issue by yanxiaoyuansan125** [fritzsedlazeck/Sniffles#291]
Hello！

I used NGMLR and the latest Sniffles 2.0.2 ,and used a gap-free genome as reference. However, I found that the 4th column of the vcf which represent REF are all 'N', such as:
`Chr01   101661  Sniffles2.INS.B6S0      N       TGGTGCTCGGCGTTGTTACCGCGCGATCGTGGAGGC    44      PASS    PRECISE;SVTYPE=INS;SVLEN=36;END=101661;SUPPORT=33;COVERAGE=34,33,31,31,29;STRAND=+-;AF=1.000;STDEV_LEN=0.951;STDEV_POS=2.033;SUPPORT_LONG=0     GT:GQ:DR:DV     1/1:60:0:33
Chr01   152136  Sniffles2.INS.102S0     N       AGATTCTCGCTGCCTAGGTATGCCAGTGCGGCCAATTTGTAGACTCCCCTCCCGGGTAACTCATCTCAAAATGTAGATCACTTTTAGTATGGTC  40      GT      PRECISE;SVTYPE=INS;SVLEN=94;END=152136;SUPPORT=13;COVERAGE=65,63,61,62,65;STRAND=+-;AF=0.213;STDEV_LEN=2.820;STDEV_POS=7.165;SUPPORT_LONG=0     GT:GQ:DR:DV     0/0:3:48:13
Chr01   268517  Sniffles2.INS.1D0S0     N       TAGCAACCAGGCATGGCCATATAATAGCTAGCAAAAAGAGGCAGAGCGGGCCAATAACAGCAGTAGGGTATATATGCCACAGGGGCAGCAAACAAGCAAGGGGCGATTA   42      PASS    PRECISE;SVTYPE=INS;SVLEN=109;END=268517;SUPPORT=12;COVERAGE=61,57,47,48,49;STRAND=+-;AF=0.255;STDEV_LEN=0.983;STDEV_POS=1.225;SUPPORT_LONG=0    GT:GQ:DR:DV     0/1:22:35:12
Chr01   270413  Sniffles2.INS.1D5S0     N       TGGAGAGGACGGCCGGTCGCGGTCGGAGATTGCGTGGGAGGCGCGGTGGAGAAGGAGTCGGGCGAGGGCGCGGAGAGGTCGGAGATGGCG      38      GT      IMPRECISE;SVTYPE=INS;SVLEN=88;END=270413;SUPPORT=16;COVERAGE=69,74,73,40,41;STRAND=+-;AF=0.219;STDEV_LEN=14.086;STDEV_POS=26.576;SUPPORT_LONG=0 GT:GQ:DR:DV     0/1:1:57:16`
Why does this happen?

Thanks!

**Comment by smolkmo** [comment]
Hello,

The INS REF nucleotide is currently not output by Sniffles - but this will be added in an upcoming patch.

Best,
Moritz

**Comment by cornellyujy** [comment]
Hello smolkmo, for this record "Chr01 101661 Sniffles2.INS.B6S0 N", the Chr01:101661 position should have a nucleotide. So do you guys have released the patch? Thanks~
