### ISSUE TITLE
Sniffles analysis took a long time without results

### ISSUE THREAD

**Issue by yuntwang** [fritzsedlazeck/Sniffles#293]
Hi,  When I use sniffles(1.0.11) to analyze mouse data(Mus_musculus.GRCm38_release95), the results will not be output for a long time, which makes me feel abnormal.

My  command is as follows:
step1.
minimap2 -ax map-ont --MD -t 10 -I 2.86G -c Mus_musculus.GRCm38_release95.genome.fa PBS1.filt.fq | samtools view -bS >PBS1.bam
step2.
samtools  sort -o  PBS1.sort.bam  PBS1.bam
step3.
sniffles -m PBS1.sort.bam -v PBS1.vcf --genotype -s 10 --max_num_splits 7 -d 1000 -t 10 -l 30 -q 20 --report_seq

Enter file size（du -sh PBS1.filt.fq）
171G	PBS1.filt.fq

[exe-shell.log](https://github.com/fritzsedlazeck/Sniffles/files/8095270/exe-shell.log)

See attachment for log 

On chromosome 9 for three days without any output~
why?

**Comment by fritzsedlazeck** [comment]
Hi @yuntwang can you try with default parameters ? Sniffles2 is optimizing its parameters on the go. 
if that doesn't change things I would suggest to inspect the alignments. Like are these Hifi reads ? Have they been collapsed before the mapping ?

Thanks
Fritz
