### ISSUE TITLE
Sniffles v2.0 README Typo? 

### ISSUE THREAD

**Issue by zhemingfan** [fritzsedlazeck/Sniffles#294]
Hi @fritzsedlazeck,

For [multi-sample calling](https://github.com/fritzsedlazeck/Sniffles#b-multi-sample-sv-calling-trios-populations), I think there's a small typo where you mean `sniffles` instead of `sniffles2`. Or was `sniffles2` going to be implemented in the future?

**Comment by smolkmo** [comment]
Thanks zhemingfan, this was indeed a typo and was supposed to read just `sniffles` as well.
