### ISSUE TITLE
VCF created with Invalid record on sequence #1: end 1943006 < begin 1943468

### ISSUE THREAD

**Issue by bbimber** [fritzsedlazeck/Sniffles#295]
Hello,

We created a multi-sample VCF with sniffles2. The resulting VCF failing tabix indexing:
```
tabix multisample.vcf.gz
[E::hts_idx_push] Invalid record on sequence #1: end 1943006 < begin 1943468
tbx_index_build failed: multisample.vcf.gz

```

The line in question is below. Should this be allowable?

```
1       1943468 Sniffles2.DEL.10FM0     N       <DEL>   54      PASS    PRECISE;SVTYPE=DEL;SVLEN=-272;END=1943006;SUPPORT=26;COVERAGE=35,None,35,None,35;STRAND=+-;AC=20;SUPP_VEC=111111101111  GT:GQ:DR:DV:ID  1/1:60:0:38:Sniffles2.DEL.66038S0,Sniffles2.DEL.66039S0 1/1:41:0:15:Sniffles2.DEL.5AE66S0,Sniffles2.DEL.5AE67S0 1/1:60:0:33:Sniffles2.DEL.5C7C8S0,Sniffles2.DEL.5C7C9S0,Sniffles2.DEL.5C7CAS0   1/1:44:0:16:Sniffles2.DEL.48EA4S0,Sniffles2.DEL.48EA5S0 0/1:60:25:23:Sniffles2.DEL.7B797S0,Sniffles2.DEL.7B799S0,Sniffles2.DEL.7B798S0  1/1:60:0:47:Sniffles2.DEL.78F76S0,Sniffles2.DEL.78F78S0,Sniffles2.DEL.78F77S0   1/1:60:0:43:Sniffles2.DEL.725AES0,Sniffles2.DEL.725AFS0 0/0:0:36:0:NULL 1/1:52:0:19:Sniffles2.DEL.8B1D6S0,Sniffles2.DEL.8B1D7S0 1/1:60:0:29:Sniffles2.DEL.4ED0CS0,Sniffles2.DEL.4ED0DS0 1/1:60:0:48:Sniffles2.DEL.90CE5S0,Sniffles2.DEL.90CE6S0 0/1:60:17:15:Sniffles2.DEL.687DFS0,Sniffles2.DEL.687E0S0
```

**Comment by smolkmo** [comment]
Hello, 

thanks for reporting this! We were able to trace the problem and just published a hotfix in this repository ( https://github.com/fritzsedlazeck/Sniffles/commit/2d7644d50285e5bf91277e3745d0ec5de29ee164 ). The change will also be included in the  version update on pip & conda, which will be following soon.

Best,
Moritz

**Comment by smolkmo** [comment]
@bbimber On pip by early next week; conda may take a bit longer to update due to additional checks.

**Comment by smolkmo** [comment]
@bbimber: Hi again - just wanted to let you know that the 2.0.3 version update is out now on PyPI, and can be installed with `pip install --upgrade sniffles`. The conda package update is still pending approval and may take some time longer.

**Comment by bbimber** [comment]
@smolkmo Thanks. I was able to install direct from github using pip, and the fix seems to have worked well.

**Comment by wdecoster** [comment]
FYI: the conda package is now available
