### ISSUE TITLE
Inversions not detected

### ISSUE THREAD

**Issue by mpalmada** [fritzsedlazeck/Sniffles#298]
Dear @fritzsedlazeck,

I have tried to move from Sniffles v1 to v2 and noticed that some inversions previously reported are not longer found with the current default parameters, do you have any idea of why this is the case? Also I have not found any "DEL/INV" variant (is this kind of variants no longer considered?).

Regarding the rest of the structural variants now the software detects much more of them, that's what I expected reading the notes of the newer version (as it is supposed to be more sensitive).

Hope you can comment on this and that I am not saying anything nonsense,

Thanks a lot!

Marc

**Comment by smolkmo** [comment]
Hi Marc,

sorry for the delayed response - may I ask what kind of minimum support value you were using with Sniffles1 and what level of read support those inversions were having? We have also introduced a number of new filters to avoid false positives, which may be reducing the number of some SVs that you may be picking up. For your other point, for Sniffles2 outputs only the five types of elementary SV calls. There are however plans to introduce the detection of compound / complex SV types using a separate postprocessing step in the future.

Best,
Moritz

**Comment by mpalmada** [comment]
The minimum support value is 10. We are going to skip working to validate those specific variants but it'd be cool to know why those are no longer found in the new version! Thanks!

**Comment by fritzsedlazeck** [comment]
Sorry for this very late reply. Sniffles 2has much mroe stricter filtering criteria than Sniffles 1 had..  this often improves the precision. We have since the release of Sniffles2 worked on refining several thresholds/criteria and we are starting to look more carefully at inversions. 
Closing this for now
Thanks
Fritz
