### ISSUE TITLE
citation for Sniffles

### ISSUE THREAD

**Issue by tangerzhang** [fritzsedlazeck/Sniffles#3]
Hi,
I am curious how can we cite Sniffles if we used it?
Do you have a publication for Sniffles?
Thanks!

**Comment by fritzsedlazeck** [comment]
Hi,
Sorry, Sniffles is not published yet.
We are currently working on a preprint. I hope we have it up on bioarchive soon. This could then be cited. 
I will post the link here as soon as this is public available. 
Thanks
Fritz

**Comment by mdkeehan** [comment]
We'd like to cite Sniffles as well!

Thanks

**Comment by JohnUrban** [comment]
Any updates on a citation?

**Comment by fritzsedlazeck** [comment]
Sorry I am working on the paper but got only few things done over the autumn. I am still positive to have a preprint up this year.

**Comment by fritzsedlazeck** [comment]
It took me obviously longer then I hoped but we have a preprint up:
http://www.biorxiv.org/content/early/2017/07/28/169557
