### ISSUE TITLE
What is "forced vcf calling"

### ISSUE THREAD

**Issue by smehringer** [fritzsedlazeck/Sniffles#30]
Hi,

I am wondering what exactly sniffles is going to do when I specify the option `--Ivcf`?
In the wiki, it says that this 'enables forced calling'. Does this mean sniffles will limit variant calling to regions of previously seen variants? If so, are the regions exact positions (variants in vcf file) or do they include flanking regions for variability?

Sorry if I misunderstood.

**Comment by fritzsedlazeck** [comment]
Hi,
so this is still a prototype. 
So Sniffles will limit the search to those SV sites. It will not detect any novel SV.
It will allow however for re-definement of the breakpoints. Meaning that the breakpoints are not constrained to the reported bp and it will report the breakpoints that Sniffles things are correct.

The idea was to enable multi sample calling by using this option.
I hope that makes sense. 
Cheers
Fritz

**Comment by smehringer** [comment]
Thanks a lot for the quick and clear answer!
How large is the allowed span for breakpoint re-definement? Because sometimes SVs (especially insertions) tend to be very imprecise.

PS: I think I have a minor bug report:
When providing sniffles with a vcf file for forced calling, in my case there happened to be some variants in the vcf where NO reads were mapped at that position in the bam file (I worked on extracted sub regions and did not crop the vcf file accordingly) causing SNIFFLES to seg fault after finalizing.
```console
Finalizing ..
[1]     21487 segmentation fault (core dumped)   path/to/sniffles 
```
When I limit the VCF file, it works fine.

**Comment by smehringer** [comment]
Thanks, 1kb should be enough. 
I'm actually using this for re-calling variants after break point polishing by the way. 'Forced calling' therefore is very neat feature when I want to compare variants afterwards, thanks for that :)

Yes, I'm using SNIFFLES 1.0.6 and since it happens after the "Finalizing" Step I guess it could be the genotyping.

Cheers,
Svenja

**Comment by fritzsedlazeck** [comment]
It may not help much, but the SV should be reported to the file by that time. 
It might take me a week or so to fix this since I am slammed with work right now. 
Sorry.
Fritz
