### ISSUE TITLE
too slow?

### ISSUE THREAD

**Issue by YichaoOU** [fritzsedlazeck/Sniffles#303]
Hi,

I have 2.5M HIFI reads with an average of 10kb length. Sniffles has been running for 2 weeks. 

`sniffles --genotype -n -1 -t 4 -s 100 -m ${bam_file} -v output.vcf`

Any idea how I can speed up?

Thanks,
Yichao

**Comment by fritzsedlazeck** [comment]
Hi Yichao,
that sounds like something is very wrong .. What organism ? 
Also please update to Sniffles2 .

Thx
Fritz

**Comment by YichaoOU** [comment]
Thanks Fritz, it's human data. I will try Sniffles2.

**Comment by YichaoOU** [comment]
Hi Fritz,

I just realized what you mean. Yes, they are already consensus reads.

Thanks,
Yichao

**Comment by YichaoOU** [comment]
upgrade to v2 solved the problem!

Thanks,
Yichao

**Comment by fritzsedlazeck** [comment]
Great. 
Thanks for letting us know
Fritz
