### ISSUE TITLE
BEDPE output

### ISSUE THREAD

**Issue by mike-molnar** [fritzsedlazeck/Sniffles#307]
Hi,
I'm testing out Sniffles2, and in the `--help` it says for output in BEDPE to use `-b` or `--bedpe` but it stops and reports that they are unrecognized arguments.  Will there be an option for BEDPE output with Sniffles2?

Thanks,
Mike

**Comment by fritzsedlazeck** [comment]
Hey Mike,
I would need to check again, but Snfifles2 doesn't have bedpe support as far as I know. 
Moritz will know for sure. 
thanks
Fritz

**Comment by mike-molnar** [comment]
Okay, thanks Fritz.  I prefer BEDPE because I use bedtools a lot.

**Comment by fritzsedlazeck** [comment]
I see. You can use it with VCF files, but I don't know how well bedtools take into account the END tag. 

The "problem" is that VCF files is the main adopted format I think... We can ask Moritz to provide a printer for this format. 

I do have also some conversion tools for VCF -> Bedpe but I would need to test them again..

Thanks
Fritz

**Comment by smolkmo** [comment]
Hi Mike,

currently Sniffles2 supports VCF & VCF.gz output only - I just added BEDPE output to the planned features list. Before this is implement, using a VCF->BEDPE conversion tool is also what I'd suggest in the meantime.

Thanks,
Moritz

**Comment by fritzsedlazeck** [comment]
sorry @mike-molnar I overlooked this.. is the bedpe output still useful for people? I feel like VCF file took over? 
Thanks
fritz
