### ISSUE TITLE
Question regarding tandem repeat annotations list 

### ISSUE THREAD

**Issue by zhemingfan** [fritzsedlazeck/Sniffles#308]
Hi @fritzsedlazeck and the Sniffles team,

I was wondering, really briefly, how the tandem repeat annotations for Hg38 were generated. 

Thanks.

**Comment by fritzsedlazeck** [comment]
They can be for sure improved, but we simply took them from pbsv 
Cheers
Fritz

**Comment by zhemingfan** [comment]
Thank you!
