### ISSUE TITLE
Sniffles v1: VCF created with Invalid record on sequence: begin > end 

### ISSUE THREAD

**Issue by zhemingfan** [fritzsedlazeck/Sniffles#309]
With Sniffles_V1, I'm running into issues where POS>END: 

> 2       214506  2131    N       GGCTGGCCCCTGCGAACAGGCACCGGGCTGCCCCTGCCAACAGGCACCGGGCTGCCCCTGCCAACAGGCACCGGGCCGCCCCTGCCAACAGGCACCGGGCTGCCCCTGCCAACAGGCACCGGGCTGCCCCTGCGAACAAGGGGCACCGCTGCCCCTGCCAACAGGCACCGGGCTGCCCCTGCCAACAGGCACCGGGCTGCCCTGCCAACAGGCACCGGGCTGCCTCTGCCAACAGGCACCGGGCTGCCTCTGCCAACAGGCACC        .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.12;CHR2=2;END=214505;STD_quant_start=10.954451;STD_quant_stop=17.102631;Kurtosis_quant_start=-1.765319;Kurtosis_quant_stop=-1.193804;SVTYPE=INS;SUPTYPE=AL;SVLEN=264;STRANDS=+-;STRANDS2=9,15,9,15;RE=24;REF_strand=24,32;Strandbias_pval=0.805084;AF=0.428571  GT:DR:DV        0/1:32:24

So it seems like this was fixed in V2: [Snifflesv2.0](https://github.com/fritzsedlazeck/Sniffles/issues/295). Will there be any future fixes with v1, or should we just use Snifflesv2 from this point forward?

**Comment by fritzsedlazeck** [comment]
Sorry v1 will be discontinued. 
I was sure I fixed that in a later release... what version of v1 are you using ? 
Thx
Fritz

**Comment by zhemingfan** [comment]
Okay thanks - this testing was done with 1.0.12b, I'll update it to the latest version and try again. Thanks for clarifying.
