### ISSUE TITLE
Segfault with forced VCF calling

### ISSUE THREAD

**Issue by smehringer** [fritzsedlazeck/Sniffles#31]
The bug I was referring to in #30 

After some debugging I don't think that the genotyping is the problem.
The program segfaults because the variant is defined as DUP/INS (sv_type = 6), causing the following [line (Breakpoint.cpp:452)](https://github.com/fritzsedlazeck/Sniffles/blob/master/src/sub/Breakpoint.cpp#L452) to be false (variant is treated as an insertion):
```cpp
		if (!(this->get_SVtype() & INS)) { //all types but Insertions:
```
and thus moving into the else clause which tries to compute the median of the lengths2 vector ([Breakpoint.cpp:468](https://github.com/fritzsedlazeck/Sniffles/blob/master/src/sub/Breakpoint.cpp#L468)), but this segfaults because lengths2 is empty.

When I change line 452 to
```cpp
		if (!(this->get_SVtype() == INS)) { //all types but Insertions:
```
the program terminates successfully.

**Comment by fritzsedlazeck** [comment]
thanks for opening this. I will try to fix it towards the end of this week.

**Comment by fritzsedlazeck** [comment]
Can you send me your parameters? Or maybe even put an example somewhere?
Thanks
Fritz
