### ISSUE TITLE
query about using multisample variant calling/genotyping feature 

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#310]
Hi,

Thanks for the new version of sniffles. I am very much interested in the multisample calling because I am dealing with trios. Just out of curiosity, is it possible to use the multisample calling/genotyping feature with a VCF from some other structural variant caller, such as cuteSV?

Regards,
Prasun

**Comment by fritzsedlazeck** [comment]
Dear Prasun,
no sorry. For that you could use e.g. SURVIVOR or Truvari. 
Sniffles merge takes the candidate files into account during the merge to produce a fully genotyped VCF file.
If you like you can try it but it will not result in a fully genotyped VCF file. 

Thanks
Fritz

**Comment by prasundutta87** [comment]
Thanks @fritzsedlazeck . I believe that the snf file making step is very important for the multisample SV calling and this is different from force calling feature where I can use SURVIVOR/Truvari to merge calls from VCFs before force calling. Have I understood it correctly?

I actually tried the multisample SV calling using snf files for a trio I am analysing. I did get a lot of genotypes in my multisample VCF file where GQ was less than the threshold I generally put i.e. 15. In my previous research experience, I always put any genotypes to missing if GQ<15, but that was for SNVs. I am following the same procedure in the GQs of SV calling. Do you have any advice if this the right thing to do for SV multisample VCF file? I will use this VCF for clinical genomics and would check for autosomal recessive/dominant diseases, etc.

**Comment by fritzsedlazeck** [comment]
You did get that right . The goal here is to get as fast as possible to a fully genotyped VCF file. 
Yes GQ is not considered the only reason when we set a ./. is when the local coverage drops below 5 reads. You can modify this. 

If you like you can of course filter for GQ after the merge. 

Thx
Fritz

**Comment by prasundutta87** [comment]
Thanks for your reply to my queries @fritzsedlazeck. Regarding ./., are you pointing towards --min-support option (whose default is 10)?

**Comment by fritzsedlazeck** [comment]
--combine-null-min-coverage Thats the one for the merging .
