### ISSUE TITLE
fail to run sniffles because of no bai file

### ISSUE THREAD

**Issue by maxineliu** [fritzsedlazeck/Sniffles#311]
sniffles version: 2.0.6

My research organism is not human. I failed to generate BAI index file for my sorted align bam by samtooles. I guess it may result from very long contigs/chromosomes in bam. But Samtools can index it in CSI file instead of BAI.

Sadly, it seems that sniffles don't accept CSI as a valid index. What can I do in this situation?

Thank the one or ones who follow this issue for your time!

**Comment by fritzsedlazeck** [comment]
What error msg do you get from samtools? 
Samtools sort worked fine?

I have never seen a failure because of a contig/ chromosme length.... do you have a length for the contig that is suspicious?
Thx
Fritz

**Comment by maxineliu** [comment]
> What error msg do you get from samtools? Samtools sort worked fine?
> 
> I have never seen a failure because of a contig/ chromosme length.... do you have a length for the contig that is suspicious? Thx Fritz

command line:
samtools index -b -@ 20 aln.sorted.cy201704.bam 
The error msg is :
[E::hts_idx_check_range] Region 536856988..536888726 cannot be stored in a bai index. Try using a csi index
[E::sam_index] Read 'm64291e_211224_041609/132253067/22850_47574' with ref_name='chr1', ref_length=759857066, flags=16, pos=536856989 cannot be indexed
samtools index: failed to create index for "aln.sorted.cy201704.bam": Numerical result out of range

Thank you~

**Comment by fritzsedlazeck** [comment]
ok one more "stupid" question ... what aligner did you use?
Thanks
Fritz

**Comment by maxineliu** [comment]
I just think about should i mention the aligner. Haha. Here is the data flow:

pb_raw_data.bam ---- samtools bam2fastq  ---- raw_data.fastq ---- minimap2 align ---- aln_data.sam ---- samtools sam2bam ---- aln_data.bam ---- samtools sort ----aln_sorted_data.bam ---- samtools index ---- BAI file (failed)

Thank you!
Maxine

**Comment by maxineliu** [comment]
> ok one more "stupid" question ... what aligner did you use? Thanks Fritz

I just think about should i mention the aligner. Haha. Here is the data flow:

pb_raw_data.bam ---- samtools bam2fastq ---- raw_data.fastq ---- minimap2 align ---- aln_data.sam ---- samtools sam2bam ---- aln_data.bam ---- samtools sort ----aln_sorted_data.bam ---- samtools index ---- BAI file (failed)

So the aligner is minimap2.

Thank you!
Maxine

**Comment by wdecoster** [comment]
> Sadly, it seems that sniffles don't accept CSI as a valid index. What can I do in this situation?

What makes you conclude it doesn't? In a very small test that I did here a CSI index works just fine.

**Comment by maxineliu** [comment]
> What makes you conclude it doesn't? In a very small test that I did here a CSI index works just fine.

Sorry for the late response. It takes me days to test 2 samples of mine again with BAM+CSI. 

It seems I misjudged. They are failed for some reasons but not because of CSI index. I'll open an new issue. 

I think it would be a good idea to also mention CSI in the manual.  

Thank you for helping!

**Comment by fritzsedlazeck** [comment]
Thanks for clarifying.
Fritz
