### ISSUE TITLE
No AF value in multisample VCF file

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#313]
Hi,

Just wanted to mention here that while testing v2.0.6 of sniffles (bioconda), I observed that although AF (allele frequency) is mentioned in the VCF header, it is not present for any of the variants. I found it after I performed multisample variant calling using trio ONT data. Is it an error? Also, it may also be helpful if it is renamed as VAF (variant allele fraction), which is sample specific. Or, is it the population allele frequency which is calculated from the genotypes?
Regards,
Prasun

**Comment by fritzsedlazeck** [comment]
Ah you mean on the single sample ? that's fine and expected. 
Thanks for reaching out
Fritz

**Comment by wdecoster** [comment]
AF is the population allele frequency, not the fraction of reads supporting the alternative allele per sample, which you could get by dividing FORMAT/DV by FORMAT/DR + FORMAT/DV

**Comment by prasundutta87** [comment]
Thanks for confirming this @wdecoster !

Hi @fritzsedlazeck ! I was mentioning the missing AF values for a multisample VCF file (trio in my case). 

Regards,
Prasun

**Comment by fritzsedlazeck** [comment]
I am closing this as I think this is fixed.
