### ISSUE TITLE
silent error with exit code 0

### ISSUE THREAD

**Issue by wdecoster** [fritzsedlazeck/Sniffles#314]
Hi,

When merging snf files to a multisample VCF I found the following error on stderr:
```
Sniffles2 Error: SNF format version for sample.snf is not supported (Fatal error, exiting.)
```
(sample.snf is not the actual name, censored).

Regardless of the error, the output file is created (empty) and the return code of sniffles is 0, causing snakemake to think all is fine.

Wouter

**Comment by fritzsedlazeck** [comment]
This is now better handeled. 
Fritz
