### ISSUE TITLE
query about force calling in sniffles v2.0.6

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#318]
Hi,

I was just testing the force calling function of sniffles v2.0.6 (just for my understanding). As I am working with trios, I was following this pipeline: (1)Call SVs using sniffles on the trio individually to get 3 VCFs (2) filter SVs to retain precise and high quality SVs (3) Merge the 3 VCFs (4) use the integrated or merged VCF to force call SVs on each individual again (5) filter the forced VCFs to retain precise and high quality SVs (6) merge the 3 VCFs to get the final trio VCF.

I was using the --genotype-vcf option for the force call feature. The issue I am facing is that I am getting empty VCF after using the merged VCF in step 4. When I used just one VCF (for example I used the proband filtered VCF from step 2 to perform force calling on the proband VCF again), it worked. I was assuming that this will work like the --Ivcf option in old sniffles. Is the force calling in the current version different?

Regards,
Prasun

**Comment by fritzsedlazeck** [comment]
Thanks Parsun,
we can take a look, but its much easier than this now .. 

You call SV per sample and use the --snfs option to name tmp files. Then use sniffles merge with all the files and get a fully genotyped VCF File. I would filter based on that. 

Let me know if that works
Fritz

**Comment by prasundutta87** [comment]
Thanks @fritzsedlazeck . I will have a look into it.
