### ISSUE TITLE
`--max-splits-kb` should be float, CLI expects int

### ISSUE THREAD

**Issue by eliavw** [fritzsedlazeck/Sniffles#323]
In the CLI argument definition [here](https://github.com/fritzsedlazeck/Sniffles/blob/c02731ad288b32949c583cca2252164b235e5cb6/src/sniffles/config.py#L92) the type of the parameter gets fixed as an int, although its default value is set as a float. Since the docs specify this parameter is a ratio, a default of `0.1` makes sense indeed.

In its actual usage
- [here](https://github.com/fritzsedlazeck/Sniffles/blob/c02731ad288b32949c583cca2252164b235e5cb6/src/sniffles/leadprov.py#L221) and
- [here](https://github.com/fritzsedlazeck/Sniffles/blob/c02731ad288b32949c583cca2252164b235e5cb6/src/sniffles/leadprov.py#L311)

it does appear that a float is expected.

**Comment by lfpaulin** [comment]
It has been fixed in the latest version
