### ISSUE TITLE
Latest version of Sniffles2

### ISSUE THREAD

**Issue by tuannguyen8390** [fritzsedlazeck/Sniffles#324]
Hi Fritz, 

What is currently the current version of Sniffles2 ? I can see a few version on [bioconda](https://anaconda.org/bioconda/sniffles) (latest is 2.0.6), whereas the github one [release](https://github.com/fritzsedlazeck/Sniffles/releases) is 2.0.3 ?

Many thanks 

Tuan

**Comment by fritzsedlazeck** [comment]
Hey Tuan,
thanks thats interesting :) . We will check that out. 
Cheers
Fritz

**Comment by quanc1989** [comment]
Hi Fritz @fritzsedlazeck 

I found that after installing the latest version of Sniffles (v2.0.6), sniffles still show a version number of 1.0.12

![截屏2022-06-21 17 28 33](https://user-images.githubusercontent.com/8258430/174767843-e5dd8d90-8542-4b48-a943-bd41a85fc3ca.png)

**Comment by wdecoster** [comment]
Can you try `which sniffles`? You probably have the older version still installed somewhere, which is not based on pip/python

**Comment by quanc1989** [comment]
Thank you.
When I reactivate my conda environment, the problem has been corrected.
