### ISSUE TITLE
SV calling on sex chromosomes

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#325]
Hi, 

I was just wondering if there is any specific methodology that needs to be followed before calling SVs on sex chromosomes using sniffles2? I am using a reference genome for SV calling in humans that has both X and Y chromosomes (GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna). I know SNP calling on sex chromosomes is a different ball game than SNP calling in autosomes (due to PAR), but just wondering if anything specific needs to be taken into account while SV calling on the sex chromosomes. I am working with trios in my case.

Regards,
Prasun

**Comment by fritzsedlazeck** [comment]
Hi,
no we haven't planned any extra steps nor experimented with this. Obviously, keep in mind that the genotypes will handle the sex chromosomes like it would be autosomes.. 

Please keep me posted. I would be interesting to see if you find any issues. 

Thanks
Fritz

**Comment by prasundutta87** [comment]
Thanks for this @fritzsedlazeck ..will keep you posted!

Regards
Prasun
