### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by harazono-yoritaka** [fritzsedlazeck/Sniffles#33]
Hi,

I am using Sniffles for my research.
I added ```--report_BND``` option but there may be bug.
In ```Sniffles/src/print/VCFPrinter.cpp``` line 95,

```if (strands[0] == '-' && strands[0] == '+')```

I think this ```if``` statement is always false.

**Comment by fritzsedlazeck** [comment]
sorry for the late reply. I was traveling and then something else came up. I changed it and tested it over some translocations in comparison to Lumpy. I just pushed a fix and made a release.
Thanks for the feedback.
Fritz
