### ISSUE TITLE
Sniffles failing to detect 5bp deletion?

### ISSUE THREAD

**Issue by caonetto** [fritzsedlazeck/Sniffles#330]
Hi,
I am currently testing sniffles in samples that have been genetically modified with a 5bp deletion. I am currently running the following parameter without filtering any QC
sniffles --input ref.s.bam --minsvlen 3 --vcf ref.vcf --snf ref.snf --threads 50 --allow-overwrite --minsupport 10 --reference ref.fasta --qc-output-all

Is there a minimum size for SVs that is supported by sniffles?

Cheers.
![sniffles_screenshot](https://user-images.githubusercontent.com/25968988/175460044-1a38059f-51fe-4179-920d-672916288496.png)

**Comment by fritzsedlazeck** [comment]
Dear @caonetto 
Sniffles2 is not recommended for small indel calling. I think we tested it down to 10bp but certainly not below. 
I would recommend e.g. Clair v3 for these things. 
Thanks
Fritz
