### ISSUE TITLE
Missing genotypes in the combined calling using multiple .snf files

### ISSUE THREAD

**Issue by quanc1989** [fritzsedlazeck/Sniffles#331]
In the second step of combined calling using multiple .snf files into a single .vcf (sniffles v2.0.6), there are still many missing genotypes in the output vcf.

So I still need force-calling to get fully genotyped vcf?

Thank you.

```
sniffles --input merge.minimap2.sniffles.snf.tsv --vcf merge.minimap2.sniffles.vcf
```

The format of my merged tsv of .snf files:
![截屏2022-06-26 10 42 56](https://user-images.githubusercontent.com/8258430/175797183-d6dc6eb9-1547-4f5b-891a-799cb4514392.png)

The result of output vcf:
![截屏2022-06-26 10 39 10](https://user-images.githubusercontent.com/8258430/175797154-f006acb1-1612-43fd-950d-adb2099669c5.png)

**Comment by fritzsedlazeck** [comment]
By default, this is when the coverage at the location is lower than 5x. Given your example this seems to be the case. You would need to change the parameter if you still want to enable that.  I think its that :   --combine-null-min-coverage N 

Thanks
Fritz

**Comment by quanc1989** [comment]
I got it.
Thank you for providing such detailed parameters for multi-sample calling, which are very practical.

Quan Cheng
