### ISSUE TITLE
how sniffles2 merges SVs cross multiple samples

### ISSUE THREAD

**Issue by Gongjiao94** [fritzsedlazeck/Sniffles#336]
Hi Fritz,
  I tried sniffles2 to call SV  using the Multi-Sample SV Calling mode, and I'd like to know how sniffles combines calling using multiple .snf files into a single .vcf. In other words, what's the criterion of sniffles2 merging SVs cross multiple samples, based on the distance of breakpoints or others?

Thanks
Jennie

**Comment by fritzsedlazeck** [comment]
Hi @AJ211 ,
yes right now its similar to SURVIVOR so a maximum distance for start and stop that I think is adjusted based on the SV size. So smaller variants allow a smaller position wobble. 

Thanks
Fritz
