### ISSUE TITLE
Small Deletion

### ISSUE THREAD

**Issue by assane-mbodj** [fritzsedlazeck/Sniffles#339]
HI Fritz,
I have any question about Sniffles. please
Is it capable to detect the small deletions or duplications of ten pb ?
Also if you tested Vulcan mapping (https://github.com/Fu-Yilei/vulcan) with SNiffles, Between minimap2 and vulcan which one is better to use Sniffles ?

Thanks you for your help

Assane
Engineer Bioinformatics

**Comment by fritzsedlazeck** [comment]
Hi Assane,
we havent tested it with Vulcan yet. It should work. 

10bp is on the edge we haven't tested that yet. I know in theory it should be possible to do it, but we have not benchmarked it. I expect that it is the edget case for the algorithm that is used. 
Cheers
Fritz
