### ISSUE TITLE
Do I need to mark duplicates before feeding sorted bam file to sniflle?

### ISSUE THREAD

**Issue by CVan19** [fritzsedlazeck/Sniffles#34]
Hello, I am working on a human genome, and I want to call SV using Sniffle. I have just mapped pacbio data to human reference genome using ngmlr and then sort the bam file using samtools. Before feeding the sorted bam file to sniffle, I wonder whether I need to mark duplicates and select only a single subread as non-duplicate?

**Comment by fritzsedlazeck** [comment]
No you should be fine. Just feed the sorted bam file into sniffles with no further filtering.
Cheers
Fritz
