### ISSUE TITLE
How to call de novo SV ?

### ISSUE THREAD

**Issue by aojielian** [fritzsedlazeck/Sniffles#343]
Hi,
I got the Oxford Nanopore sequencing data from trios family and want to get the denovo SV, Can Sniffles call denovo SV?

**Comment by fritzsedlazeck** [comment]
Hi,
it can generate a VCF file with all information necessary but you will need to parse for the sample that has de novo variants. This can be over bcftools or even simple grep query. 

Thanks
Fritz
