### ISSUE TITLE
query about force calling 

### ISSUE THREAD

**Issue by maxineliu** [fritzsedlazeck/Sniffles#345]
Force calling is aimed to genotype individuals if my understanding is correct. My question is if an SV has multiples alleles, in another word, the `AC` parameter in VCF is more than 2, will these alleles be distinguished in force calling results? For example, if SV-A has 3 allelles. Then the genotype of sample 1 may be 0/1, sample 2 may be 0/2, and so on...

**Comment by maxineliu** [comment]
any clue?

**Comment by fritzsedlazeck** [comment]
Sorry, no we dont do that yet. 
multiallelic is hard even for SNV. 
Hope that helps
Fritz

**Comment by maxineliu** [comment]
I just need a clear answer. So thank you Fritz!
