### ISSUE TITLE
install sniffles2 issues

### ISSUE THREAD

**Issue by FarmOmics** [fritzsedlazeck/Sniffles#347]
I try to install sniffles2 using different strategies, but all failed:
1. pip install sniffles, see error:
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement sniffles (from versions: none)
ERROR: No matching distribution found for sniffles

2. conda install -c bioconda sniffles=2.0 -n sniffles -m, then run sniffles -h, see error:
Traceback (most recent call last):
  File "/home/dguan/anaconda3/envs/sniffles/bin/sniffles", line 33, in <module>
    from sniffles import parallel
  File "/home/dguan/anaconda3/envs/sniffles/lib/python3.8/site-packages/sniffles/parallel.py", line 17, in <module>
    from sniffles import leadprov
  File "/home/dguan/anaconda3/envs/sniffles/lib/python3.8/site-packages/sniffles/leadprov.py", line 137, in <module>
    OPTAB={pysam.CMATCH:     (1,1,0),
AttributeError: module 'pysam' has no attribute 'CMATCH'

3. install  sniffles 1 first in conda, then update to 2
conda install -c bioconda  sniffles -n sniffles -m, then conda update -c bioconda sniffles, then run sniffles -h

Usage: sniffles [options] -m <sorted.bam> -v <output.vcf> 
Version: 1.0.12
Contact: fritz.sedlazeck@gmail.com

Not update it.

**Comment by fritzsedlazeck** [comment]
Do you have python 3 installed ? 
Thx
Fritz

**Comment by guandailu** [comment]
I test the version:
python --version
Python 3.8.13

**Comment by fritzsedlazeck** [comment]
ok my last guess: pysam ? 
Other than that we would need to look into what would cause this.. 
Thanks
Fritz

**Comment by guandailu** [comment]
The installed pysam is:  
pysam              bioconda/linux-64::pysam-0.9.1-py38hd1a2d5f_10

Then I try to install a higher version:
conda install -c bioconda pysam=0.16.0.1
Unfortunately,  there are a lot of conflicts:
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for wheel libssh2 pysam setuptools sniffles python_abi samtools openssl krb5 curl htslib libcurl pip python bcftoo\ :

**Comment by danrdanny** [comment]
I had a similar error. `conda install python=3.7` followed by `conda install sniffles=2.0` worked for me.

**Comment by guandailu** [comment]
> 

Thank you so much! It also works me!
