### ISSUE TITLE
No complementary entry for a translocation

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#357]
Hi,

Generally, a translocation or BND event should have a complementary entry in the VCF. I have found cases where there is one, but I also found a case where there was none. How do I interpret this? It seems to be an error of some sort as I read from some other issues. I am using v2.0.6 for my analysis.

Regards,
Prasun

**Comment by prasundutta87** [comment]
Any update on this?

**Comment by fritzsedlazeck** [comment]
thanks for reporting this. Yes for many cases there should be an event leading back but that's not necessarily always the case. Depends a lot on the underlying cases. 
Right now our focus is more on non bnd events, but we will cycle back to this too. 
Thanks
Fritz

**Comment by prasundutta87** [comment]
Thanks a lot for this update, @fritzsedlazeck !
