### ISSUE TITLE
RNAMES not defined in the header

### ISSUE THREAD

**Issue by FrankFeng** [fritzsedlazeck/Sniffles#36]
Hello,

Just a minor issue -- RNAMES is not defined in the VCF header. 

Thanks!

**Comment by fritzsedlazeck** [comment]
Thanks Frank,
I will upload a fix tomorrow. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Dear Frank,
I just uploaded the fix for this. Please clone the code as I am not putting out a new version for this. 
Thanks for pointing this out.
Fritz
