### ISSUE TITLE
Using sniffles on alignments that exclude non-primary aligned reads

### ISSUE THREAD

**Issue by elcortegano** [fritzsedlazeck/Sniffles#360]
I'm using sniffles (more specifically I did use the old version v1.0.12b), and when running it we excluded non-primary alignment reads from the BAM files (using `samtools view -F 256`).

I do wonder if this could have any impact on sniffles results (e.g. when detecting certain types of variants such as transposable elements), or if it has no effect on its performance.

Thanks

**Comment by fritzsedlazeck** [comment]
It does. Split reads are one of the main sources to detect mid to larger size of SV. If you discard split reads, only alignment events (typically insertions and deletions < 500bp) are reported. 

So I would encourage you to use the original bam file
Thanks
Fritz
