### ISSUE TITLE
"GT" in FILTER field

### ISSUE THREAD

**Issue by soymintc** [fritzsedlazeck/Sniffles#363]
Good morning,

I have an SV that visually looks like a true SV on IGV, which is labelled af "GT" in its filter column. I've looked up what GT in the FILTER field is, but all I could find is `##FILTER=<ID=GT,Description="Genotype filter">`. 
It does seem that GT of samples are `0/0` in this case, but there are a lot of cases where DV is greater than 5 & VAF (DV/(DR+DV)) greater than 0.1 but still being called `0/0` on its GT. 

An example:
```
19      29258997        Sniffles2.INV.2A8M12    N       <INV>   59      GT      PRECISE;SVTYPE=INV;SVLEN=4356;END=29263353;SUPPORT=53;COVERAGE=349,302,304,242,245;STRAND=-;AC=0;STDEV_LEN=0;STDEV_POS=0;SUPP_VEC=10  GT:GQ:DR:DV:ID  0/0:60:270:53:Sniffles2.INV.36F2S12     0/0:0:27:0:NULL
```

So the main question is, [1] how is GT FILTER set, [2] and how is GT of sample columns defined? Could this be added in docs or any wiki of some kind? 

Thank you.

Best,
Seongmin

**Comment by fritzsedlazeck** [comment]
Thanks Seongmin, 
we will extend the documentation for these filtering tags. Its correct that the GT in the filter just indicates that the estimated GT is 0/0 . 
Thanks
Fritz

**Comment by soymintc** [comment]
Thanks for the response Fritz! I wonder why the GT would be estimated `0/0` for the first sample with `0/0:60:270:53:Sniffles2.INV.36F2S12`. Asking because I'm thinking of including the SV regardless of the GT filter, but leaving it out would be a good idea if there's a solid rationale for setting the genotype of this sample as wildtype.

**Comment by fritzsedlazeck** [comment]
0.1 is still very low for a het SV.. so thats probably why... For a het you would expect 0.3+ I would assume.. There is a statistical model working underneath this. .. 
hope that helps
Fritz
