### ISSUE TITLE
SUPPORT_LONG

### ISSUE THREAD

**Issue by adottoma** [fritzsedlazeck/Sniffles#369]
Hello, 

I'm investigating structural variations with Sniffles and --output-rnames option,  and for one of the insertions found I have these informations : 

PRECISE;SVTYPE=INS;SVLEN=2947;END=191202;SUPPORT=34;RNAMES=66d37d13-2fc3-416d-a0a1-22c5ffe7c626;COVERAGE=4624,4692,4687,4712,4656;STRAND=+;AF=0.029;STDEV_LEN=0;STDEV_POS=0;SUPPORT_LONG=33

My questions are:  what does SUPPORT_LONG mean and how can I recover the names of the 33 reads identified as SUPPORT_LONG ? 

Thanks in advance,
Aurélie

**Comment by fritzsedlazeck** [comment]
You should get all read names with   --output-rnames as you mentioned. 
Can you paste the command that you ran?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Closing because of time.. @hermannromanek can you check about number of read names written out ?
