### ISSUE TITLE
a question about detected duplications

### ISSUE THREAD

**Issue by FrankFeng** [fritzsedlazeck/Sniffles#37]
Duplications can be detected by Sniffles. There are at least two types of duplication, dispersed and tandem duplications. Can Sniffles tell which is the type? Thanks!

**Comment by fritzsedlazeck** [comment]
Hi Frank,
like all SV caller Sniffles only reports tandem duplication as DUP.
Other duplications eg. in cancer are often reported over translocation events or other events flanking the regions and thus highlighting what is actually going on.
In the SKBR3 cancer for example we characterized a combination of translocations and inversions that highlight the amplification of Her2 region: https://www.biorxiv.org/content/early/2017/08/10/174938

I hope that helps
Fritz

**Comment by FrankFeng** [comment]
Thanks Fritz!
