### ISSUE TITLE
Question about Strand definition and DUP records

### ISSUE THREAD

**Issue by infotmatician** [fritzsedlazeck/Sniffles#370]
Dear Fritz,
Hope you are doing well. I am a little bit confused about the "Strands". How sniffles2 assign strands of variants ? 
If DUP variants located  two times in a region, how sniffles will show those variants?
Best

**Comment by fritzsedlazeck** [comment]
Dear @infotmatician 
this is more for our own debugging and interest. It might become a filter in future releases. 
So please ignore for now.
Thanks
Fritz

**Comment by infotmatician** [comment]
Thank you
