### ISSUE TITLE
Insertion (Precise) without insertion sequence

### ISSUE THREAD

**Issue by weilu1998** [fritzsedlazeck/Sniffles#375]
Hi,

I noticed  that around 180 insertion variants in my VCF file didn't have insertion sequence displayed, only symbolic "INS" are placed in the ALT column. I am wondering what cause this? The majority of insertion variants have inserted sequence at the ALT column, Here is one example. I generated the vcf by merging 3 snf files.

 `Chr1      2792801 Sniffles2.INS.580M11    N       <INS>   50      PASS    PRECISE;SVTYPE=INS;SVLEN=11607;END=2792801;SUPPORT=2;COVERAGE=49,42,42,42,50;STRAND=+;AC=1;STDEV_LEN=0;STDEV_POS=0;SUPP_VEC=100;SEQ=<INS> GT:GQ:DR:DV:ID  0/1:10:32:10:Sniffles2.INS.6C5S11 0/0:0:72:0:NULL ./.:0:2:0:NULL`

**Comment by wdecoster** [comment]
Because it is a pretty long insertion.

**Comment by weilu1998** [comment]
@wdecoster  Thanks for the reply! Is there a way to get the breakpoint information of these long insertions?

**Comment by fritzsedlazeck** [comment]
you have these breakpoings: reference location: Chr1:29..  length: SVLEN=11607
hope that helps
Fritz

**Comment by fritzsedlazeck** [comment]
We will be working on something , but right now no.. You can assemble your sample and see if the region gets resolved.. 
Another way is to extract the supportive reads (RNAMES) and the unmapped reads and try to do a local assembly. 

Cheers
Fritz

**Comment by weilu1998** [comment]
@fritzsedlazeck Thanks for the suggestion!
