### ISSUE TITLE
Zero GQ value for homozygous reference call

### ISSUE THREAD

**Issue by weilu1998** [fritzsedlazeck/Sniffles#376]
Hi,

I am curious what's the impact of misaligned reads to the GQ value? In the IGV screenshot below, I am aligning ONT reads of an individual (N29) to the de novo assembly (based on ONT reads from the same individual). For the 404 bp deletion, this individual has homozygous call with 70 reads supporting the genotype, however, the GQ value is 0. This deletion is largely overlapped with a repeat element (orange color in the repeat gff3 panel). Is this causing the 0 GQ value?

<img width="862" alt="image" src="https://user-images.githubusercontent.com/55032100/215581492-960fa4f5-267e-4f5e-a129-60c42b31ba3d.png">

Thanks,
Wei

**Comment by fritzsedlazeck** [comment]
Yeah this is something maybe we are also discussing internally. Sniffles2 only sees reads with MQ20 (parameter) so if the reads are not having that MQ the GT can be skewed. 
GQ is the quality.. yeah that will for sure also be impacted. 
Hope that helps a little. SO GQ obviously means that Sniffles is not certain about the GT.  
thx
Fritz

**Comment by weilu1998** [comment]
Hi @fritzsedlazeck ,

Thanks for the rapid reply! Are you referring to the read MAPQ score? I just pulled out the MAPQ for the reads at this region and the MAPQ scores seem to be high enough with a few mis-mapped reads (due to the repeat). I also observed the same 0 GQ pattern for this SV even after I set the -mapq to 35.

```
samtools view N29.sorted.bam chr1:15193352-15193775  |  awk '{print $5}' | sort | uniq -c
      3 0
      5 1
      1 15
      1 2
      1 43
     74 60
```

**Comment by fritzsedlazeck** [comment]
interesting, yeah there are multiple factors that go into computing the GQ score.. 
The MQ filter in some extreme cases we recently reviewed had some impact on GT value itself. so sorry for that confusion.

**Comment by lfpaulin** [comment]
GQ is computed based on reas calling alternative allele, in your example you have zero reads covering the alt and  70 the reference. In al cases when there are only Reference reads GQ is zero
