### ISSUE TITLE
--non-germline option

### ISSUE THREAD

**Issue by JHBI115** [fritzsedlazeck/Sniffles#377]
Hi , 
 When using the --non-germline I get almost half of the variants (compared with a run that does not uses this option). I would expect to get more, because --non-germline add the ones with low coverage.  
(For both runs I also use --cluster-merge-bnd 50 --minsupport 2 --minsvlen 20 --tandem-repeats  --reference )

Can you please help me understand why using germline yields such a reduced no of variants?

thank you !

**Comment by fritzsedlazeck** [comment]
Yeah this is confusing and will be changed in the next release that is coming now very soon (2-3 weeks).

The non-germline mode is much more conservative when calling variants. This will change now as we specify non-germline mode to 5-20%. This will clear this up . 
Thanks
Fritz
