### ISSUE TITLE
unclear point about strands

### ISSUE THREAD

**Issue by harazono** [fritzsedlazeck/Sniffles#38]
Hi,

thank you for fixing bugs. i sincerely appreciate.
i have some questions about "strands" in  INFO column.
 there is "STRANDS=xx" records.
i extracted SV type and STRANDS pairs from Sniffles output.
i used cancer reads generated by MinION.
result is as below:
```
DEL	+	-
DEL/INV	+	-
DEL/INV/INVDUP	+	+
DUP	-	+
DUP/INS	+	-
INS	+	-
INV	+	+
INV	+	-
INV	-	-
INV/INVDUP	+	+
INV/INVDUP	-	-
INVDUP	+	+
INVDUP	-	-
TRA	+	+
TRA	+	-
TRA	-	+
TRA	-	-
```
i read this ##INFO line:
##INFO=<ID=STRANDS,Number=.,Type=String,Description="Strand orientation of the adjacency in BEDPE format (DEL:+-, DUP:-+, INV:++/--)">

i think INV will have only  ```STRANDS=--```  or ```STRANDS=++``` but in  my ```.vcf```, ```INV``` sometimes have ```STRANDS=+-```.

i would like to know what  +/- means.

**Comment by fritzsedlazeck** [comment]
Hi,
thanks for reaching out. The strands should help with the design of primers for the PCR based validation of the breakpoints/ SVs. In most cases INV are ++/-- . There are however sometimes some more complicated breakpoints that change this rule of  thump. I will update the header.

Let me know if you have further questions. 
Thanks
Fritz

**Comment by harazono** [comment]
Hi Fritz

thanks for kindness reply.
So strands don't have any relation with reference genome's direction?
I have thought that strands informations are corresponding to direction which SV goes from a break point.
and in case of TRA, like fusion genes, I think there are 4 types of connections between two chromosomes.
I wrote 4 cases and I'd like to know which strands pair (++, --, +-, -+) is most suitable for each case.


![2017-11-26 0 59 45](https://user-images.githubusercontent.com/29177343/33232244-e97f14ea-d245-11e7-8240-a5f6bca0f75d.png)

Thanks
Harazono

**Comment by fritzsedlazeck** [comment]
Yes they encode the direction away or coming to the breakpoint, but they do not exactly relate to the strand (reference) itself. 
e.g. I cannot predict the strand (reference) of a heterozygous deletion.

I hope that makes sense.
Cheers
Fritz

**Comment by harazono** [comment]
thank you !
