### ISSUE TITLE
query about PASS tags in reported SVs

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#380]
Hi,

I am not sure if it is a bug or not, but the final SVs reported by Sniffles2 contains a mix of PASS and non-PASS SVs. I understood that the final reported SVs are already QC'ed and filtered. For reference, I am pasting a SV line with GTs from a VCF which has high QUAL but has no PASS tag.

`SSniffles2.DEL.14M0	55	0/1	0/1	0/1	0/1	0/1	0/1	./.	0/1	0/1	0/1	0/1	0/1	./.	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	1/1	0/1	1/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	1/1	0/1	0/1	0/1	0/1	0/0	0/1	0/1	0/1	0/1	1/1	0/1	0/1`

Regards,
Prasun

PS-I am running Sniffles2, build 2.0.6

**Comment by fritzsedlazeck** [comment]
Thanks, Prasun, 
you are asking about in the merged file? 
In the single sample file we sometimes report GT as indication that the GT quality is not good enough ... but the SV itself should be reliable. In our benchmarks we only consider pass SV. 
Thanks
Fritz

**Comment by prasundutta87** [comment]
Hi @fritzsedlazeck , thanks for your reply. Yes, I was asking about the merged file. How do I infer this for the merged file? 

I understood the concept for a single sample file. Is there a theshold for a GQ value for an SV to get PASS?
