### ISSUE TITLE
INV, DEL, DUP with huge SVLENs in sniffles 2.0.7

### ISSUE THREAD

**Issue by ddrichel** [fritzsedlazeck/Sniffles#387]
Re-opening the previously reported issue https://github.com/fritzsedlazeck/Sniffles/issues/235, as it persists in sniffles 2.0.7 and we are still looking for a reasonable solution to filter FP calls without losing too many TPs.
According to sniffles 2.0.7, our largest SVs in a dataset unrelated to the previous report, by SV type:
A 149Mb DUP on chr4, a 131Mb INV on chr1, and a 64.5Mb DEL on chr3.

Kind regards

Dmitriy

**Comment by fritzsedlazeck** [comment]
Thanks Dmitriy, 
yes, this can happen. sometimes these are real events and sometimes they just indicate a transposon jump. Worst case they are alignment errors.  We are working on a better annotation for these events. Maybe we should just refer to them as BND? 
The issue here is really that there is no signal differentiating between a inter chromosomal BND vs. a large e.g. INV. 

Thanks
Fritz

**Comment by ddrichel** [comment]
Hello Fritz,
In the example I worked out here: https://github.com/fritzsedlazeck/Sniffles/issues/235 it is a clear case of Sniffles' internal logic getting confused about start and end positions of the SV in the case that an intrachromsomal transposition is inverted.
In cases like this, there is no reason to assume that this is not a real event - alignment errors are always a prossible problem, independent of this specific issue. Here, Sniffles combines one coordinate from the position where the transposon ends up, and one from the position where it originates from - due to the additional inversion, which is not accounted for in the calculation.
Catching transpositions+inversions would eliminate at least some of these artifacts - maybe all? If not, one could follow up the remaining ones on case-by-case basis, as I did with this one. 
Regarding the SV type - transposition+inversion does not really fit into any other SV category used by Sniffles, other than BND, so I guess that would be reasonable enough, although of course a more fine-grained annotation would be ideal.

Kind regards

Dmitriy

**Comment by leone93** [comment]
Same problem here. Did you find a solution to filter these events @ddrichel ( @fritzsedlazeck )? Otherwise, it isn't easy to use this tool, especially going to the multisample level. I have SV that spans everywhere.

**Comment by ddrichel** [comment]
@leone93 unfortunately I have no solution except for a hard SVLEN cutoff

**Comment by leone93** [comment]
That was honestly my only idea to solve this problem. Which SVLEN did you use? Thanks, Dmitriy

**Comment by leone93** [comment]
I will give it a look. Thank you!         (however I was thinking to choose a conservative threshold)

**Comment by fritzsedlazeck** [comment]
We have now also implemented spetre a CNV caller that is better at very large events using coverage as an input. We have in the newest version also improved GT for del/dup and thus calling accuracy.
