### ISSUE TITLE
[E::hts_open_format] Failed to open "file.name" : Exec format error (mapping with NGMLR, sort/index with samtools, calling with sniffles)

### ISSUE THREAD

**Issue by nbertholdpgc** [fritzsedlazeck/Sniffles#389]
Hey all,
Just to give a disclaimer, I am most definitely VERY new to coding and bioinformatics and so it's quite likely I'm missing something simple!
I have posted this issue [here](https://github.com/samtools/samtools/issues/1825). In summary, I have raw ONT data from performing adaptive sampling. I performed mapping with NGMLR, sorted and indexed the sam/bam file outputs with samtools and then attempted to call with sniffles. However, I keep getting this error when I try and run the sniffles component of my pipeline:

'--2023-04-04 16:35:23-- https://github.com/fritzsedlazeck/Sniffles/blob/master/annotations/human_GRCh38_no_alt_analysis_set.trf.bed
Resolving github.com (github.com)... 20.248.137.48
Connecting to github.com (github.com)|20.248.137.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/path/to/human_GRCh38_no_alt_analysis_set.trf.bed/human_GRCh38_no_alt_analysis_set.trf.bed.31’

 0K .......... .......... .......... .......... ..........  581K
50K .......... .......... .......... .......... .......... 1.11M
100K .......... .......... .......... ........ 91.2M=0.1s

2023-04-04 16:35:24 (1.03 MB/s) - ‘/path/to/human_GRCh38_no_alt_analysis_set.trf.bed.31’ saved [141385]

[E::hts_hopen] Failed to open file merged_fastq-indx.bam
[E::hts_open_format] Failed to open file "merged_fastq-indx.bam" : Exec format error
Running Sniffles2, build 2.0.7
Run Mode: call_sample
Start on: yyyy/dd/mm 00:00:00
Working dir: /path/to/workdir
Used command: sniffles -i /path/to/merged_fastq-indx.bam -v /path/to/merged_fastq.vcf --tandem-repeats /path/to/human_GRCh38_no_alt_analysis_set.trf.bed
Opening for reading: /path/to/merged_fastq-indx.bam
Traceback (most recent call last):
File "/home/usr/.local/bin/sniffles", line 616, in
Sniffles2_Main(config.from_cmdline(),processes)
File "/home/usr/.local/bin/sniffles", line 118, in Sniffles2_Main
bam_in=pysam.AlignmentFile(config.input, config.input_mode)
File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.cinit
File "pysam/libcalignmentfile.pyx", line 950, in pysam.libcalignmentfile.AlignmentFile._open
OSError: [Errno 8] could not open alignment file /path/to/merged_fastq-indx.bam: Exec format error'

Here is the code I've been running
#QC and Chopper
cd "/path/to/fastq_pass/"
gunzip *.fastq.gz
cat *.fastq > merged_fastq.fastq
gzip merged_fastq.fastq
cd /work/dir
gunzip -c /path/to/merged_fastq.fastq.gz | /home/usr/.local/bin/chopper -q 09 -l 500 | gzip > /path/to/merged_fastq.filtered.fastq

#Alignment
wget https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz -P "/path/to/RefIndex_Hg38/"
gunzip /path/to/RefIndex_Hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

"/home/usr/.local/bin/NGMLR/ngmlr-0.2.7/ngmlr" -t 5 -r "/path/to/RefIndex_Hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa" -q /path/to/merged_fastq.filtered.fastq -o /path/to/merged_fastq.sam --bam-fix

samtools view -bhq 1 --output-fmt-option filter="mapq >=0" -o /path/to/merged_fastq.bam  /path/to/merged_fastq.sam

samtools sort -l 0 -m 50G -@ 1 -o /path/to/merged_fastq.sorted.bam -O BAM /path/to/merged_fastq.bam
samtools index -b /path/to/merged_fastq.sorted.bam /path/to/merged_fastq-indx.bam -@ 1
cd /work/dir

#Sniffles variant calling
wget https://github.com/fritzsedlazeck/Sniffles/blob/master/annotations/human_GRCh38_no_alt_analysis_set.trf.bed -P /path/to/human_GRCh38_no_alt_analysis_set.trf.bed
pip install sniffles
sniffles -i /path/to/merged_fastq-indx.bam -v /path/to/merged_fastq.vcf --tandem-repeats path/to/human_GRCh38_no_alt_analysis_set.trf.bed

N.B. I was, using version 1.09 of samtools because the later versions kept giving me a truncated file as [here](https://github.com/philres/ngmlr/issues/83), however, I updated to the latest version and added in the samtools view filtering step as advised in my posting to the samtools issues pages. I

Thanks so much!

**Comment by wdecoster** [comment]
Hi,

A couple of points to address, all potential sources of errors:

1) Instead of 

```
gunzip *.fastq.gz
cat *.fastq > merged_fastq.fastq
gzip merged_fastq.fastq
```

You can do
`cat *.fastq.gz > merged_fastq.gz`


2) This command would probably be better changed to the one below, since you are using `gzip` in that command and therefore write a gzipped fastq.
`gunzip -c /path/to/merged_fastq.fastq.gz | /home/usr/.local/bin/chopper -q 09 -l 500 | gzip > /path/to/merged_fastq.filtered.fastq`

`gunzip -c /path/to/merged_fastq.fastq.gz | /home/usr/.local/bin/chopper -q 09 -l 500 | gzip > /path/to/merged_fastq.filtered.fastq.gz`

3) While ngmlr, in theory, should work, there hasn't been a release in a very long time, and it is to my knowledge not actively maintained. I recommend minimap2. Note that this would also remove the error with the negative mapq.

4) Except for problems from ngmlr, there is no need to remove reads with a low mapping quality. Most tools ignore them.

5) I suspect your final bam file is corrupted. What is the output of `file /path/to/merged_fastq-indx.bam`?

**Comment by nbertholdpgc** [comment]
Thanks!
