### ISSUE TITLE
failed to pass a string to the --min_seq_size optoin

### ISSUE THREAD

**Issue by FrankFeng** [fritzsedlazeck/Sniffles#39]
Hello,

Just a question about how to use the --min_seq_size optoin.

I tried `--min_seq_size  1kb` and got this error `Couldn't read argument value from string '1kb'`. Should I have to pass 1000 instead of 1kb?

The reason that I thought I could pass a string to that option is because `2kb` is the default value according to the HELP:

```
  -r <int>,  --min_seq_size <int>
     Discard read if non of its segment is larger then this. Default: 2kb
```

Thanks~

**Comment by fritzsedlazeck** [comment]
Yes that expects an integer. So 2000. I have corrected the help message for the next version.
Sorry for the confusion.
Thanks
Fritz
