### ISSUE TITLE
Calling variants below the set support

### ISSUE THREAD

**Issue by Akazhiel** [fritzsedlazeck/Sniffles#392]
Hello, 

I used sniffles to call variants with the min support set to 2, but in the resulting VCF I get variants with SUPPORT=1 and DV=1. Why could this be happening?

Command used:
`sniffles --sample-id SNIFFLES_Normal --minsupport 2 --allow-overwrite --cluster-binsize 5 --cluster-merge-len 0 --no-consensus --no-qc --quiet --reference GRCh38.fa -t 20 --minsvlen 10 --mapq 20 --input Normal.bam --vcf Normal_sniffles.vcf`

VCF result with support=1:
```
chr1    145330312       Sniffles2.DEL.2B8BES0   N       <DEL>   60      SUPPORT_MIN   PRECISE;SVTYPE=DEL;SVLEN=-1572;END=145331884;SUPPORT=1;COVERAGE=34,34,34,35,35;STRAND=-;AF=0.029;STDEV_LEN=0;STDEV_POS=0      GT:GQ:DR:DV     0/0:60:33:1
```

Thank you,

Jonatan

**Comment by fritzsedlazeck** [comment]
Thanks for bringing this up. @hermannromanek  maybe we can check this out. 
Thanks
Fritz

**Comment by hermannromanek** [comment]
Hello Jonatan,

Sniffles reports this read because of the --no-qc flag, which disables quality checks including min support.

~Hermann
