### ISSUE TITLE
[Question] Recommended visualization method for multi-sample VCF 

### ISSUE THREAD

**Issue by jolespin** [fritzsedlazeck/Sniffles#394]
I have just successfully run Sniffles2 with ~45 yeast genomes.  What is the recommended way to visualize multi-sample VCF files generated from Sniffles?

**Comment by fritzsedlazeck** [comment]
Sadly there are not really any solutions for this.  did you do the merging also in Sniffles? 

SURVIVOR has some packages to help you QC the overall stats. 
In general its a VCF file so its a common problem to generate plots with small coding required. There are some examples online but nothing like a finished thing. You should be able to use this VCF as any other SV VCF.
Sorry
Fritz

**Comment by jolespin** [comment]
Oh ok no worries.  Thanks for creating this tool btw. The only one that is well documented, easy to install, and works well 🙏🏾. 

Is SURVIVAL the package you would recommend for calculating stats in insertions, deletions, translocations, etc?

**Comment by fritzsedlazeck** [comment]
Thanks, we have now just implemented a small python package to plot and help with QC of Sniffles output. Please try this and give feedback: https://github.com/farhangus/sniffles2_helper
