### ISSUE TITLE
About --minsupport paramter

### ISSUE THREAD

**Issue by songbowang125** [fritzsedlazeck/Sniffles#395]
Hi, I am using sniffles2 on AshkenazimTrio from GIAB by the following cmds:

For each sample:
sniffles --input child.srt.bam --snf sniffles2.child.s10.snf --minsupport 10 
sniffles --input father.srt.bam --snf sniffles2.father.s10.snf --minsupport 10 
sniffles --input mother.srt.bam --snf sniffles2.mother.s10.snf --minsupport 10

Combined calling:
sniffles --vcf sniffles2.combined.vcf --input sniffles2.child.s10.snf sniffles2.father.s10.snf sniffles2.mother.s10.snf --minsupport 10

As you can see, I want to set the minimum support read number to 10. Howerer, in the output VCF, I found some records has DV (Number of variant reads, in the GT fileld) value less than 10. Perhaps the --minsupport was not working when perform multi-sample calling? (I found --minsupport worked on single sample calling). Is there any other parameter that could achiese this?

**Comment by fritzsedlazeck** [comment]
Correct, the merge is trying to rescue variants even if they dont pass the initial calling per sample. 

Thanks
Fritz
