### ISSUE TITLE
tandem repeat beds and genome choice

### ISSUE THREAD

**Issue by jamesdalg** [fritzsedlazeck/Sniffles#398]
Two questions:
1. is there a reason that the no analysis set of hg38 is the version of tandem repeat bed available? What is the advantage?
2. If one wanted to create a custom tandem repeat bed that is compatible with sniffles, is there a specific format for the bed file that must be followed precisely (other than the standard columns)?

**Comment by fritzsedlazeck** [comment]
The short answer is we typically don't recommend using the bed file. It's used to almost overmerge SV signals in those regions defined.
Hope that helps
Fritz

**Comment by jamesdalg** [comment]
Thanks for the fast response! :) That makes things quite simple.

Thanks again,
James Dalgleish
