### ISSUE TITLE
--use_MD_Cigar

### ISSUE THREAD

**Issue by JohnUrban** [fritzsedlazeck/Sniffles#4]
Hi,

Thanks for developing this tool. It seems to do what you says it does. :)

I was curious about the "--use_MD_Cigar" flag. Could you give me any insight of when I would or would not want to use it?

Many thanks.

--John

**Comment by fritzsedlazeck** [comment]
Hi John,
I am working on a new version right now. The parameter you mentioned is actually not effecting anything on that version or in the next. It was in some time ago to speed up the search. 
Sorry for the confusion. 
Cheers
Fritz

**Comment by JohnUrban** [comment]
No problem - thanks for the speedy reply!
Any idea on when the new version will be out? 
...and how much will it differ in performance/outcome from the current version?

**Comment by JohnUrban** [comment]
Apologies for the onslaught of questions here (i.e. I have more).

I am not sure I understand "--max_distance" and when I would want it smaller or larger than the default of 1 kb.

Also, I am curious as to when I would want "--min_cigar_event" to be smaller or larger than the default of 50.

And finally, out of pure curiosity, would there be any merit in making "--max_num_splits" proportional to a given read's length?

**Comment by fritzsedlazeck** [comment]
Hi John,
these are some very good questions. Sorry for not being clear on that. I have just extended the readme so please check it out and let me know if that helps a bit to understand these. 

I have promised some people to get the next version out by next week and I hope I can keep my promise. The new version will be better in detecting smaller SVs (indels) and have options to estimate the genotype and also to do some read phasing. So it will be a major release.
Thanks
Fritz

**Comment by JohnUrban** [comment]
Hi Fritz,
Thanks for the extra bits in the README. They are helpful.
I look forward to your next major release. I will likely be using Sniffles for real stuff in 1-2 weeks, so the timing works out well.
Thanks again.
--John

**Comment by fritzsedlazeck** [comment]
Hi John, 
a bit later as promised, but there is now a new version online. 
Cheers
Fritz

**Comment by JohnUrban** [comment]
Thanks for letting me know. I look forward to using it. Things are slightly delayed on my side as well, but I will likely use it in the next couple weeks.
