### ISSUE TITLE
[Question] How to avoid an SV obscuring another after merge

### ISSUE THREAD

**Issue by waltergallegog** [fritzsedlazeck/Sniffles#400]
Hello,

Continuing the work described in https://github.com/fritzsedlazeck/Sniffles/issues/399 I have run sniffles in tumor samples in default and non-germiline mode, and control sample in default mode.

I have one deletion of length **541** at **chr3:109412879** which is found in the tumor samples. For example in tumor0 it is found with genotype **0/1** (11:10):

```
chr3 109412879 Sniffles2.DEL.2021S2	60	PASS	PRECISE;SVTYPE=DEL;SVLEN=-541;END=109413420;SUPPORT=10;COVERAGE=21,21,21,20,21;STRAND=+-;NM=0.156;AF=0.476;STDEV_LEN=0.000;STDEV_POS=0.000	GT:GQ:DR:DV	0/1:60:11:10 
```

The deletion is not found in the control, which is expected as it has been marked as somatic by other variant callers. From IGV visual inspection this seems to be the case as well  (top control, bottom tumor):
![del-obscured-in-merge](https://github.com/fritzsedlazeck/Sniffles/assets/5270762/4c893077-3a5d-4f96-bf10-1c95c781fd2c)

The problem is that after performing the merge this deletion is not present anymore (at least it is not complete). Instead in the same position (**chr3:109412879**) I get a deletion of size **270**. The deletion is also marked as 0/0 in the control, with 1 supporting read:

| sample | GT:GQ:DR:DV:ID |
|---------------------|--------------------------------------------------------------------------------------------------|
| Control             | **0/0:59:25:1**:Sniffles2.DEL.802DS2,Sniffles2.DEL.802ES2                                            |
| Tumor0 germline     | 0/1:60:11:10:Sniffles2.DEL.2021S2,Sniffles2.DEL.201ES2,Sniffles2.DEL.201FS2,Sniffles2.DEL.2020S2 |
| Tumor0 non germline | 0/1:60:11:10:Sniffles2.DEL.3611S2,Sniffles2.DEL.360ES2,Sniffles2.DEL.360FS2,Sniffles2.DEL.3610S2 |
| Tumor1 germline     | 0/1:20:25:9:Sniffles2.DEL.229BS2                                                                 |
| Tumor1 non germline | 0/1:20:25:9:Sniffles2.DEL.3D33S2                                                                 |

I suppose that when performing the genotyping, the shorter deletion of **270** is found in the control sample at that position, and even if it has only one supporting read, it is obscuring the **541** deletion in the tumor samples, which has much better support.

My question is, is there any way I can avoid this from happening? Ideally I would like both deletions to be reported in the merge:
 - The **541** one, present in the tumor samples and not in the control.
 - The **270** present in all samples, and in control with 0/0 genotype indicating the low coverage.

I tried the option `--combine-separate-intra` and this time got the **541** deletion with this genotyping:

| sample | GT:GQ:DR:DV:ID |
|---------------------|--------------------------------------------------------------------------------------------------|
| Control             | 0/0:0:21:0:NULL                   |
| Tumor0 germline     | 0/1:60:11:10:Sniffles2.DEL.2021S2 |
| Tumor0 non germline | 0/1:60:11:10:Sniffles2.DEL.3611S2 |
| Tumor1 germline     | 0/1:20:25:9:Sniffles2.DEL.229BS2  |
| Tumor1 non germline | 0/1:20:25:9:Sniffles2.DEL.3D33S2  |

But I'm not entirely sure what the option does and what side effects it could have.

Thanks for any help and BR
Walter

**Comment by fritzsedlazeck** [comment]
Sorry @waltergallegog we have improved the rules for merging now significantly and the over-merge as you describe should be resolved. Happy to get feedback but I know this is late. 
Thanks
Fritz
