### ISSUE TITLE
Hello, I'd like to ask if the ref site of < INV><INS > in the vcf result is displayed as N. Is there any way to display the base (ATCG) from the original ref?

### ISSUE THREAD

**Issue by SUGARlx** [fritzsedlazeck/Sniffles#404]
Hello, I'd like to ask if the ref site of < INV><INS > in the vcf result is displayed as N. Is there any way to display the base (ATCG) from the original ref?

#CHROM  POS     ID      **REF**     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
A01     41532   Sniffles2.INS.BS0       **N**       TGACTTTCCGTCTTGATCCCCATCCA......TGCTCGCGCCTCTCTACAAACACTTGA       53      PASS      IMPRECISE;SVTYPE=INS;SVLEN=10702;END=41532;SUPPORT=5;COVERAGE=21,5,5,5,13;STRAND=+-;AF=1.000;STDEV_LEN=43.589;STDEV_POS=0.000;SUPPORT_LONG=0    GT:GQ:DR:DV     1/1:41:0:15

**Comment by SUGARlx** [comment]
hello？🙍🙍🙍

**Comment by fritzsedlazeck** [comment]
WE are currently not supporting the report of ref base. We realize that this is not anymore VCF standard confirm as this has changed in the past 2 versions.
