### ISSUE TITLE
END one off for imprecise deletion

### ISSUE THREAD

**Issue by irunonayran** [fritzsedlazeck/Sniffles#405]
Running sniffles 2.0.7, I get the following output (sequence replaced with random chars):
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
bestref	3723087	Sniffles2.DEL.116S0	ccgggtaggtagtaaatcggataggttcttgtccctgcgtcttctccccatgaagtaatacagaatatatctggcatgcaagttaacgaagtcgccatcaacactctgtcattgtccgtgcaccacagatcc	N	60	PASS	IMPRECISE;SVTYPE=DEL;SVLEN=-132;END=3723219;SUPPORT=8;COVERAGE=20,18,20,22,20;STRAND=+-;AF=0.4;STDEV_LEN=3.83;STDEV_POS=23.685	GT:GQ:DR:DV	0/1:46:12:8
```
Citing the vcf spec 4.2 p.7:

> For precise variants, END is POS + length of REF allele - 1, and the for imprecise variants the corresponding best
estimate.

Therefore `END` should be one less, `END=3723218` . I'm processing the vcf with `bcftools` and it catches this deviation and refuses to process the file: 
`The fasta sequence does not match the REF allele at bestref:3723087:`

**Comment by fritzsedlazeck** [comment]
Thanks for highlighting this. I am not sure (like always) I understand the VCF standard (-1 ?) but it is what it is.. 
Thx
Fritz
