### ISSUE TITLE
A question about the --max_distance option

### ISSUE THREAD

**Issue by FrankFeng** [fritzsedlazeck/Sniffles#41]
I have read the wiki page about this option, and it says that this is the maximum distance to group SV together. I am sorry, but I am still not clear how to use this option. When should I make this parameter smaller or larger than the default of 1 kb?  Thanks!

**Comment by fritzsedlazeck** [comment]
Hi Frank,
so sniffles detects SVs on a per read level. To group these informations together we use the --max_distance parameter to account for inaccuracies of breakpoints across the reads. 
It gets even a bit more complicated as Sniffles estimates that parameter for each SV given its length and type. E.g. for TRA it is the value that you set (default 1kbp). for indel it is more depending on the size (so smaller indels get smaller thresholds, larger indels have a maximum threshold of what you set (default 1kbp)). 

So we actually never alter that parameter, but if you have a e.g. evolutionary distance of your sample vs. reference genome or your reads are even more noisy then normal (e.g. sequenced a pool of flyies on ONT) then I would test out what the increase might result in. E.g. up to 5kbp. 

I hope that helps. I have discussed this a bit more in our Supplement: http://www.biorxiv.org/content/early/2017/07/28/169557

Cheers
Fritz

**Comment by FrankFeng** [comment]
Thanks Fritz!
