### ISSUE TITLE
AlleleFraction filter in sniffles

### ISSUE THREAD

**Issue by netwon123** [fritzsedlazeck/Sniffles#410]
Hello, I've been working on a batch of ont data. in order to avoid the bias of DEL and INS, i want to balance their count by AlleleFraction. I found the af dict in the src/sniffles/postprocessing.py, so i added a few lines of code as a condition judgment, if af was less than a certain value I mark it as "GT". Structurally I got more GT marks, but the count of other variants(DUP, INV) also increased. I don't know why. So I came to you for help!

**Comment by fritzsedlazeck** [comment]
The AF is computed for all SV types and is used in the GT mode and other checks. I dont fully understand what you modified frankly, there are some filters inside of Sniffles that might be avoided by you setting this manually. 
Cheers
Fritz
