### ISSUE TITLE
repeat at the SV breakpoint

### ISSUE THREAD

**Issue by charliechen912ilovbash** [fritzsedlazeck/Sniffles#411]
Hi,
I'm wondering if there exist repeat sequence (e.g. simple repeat) on the SV (e.g. deletion) breakpoint, will it affect the accuracy of SV position? or how does Sniffles v1.0.12 overcome this issue.

**Comment by lfpaulin** [comment]
Hi @charliechen912ilovbash 
In the current version (Sniffles 2) you can provide a tandem repeat annotation file (see annotations directory) to improve the calls
Also, Sniffles 2 will provide and PRECISE/IMPRECISE tag for the breakpoints.
Sniffles 1 development has been discontinued
