### ISSUE TITLE
Why is qc_strand turned off by default?

### ISSUE THREAD

**Issue by weishwu** [fritzsedlazeck/Sniffles#416]
Is there a reason why strand bias filter is turned off by default? Does Nanopore sequencing have some level of strand bias for certain types of SVs by nature?

**Comment by fritzsedlazeck** [comment]
Yes we are still evaluating if that parameter is actually worth including..  The results are currently really mixed. 
Thanks
Fritz

**Comment by weishwu** [comment]
Thanks for the quick answer.
If I need a stringent set of clean variants, what filters should I apply on the Sniffles outputs?

**Comment by fritzsedlazeck** [comment]
PASS filter should get you there. The precision is typically very high as we care about that. So not really much to suggest here..

**Comment by weishwu** [comment]
Does it make sense to use a hard filter on DV or GQ?

**Comment by fritzsedlazeck** [comment]
You of course can try that.. we have not evaluated that to be that useful ... GQ has sometimes a good indication on how reliable the GT is, but there is also something in there that we need to tune a bit more in extreme situations..

**Comment by weishwu** [comment]
Thanks for the explanation.
