### ISSUE TITLE
How to phase SVs

### ISSUE THREAD

**Issue by weishwu** [fritzsedlazeck/Sniffles#417]
I tried using the `--phase` parameter but it's `PHASE=NULL` for all variant in the output. The documentation says `--phase` requires the input alignment to be phased. Could anyone tell me how to phase the alignment? (I used minimap2 to align the reads).

**Comment by fritzsedlazeck** [comment]
Hi,
You need a phased tagged bam file. This can be produced be eg. Whatshap.  So after mapping, call Snv , phase them and then tag the bam file.

We have implemented a workflow in princess.

Hope that helps
Fritz

**Comment by weishwu** [comment]
Got it. Thanks!
