### ISSUE TITLE
Filter variants before merging multiple VCFs? 

### ISSUE THREAD

**Issue by jjuhh** [fritzsedlazeck/Sniffles#419]
Hi,

I really enjoy using Sniffle2 due to its fast speed, low resource usage, and fancy algorithm. Thank you! 

I have HiFi DNA bam files from tumors and paired normal samples from 2 patients, respectively. So, I have two tumor HiFi DNA and two normal HiFi DNA samples. 
I have called SVs using Sniffles2 with default options for each HiFi DNA Bam files.  Then, I merged the four VCFs according to the instruction described in Sniffles2's GitHub markdown page.

I have a question about using `SUPP_VEC` for plotting an upset plot. Even if the `SUPP_VEC` was 0101(Normal1,Tumor1,Normal1,Tumor1) for one SV, the genotypes of the samples looked like the following : 

> GT:GQ:DR:DV:ID  0/0:0:12:0:NULL 0/0:20:11:1:Sniffles2.DEL.E6CS0 ./.:0:1:0:NULL  0/1:6:5:2:Sniffles2.DEL.C55S0,Sniffles2.DEL.C57S0,Sniffles2.DEL.C58S0,Sniffles2.DEL.C59S0,Sniffles2.DEL.C56S0

> GT:GQ:DR:DV:ID  0/0:0:7:0:NULL  0/0:15:9:1:Sniffles2.DEL.E6DS0  ./.:0:1:0:NULL  0/1:4:1:2:Sniffles2.DEL.C63S0,Sniffles2.DEL.C64S0,Sniffles2.DEL.C65S0

> GT:GQ:DR:DV:ID  ./.:0:0:4:Sniffles2.INS.262S0   1/1:5:0:2:Sniffles2.INS.267S0,Sniffles2.INS.268S0       ./.:0:0:1:Sniffles2.INS.1FES0   1/1:2:0:1:Sniffles2.INS.234S0,Sniffles2.INS.235S0

> GT:GQ:DR:DV:ID  ./.:0:3:0:NULL  0/1:18:4:3:Sniffles2.DEL.123CS0,Sniffles2.DEL.123BS0    ./.:0:3:0:NULL  0/0:6:6:1:Sniffles2.DEL.1094S0,Sniffles2.DEL.1096S0,Sniffles2.DEL.1095S0

> GT:GQ:DR:DV:ID  ./.:0:3:0:NULL  0/1:13:6:3:Sniffles2.DEL.123DS0 ./.:0:2:0:NULL  0/1:1:3:1:Sniffles2.DEL.109BS0,Sniffles2.DEL.109ES0,Sniffles2.DEL.109DS0

I believed that only the tumor samples had the supported SV called in the original VCF iles, but the GT, GQ and depth of some variants were not sufficient to support the SV that much.

So, my question is : What do you think about filtering the original VCF files based on GQ and depth before merging multiple VCFs? Or is it better to filter variants after merging the VCFs before plotting upset plot. I thought the order of the filtering steps could affect the final SUPP_VEC, and I believed the former might be a better way to ensure biologically correct discovery of shared SVs between tumors. 

Finally, considering my situation, would it be better to run Sniffle2 with the `--mosaic` option on tumor samples and without the `--mosaic` option on normal samples, and then merge them, rather than using the default settings for all the data?

Thank you!
JH

**Comment by jeremymchacon** [comment]
Hi @jjuhh , did you ever come to a conclusion about this? I am also wanting to do some filtering on the single-sample vcfs prior to merging, but it seems like the merging call only supports snf files, which I don't know how to filter.

**Comment by jjuhh** [comment]
@jeremymchacon I have chosen to filter variants after merging all VCF(or SNF) files and update the variant call results based on the base quality for each sample. 
For instance, if the Genotype Quality(GQ) is below 30 in a specific sample, I replace the GT, regardless of its original value, with `./.`. 

What are your thoughts on this strategy? Does it seem reasonable to you? I would appreciate it if you could suggest an alternative strategy or share your opinion.

Thank you!

**Comment by jeremymchacon** [comment]
Thanks for responding @jjuhh. I think my question is more mundane than yours; the problem I am having is that the population mode (merging the files) only takes snf files as input, and I don't know how to filter these the way I would vcfs. Did you have a way to filter the snf files? Or was not being able to do this why you switched to filtering the merged vcf?

Regarding your biological question, your approach seems reasonable to me. It seems like the ideal situation would be to have genotype quality filtering be a parameter in the single-sample mode, so that they would be filtered before the snfs are made,  but since this isn't available, your approach seems good.

**Comment by fritzsedlazeck** [comment]
sorry @jeremymchacon and @jjuhh  its getting hard for me to stay on top of all issues. 

Yes defenelty filter after merge. Sniffles uses these SNF files and basically doesnt care about the pre-filtered vcf file at the merge stage!  Also filtering after the merge makes things more conistent. 

Closing this now and sorry for the late reply. 
Fritz
