### ISSUE TITLE
How to specify pedigree information in multisample calling mode?

### ISSUE THREAD

**Issue by tnguyengel** [fritzsedlazeck/Sniffles#420]
How do we specify pedigree information for families or trios for multisample calling mode?

**Comment by fritzsedlazeck** [comment]
you cannot right now. Its a gernal merge meaning that it just merges across the samples. The GT field and SUP_VEC field will help you navigate which variants are e.g. de novo in a trio setting or somatic between tissues. 
Hope that helps
Fritz

**Comment by tnguyengel** [comment]
Do you suggest merging different families or different populations in separate batches so that we can tweak the merge settings to be more aggressive within a family or within a population?

**Comment by fritzsedlazeck** [comment]
Sorry for the super slow reply :( . So if we have multiple families we typically merge all of them at once to avoid inconsistencies. Then we analyze each family independently but also have the benefit of knowing if a certain variant is co-detected in other samples. 
Cheers
Fritz
