### ISSUE TITLE
Sniffles2 Error: A tandem repeat annotations file was provided, but no matching annotations were found for any contig in the sample input file. Please check if the contig naming scheme in the tandem repeat annotations matches with the one in the input sample file. (Fatal error, exiting.)

### ISSUE THREAD

**Issue by nbertholdpgc** [fritzsedlazeck/Sniffles#421]
Hi all,
I've been struggling with the --tandem-repeats flag. Briefly, I am trying to perform variant calling on Nanopore adaptive sampling data that has been basecalled with Dorado. When I remove the --tandem-repeats flag, it works fine, however when I include it I get the following error message:
_Sniffles2 Error: A tandem repeat annotations file was provided, but no matching annotations were found for any contig in the sample input file. Please check if the contig naming scheme in the tandem repeat annotations matches with the one in the input sample file. (Fatal error, exiting.)_
My code for this is:
`sniffles -i Dorado_sorted.bam -v DoradoTR.vcf --reference GCF_000001405.40/GCF_000001405.40_GRCh38.p14_genomic.fna --non-germline --no-consensus --tandem-repeats human_GRCh38_no_alt_analysis_set.trf.bed`
I'm very new to coding, so it's likely a simple fix :) 
Thanks in advance!

Natasha Berthold

**Comment by wdecoster** [comment]
I think the error is rather descriptive of what is wrong, and suspect the chromosome identifiers in the tandem-repeats file (e.g. chr1, chr2, chr3) do not match with the chromosome names in the reference (e.g. 1, 2, 3) (and the one you used to align the data).

**Comment by wdecoster** [comment]
See [this post](https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use) about the recommended reference genome to use: GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

**Comment by nbertholdpgc** [comment]
Worked brilliantly! Thank you :D
