### ISSUE TITLE
Sniffles output for breakpoints to circos 

### ISSUE THREAD

**Issue by deepti100rao** [fritzsedlazeck/Sniffles#423]
I have a sniffles vcf for a plant genome. I am trying to plot the bnd variants as ribbons in circos. Sniffles doesn't provide the end positions for bnd variants. Since I need to provide a circos input in the format: chr1 start1 end1 chr2 start2 end2, can you tell me how to get the end1 and end2 positions from the sniffles vcf file?

**Comment by fritzsedlazeck** [comment]
It does report the end locations of BND in the breakend format. Look at the alt column.  
I think cicos / ribbon uses bedpe format. Here the two start and the two end coordinates represent variability of the breakpoint. So the easiest is to just take the start/ stop of Sniffles and put it twice in these columns .   I think SURVIVOR has also a package to translate VCF to bedpe. 
Hope that helps
Fritz
