### ISSUE TITLE
How to group CNV

### ISSUE THREAD

**Issue by CVan19** [fritzsedlazeck/Sniffles#43]
Hi,
I have got many structral variants called by Sniffles. Now I want to extract copy number variants from them, but I don't know what to do .  Is it proper to just treat DUP and DEL as copy number variants ?
I'll appreciate your help!

**Comment by fritzsedlazeck** [comment]
Hi,
so DUP (for every SV caller) are just tandem duplications not general duplications (in terms of CNV calling).  Do you have a CNV call set from Illumina?

What we saw is that (at least for cancer) often TRA indicate the copy number changes in addition to DUP and DEL. But there is not a straight forward answer that always works. 

 What exactly do you have in mind? If its somehow secrete just message me  over email.
Cheers
Fritz

**Comment by CVan19** [comment]
Thanks for your reply. I read an artical named "Detection and assessment of copy number variation using PacBio
long-read and Illumina sequencing in New Zealand dairy cattle". The author grouped DUP and DEL called by Sniffles as CNV . Here is the original words in the artical:
```
Sniffles software identified a total of 38,709 putative
SV, of which 19,797 were CNV (deletions, n = 18,577;
duplications, n = 1,220) in a PacBio sequence generated
from Esteem’s DNA. Of the 3,532 CNV (deletions,
n = 3,055; duplications, n = 477) that remained after
filtering, 899 (deletions, n = 740; duplications, n = 159)
and 126 (deletions, n = 76; duplications, n = 50) overlapped
by at least 1 bp with Ensembl (build 84; http://
mar2016.archive.ensembl.org/index.html) annotated
genes and exons, respectively (Table 1).
```
I am not sure whether he is right. 
If you are interested , you can read the full articale:[http://www.journalofdairyscience.org/article/S0022-0302(17)30352-1/pdf](url)

**Comment by mschatz** [comment]
It is true that the Sniffles insertions and deletions are copy number changes, but they will be fairly small in size, especially the insertions. If you are looking for very large amplifications (100s of kb to megabases) you will probably be more successful using a read depth approach since it is hard to always capture and connect the breakpoint for these big events

Good luck!

Mike

**Comment by fritzsedlazeck** [comment]
Thanks for pointing me at that. My point is yes DEL + DUP are CNVs but not exclusive.
As Mike is pointing out an INS or TRA can cause CNV alterations as well.
So no the author is not wrong, but maybe ignoring other events that might get classified by a CNV caller.
Cheers
Fritz

**Comment by CVan19** [comment]
Thanks , Mike and Fritz.  I think I should use another tool designed for calling CNV like CNVnator. But most of them are intended for Illumina data. Is there a CNV caller for Pacbio data you can recommend for me?

**Comment by mschatz** [comment]
We find that you can still use CNVnator or other tools as they will just
use the beginning of the read alignments. I have a hunch that you could do
a little bit better for smaller event by incorporating the full length read
but we dont have any code at this time to work with it.

Mike

**Comment by CVan19** [comment]
Thank you for your advice. I will try that !
