### ISSUE TITLE
Detect base mutations

### ISSUE THREAD

**Issue by ShelaLJJ** [fritzsedlazeck/Sniffles#430]
Dear developers,

Thank you for developing this tool! May I ask is it possible to use Sniffles to detect base mutations that are introduced on purpose in my sample? (For example, A to G)

Many thanks!
Shela

**Comment by fritzsedlazeck** [comment]
Dear Shela
You mean like substitutions ?  No it's not. Sniffles is designed for Sv detection by default down to 50bp but can likely be accurate down to 10bp maybe . 

Thanks 
Fritz

**Comment by fritzsedlazeck** [comment]
Closing due to no answer.
