### ISSUE TITLE
Any updates about duplication number on Sniffles2

### ISSUE THREAD

**Issue by justwalking2017** [fritzsedlazeck/Sniffles#431]
Hi Friz,

Is there any update about how to interpret duplication number from the results of Sniffles2? 
We want to get exact copy number of duplication variants from the vcf file by Sniffles2. Any comments or suggestions would be appreciated.

Pan

**Comment by fritzsedlazeck** [comment]
sorry not yet.. There is spectre that we are also developing which is a CNV caller that then also reports out copy numbers directly. 
Here is the link:
https://github.com/fritzsedlazeck/Spectre 

Thanks
Fritz
