### ISSUE TITLE
Optimum parameters for long SV detection

### ISSUE THREAD

**Issue by MariosGvr** [fritzsedlazeck/Sniffles#439]
Hi and thank you for this amazing tool!

We are currently trying to detect known inversions (much larger than 100kbp, they could reach several Mbp) in some genomic regions of interest.
How would you advise setting the parameters to help Sniffles detect and report long SVs (deletions and inversions)?
I have Hifi reads (~20x coverage) aligned on GRCh38 and CHM13 using pbmm2 and Winnomap.

Thank you,
Marios

**Comment by fritzsedlazeck** [comment]
We found recently an issue with long deletions being aggressively filtered. This has been fixed now since 2.5.0. For inversions we benchmarked more using StrandSeq data and are working on new approaches. 
Cheers
Fritz
