### ISSUE TITLE
--reference options doesn't override the reference genomes in a CRAM file

### ISSUE THREAD

**Issue by bcantarel** [fritzsedlazeck/Sniffles#440]
I was trying to run sniffles in a workflow, where the alignments and variant calls are done on separate VMs.  

I get an error that it can't find the genome.fa file (gives the path from the alignment work directory) even though I pass that file as --reference genome.fa.  

If I convert the cram file to cram using samtools with the local genome.fa ie 
samtools view -@ ${threads} -C -T genome/genome.fa -o test.cram original.cram
samtools index -@ ${threads} test.cram

With the new cram sniffles runs without error.

**Comment by fritzsedlazeck** [comment]
@hermannromanek is that fixed? maybe we can just close this?
