### ISSUE TITLE
how do you find the sequence of a long insertion?

### ISSUE THREAD

**Issue by jshenVaxart** [fritzsedlazeck/Sniffles#441]
I get this output in my vcf file
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
Ad-ED119.9_ECJ9+CMV-JnJ-StabWuS-SV40-dsRNA      18587   Sniffles2.INS.3S0       N       <INS>   56      PASS    PRECISE;SVTYPE=INS;SVLEN=8050;END=18587;SUPPORT=1609;COVERAGE=87914,88129,88187,88034,87662;STRAND=+;NM=0.032;AF=0.099;STDEV_LEN=0;STDEV_POS=0;SUPPORT_LONG=1608        GT:GQ:DR:DV     ./.:60:79428:8759

so the insertion is at position 18587, but I can't figure out what the sequence is. Is there a way to print that out? 

Thanks

**Comment by jshenVaxart** [comment]
As an update, I have tried --genotype-vcf and it did not print out the genotype ie:

sniffles \
--input /output/barcode01/barcode01_ngmlr_sorted.bam \
--ref /output/reference/reference.fa \
--genotype-vcf /output/barcode01/barcode01_ngmlr.vcf \
--non-germline \
--vcf /output//barcode01/barcode01_ngmlr_altPrinted.vcf

**Comment by fritzsedlazeck** [comment]
Sorry for the late reply. I can only speculate. When an insertion is getting too long its not anymore represenated as a CIGAR event from the mapper. Then Sniffles tries to figure it out over the split reads or branching reads (the unmapped parts) but that is not super sophisticated at the moment..  

If you need that particular sequence you can do two things:
1. Check it out in IGV, maybe Sniffles is doing something wrong and we are happy to look at this. 
2. Ask Sniffles to report the read names (parameter --rnames. I think). Extract the reads and try to assemble the region. 

Hope that helps. We will work on a better solution which is on our list of things to tackle this or early next year. 
Fritz
