### ISSUE TITLE
Wrong header after genotyping

### ISSUE THREAD

**Issue by Riccardo1274** [fritzsedlazeck/Sniffles#449]
Good morning,

I am having a problem after genotyping with sniffles2 a vcf obtained by a merging step with SURVIVOR. 
The format field after the genotyping step is:
GT:GQ:DR:DV     0/1:14:2:2
while the header remains the same as after the SURVIVOR merging process:
##FORMAT=<ID=PSV,Number=1,Type=String,Description="Previous support vector">
##FORMAT=<ID=LN,Number=1,Type=Integer,Description="predicted length">
##FORMAT=<ID=DR,Number=2,Type=Integer,Description="# supporting reference,variant reads in that order">
##FORMAT=<ID=ST,Number=1,Type=String,Description="Strand of SVs">
##FORMAT=<ID=QV,Number=1,Type=String,Description="Quality values: if not defined a . otherwise the reported value.">
##FORMAT=<ID=TY,Number=1,Type=String,Description="Types">
##FORMAT=<ID=ID,Number=1,Type=String,Description="Variant ID from input.">
##FORMAT=<ID=RAL,Number=1,Type=String,Description="Reference allele sequence reported from input.">
##FORMAT=<ID=AAL,Number=1,Type=String,Description="Alternative allele sequence reported from input.">
##FORMAT=<ID=CO,Number=1,Type=String,Description="Coordinates">

Do you know any way to fix this?

Kind regards,

Riccardo Rossi

**Comment by fritzsedlazeck** [comment]
This will be fixed in the new release thats coming today/tomorrow. 
Thanks for reporting and thanks @zhengxinchang for fix.
