### ISSUE TITLE
Analysis performed only on 13 first contig

### ISSUE THREAD

**Issue by RxLoutre** [fritzsedlazeck/Sniffles#45]
Hi again, sorry for the second and maybe dumb question.

I just noticed that sniffles only worked on my first 13 contigs, but I have 500+ contigs in total. I did not saw any option to restrict the analysis only on the first contigs... But maybe I did something wrong ? Any idea ?

Thanks again,

Roxane
```

	Switch Chr Contig_11
		# Processed reads: 2680000
		# Processed reads: 2690000
		# Processed reads: 2700000
		# Processed reads: 2710000
		# Processed reads: 2720000
		# Processed reads: 2730000
		# Processed reads: 2740000
		# Processed reads: 2750000
		# Processed reads: 2760000
	Switch Chr Contig_12
		# Processed reads: 2770000
		# Processed reads: 2780000
		# Processed reads: 2790000
	Switch Chr Contig_13
		# Processed reads: 2800000
		# Processed reads: 2810000
		# Processed reads: 2820000
		# Processed reads: 2830000
Finalizing  ..

```

**Comment by fritzsedlazeck** [comment]
Hi Roxane,
Thanks for reaching out.
Could you check if there are other reads mapped to the other contigs?

Thanks
Fritz

**Comment by RxLoutre** [comment]
Hi Fritz, thanks for your fast answer,

Indeed, reads are also mapped on all other contigs.

I tried to launch again sniffle by using more parameters (First time I only used input and output), and it seems it is still running and it is reading my others contigs as well in the end.

Here the difference between my first and e second command : 

```
#SNiffle try number1
./sniffles -m '/media/loutre/SUZUKII/alignement/ngmlr-pacbio/ngmlr-pacbio-suzukii-sorted.bam' -v '/media/loutre/SUZUKII/break-point-research/sniffles/variant-detection-sniffles.vcf'

#Sniffle with more parameters
./sniffles -m '/media/loutre/SUZUKII/alignement/ngmlr-pacbio/ngmlr-pacbio-suzukii-sorted.bam' -v '/media/loutre/SUZUKII/break-point-research/sniffles/variant-detection-sniffles2.vcf' --cluster --genotype --cluster_support 10 -l 1000
```
