### ISSUE TITLE
query about filtering SVs in tandem repeat and segmental duplications

### ISSUE THREAD

**Issue by prasundutta87** [fritzsedlazeck/Sniffles#453]
Hi,

When working with trios, is it recommended to filter out SVs which are present in tandem repeat and segmental duplications? Mapping of long reads (ONT in my case, R9+R10 chemistry) has been kind of noisy there when checked randomnly some of them. Since I am currently interested in de novo SVs (and other modes of inheritance), a lot of false positives erupt and filtered using genotypes and depth. Ideally, there should be just 1 or a couple of true de novo of SVs per generation, but I am getting approx. upto 100 de novo SVs and many of them will be false +ves. What is your recommendation and have you seen the same? 

For your reference, I have also pasted some information below where I found de novo SVs in proband. You can see that both parents are homozygous for the reference allele, have good depth as well (> 5 reads filter) but have 0 GQ. Why is it like this?

chr1 10111327  GTs: 0/0 0/0 0/1	 DPs: 15 18 13	 GQs: 0 0 2
chr1 42285251  GTs: 0/0 0/0 0/1	 DPs: 19 15 11	 GQs: 0 0 7
chr1 74500612  GTs: 0/0 0/0 0/1	 DPs: 14 15 13	 GQs: 0 0 2
chr1 134075083  GTs: 0/0 0/0 0/1	 DPs: 27 28 16	 GQs: 0 0 6
chr17 56431596  GTs: 0/0 0/0 0/1	 DPs: 6 14 18	 GQs: 0 0 0
chr17 80903066  GTs: 0/0 0/0 0/1	 DPs: 11 17 22	 GQs: 0 0 40
chr17 80445220  GTs: 0/0 0/0 0/1	 DPs: 7 14 19	 GQs: 0 0 60
chr17 81233355  GTs: 0/0 0/0 0/1	 DPs: 13 11 14	 GQs: 0 0 24
chr17 83296126  GTs: 0/0 0/0 0/1	 DPs: 8 8 7	 GQs: 0 0 6
chr20 61555400  GTs: 0/0 0/0 0/1	 DPs: 20 14 10	 GQs: 0 0 10
chr21 42111131  GTs: 0/0 0/0 0/1	 DPs: 13 12 13	 GQs: 0 0 2
chr22 12198768  GTs: 0/0 0/0 0/1	 DPs: 15 30 8	 GQs: 0 0 3
chr22 56788496  GTs: 0/0 0/0 0/1	 DPs: 13 17 12	 GQs: 0 0 17
chr22 20336502  GTs: 0/0 0/0 0/1	 DPs: 11 14 11	 GQs: 0 0 7

Regards,
Prasun

PS (I have ised Sniffles2_2.0.6)

**Comment by fritzsedlazeck** [comment]
This is tricky. not all SV from tandem repeats need to be filtered. We only filter for paracentromeric regions.. You will end up with a couple of candidate de novo variants. We are currently using Samplot for manual assessment. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Closing this. Hope the answer made sense.
