### ISSUE TITLE
AF calculation question

### ISSUE THREAD

**Issue by ErminZ** [fritzsedlazeck/Sniffles#455]
Hello, 

Thank you for writing the sniffles, it's the best long-read SV caller that I used so far. Would I ask how sniffles2 generates the AF number in the info section? 

For example: a deletion candidate filtered by GT.

IMPRECISE;SVTYPE=DEL;SVLEN=-7922;END=9983521;SUPPORT=567;-AND=+ ;**AF=0.000**;STDEV_LEN=323.034;STDEV_POS=205.315

GT:GQ:DR:DV.   0/0:60:1512714:567

If I extract the DV:DR number and calculate AF by myself, it's 0.0003746 for this deletion, not 0. Thank you for your explanation of the GT filter in advance!

**Comment by fritzsedlazeck** [comment]
I think for this .. its a rounding thing.  like if you round the exact AF to the digits you see that is the same. 
Thanks
Fritz

**Comment by hermannromanek** [comment]
Hi Ermin,

Fritz is correct, AF (or any float values in the INFO field) are rounded to 3 digits. While not explicitly stated in the VCF spec, it can be inferred from the example VCF in Chapter 1.1, which I guess was the reason Moritz implemented it that way.

Kind regards,
Hermann
