### ISSUE TITLE
Reference or alternate bases are N and SVLEN is off by one

### ISSUE THREAD

**Issue by tcezard** [fritzsedlazeck/Sniffles#456]
Hi,
I work at the [European Variation Archive](https://www.ebi.ac.uk/eva/) where we receive submissions of variation including some generated by Sniffles:
We wrote a [vcf-validator](https://github.com/EBIvariation/vcf-validator) to ensure compliance with the specification and it has flagged couple of issues with files generated by your software. 

I'm not too familiar with how sniffles works so it is possible that I'm getting things wrong. Apologies if I did.

 - It looks like the when insertion/deletion are written N is being added to the ref or alt field instead of the correct base. 
This has also been reported [here](https://github.com/fritzsedlazeck/Sniffles/issues/433#issuecomment-1761194602)
The requirement for padding bases is described in section 1.4.1 of the [VCF 4.2 specification](https://github.com/samtools/hts-specs/blob/master/VCFv4.2.pdf) and include cases with symbolic allele.

- I believe there is a related issue with SVLEN where the VCF specs says:
 > `##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">`
One value for each ALT allele. Longer ALT alleles (e.g. insertions) have positive values, shorter ALT alleles (e.g.
deletions) have negative values.
and when sniffles output the REF or or ALT with an N it does not count the length of the N. 
```
1       10000  .     N       AATTTCTGTT .      .    SVTYPE=INS;SVLEN=10;
```
SVLEN should be `len(AATTTCTGTT) - len(N) = 9` here. Although I think if both issue could be solved if the padding base was added.

- Finally I wanted to bring to your attention the new version of [VCF 4.4](https://github.com/samtools/hts-specs/blob/master/VCFv4.4.pdf) that attempt to make writing structural variants a bit clearer.

**Comment by hermannromanek** [comment]
Hi Timothee,

Thank you for your input. For the next version of Sniffles we are in the process of improving adherence to the VCF spec. This release may not address all issues yet, but we're trying to tackle them one by one. I'll check the one you mentioned.

Thanks,
Hermann

**Comment by tcezard** [comment]
Thanks for the reply. Happy to help if we can. Feel free to contact us.

**Comment by fritzsedlazeck** [comment]
Dear @tcezard the new code base (not yet a full release) should have that fix included for the off by one. You can force reference character for deletions with the usage of the reference parameter.

**Comment by tcezard** [comment]
Awesome. Thank you!
