### ISSUE TITLE
Sniffles2 Error: Malformed CIGAR

### ISSUE THREAD

**Issue by weishwu** [fritzsedlazeck/Sniffles#457]
Sniffles version: 2.2 (pulled from: `docker://quay.io/biocontainers/sniffles:2.2--pyhdfd78af_0`)

Command-line:
```
sniffles \
       --sample-id {wildcards.sample} \
       --reference {params.ref} \
       --input {input} \
       --vcf {output} \
       --no-qc \
       -t {threads} \
       --mosaic \
       --minsvlen {params.minsvlen} \
       --mapq {params.mapq} \
       --min-alignment-length {params.min_alnlen} \
       --genotype-ploidy {params.ploidy} \
       --phase \
       --output-rnames
```

Problem:
Many lines saying this kind of errors:
```
Sniffles2 Error: Malformed CIGAR '29840M376D-27298H' with pos 12695989 of read '3cfe99aa-be26-4d2b-9f98-63272a5dfa87' (invalid literal for int() with base 10: ''). Skipping.
```

The log file is attached.
[5555C-A-9815-CV-1.sniffles.log.zip](https://github.com/fritzsedlazeck/Sniffles/files/14451228/5555C-A-9815-CV-1.sniffles.log.zip)

What does this error mean? Is it ignorable?

Thanks.

**Comment by fritzsedlazeck** [comment]
Hi @weishwu 
sorry for the slow reply. The - in the cigar string is strange/wrong! See specifications: https://samtools.github.io/hts-specs/SAMv1.pdf 
I would contact the developer of the mapping method.  In your example it should be  without the - ! 
Thanks
Fritz
