### ISSUE TITLE
Why are there fewer SVs with --mosaic?

### ISSUE THREAD

**Issue by weishwu** [fritzsedlazeck/Sniffles#458]
I ran Sniffles2 twice, once with `--mosaic` and once without it. My understanding is that `--mosaic` finds variants with a wider range of frequencies, so theoretically there should be more SVs found than the germline mode. However, Sniffles output 7599 SVs with `--mosaic`, and 29000 without it. 
I guess my understanding is wrong. Does `--mosaic` actually exclude germline variants?
Thanks.

**Comment by fritzsedlazeck** [comment]
Mosaic only targets SV with variant allele frequencies of 30% or below. Thus you expect lower.  So yes exclude germline.
