### ISSUE TITLE
support needed: if ALT is base-level identical across samples from a muli-sample vcf generated by sniffles2?

### ISSUE THREAD

**Issue by maxineliu** [fritzsedlazeck/Sniffles#462]
For the output from combined calling, sniffles2 will provide an actual sequence in the ALT column for nearly every SV, except for a few symblic ALT representations. Does this imply the SV exited in every sample is identical at base-level? If not, could you decribe the criterior used for this step -- how is a consensus ALT sequence generated?

I have searched in [the articled pubilished in 2024](https://www.nature.com/articles/s41587-023-02024-y#Sec7), no clue found. 

Thanks,
Maxine

**Comment by fritzsedlazeck** [comment]
so on a per sample bases you can get the ALT coloumn completelfy filled with providing the reference fasta. 

You are probably asking for the merge (across different samples)? This case one representative sequence is chosen. In the new code version (short before release) we also cross check sequencing identity thus the sequence reported should represent all samples closely (identity above 85% I think.. would need to look it up again or @hermannromanek might know.

**Comment by maxineliu** [comment]
Thank you for answering!

**Comment by maxineliu** [comment]
> Thank you for answering! Another question is when combining SNFs, [An SV candidate matches a group if it has the same SV type and the sum of start position and length deviation is less than](https://www.nature.com/articles/s41587-023-02024-y#Sec7:~:text=An%20SV%20candidate%20matches%20a%20group%20if%20it%20has%20the%20same%20SV%20type%20and%20the%20sum%20of%20start%20position%20and%20length%20deviation%20is%20less%20than) multiply M by the square root of the smaller value between `SVLength` and `GoupSVLength`.
> 
> That's what is mentioned in the article. What is the defination of `start position`. I mean if it is chromsomal coordinates, looks weired...

Does the start position refer to a relative distance to the group average start position? It should be negtive if the sv start before the average group start?

**Comment by fritzsedlazeck** [comment]
So start is the left most and stop is the right most position/breakpoint. The positions are defined by the read alignments (ie. based on the split or alignment signal) there is a filtered distribution that we eliminate the outliers of the signals and then take the median position from the alignments. 
Hope that helps
Fritz

**Comment by maxineliu** [comment]
I'm still not quite clear. Perhaps you misunderstood my question?

The formula that I'm struggling to understand is:
![math](https://github.com/maxineliu/picBed/blob/main/img/sniffles_snf_cluster.png?raw=true)

It belongs to the section on how to cluster SV candidates across multiple SNFs.  In my understanding, every SV candidate in SNFs already has a definite start position. This position is determined in the way you explained.

This start position should be something like chr1 2034 (the base at position 2034 on chromosome 1). But if that's the case, then on the left side of this equation—the sum of the start position and the length deviation, the value for SV at the tail of a chromosome would be larger than that from beginning, which seems illogical.

**Comment by fritzsedlazeck** [comment]
Oh I see my reply was on a per read/sample level. You are interested in the population/ across sample merge. 
So again the start is always the left most and stop is the right most position. So the start will always be < than the stop. 
Each position is redefined independently from each other.  What basically happens is that we have a minimum wobble/tollorance of 500bp across samples. The 500bp are  scaled to avoid over or under merging when the SV size (SV length) gets smaller.  So the square root is just to account for the SV sizes within a cluster. The mechanism starts with one SV from one sample as a representative and then gets added new SV to it. 

We have now btw. changed this :) . We are following much more closely what Truvari collapse is doing as we observed some overmerging for smaller SV..

**Comment by fritzsedlazeck** [comment]
I am closing this. Hope its answered.
