### ISSUE TITLE
Feature Request - Force calling FORMAT header lines

### ISSUE THREAD

**Issue by ACEnglish** [fritzsedlazeck/Sniffles#466]
When force calling, sniffles populates the fields FORMAT/GQ,FORMAT/DR,FORMAT/DV but does not add tags defining these fields to the header. For example `##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Phred scaled quality of genotype">`. If these header lines aren't present in the input vcf then the output vcf is invalid.

**Comment by fritzsedlazeck** [comment]
Right I think @zhengxinchang has a code request for that. 
Thanks for this
Fritz

**Comment by hermannromanek** [comment]
Yes, it's #451 

I'll merge it once #465  is fixed.
