### ISSUE TITLE
How to view the tandem repeats in the VCF file generated by Sniffles2?

### ISSUE THREAD

**Issue by RenqiuguoLi** [fritzsedlazeck/Sniffles#469]
Hi team and really thankful for your development!

I am just confusing on how to view the tandem repeats from our resulting VCF files?
I fed with the .bed file provided by the Sniffles2 and my simple codes are downbelow:
```
sniffles --threads 10\
         --input /data/TGS/data/hg38_aln.sorted.bam\
         --vcf hg38.vcf\
         --tandem-repeats /data/GRCh38_sniffles_provided.trf.bed\
         --reference /hg38.p14.fa\
         --minsvlen 50\
         
``` 

Thanks

**Comment by fritzsedlazeck** [comment]
Dear @RenqiuguoLi 
just to avoid confusion: Sniffles is a SV caller and thus a bit different than a tandem repeat caller (e.g. TRGT).  The bed file is just to control merging of SV to be more aggressive in these regions. 

For visualization we are often using IGV or Samplot . 

For Tandem repeats it depends what technology you used: ONT (STRGLR) Pacbio (TRGT) are what I would recommend. 

Hope that helps. 
Fritz

**Comment by RenqiuguoLi** [comment]
@fritzsedlazeck 
Thank you so much for your quick response, I am gonna check it right now.

Li

**Comment by RenqiuguoLi** [comment]
@fritzsedlazeck  
Hi Fritz!
Thank you so much for your quick response.
I am currently performing the STR/VNTR calling from ONT reads.
Based on your knowledge, Do you have tools recommandations other than STRGLR for this?
I am really thankful appreciate for your advice and 
Thank you so much

ps: I am using STRGLR right now,

**Comment by fritzsedlazeck** [comment]
Hi @RenqiuguoLi 
We are also testing medaka for this. Seems to be better than strglr.. 
Good luck
Fritz

**Comment by rl4940** [comment]
@fritzsedlazeck  
Thank you for your generous answer and this question is also in my concern right now.
I am also doing STR/TR calling right now.
I traced back to where are those two bed files:
```
Source for human_hs37d5.trf.bed: https://github.com/PacificBiosciences/pbsv/tree/master/annotations
Source for human_GRCh38_no_alt_analysis_set.trf.bed: https://github.com/PacificBiosciences/pbsv/tree/master/annotations
```
I was wondering what is can I feed these two to Straglr & medaka for STR/TR calling?
Do these two bed files contain global genes? and are they accreditable
