### ISSUE TITLE
Which ngmlr paramters should be enabled to be compatible with sniffles?

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/Sniffles#47]
Hi Fritz,

For BWA it is obvious -x and -M but I am not 100% sure which parameters for ngmlr that I should enable to use for sniffles?

Best,
Mehmet

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
just take care about the -x to set it to the right technologies. 
Otherwise default parameter should do the job.
Cheers
Fritz

**Comment by MehmetGoktay** [comment]
Thank you very much fritz!
