### ISSUE TITLE
[Question] SNF compatibility across version 

### ISSUE THREAD

**Issue by tuannguyen8390** [fritzsedlazeck/Sniffles#470]
Hi @fritzsedlazeck,

Congrats on v2.3 release ! I put the question here as I'm wondering if can we use the new version for the older snf file (v.2.2 to be precise), we are gathering the files from people in the consortium and I believe all of the SNF will be generated with the lower version. 

Best,

Tuan

**Comment by hermannromanek** [comment]
Hi @tuannguyen8390,

Thank you. Yes, SNF format did not change, so all files generated with v2.2 will continue to work in v2.3.

Our tests also included files generated by v2.2, so if you do encounter any issues please report them.

Thanks,
Hermann

**Comment by tuannguyenpi** [comment]
many thanks, very good to know ! We will test this out & report back soon.
