### ISSUE TITLE
redundant translocation call

### ISSUE THREAD

**Issue by CVan19** [fritzsedlazeck/Sniffles#48]
Hi,
I have just run Snifflesv1.0.7 to call structural variants with pacbio data. However, when I checked my results, I found many translocation calls are redundant. For example , there are 8 records located on chromosome 9 that seems to represent the same variant.
```
9       110248031       28615   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23388487;ZMW=15;STD_quant_start=0.000000;STD_quant_stop=0.632456;Kurtosis_quant_start=6.944904;Kurtosis_quant_stop=-1.664143;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1203722464;STRANDS=--;RE=18        GT:DR:DV        ./.:.:18
9       110248031       28616   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23524163;ZMW=15;STD_quant_start=0.000000;STD_quant_stop=0.632456;Kurtosis_quant_start=1.716204;Kurtosis_quant_stop=-0.498174;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1203858140;STRANDS=-+;RE=18        GT:DR:DV        ./.:.:18
9       110249307       28617   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23388486;ZMW=28;STD_quant_start=0.000000;STD_quant_stop=0.516398;Kurtosis_quant_start=10.688393;Kurtosis_quant_stop=2.387808;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1203721187;STRANDS=--;RE=30        GT:DR:DV        ./.:.:30
9       110249307       28619   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23524163;ZMW=19;STD_quant_start=0.288675;STD_quant_stop=0.645497;Kurtosis_quant_start=1.002878;Kurtosis_quant_stop=2.246256;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1203856864;STRANDS=-+;RE=24 GT:DR:DV        ./.:.:24
9       110250549       28621   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23388492;ZMW=34;STD_quant_start=0.000000;STD_quant_stop=0.677003;Kurtosis_quant_start=-0.195078;Kurtosis_quant_stop=-1.416803;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1203719951;STRANDS=++;RE=48       GT:DR:DV        ./.:.:48
9       110250549       28622   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23524158;ZMW=30;STD_quant_start=0.000000;STD_quant_stop=0.000000;Kurtosis_quant_start=0.167256;Kurtosis_quant_stop=5.765222;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1203855617;STRANDS=+-;RE=38 GT:DR:DV        ./.:.:38
9       133681711       28629   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23632361;ZMW=40;STD_quant_start=0.935414;STD_quant_stop=0.500000;Kurtosis_quant_start=4.041601;Kurtosis_quant_stop=6.036755;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1180532658;STRANDS=-+;RE=49 GT:DR:DV        ./.:.:49
9       133681337       29767   N       <TRA>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=22;END=23632359;ZMW=37;STD_quant_start=0.759555;STD_quant_stop=0.960769;Kurtosis_quant_start=2.699066;Kurtosis_quant_stop=7.087048;SVTYPE=TRA;SUPTYPE=SR;SVLEN=1180533030;STRANDS=+-;RE=53 GT:DR:DV        ./.:.:53

```
According to other research, there are only one reciprocal translocation between chromosome 9 and 22, so I wonder why this happened, and what I can do to get a better result.

**Comment by fritzsedlazeck** [comment]
Hi there can be several reasons:

1. The regions of  22: 23388487-23524163 and 9: 110248031-110249307 are somehow swapped in your sample. So it could be e.g. some transposon that is jumping or other reasons. It is hard to say without additional information.

2. An artifact from the mapping, but you have multiple reads supporting it. IF you use --genotype you will also get an allele frequency estimate, which might help you to filter these calls out.

3. Are these regions highly repetitive? If so are these multiple calls collapsable. You can use the -d parameter and set it to e.g. 2000 . Then these events should get merged. Note the default is 1kbp and you can see that they are only 1.3kb apart.

Let me know if that helps.
Fritz

**Comment by CVan19** [comment]
Thanks for your reply. I will try to set -d 2000 soon.But I still have some questions. 
First , how to genotype haploid sample?  
Second, are all TRA variants called by Sniffles reciprocal translocation?

**Comment by fritzsedlazeck** [comment]
Hi,
genotype haploid samples: I frankly dont know. You must adopt the parameters for the thresholding:
> 
```

--min_het_af <float>
     Threshold on allele frequency (0-1). Default=0.0

   --min_homo_af <float>
     Threshold on allele frequency (0-1). Default=0.0


```

About the TRA: no. What we are calling are the breakpoints independently if the region is swapped or the chr arms are. 

cheers
Fritz

**Comment by fritzsedlazeck** [comment]
You could also try to filter the calls when you run Sniffles with e.g.: -f 0.8

This is setting the allele frequency threshold for the SV calling and will repot only SVs that are supported by 80% or more reads in that region.

**Comment by CVan19** [comment]
Which one of them I should choose in order to genotype, --min_het_af or --min_homo_af ? And should I try different value for this parameter to get a better result?

**Comment by fritzsedlazeck** [comment]
These two parameter will only influence the estimation of het or homozygous event. I think -f 0.8 might be better for your purpose. Or maybe 0.7 if you want to be more variable on the allele frequency.
Cheers
Fritz

**Comment by CVan19** [comment]
Thanks, I will try that!

**Comment by CVan19** [comment]
Following your advice, I used the commands below to call sv:
```
sniffles -m ngmlr_sort.bam -d 2000 --genotype -f 0.8 -t 30 -v raw_sv.vcf
```
I found thar some variants have genotype while others don't . What does this mean?
```
1       724785  0       N       <DUP>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=1;END=224202072;ZMW=20;STD_quant_start=56.803981;STD_quant_stop=71.403512;Kurtosis_quant_start=1.256655;Kurtosis_quan
t_stop=-0.676883;SVTYPE=DUP;SUPTYPE=SR;SVLEN=223477287;STRANDS=-+;RE=27
1       755668  1       N       <DUP>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=1;END=755923;ZMW=9;STD_quant_start=109.999545;STD_quant_stop=107.596468;Kurtosis_quant_start=-0.006099;Kurtosis_quant
_stop=-0.134801;SVTYPE=DUP;SUPTYPE=SR;SVLEN=255;STRANDS=-+;RE=10
1       756265  2       N       <INS>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=1;END=756267;ZMW=28;STD_quant_start=4.596194;STD_quant_stop=12.693502;Kurtosis_quant_start=-0.266108;Kurtosis_quant_s
top=6.404143;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=249;STRANDS=+-;RE=32;AF=0.914286        GT:DR:DV        1/1:3:32
1       757831  3       N       <DEL>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=1;END=757864;ZMW=27;STD_quant_start=7.586995;STD_quant_stop=7.348469;Kurtosis_quant_start=-1.699772;Kurtosis_quant_stop
=-1.688150;SVTYPE=DEL;SUPTYPE=AL;SVLEN=33;STRANDS=+-;RE=33;AF=0.825 GT:DR:DV        1/1:7:33
1       774848  4       N       <DEL>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=1;END=774889;ZMW=36;STD_quant_start=7.367496;STD_quant_stop=7.326664;Kurtosis_quant_start=1.502740;Kurtosis_quant_stop=
1.546023;SVTYPE=DEL;SUPTYPE=AL;SVLEN=41;STRANDS=+-;RE=50

```

**Comment by fritzsedlazeck** [comment]
Hi,
I am still traveling, the only thing I can imagine is that the non genotyped calls are these that have a lower frequency. 

Sorry for that. I will look into that as soon as possible.
Cheers
Fritz

**Comment by CVan19** [comment]
Hi,fritz
Sorry to bother you at Christmas. I have confirmed that non genotyped calls are those variants that have a lower frequency and I have removed them manually. 
Now I have a new question. 
```
16	29238670	19009	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=16;END=88226804;ZMW=10;STD_quant_start=357.824817;STD_quant_stop=380.373895;Kurtosis_quant_start=1.393989;Kurtosis_quant_stop=1.550278;SVTYPE=DUP;SUPTYPE=SR;SVLEN=58988134;STRANDS=-+;RE=11;AF=0.916667	GT:DR:DV	1/1:1:11
3	60001	24690	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=3;END=75279194;ZMW=7;STD_quant_start=233.696812;STD_quant_stop=127.458228;Kurtosis_quant_start=6.999231;Kurtosis_quant_stop=6.994215;SVTYPE=DUP;SUPTYPE=SR;SVLEN=75219193;STRANDS=-+;RE=10;AF=1	GT:DR:DV	1/1:0:10
```
You can see that the length of these two DUP is 60Mb and 75Mb. Considering  the average length of my Pacbio reads is 10kb, it is impossible for them to span so long duplication variants. So can I treat these two DUP as false positive calls?

**Comment by fritzsedlazeck** [comment]
No the point is that for events that are longer then the read length you cannot span the entire Svs.
However, due to the relative positioning of the split reads it is clear that it just can be a tandem duplication. 

This means that if a read is e.g. mapped on + strand and its first part is after its second half and both have the same orientation it forms a tandem duplication signal. This means that likely the read branches over the connection of the two copies that are representing the duplicated region.

Let me know if you need further explanation.
Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
I have just uploaded a fix for the filtering based on AF (-f parameter). Please clone the code and give it a try.
Thanks for reporting this.
Merry Xmas!
Fritz
