### ISSUE TITLE
The index file is older than the data file: alignment.sorted.bam.bai

### ISSUE THREAD

**Issue by rl4940** [fritzsedlazeck/Sniffles#482]
Hi Team:
I got this error message which is kinda weird to me to be understood:
I crop a portion of the log:
``
2024-05-18 08:35:25,380 [INFO] Finished chrUn_KI270442v1-chrUn_KI270589v1:TRA/BND.
2024-05-18 08:35:25,380 [INFO] Finished chrUn_KI270442v1-chrUn_KI270590v1:TRA/BND.
2024-05-18 08:35:25,380 [INFO] Finished chrUn_KI270442v1-chrUn_KI270756v1:TRA/BND.
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.csi
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.csi
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.csi
```
You see, there are threads running fine, in the mean time, some threads says this error...
And I changed to .bam.bai instead, but I got the same message:
```
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
Running Sniffles2, build 2.2
  Run Mode: call_sample
  Start on: 2024/05/22 10:38:16
  Working dir: /data/renqgli/project/TGS/pipeline/test_hg002_giab_hg19
  Used command: /data/renqgli/miniconda3/bin/sniffles --threads 10 --input alignment.sorted.bam --vcf sniffles2_hg19_hg002.vcf --sample-id hg002 --reference /data/renqgli/project/refseq/hs37d5.fa --minsvlen 50
==============================
Opening for reading: alignment.sorted.bam
Opening for reading: /data/renqgli/project/refseq/hs37d5.fa
Opening for writing: sniffles2_hg19_hg002.vcf (single-sample, sorted)
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] [W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] 
[W::hts_idx_load3] [W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.baiThe index file is older than the data file: alignment.sorted.bam.bai[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai

The index file is older than the data file: alignment.sorted.bam.bai

[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data 2024-05-22 10:39:16,934 [INFO   ]  Processed read 240000
2024-05-22 10:41:08,464 [INFO   ]  Processed read 250000
2024-05-22 10:42:59,035 [INFO   ]  Processed read 260000
data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
```
Btw, my .bam.bai generated code is downblow (I am writing a pipeline):
```
# >>> Part I intiates: requirments: minimap2, samtools, fastq files, reference genome <<<
fastqgz_all=''
for fn in *.fastq.gz; do
    fastqgz_all=${fn}' '${fastqgz_all};
done
fastqgz_all="${fastqgz_all%" "}"  # Trim trailing space at the end of string
echo "#######-- pipeline start --#######"
minimap2 -ax map-ont --secondary=no --MD -t 18 $ref $fastqgz_all\
|samtools sort -O BAM --write-index -o alignment.sorted.bam##idx##alignment.sorted.bam.bai -
echo "#######-- Calculate End Time:date +%Y/%m/%d--%H:%M --#######"
# >>> Part I ends: output: alignment.sorted.bam <<<
```

Thank you for your help

**Comment by rl4940** [comment]
Godly such a messy layout. sorry, I will reformat, really apologize for that:
Here is the .bam.bai
```
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
Running Sniffles2, build 2.2
  Run Mode: call_sample
  Start on: 2024/05/22 10:38:16
  Working dir: /data/renqgli/project/TGS/pipeline/test_hg002_giab_hg19
  Used command: /data/renqgli/miniconda3/bin/sniffles --threads 10 --input alignment.sorted.bam --vcf sniffles2_hg19_hg002.vcf --sample-id hg002 --reference /data/renqgli/project/refseq/hs37d5.fa --minsvlen 50
==============================
Opening for reading: alignment.sorted.bam
Opening for reading: /data/renqgli/project/refseq/hs37d5.fa
Opening for writing: sniffles2_hg19_hg002.vcf (single-sample, sorted)
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] [W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] 
[W::hts_idx_load3] [W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.baiThe index file is older than the data file: alignment.sorted.bam.bai[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai

The index file is older than the data file: alignment.sorted.bam.bai

[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
```
Here is the code of minimap2:
```
fastqgz_all=''
for fn in *.fastq.gz; do
    fastqgz_all=${fn}' '${fastqgz_all};
done
fastqgz_all="${fastqgz_all%" "}"  # Trim trailing space at the end of string
echo "#######-- pipeline start --#######"
minimap2 -ax map-ont --secondary=no --MD -t 18 $ref $fastqgz_all\
|samtools sort -O BAM --write-index -o alignment.sorted.bam##idx##alignment.sorted.bam.bai -
echo "#######-- Calculate End Time:date +%Y/%m/%d--%H:%M --#######"
```

**Comment by lfpaulin** [comment]
Hi Li,

The message you see is a warning, not an error. This happens when as it is stated the index is older than the alignment. The warning is given because it may be that the alignment was modified after indexing. It also happens when you download files from the internet and the index finishes first.
I will close the issue as this is part of HTSLib

**Comment by rl4940** [comment]
@lfpaulin  Hi Paulin:
Thank you for your help!
Yes it's a warning, I am sure the index is not outdated, but still, there is no output generated from sniffles2...
How should I deal with this?

Thanks
Li

**Comment by lfpaulin** [comment]
Hi Li can you please upload the full output log from Sniffles, if possible attached to the message

Best
Luis
