### ISSUE TITLE
[Report] Significant inflation of INS when joint calling with Sniffles 2.3.3

### ISSUE THREAD

**Issue by tuannguyen8390** [fritzsedlazeck/Sniffles#483]
Hi Sniffles dev team,

First of all, this is a report, rather than a bug issue :) 

Extremely exciting to test out v.2.3.3 👍 . We did a test run recently on bovine, 277+ individuals & data from both HIFI & ONT. When observing the results, we saw a significant inflation of INS compare to DEL (nearly 3x). Well, this seems ... unordinary.

![image](https://github.com/fritzsedlazeck/Sniffles/assets/47171822/915af9f4-8e4f-4a1c-a42d-b1622b835dab)

By the way, this was not recorded with previous version (2.2) - with same set of individuals
![image](https://github.com/fritzsedlazeck/Sniffles/assets/47171822/5f71f669-c1a2-496f-8cf9-06d38b701fed)

We did a bit of investigation. Below is the STDEV_POS & STDEV_LEN between the 2 classes, we found that for some reason, INS were not merged properly => more INS. 
![image](https://github.com/fritzsedlazeck/Sniffles/assets/47171822/cd025820-e7ee-4216-b956-0e796b95b526)

We then revise the changelog and found `--combine_pctseq` as a new add on feature that suppose to separate more variants. Indeed 
a test was run with that = 0. Things were back to normal - still a bit different between v2.2 & v.2.3.3 tho

![image](https://github.com/fritzsedlazeck/Sniffles/assets/47171822/83fd45dc-b9f6-4f59-b0ae-fb09f2101152)
![image](https://github.com/fritzsedlazeck/Sniffles/assets/47171822/a2b34a2b-06c8-483b-8329-f0f0fef9159a)

We are unsure if this is a bovine specific problem (as we have multiple breeds in the cohort). We also tried to split the data into HIFI vs ONT and this inflation seems happen with `--combine_pctseq = 0.7` too. Unfortunately, with bovine we also don't have a GIAB truth set to test yet, so we cannot conclude how many of the inflated INS are real.  But I think it's worth noticing that `--combine_pctseq` seems to need more user attention, perhaps especially with non-human samples.

Many thanks for the release again, for the record v.2.3.3 shifting one known bovine SV to the correct location & size 💯 

Best,

Tuan

**Comment by fritzsedlazeck** [comment]
Hey @tuannguyen8390 
thanks for reporting this back . 

So in the v2.3 we introduced sequence comparison for insertions in order to not over merge them. As you might know we also published Truvari (https://pubmed.ncbi.nlm.nih.gov/36575487/  ) which discusses over merging of SV. So to overcome this we  now treat insertions differently to better distinguish if the sequences are not similar enough. I think right now we do 75% identity thresholds besides the usual length and breakpoint agreement. 
@lfpaulin or @hermannromanek can jump in if I say something stupid :) . 

Thanks for running these tests. We will carefully read your summary. 
Cheers
Fritz

**Comment by tuannguyen8390** [comment]
Thanks Fritz,

We are looking at the coding and we agree that similarity threshold is indeed valuable to distinguish INS. My personal thought is that with large scale population study (multiple platform, non-uniform coverage, N50, QC...), there are multiple factors at play. In our context, we will have out-species as well, which might be interesting to look at tinkering with this flag. More SVs have further impact downstream (phasing/imputation), hence we really want to keep the number relatively realistically. 

We will testing a bit with the params to hit a balance sweet spot, more on that later. 

Best,

Tuan

**Comment by fritzsedlazeck** [comment]
Thanks @tuannguyen8390 .

**Comment by tuannguyen8390** [comment]
Hi @bbimber, with bovine we don't have a clear conclusion for bovine, that's why I call it a report at the beginning :). We don't have GIAB data yet, so we only can rely on Mendelian inconsistencies ratio in trios. Please see the panel below.

Y-axis is Mendelian incon,
X-axis is the tested pct - for our case we test 0, 0.2 & 0.7 pct. 

![image](https://github.com/user-attachments/assets/b7b47953-fbe7-4340-b935-45463789f063)

The first 2 trios are ONT, but the 3rd one is PB Hifi. For our case increase pct doesn't seem to increase accuracy in genotyping - which is a bit sad. So at the moment we decide to cut it to 0 to maintain consistency with our previous run (v2.2 doesn't have this option).

I believe you have Hifi data, so the reads itself would be quite accurate. Therefore, I think it is of interest to include some certain degree alignment merging and try to bench that with GIAB data.

**Comment by hermannromanek** [comment]
Hi,

Right now the parameter --combine-pctseq is the threshold for the alignment edit distance determining whether two SVs should be considered the same event and be merged or not, i.e.:

If we have two 200 BP Insertion SVs at the same location, given the default of 0.7 means the sequences of those two variants may differ by up two 60 bases to still be considered the same SV to be merged and reported as one variant.

Deletions are not affected by this parameter since there is no sequence.

Hope that makes sense?

Hermann

**Comment by bbimber** [comment]
@hermannromanek, yes, it does make sense why enforcing some kind of sequence-identity based threshold for collapsing INS would result in a higher number of distinct INS being called. 

I understand the docs then combining insertions isnt actually limited to identical start/stop (as has been implied by some posts). Doesnt "--combine-match" allow some leeway in terms of the actual start/stop positions, and therefore mean not-quite-identical insertions can be collapsed too (irrespective of BP identity)?

**Comment by hermannromanek** [comment]
I just saw I somehow typed an answer but apparently didn't send it:

Yes, "same location" actually means roughly the same location. There is some leeway on this, controlled by --combine-match and --combine-match-max, dependent on both position and length, so yes.

The order is actually the other way round, so alignments (if enabled) are one more step after combine-match determines two SVs should be merged, and only if the alignment distance is above the given threshold we merge.

**Comment by bbimber** [comment]
yes, that makes sense. In case anyone is interested, here are the differences in our 59 PacBio samples, with our without --combine-pctseq=0. As you can see, there is a considerable increase in short insertions in particular, which makes sense based on what the sequence-based merging does:

![image](https://github.com/user-attachments/assets/65565801-9e1b-47ec-9e41-4520ad759306)

**Comment by tuannguyen8390** [comment]
Yeah I think it's nearly the same results as my previous runs. It's up to you then to choose if you want to enable the setting, modify it a bit or not running it at all 🔢
