### ISSUE TITLE
vcf results are different between one-step direct calling and snf-vcf calling

### ISSUE THREAD

**Issue by lg10is1** [fritzsedlazeck/Sniffles#485]
Hi,
Thanks for your development of sniffles. It is a helpful tools for SV calling. 
I am using 
"sniffles --input 1.align.bam  --reference $REF_FASTA --threads 16 --vcf 1.sniffles_2.3-onestep.vcf"
"sniffles --input 1.align.bam --reference $REF_FASTA --threads 16 --snf 1_2.3.snf
sniffles --input 1_2.3.snf --reference $REF_FASTA --threads 16 --vcf 1.sniffles_2.3-2step.vcf"
to call SV in my sample. However, I found the results between 1.sniffles_2.3-onestep.vcf and 1.sniffles_2.3-2step.vcf are different.
Could you tell me which one is correct?
Thank you again.
Yang

**Comment by lfpaulin** [comment]
Dear Yang
You can run the following command to produce the VCF and SNF at the same time in a single run
```
sniffles --input sample1.bam --vcf sample1.vcf.gz --snf samples.snf --reference genome.fasta
```
Also, the SNF files are expected to be used for merging/population calling, it is not expected to be used for single sample calling so we have not tested it.

Luis
