### ISSUE TITLE
tandem repeat annotation for another human genome resource

### ISSUE THREAD

**Issue by ilivyatan** [fritzsedlazeck/Sniffles#489]
HI,
Are any of the current tandem repeat lists compatible with this genome version?

GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna?

If not, is it possible to add a tandem repeat annotation for this version of human genome?

The link for download:
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz

Thanks

**Comment by fritzsedlazeck** [comment]
Dear @ilivyatan 
you dont need tandem repeats for Sniffles to run. We are not maintainig a new list for this genome build specifically. Maybe did you try to reach out to UCSC or whoever put this together?
Thanks
Fritz
