### ISSUE TITLE
Does Sniffles need cs tag

### ISSUE THREAD

**Issue by hui-liu** [fritzsedlazeck/Sniffles#494]
I used minimap2 to align my ONT reads and ran Sniffles2 to call SVs. The reference genome is large and needs a "--split-prefix" when mapping, but this parameter doesn't work with --cs or --MD. I found Sniffles2 doesn't need the MD tag. Does it need a cs tag?

**Comment by fritzsedlazeck** [comment]
It should be fine. Keep us posted as this seems to be a case that we didn't test before.
Thanks 
Fritz
