### ISSUE TITLE
Accessing dev releases/OSX Parallelism bug

### ISSUE THREAD

**Issue by ryan-moreno** [fritzsedlazeck/Sniffles#507]
Is there a way to access the current version of the package rather than the one distributed by PyPI? I am running into an issue on OSX, which I see was fixed [here](https://github.com/fritzsedlazeck/Sniffles/blob/a4af9926a4ec8278d28ea6d9382b15908ed51488/src/sniffles/sniffles#L74) July 19th, but the most recent release was July 8th. How can I access a version with the fix?

**Comment by wdecoster** [comment]
Would cloning the repository, and installing with pip from the clone work for you?
For that, you need to be in the directory containing the setup.py file and run `pip install .`
