### ISSUE TITLE
vcf file columns

### ISSUE THREAD

**Issue by webbchen** [fritzsedlazeck/Sniffles#52]
Dear Fritz

When  I try to upload the vcf file into IGV I'm getting an error complaining about missing columns. In the example below the 3rd line is missing the GT:DR:DV field and the field behind that. I'm not too worried about these fields missing but having a couple of tab-separated dots in the lines before the line break where these fields would be would make IGV's problem go away, I reckon.

`ENA|CM001196|CM001196.1	83605	0	N	<DUP>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=ENA|CM001196|CM001196.1;END=4960077;STD_quant_start=7.925792;STD_quant_stop=0.797724;Kurtosis_quant_start=-1.159180;Kurtosis_quant_stop=-1.284778;SVTYPE=DUP;SUPTYPE=SR;SVLEN=4876472;STRANDS=-+;RE=22;AF=0.956522	GT:DR:DV	1/1:1:22
ENA|CM001196|CM001196.1	85847	1	N	<DEL>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=ENA|CM001196|CM001196.1;END=4960071;STD_quant_start=2.102630;STD_quant_stop=1.076055;Kurtosis_quant_start=5.490807;Kurtosis_quant_stop=-1.172381;SVTYPE=DEL;SUPTYPE=SR;SVLEN=4874224;STRANDS=+-;RE=39;AF=0.975	GT:DR:DV	1/1:1:39
ENA|CM001196|CM001196.1	116744	2	N	<INS>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=ENA|CM001196|CM001196.1;END=116744;STD_quant_start=5.024938;STD_quant_stop=14.515509;Kurtosis_quant_start=-1.800901;Kurtosis_quant_stop=-1.888449;SVTYPE=INS;SUPTYPE=AL;SVLEN=71;STRANDS=+-;RE=40
ENA|CM001196|CM001196.1	117804	3	N	<INS>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=ENA|CM001196|CM001196.1;END=117804;STD_quant_start=4.156655;STD_quant_stop=12.062338;Kurtosis_quant_start=-1.102856;Kurtosis_quant_stop=-1.052519;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=610;STRANDS=+-;RE=37;AF=0.902439	GT:DR:DV	1/1:4:37
ENA|CM001196|CM001196.1	146939	4	N	<DEL>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=ENA|CM001196|CM001196.1;END=150338;STD_quant_stop=-1.052519;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=610;STRANDS=+-;RE=37;AF=0.902439	GT:DR:DV	1/1:4:37
`
Regards,

A. Webb

**Comment by fritzsedlazeck** [comment]
Hi,
thanks for pointing this out. Did you use the -f parameter to set a minimum allele frequency.
That is/was a previous reported problem. 
In any case, I will take a look at this beginning of January as I am currently traveling and then probably being off for a week. 

Cheers
Fritz

**Comment by webbchen** [comment]
Hello,

Yes, I did. I ran it with -f 0.8. 
Thanks for the quick reply!

Regards,
A.Webb

**Comment by fritzsedlazeck** [comment]
Yeah sorry for that.
I will try to fix it soon.
Cheers
Fritz

**Comment by webbchen** [comment]
That's alright!
Merry Christmas!

**Comment by fritzsedlazeck** [comment]
I just pushed a correction for that behavior to the code. Please clone the code and try it out.
Thanks for reporting it. 
Cheers
Fritz
