### ISSUE TITLE
masked regions

### ISSUE THREAD

**Issue by askleppe** [fritzsedlazeck/Sniffles#525]
Hi,

We have regions in the reference fasta that are masked and that we ideally would like for sniffles to ignore when scanning for SVs. I could not find anything regarding what Sniffles does or how it handles masked regions. If we want it to be ignored, how do we do go about that? Currently we get SVs that have masked regions, eg N in reference show up with an insertion. The regions are not many but they're there and they seem to dominate the SV findings at this stage. It seems a bit dubious.

Does sniffles distinguish between soft masked and hard masked regions, or is there a setting we may apply to avoid masked regions?

Thank you for your input.

Best wishes,
April

**Comment by fritzsedlazeck** [comment]
Dear April, 
correct this case is currently not directly supported. What I would suggest is to call with sniffles and then use e.g. bedtools to disregard the SV entries in the regions you want to ignore. 

Are you aligning two genomes?  The N in the insertion might be the reference allele. you need to specify the reference sequence to avoid the N (as the reference position). If there are literally N in the inserted sequence (so the ALT column ) that would mean that these are also in your reads. 

Hope that helps
Fritz
