### ISSUE TITLE
Do you really need to limit to python 3.10?

### ISSUE THREAD

**Issue by bbimber** [fritzsedlazeck/Sniffles#528]
Hello,

As part of your 2.5 release, @lfpaulin posted a few iterations that ended with "Sniffles requires python to be==3.10.15 given a constrain of edlib (py)". Are you sure about this? I just installed edlib through pip on python 3.11 without problems. In our case, our cluster environment makes python 3.11 easier to use (though in theory we can use alternate solutions). Prior to your formal release, we were using the development branch installed onto python 3.11 just fine. Just curious what is driving this restriction, since it is somewhat limiting on using sniffles.

**Comment by lfpaulin** [comment]
The restriction was due to conda not compiling with python >=3.10,<3.11
I think the issue was with the library now being calles python-edlib
We are looking for a solution and we will update the version with other bug fixes soon, 
hopefully not requiring python to be only 3.10.x

**Comment by bbimber** [comment]
OK, that would be appreciated, thank you.
