### ISSUE TITLE
Breakpoints of SVs

### ISSUE THREAD

**Issue by reshu23** [fritzsedlazeck/Sniffles#532]
Dear Team,
I have question related to reported break points of SVs by Sniffles. Are breakpoints detected at single nucleotide resolution(exact breakpoints)?
Thank you.

**Comment by tuannguyen8390** [comment]
Yes, you can look at the flag STDEV_POS
##FILTER=<ID=STDEV_POS,Description="SV Breakpoint standard deviation filter">

Variant with STDEV_POS=0 variant would have "perfect" breakpoint. But some variability perhaps might be expected depending on sequencing technology.

**Comment by reshu23** [comment]
Thank you. I will check it.
