### ISSUE TITLE
change 'Number=.' to 'Number=A' or 'Number=R'  in VCF

### ISSUE THREAD

**Issue by wangyugui** [fritzsedlazeck/Sniffles#54]
Hi.

please change 'Number=.' to 'Number=A' or 'Number=R'  in VCF for more strict VCF.

then 'bcftools norm --multiallelics' can be used to split/merge VCF record.

This will be  a minor enhancement.

Best Regards

**Comment by fritzsedlazeck** [comment]
I changed it to Number=R . Let me know if that works. 
thanks
Fritz

**Comment by wangyugui** [comment]
'AF' should be 'Number=A'.  'Number=A' is diff from 'Number=R'.

I'm sorry that I have checked AF only.

**Comment by fritzsedlazeck** [comment]
Sorry I just read the specs again. Every value should be actually an A. 
 I just pushed the code. Please give it a try.
Thanks
Fritz
