### ISSUE TITLE
DUP in Sniffles?

### ISSUE THREAD

**Issue by woodoo46** [fritzsedlazeck/Sniffles#55]
Hi Sniffles developers,

What does the DUPcalls in Sniffles result file refer to, interspersed duplication or tandem duplication?

Thanks.

George

**Comment by fritzsedlazeck** [comment]
Hi George,
tandem duplications. Almost all SV caller are only calling tandem duplications.

Interspersed duplications are often flanked by other types. Eg. TRA for cancer genomes.
Cheers
Fritz

**Comment by hd00ljy** [comment]
Hello!

I also have a question regarding the interspersed duplications.

How are the **intra**-chromosomal interspersed duplications reported?

Will the direct and inverted ones be reported as SV types different from each other?



For **inter**-chromosomal ones, it seems to be clear that it would be reported as TRA. ( 2 phased TRA for short ones)

But I could not come up with how the **intra**-chromosomal ones would be reported.


Best,

Jinyoung

**Comment by fritzsedlazeck** [comment]
Dispersed duplications are tricky. Typically they are not reported as DUP but you can see the connections likely as INV or DEL. typically as long events as the element is likely to be reinserted quite some distance away.

DUP are for Sniffles really only tandem duplication or higher amplification, but tandem! 
Does that explain it better?
Thanks
Fritz

**Comment by woodoo46** [comment]
Or maybe even reported as inter-chromosome calls?

**Comment by fritzsedlazeck** [comment]
The problem is that the signal for large e.g. deletions and interchromosomal events are identical. The only differentiation is often the SV length. However, I didnt want to make an arbitrary cutoff back then.. 
Thx
Fritz

**Comment by hd00ljy** [comment]
Thank you for your detailed reply!
Then I think I will have to be careful with very large DELs and INVs.

Best,
Jinyoung

**Comment by fritzsedlazeck** [comment]
Yes like mb large events. We are working on improving this but for now it's like that.
Thanks
Fritz
