### ISSUE TITLE
Run the same data twice?

### ISSUE THREAD

**Issue by woodoo46** [fritzsedlazeck/Sniffles#56]
I am just wondering if I run Sniffles twice with exactly the same data and settings, such as

${SNIFFLES} -m ${inputfile} -v ${outputfile} -t 20 --report_BND --genotype -s 5

Should the results be exactly the same?

Thanks.

**Comment by fritzsedlazeck** [comment]
There can be some variation due to the automated parameter estimation plus the breakpoint coordinates that are reported. I would not expect something major.
Why?
Cheers
Fritz

**Comment by woodoo46** [comment]
I just want to confirm what I have seen. Yes, nothing major different.
1) I did see coordinates are off by 1 bp, for some calls, therefore breakpoints are slightly different
2) sometimes, the number of supporting reads are different too?

**Comment by fritzsedlazeck** [comment]
Yes that can happen. I still will check everything again next week to make sure that the recent updates did not include a bug.

Thanks for reaching out!
Cheers
Fritz
