### ISSUE TITLE
Trouble to understand some coordinates

### ISSUE THREAD

**Issue by ebioman** [fritzsedlazeck/Sniffles#6]
Hello
I am curious regarding the way the results are represented.
I have for example a position which was confirmed through another independent analysis:

    000000F 11430646        11430740        000000F 11580771        11580779        8       -1      +       -       DEL     15      000000F 11430739        000000F 11580772        150033

So I understand the format of the *.bede file here the following way:
At position 11430646 there is a potential deletion on one of the alleles which ranges till 11580772.
This is similarly as well graphically represented in the VCF file in IGV.

Now I have another candidate:

     006538F 3752    3780    006956F 783     1387    7718    -1      +       +       TRA     16      006538F 3779    006956F 1222    1406222

This is now a translocation which supposedly starts at 3752 on 006538F. But where does it no stop ?
I guess if I understood correctly is stops on 006956F @ 1222 ?

These are not visualized in the VCF if visualized by IGV .

**Comment by fritzsedlazeck** [comment]
Hi,
yes the visualization of translocation is tricky. So the bedpe file gives you ranges where the breakpoints of the SV occur. As you said it starts at 006538F @3752  and goes to 006956F @1387 (not sure why 1222). 

I am not sure I get your question or concern about your last sentence. Is that entry not included in the VCF file or is it not visualized in IGV?

**Comment by ebioman** [comment]
Hi 
Thanks for the swift answer and clarifying the proper position for the second contig (1387 instead of 1222). I got confused with the positions

    Chrom	start	stop	chrom2	start2	stop2	variant_name/ID	score (smaller is better)	strand1	strand2	type	number_of_split_reads	best_chrom	best_pos	best_chrom2	best_pos2	predicted_length

What are then the "best" labelled chromosomes and positions actually ?

>I am not sure I get your question or concern about your last sentence. Is that entry not included in the VCF file or is it not visualized in IGV?

These entries are not visualized in IGV if I use the corresponding vcf file and I was wondering whether this is a known issue or a bug.
Cheers

**Comment by fritzsedlazeck** [comment]
Oh I see. Sorry I did not scroll over. So the best coordinates are these that are supported by the most reads. So start(2) stop(2) gives you the ranges in which reads are supporting the same variant. You were right with the 1222 !

I just looked at some translocations myself using the vcf files produced and I see what you are saying. It is simply not displayed. I found a solution and will upload a newer version today. 
The main issue is that I report the CHR2 and END in the info field in the vcf format.

Thanks for pointing it out! Let me know if something else comes up. I leave the issue open until you confirm that it looks fine now.

**Comment by fritzsedlazeck** [comment]
Hi,
I just uploaded the new version. Please check it out. 
thanks
Fritz

**Comment by ebioman** [comment]
Hi
I am not sure what is happening here. I switched to your newer version and the results changed compared to the last one, so the previous coordinate does not exist anymore (same options, just different Sniffles version ). 
Then (see other ticket) I executed twice once with BEDE output once with VCF, and the results are not similar:

<pre><code>
006538F 1493    7645    N       <INS>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.1;CHR2=006538F;END=1769;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=168;STRANDS=+-;RE=25     GT:DR:DV        ./.:.:25
006538F 2194    7646    N       <INS>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.1;CHR2=006538F;END=2332;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=51;STRANDS=+-;RE=14      GT:DR:DV        ./.:.:14
006538F 3779    9924    N       N[006956F:1161[ .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.1;SVTYPE=BND;SUPTYPE=SR;SVLEN=1228661;STRANDS=++;RE=46  GT:DR:DV        ./.:.:46
006538F 3779    9925    N       N[007112F:1325[ .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.1;SVTYPE=BND;SUPTYPE=SR;SVLEN=1350362;STRANDS=++;RE=34  GT:DR:DV        ./.:.:34
</code></pre>

<pre><code>
006538F 1210    1781    006538F 1781    1781    7645    -1      +       -       INS     25      006538F 1493    006538F 1601    168     25
006538F 2047    2621    006538F 2621    2621    7646    -1      +       -       INS     14      006538F 2194    006538F 2281    51      14
006538F 3609    3780    006956F 783     1387    9924    -1      +       +       BND     46      006538F 3779    006956F 1161    1228661 46
006538F 3602    3780    007112F 891     1559    9925    -1      +       +       BND     34      006538F 3779    007112F 1325    1350362 34
</code></pre>

Any advice or suspicion what might be going on?

**Comment by fritzsedlazeck** [comment]
Hi,
yes I am trying to improve Sniffles. The previous verion 1.0.0 had high sensitivity but I also observed higher FDR in some real PacBio data and Nanopore data. I am trying to get this fixed. The version 1.0.1 has now the correction for the vcf output and should be more robust when it comes to alignment mistakes. 

Overall, please keep in mind that it is still under development and I am trying to improve it constantly. Sorry for the confusion.

**Comment by ebioman** [comment]
Hi
No problem, just trying to report and funky stuff.
Cheers
