### ISSUE TITLE
Subreads

### ISSUE THREAD

**Issue by woodoo46** [fritzsedlazeck/Sniffles#60]
Hi there,

I have a question about subreads. How does the program handle subreads from the same well, when the program requires 10 supporting reads, does the program count the subreads from the same well individually? For example, if there are 5 subreads from the same well, does the program count five supporting reads?

Thanks.

George

**Comment by fritzsedlazeck** [comment]
Hi George,
yes it would count 5 subreads from the same ZMW. However, you get an extra flag for the # of ZMW supporting the event. 

Let me know if you have further questions. 
Cheers
Fritz

**Comment by woodoo46** [comment]
OK. Thanks. For Sniffles to work properly, how should I run ngmlr?  Currently, we are running as this

${NGMLR} -t ${ncores} -r ${genome} -q ${inputfile} -o ${work_file} --bam-fix

Will this be good? This is irrelevant to the original question, sorry.

**Comment by woodoo46** [comment]
Another question related to the subreads, for the subreads from the same well, is the coverage calculated multiple times? For example,  a reference base is covered by 5 subreads from the same well, does the coverage is calculated as 5? Thanks!

**Comment by fritzsedlazeck** [comment]
ad mapping:
--bam-fix is probably not necasary as it is for really long reads ONT sequencing. Apart from that it looks good. 

ad coverage:
yes every read is counted. If they are from the same well the ZMW number is indicating that.
