### ISSUE TITLE
Find shared structural variants

### ISSUE THREAD

**Issue by wdecoster** [fritzsedlazeck/Sniffles#61]
Hi,

I'm looking for a convenient method to find shared structural variants between datasets, and wonder if you have any suggestions. I'm working on PromethION genome sequencing of human genomes. Given that breakpoints are not always exact I should need a bit of padding around positions to identify overlaps. I'd expect that tools like this already exist and as such I could avoid spending time rolling my own solution.

I've tried `bedtools intersect`, but that throws an error which according to a quick google search could be the consequence of "stop == start" in the bedpe files, which is for sure the case for deletions of sniffles. Which I assume makes sense, since a breakpoint is between nucleotides, in 0-based coordinates, this would be stop==start I guess.

I have had a look at your SURVIVOR tool, but the wiki/documentation appears out of sync with the software itself. It looks like I could use SURVIVOR merge.
_"Compare or merge VCF files to generate a consensus or multi sample vcf files."_

The command line help shows me the following items, which I assume are required arguments:

```
Tab file with names
max distance between breakpoints 
Minimum number of supporting caller
Take the type into account (1==yes, else no)
Take the strands of SVs into account (1==yes, else no)
Estimate distance based on the size of SV (1==yes, else no).
Minimum size of SVs to be taken into account.
Output prefix
```

It's not obvious to me how to best approach this.

Thanks in advance,
Wouter

**Comment by fritzsedlazeck** [comment]
Hi,
yes the SURVIVOR interface changed like a month ago and I havent updated the documentation yet. 

What you want to do is to 
1. call SVs using e.g. Sniffles , but with the vcf output
2. take all the files you want to compare:  ls *vcf > files
3. Run SURVIVOR merge files 1000 1 1 0 0 0 output_merged.vcf
Then you have a multi sample vcf file for all samples. Feel free to alter the parameters (e.g. 1000).

If you want to take additional steps to be more precise when comparing things (beta version):

4. run Sniffles again: sniffles -m reads.bam -v output_genotyped.vcf --Ivcf output_merged.vcf
This genotypes all the variations that you found previously. 
5. merge the so generated files again with:
ls *genotyped.vcf  > files_genotyped
 SURVIVOR merge 1000 0 1 0 0 0 output_genotyped_merged.vcf

Let me know if you have other questions. I will try to update the documentation again this week.
Cheers
Fritz

**Comment by wdecoster** [comment]
Hi Fritz,

Thanks for those suggestions, I'll repeat the SV calling and see how it goes.

Cheers,
Wouter

**Comment by fritzsedlazeck** [comment]
Thanks I will close this thread as it belongs more to the SURVIVOR repo. 
I have updated some of the method description:
https://github.com/fritzsedlazeck/SURVIVOR/wiki/Methods-and-Parameter

If you have other questions, please go to the SURVIVOR repo or just drop me an email.
Thanks
Fritz

**Comment by wdecoster** [comment]
Note to future me or someone else stumbling on this thread: --lvcf starts with an uppercase i, not with a lowercase L.
