### ISSUE TITLE
unexpected results of predicted_length

### ISSUE THREAD

**Issue by wdecoster** [fritzsedlazeck/Sniffles#62]
Hi,

Thanks for this great tool. As I also wrote in my other issue I'm working on PromethION genome sequencing of human genomes, and I'm looking at the calls made by sniffles (after ngmlr alignment).

Using the bedpe output I was looking at the predicted_length column and saw some (to me) unexpected things. I'm not sure if I misunderstood things, or those are bugs.

- TRA calls get a predicted_length (which I believe doesn't really make sense) and this predicted_length can be negative.

examples:
```
chr2                   133015077  133015077   chr16                  33961232    33961232   19899  -1  -  -  TRA  15   chr2                   133015074  chr16                  33961231   2062700135
chr2                   133015793  133015793   chrUn_gl000229         16147       16147      19900  -1  +  +  TRA  11   chr2                   133015461  chrUn_gl000229         16482      -1791466755
chr2                   133018560  133018560   chrUn_gl000229         14574       14574      19901  -1  -  -  TRA  14   chr2                   133018640  chrUn_gl000229         14487      -1791471929
chr2                   133120103  133120103   chr13                  19641640    19641640   19902  -1  +  -  TRA  10   chr2                   133120100  chr13                  19641640   1723221708
chr2                   162136184  162136184   chr21                  9827551     9827551    19903  -1  +  -  TRA  25   chr2                   162136202  chr21                  9827577    -1913137712
chr2                   209574735  209574735   chr8                   57984550    57984550   19904  -1  +  -  TRA  12   chr2                   209574718  chr8                   57984577   992528082
chr3                   73159986   73159986    chr17                  41465643    41465643   19905  -1  -  -  TRA  16   chr3                   73159983   chr17                  41465643   1977215018
```

- some (a small fraction) INS calls get a 'NA' length. How should I interpret these? I can't find an obvious difference with insertions which did get an integer length, except perhaps that these insertions have exactly the same start1/stop1/start2/stop2

examples:
```
chr1                   206332221  206332221  chr1                   206334221  206334221  1138   -1  +  -  INS  13  chr1                   206332221  chr1                   206334221  NA
chr1                   235192211  235192211  chr1                   235194211  235194211  1332   -1  +  -  INS  11  chr1                   235192211  chr1                   235194211  NA
chr2                   239801978  239801978  chr2                   239803978  239803978  2878   -1  +  -  INS  18  chr2                   239801978  chr2                   239803978  NA
chr7                   61917156   61917156   chr7                   61919156   61919156   7937   -1  +  -  INS  14  chr7                   61917157   chr7                   61919157   NA
chr7                   139379369  139379369  chr7                   139381369  139381369  8449   -1  +  -  INS  12  chr7                   139379377  chr7                   139381377  NA
chr8                   146301393  146301393  chr8                   146303393  146303393  9600   -1  +  -  INS  22  chr8                   146301393  chr8                   146303393  NA

```

- the (default) minimal length of SVs to be reported is 30, although the smallest number I saw was 31. But this might be an off-by-one error in my interpretation.

- While having a look at the insertion mentioned above I saw two odd calls, which look like "inter-contig insertions". I'm not sure what to make out of those:

```
chr17_gl000205_random  174588     174588     chr17_gl000206_random  1000       1000       16401  -1  +  -  INS  27  chr17_gl000205_random  174588     chr17_gl000206_random  1000       NA
chrUn_gl000220         161802     161802     chrUn_gl000221         1000       1000       19149  -1  +  -  INS  20  chrUn_gl000220         161802     chrUn_gl000221         1000       NA
```

- while having a look at the translocations I saw two odd calls in which the stop was negative and a very high number:
```
chr1                   0          -423637983  chr1                   14          0          19874  -1  -  +  TRA  116  chr1                   121484046  chr19                  27732336   -1727083608
chr1                   0          -423637983  chr1                   11          0          19878  -1  -  +  TRA  86   chr1                   121484047  chr19                  27736769   -1727079176
```

Cheers,
Wouter

**Comment by fritzsedlazeck** [comment]
Hi Wouter,
thanks for reaching out. 

1. TRA do have an undefined length. Thus, for now I am just putting in the distance along the genome.  Its not clear to me what else I should put in there...

2. When INS called with a length of NA it means that those lengths cannot be predicted. This happens if an INS is larger than all the reads can overlap in that region. Again I am not really aware of a standard to set the length for that.

3. Yes I like to do >X instead of >=X

4. I am currently ignoring the alternative contigs for my analysis. I will check again what is going on for those..

5. Ok this is strange. Did you use Sniffles with the bedbe output? Unfortunately I have to admit I havent tested that for a long time and there were some changes. Let me look into that. 

Thanks for highlighting these. I hope some answers are helpful.
Cheers
Fritz

**Comment by wdecoster** [comment]
Hi Fritz,

Thanks for the quick reply.

1. I would say that the length of a TRA would be NA

1. So that means there are no reads spanning the entire insertion? I would suggest a more explicit notation then such as "LONG"/"TOO_LONG"/... to make this more obvious.

1. Good to know!

1. I usually don't pay too much attention to these "extra" contigs, but this struck me as odd

1. Yes, sniffles was used with default settings and bedpe output. I find that easier to read than the vcf output...

Cheers,
Wouter

**Comment by fritzsedlazeck** [comment]
Hi Wouter,

1. Yes, NA is also not great as other programs complain if that value is not a number. I can fix it like this for the bedpe output... 

2. Yes there are. I have introduced a flag for them in the vcf output. I can update the bedpe output, but it does not give me that flexibility. Again sorry that I did not kept that up to date. 

@4+5: I agree. I will update the bedpe format and then this should be resolved. I will try to submit a fix this week. 

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Wouter,
I  just updated the bed file output and that should fix 4 and 5. Plus I also included Filter tag to indicate if a variant is PRECISE, IMPRECISE (depending on the agreement of the reads) and UNRESOLVED (e.g. if the length cannot be determined) .

**Comment by wdecoster** [comment]
Thanks a lot!
