### ISSUE TITLE
Left realignment

### ISSUE THREAD

**Issue by woodoo46** [fritzsedlazeck/Sniffles#63]
Hi,

I guess Sniffles does not do left realignment (or normalization) on calls in repeat region? For example, if a call is made in a simple repeat region, the call could be at anywhere in the region depending on how the aligner aligns the subreads. Sniffles does not do anything to adjust the call position at the beginning of the repeat region?

Thanks.

George

**Comment by fritzsedlazeck** [comment]
Hi George,
No it does not. For the sites I have seen it is often not necessary and also not really discussed at the moment.
 
What Sniffles and SURVIVOR do is to have a wobble parameter that can cluster together the signal among reads / or reported SVs. 

Let me know if that is needed. I would be interested to look at this. 
Thanks
Fritz

**Comment by woodoo46** [comment]
Nothing. I just want to confirm this information, as it is hard to compare the calls from other callers on these repeat regions. Thanks!
