### ISSUE TITLE
Internal filtering deletions

### ISSUE THREAD

**Issue by woodoo46** [fritzsedlazeck/Sniffles#64]
Hi,

Other than minimum number of supporting reads, is there any other rules for Sniffles internally filtering some potential deletion calls? For our case, from IGV, I saw a set of reads have a small deletion. The same bam file, PBSV calls a deletion in that region; while Sniffles does not? Any idea? 

Thanks.

George

**Comment by fritzsedlazeck** [comment]
Yes. sniffles has multipe parameters to check:
1. Coverage (-s ) is set at default at 10bp
2. min size of SVs: set to 30bp
3. Requirement that the concordance of reads are tight. disable with     --ignore_sd
4. There are also estimations of deletion and insertion rates which it tests on to avoid basecalling errors. 

Can you share a screen shot?

Cheers
Fritz

**Comment by woodoo46** [comment]
Sent to you gmail account.
