### ISSUE TITLE
Segmentation fault with --Ivcf argument

### ISSUE THREAD

**Issue by wdecoster** [fritzsedlazeck/Sniffles#65]
This seems similar to https://github.com/fritzsedlazeck/Sniffles/issues/31

sniffles runs, happily printing out progress, and at the end I get:
```
                [...........]
		# Processed reads: 6170000
		# Processed reads: 6180000
		# Processed reads: 6190000
	Switch Chr chrY
		# Processed reads: 6200000
Print:
Finalizing  ..
/bin/bash: line 1: 35826 Segmentation fault      (core dumped) sniffles --mapped_reads ngmlr_alignment/anon.bam --vcf sniffles_genotypes/anon.vcf --threads 12 --Ivcf sniffles_combined/calls.vcf 2> logs/sniffles_genotype/anon.log
```

No vcf is produced, but I can see a "anon.vcf_tmp_genotype" binary file in the output directory.

Unfortunately, I cannot share my input data. The alignment is done using ngmlr, the vcf for --Ivcf is made using Survivor after using sniffles without --Ivcf (which did not lead to this problem).

What can I do to try to debug this?

**Comment by fritzsedlazeck** [comment]
Can you check if you have the latest version? I know this always sounds stupid. I have made several smaller corrections over the code , but did not form a newer release. 

Also can you check for permissions and if that folder exists: "sniffles_genotypes"
Just trying to cross out the obvious. 


thanks
Fritz

**Comment by wdecoster** [comment]
I'm using sniffles version: 1.0.7 (from bioconda). That appears to be the latest version on bioconda, but may not include these corrections you made? I can install from GitHub and try again.

The target folder exists and permissions are okay.

**Comment by fritzsedlazeck** [comment]
Yes please. I made quite some corrections especially in that part. 
It should be easy to install. 

Let me know how it goes. 
Thansk
Fritz

**Comment by wdecoster** [comment]
Alright, I will keep you posted on the results.

Installation from source is indeed no problem - our old server with outdated OS has given me quite some headaches with other software.

**Comment by fritzsedlazeck** [comment]
If you have conda installed you can update your cmake version if it is too old. 
e.g.: conda install -c anaconda cmake

**Comment by wdecoster** [comment]
cmake appears to be fine for Sniffles, and the installation went fine without issues (unlike what I'm used to - thanks!)

**Comment by fritzsedlazeck** [comment]
customer service ;)

**Comment by wdecoster** [comment]
Absolutely great service.

While I'm rerunning "[the workflow](https://github.com/wdecoster/nano-snakemake/blob/master/SV-nanopore.smk)" I also changed the reference genome for ngmlr so it will take a while before I can report how things go with the latest version - so no need to stay awake ^_^

**Comment by wdecoster** [comment]
Oh well, that took even longer than expected, but now I can confirm that there is no longer a segmentation fault in this version. Perhaps it's worth creating another release to allow updating the bioconda version?

**Comment by fritzsedlazeck** [comment]
Yes. I wil soon make a new release and then update the bioconda version. Thanks for getting back to me. Let me know if there are other issues or suggestions. 
Thanks
Fritz
