### ISSUE TITLE
Support for reads shorter than 1kb?

### ISSUE THREAD

**Issue by MattBashton** [fritzsedlazeck/Sniffles#67]
I have a usage case were we have a PCR based assay for detecting a deletion with sequencing taking place on a MinION some of our sequenced products are less than 500bp this is down to the design of our primers and there proximity to the event, we can't easily get longer reads owing to the difficulty of producing PCR primers for tricky regions of the genome.

Would it be possibly to enable non integer values for the `-r` argument as currently I can't specify a minimum read length shorter than 1kb.  I appreciate this is somewhat an edge case.

We are also interested in a grater degree of granularity with respect to clustering so would it also be possible for `-d` to accommodate values less than 1kb?

**Comment by fritzsedlazeck** [comment]
Hi Matt,
this parameter is necessary for Pacbio to cope with a problem/bug during the adapter identification/basecalling that can cause a read to fold over and over itself.

I would try to set this to 0 and run it on ONT. Otherwise we can investigate. 

Cheers
Fritz

**Comment by MattBashton** [comment]
Hi Fritz, 

Thanks for the suggestion of setting `-r` to 0, was not aware that was a viable option, I'll investigate how this affects detection of the SV we're after.

**Comment by fritzsedlazeck** [comment]
Frankly, I have not tested it, but it should work. Let me know.
Thanks
Fritz

**Comment by MattBashton** [comment]
Hi Fritz,

I've been playing around with the `-r` and `-d` arguments, what was not immediately apparent, is that whist the documentation notes 1kb is default, I was unaware that the actual values you're specifying with these arguments are actually in base pairs, this only became apparent when I played with the options here and observed the results.  So perhaps you might want to consider replacing the value of 1kb with 1000 under the output of `--help` to make this clear to avoid confusion! :)

**Comment by fritzsedlazeck** [comment]
Hi Matt,
thanks for getting back to me. So did this help in your case?

I have recently changed that for version 1.0.8. Might be that the bioconda package is a bit behind. 
e.g.
`    -r <int>,  --min_seq_size <int>
        Discard read if non of its segment is larger then this. [2000]
`

Thanks
Fritz

**Comment by MattBashton** [comment]
Hi Fritz, 

Yes it's really helped in our case we're now able to accurately call the SVs we're after and control the degree of granularity of the clustering of nearby events into one.  I'm using version 1.08 direct from GitHub (circa Dec 20) so I'll clone it a fresh and recompile.  

Thanks again for the advice,

Matt

**Comment by fritzsedlazeck** [comment]
Cool. happy to help.
Cheers
Fritz

**Comment by MattBashton** [comment]
Just a note, it's `sniffles-debug` at least from the output of the build in my case which has the:

 `r <int>,  --min_seq_size <int>
        Discard read if non of its segment is larger then this. [2000]`

Sniffles is still reporting the older dialog:

`-r <int>,  --min_seq_size <int>
     Discard read if non of its segment is larger then this. Default: 2kb`

**Comment by fritzsedlazeck** [comment]
Ah strange. I will check that. 
Thanks
Fritz
