### ISSUE TITLE
Error in the second force SV calling for population

### ISSUE THREAD

**Issue by yunshew** [fritzsedlazeck/Sniffles#68]
I have got the SV for each sample firstly. But when I try to force call SVs across all the sample with --Ivcf, I got "Segmentation fault".

**Comment by fritzsedlazeck** [comment]
Can you please check:
1. The version
2. The input vcf file? Maybe if you can post a copy. 

Thanks
Fritz

**Comment by yunshew** [comment]
Yes, it worked perfectly when I update to the newest version. Thanks

**Comment by fritzsedlazeck** [comment]
Great.
Thanks
Frotz
