### ISSUE TITLE
vcf entry

### ISSUE THREAD

**Issue by matthewpendleton** [fritzsedlazeck/Sniffles#69]
The vcf header you have as an output instantiates a "ZMW"  info line, but your entries have been generalised to indicate "RNAME". VCF parsing/sorting/indexing software throw an error because they don't know what to do with this new RNAME field.

**Comment by fritzsedlazeck** [comment]
Sorry I will correct these. Those are depending on the data and parameters.
Thanks for pointing that out.
Fritz

**Comment by fritzsedlazeck** [comment]
So the header has the ZMW and if the parameter is selected the RNAME tag. Maybe I misunderstood you and you are saying they should not have that?

The RNAME should be defined only if the parameter is set. For the ZMW that I can only tell once I print out the reads... Is that the problem?

Thanks
Fritz

**Comment by matthewpendleton** [comment]
So, I happened upon this when I tried to sort with bcftools. When I replaced the ZMW line with:

##INFO=<ID=RNAMES,Number=.,Type=String,Description="Comma separated list of read names supporting SV.">

bcftools didn't object. I suppose that above line could simply be added to the header without replacing the ZMW line. 

Either way, there was no RNAMES definition in the header, but RNAMES fields were generated for all the entries. This happened for both a PacBio data set and an ONT data set.

**Comment by fritzsedlazeck** [comment]
Thanks. I am just confused because the RNAMES is included in the output in my test cases. Can you tell me the version you used?

Thanks
Fritz

**Comment by matthewpendleton** [comment]
The versions I'm using:
sniffles=1.0.7
ngmlr=0.2.6

**Comment by fritzsedlazeck** [comment]
Thanks. yep sorry in the 1.0.7 I had this problem with the header. 
Cheers
Fritz
