### ISSUE TITLE
Parallel output in vcf and bede ?

### ISSUE THREAD

**Issue by ebioman** [fritzsedlazeck/Sniffles#7]
Hello 
It seems that the parallel output in VCF and BEDE is not working . E.g. if I try:

```
sniffles -m file.sorted.bam -t 10 -v file.sniffles.vcf -b file.sniffles.bede
```

Only the VCF is generated. If I try on the other hand:

```
sniffles -m file.sorted.bam -t 10  -b file.sniffles.bede &
```

Everything works well. Is is possible to generate both outputs the same time?

Cheers

**Comment by fritzsedlazeck** [comment]
Hi,
frankly I never thought of someone trying to get both outputs. That will not work. You have to choose one or the other. I will fix this in the next version. 
Thanks for telling!
Fritz

**Comment by ebioman** [comment]
Hi
I just was testing some overlaps using *bedtools* and received often the error that the VCF was faulty as end coordinates were larger than start coordinates (translocations seem not to be correctly handled). Therefore I tried to look into the (in my opinion more comprehensive) BEDE file.
The BEDE format seems to be richer in information.

**Comment by fritzsedlazeck** [comment]
Oh I see. Yes for bedtools bedpe might be better.
I always try to give the same information in both formats, but bedpe is often easier to read for us humans :).
