### ISSUE TITLE
vcf UNRESOLVED definition missing

### ISSUE THREAD

**Issue by matthewpendleton** [fritzsedlazeck/Sniffles#70]
You have a Filter status "UNRESOLVED" that is not defined in your VCF header. (I'm using 1.0.8 now, wherein the RNAMES problem has been resolved)

Also, I realise I am in danger of being labeled a vcf file header pedant. :)

**Comment by fritzsedlazeck** [comment]
Sorry. I really appreciate that feedback.
I did not know that I had to define that as well since PASS is also not typically defined or other flags (from what I saw from Manta). 
Anyway, I just uploaded a fix in the code. Please give it a try. 
Thanks
Fritz

**Comment by matthewpendleton** [comment]
I actually made the exact change you did and recompiled. I can report that it does indeed work with bcftools sort.

**Comment by fritzsedlazeck** [comment]
Awesome thanks.
