### ISSUE TITLE
Unexpected svtype (TRA) in vcf.

### ISSUE THREAD

**Issue by vpolyakov88** [fritzsedlazeck/Sniffles#73]
Hello,

According to the header Sniffles follows the VCFv4.1 format. Unfortunately Sniffles seems not to follow the vcf specs, as I see in example file NA12878. I found undefined, in VCFv4.2 specification, svtype - TRA:

| #CHROM | POS    | ID            | REF | ALT   | QUAL | FILTER | INFO                                                                                                              | FORMAT            | ERR194147_.bwamem.ill.mapped.sort.bam.delly_noalts.vcf | ERR194147_.bwamem.ill.mapped.sort.bam.lumpy_noalts.vcf | ERR194147_.bwamem.ill.mapped.sort.bam.manta_noalts.vcf      |
|--------|--------|---------------|-----|-------|------|--------|-------------------------------------------------------------------------------------------------------------------|-------------------|--------------------------------------------------------|--------------------------------------------------------|-------------------------------------------------------------|
| 1      | 797316 | TRA0029399SUR | N   | \<TRA\> | .    | PASS   | SUPP=2;AVGLEN=100000;med_start=797265;med_stop=797265;SVTYPE=TRA;SVMETHOD=SURVIVORv2;CHR2=8;END=245650;STRANDS=++ | GT:LN:DR:ST:TY:CO | ./.:0:0,0:--:NaN:NaN                                   | ./.:551666:0,4:++:TRA:1_797316-8_245650                | 0/1:31:91,11:++:TRA,TRA:1_797265-8_245687,1_797265-8_245687 |

Translocations / breakends are described in the VCFv4.2 (paragraph 5.2) specification as follows:

| #CHROM | POS    | ID    | REF | ALT          | QUAL | FILTER | INFO       |
|--------|--------|-------|-----|--------------|------|--------|------------|
| 2      | 321681 | bnd_W | G   | G]17:198982] | 6    | PASS   | SVTYPE=BND |
| 2      | 321682 | bnd_V | T   | ]13:123456]T | 6    | PASS   | SVTYPE=BND |
| 13     | 123456 | bnd_U | C   | C[2:321682[  | 6    | PASS   | SVTYPE=BND |
| 13     | 123457 | bnd_X | A   | [17:198983[A | 6    | PASS   | SVTYPE=BND |
| 17     | 198982 | bnd_Y | A   | A]2:321681]  | 6    | PASS   | SVTYPE=BND |
| 17     | 198983 | bnd_Z | C   | [13:123457[C | 6    | PASS   | SVTYPE=BND |

It would be nice and very useful if Sniffles would output these variants according to the vcf specifications.

**Comment by vpolyakov88** [comment]
Thanks for an explanation, I try to run Sniffles with "--report_BND true".

**Comment by jiadong324** [comment]
Hello,

I want to use Sniffles call SVs from Blasr aligned BAM files, but I note that Sniffles requires BWA-MEM or NGMLR alignment. I am wondering if Blasr aligned BAM is able to run Sniffles.

Thanks!
