### ISSUE TITLE
0/0 call in VCF file

### ISSUE THREAD

**Issue by snashraf** [fritzsedlazeck/Sniffles#75]
Hi Fritz,

I generated VCF from all_reads.fa.giab_h003_ngmlr-0.2.3_mapped file . There are few 0/0 calls in my VCF as well. Are they because of low coverage region? 
1       821627  3       N       <INS>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=1;END=821629;ZMW=10;STD_quant_start=6.700746;STD_quant_stop=5.761944;Kurtosis_quant_start=-1.134627;Kurtosis_quant_stop=-0.896457;SVTYPE=INS;SUPTYPE=AL;SVLEN=31;STRANDS=+-;RE=13;AF=0.240741      GT:DR:DV        0/0:41:13

Thanks
Najeeb

**Comment by fritzsedlazeck** [comment]
0/0 indicates low frequency. In this case just 24%of the reads of this locations supports the event.
We do not filter these events out since they could still represent interesting variations.

i hope that answers the question
Cheers
Fritz
