### ISSUE TITLE
Annotation of translocations

### ISSUE THREAD

**Issue by Jquimcrz** [fritzsedlazeck/Sniffles#76]
Hi,

That might be quite a trivial question, but I'm facing some troubles understanding the annotation of the translocations. Below, you can see  one call for a translocation that is reported in the VCF.

S1_scaffold0001	80718	10754	N	<TRA>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=S1_scaffold0039;END=711463;ZMW=40;STD_quant_start=0.436436;STD_quant_stop=0.000000;Kurtosis_quant_start=16.794728;Kurtosis_quant_stop=7.648387;SVTYPE=TRA;SUPTYPE=SR;SVLEN=93457768;STRANDS=+-;RE=43	GT:DR:DV	./.:.:43

I'm getting confused with the meaning of CHR2, END and SVLEN in the case of translocations. As far as I understood, in the case shown above the first breakpoint of that translocation is in scaffold0001 position 80718. Second breakpoint, however, it is not located in the same scaffold (what indicates that is a translocation).

1) So, is CHR2 indicating in what contig is the DNA fragment translocated?
2) Then, what END means? Is that the position of the first breakpoint in the CHR2? (that would be the starting position of the translocation in the new location, wouldn't it?)
3) SVLEN is of about 93Mb in the case above, the genome size of the organism I study is of 150Mb aprox. so obviously it cannot mean that the length of the fragment that is being transolcated is that huge. What is the interpretation of that value?

Thank you very much in advance!

**Comment by fritzsedlazeck** [comment]
Sorry I thought I responded to that... 

So TRA/BND events are connections between two chromosomes.
Therefore, CHR2 is the second chromosome and END is the position on that chromosome. The first coordinate is in column 1 and 2 (ie. chr1 and start). 
SVLEN is meaningless, but needed to be specified.

I hope that answers it
Sorry for the delay.
Fritz
