### ISSUE TITLE
CMake error: NOT find OpenMP_C

### ISSUE THREAD

**Issue by Coaxecva** [fritzsedlazeck/Sniffles#78]
============================================================
-- No build type specified. Using 'release'
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindOpenMP.cmake:442 (find_package_handle_standard_args)
  CMakeLists.txt:27 (FIND_PACKAGE)

============================================================

I tried to install OpenMP via LLVM, but couldn't solve the issue. And I couldn't use "brew install clang-omp" for installing openMP:

Error: No available formula with the name "clang-omp" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by fritzsedlazeck** [comment]
Are you on a Mac or Linux machine?
Thanks
Fritz

**Comment by Coaxecva** [comment]
I am on Mac,

**Comment by fritzsedlazeck** [comment]
Can you try this: https://github.com/fritzsedlazeck/Sniffles/wiki#how-to-build-sniffles

I am using this command on my mac:
cmake -D CMAKE_C_COMPILER=/opt/local/bin/gcc-mp-4.7 -D CMAKE_CXX_COMPILER=/opt/local/bin/g++-mp-4.7 .. 


Alternatively you could use bioconda to install it automatically.
Let me know how it goes.
thanks
Fritz

**Comment by Coaxecva** [comment]
Do you have to install gcc-mp-4.7 and g++-mp-4.7 or can we just use the default gcc and g++?

When run:
conda install sniffles

I got this:
==================================================
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - sniffles

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by fritzsedlazeck** [comment]
No it does not require a certain gcc version. 
@Conda:
Add the channels:
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

then it should work:
conda install -c bioconda sniffles

**Comment by Coaxecva** [comment]
Can't build from the source with your option of cmake; However, it works with conda.
Thank you.

**Comment by fritzsedlazeck** [comment]
Np. Macs are sometimes a bit extra tricky...
Cheers
Fritz
