### ISSUE TITLE
Question on bwa options

### ISSUE THREAD

**Issue by yaohaobin** [fritzsedlazeck/Sniffles#8]
I am trying to use sniffle to detect sv on human genomes. The guide says "requires output from BWA-MEM with the optional SAM attributes enabled". What sam attributes are required? Thanks!

**Comment by fritzsedlazeck** [comment]
Hi
thanks for reaching out and trying Sniffles. 
I am using the best and second best alignment score fields to get a better estimate about the reliability of the read. (AS, XS) Furthermore I am using the tag which reports the secondary alignments (SA).

**Comment by jfass** [comment]
Those seem to be present by default in the current bwa-mem (bwa 0.7.13). Should we be running it any special way? Like, with any of these:

-a            output all alignments for SE or unpaired PE
-Y            use soft clipping for supplementary alignments
-M            mark shorter split hits as secondary

... ?

**Comment by fritzsedlazeck** [comment]
Yes the best thing is to run -M and  -x with pacbio or ont2d. 
You can also try our own mapper NGM-LR ;)

**Comment by jfass** [comment]
Thanks Fritz!
I actually did switch to NGM-LR, since Sniffles wasn't able to open my BAM files produced by bwa-mem ... maybe because of lack of the -M option.
With NGM-LR, I ran pretty much default (-t 10 -x pacbio -i 0.75 ... nothing that should affect SAM line content) and Sniffles ran fine.

**Comment by fritzsedlazeck** [comment]
Mhm strange. Was it sorted? Do you have the cmd output from Sniffles using bwa-mem?

The -M option just gives me the information which aligned segment is the primary and thus avoids that I process one read more then one time. 
Thanks for trying NGM-LR. Let me know If you have a hint on what when wrong with the bwa-mem results. I am testing Sniffles usually on both. 
Thanks
