### ISSUE TITLE
Key SEQ found in VariantContext field INFO at I:133074 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.

### ISSUE THREAD

**Issue by CristianRiccio** [fritzsedlazeck/Sniffles#80]
Hi,

Thanks for adding the option to return the SEQ in the VCF file. However, you don't define it in the header, so tools handling VCF files complain.

Key SEQ found in VariantContext field INFO at I:133074 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.

**Comment by fritzsedlazeck** [comment]
sorry, I just added it to the VCF header code. 
Please download, compile and test.
Thanks
Fritz

**Comment by CristianRiccio** [comment]
Is this sufficient:

`conda install --yes sniffles`

or do I need to clone https://github.com/fritzsedlazeck/Sniffles and follow some other installation procedure?

Cheers.

**Comment by fritzsedlazeck** [comment]
You would need to clone. I won't do a release for this mionor fix.

**Comment by CristianRiccio** [comment]
Hi,

I cloned with `git clone https://github.com/fritzsedlazeck/Sniffles output/software/Sniffles` and moved to the Sniffles folder. What should I do next to install it? I could not find any installation instructions in the folder.

**Comment by fritzsedlazeck** [comment]
Hi,
The instructions are on the wiki page:
https://github.com/fritzsedlazeck/Sniffles/wiki#how-to-build-sniffles

Best
Fritz

**Comment by CristianRiccio** [comment]
Hi,
I am sorry if my questions go beyond your tool. I am on mac and at the cmake step, I have errors. I don't have anything in /opt/local/bin/gcc-mp-4.7  nor /opt/local/bin/g++-mp-4.7. I have gcc here: /usr/bin/gcc (using the which command from Unix) but cannot find g++. I also could not find g++ in brew.

**Comment by fritzsedlazeck** [comment]
Do you have cmake and GCC installed? These tools need to be there. They are standard on Linux, but not necassary on Mac.
Cheers
Fritz

**Comment by CristianRiccio** [comment]
`cmake --version
cmake version 3.8.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).`

`gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

These two outputs suggest that they are installed.
