### ISSUE TITLE
Encountering Build issue with VCFPrinter

### ISSUE THREAD

**Issue by AndrewCarroll** [fritzsedlazeck/Sniffles#81]
I think a recent commit to VCFPrinter may break the build (5b5c7e788d3d450cd7154c47ad90d535858665a7). I am able to build from the immediately prior commit (85eb390cdfadf52c1bc4e1fbfafe4cab0da6f337)

/home/dnanexus/Sniffles/src/print/VCFPrinter.cpp: In member function ‘virtual void VCFPrinter::print_header()’:
/home/dnanexus/Sniffles/src/print/VCFPrinter.cpp:47:43: error: ‘SV’ was not declared in this scope
  if (Parameter::Instance()->print_seq && !SV->get_sequence().empty()) {
                                           ^
/home/dnanexus/Sniffles/src/print/VCFPrinter.cpp: In member function ‘virtual void VCFPrinter::print_body(Breakpoint*&, BamTools::RefVector)’:
/home/dnanexus/Sniffles/src/print/VCFPrinter.cpp:185:41: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
     fprintf(file, "%i", SV->get_length());
                                         ^
/home/dnanexus/Sniffles/src/print/VCFPrinter.cpp: In member function ‘virtual void VCFPrinter::print_body_recall(Breakpoint*&, BamTools::RefVector)’:
/home/dnanexus/Sniffles/src/print/VCFPrinter.cpp:280:39: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
   fprintf(file, "%i", SV->get_length());
                                       ^
make[2]: *** [src/CMakeFiles/sniffles.dir/print/VCFPrinter.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/sniffles.dir/all] Error 2
make: *** [all] Error 2

**Comment by fritzsedlazeck** [comment]
Hi Andrew,
thanks for pointing it out. I just fixed it. I should not try to fix something while transiting on an airport :)

Thanks
Fritz
