### ISSUE TITLE
Meaning of UNRESOLVABLE filter value

### ISSUE THREAD

**Issue by gbdias** [fritzsedlazeck/Sniffles#84]
Hi,

- I noticed that the current version of Sniffles (1.0.9) outputs two values in the filter field of the vcf file: `PASS` or `UNRESOLVABLE`.
- I could not find an explanation for the unresolvable value in the NGMLR/Sniffles paper or in the wiki. Could you give me any info on that? Should these variants be dismissed as artifacts?

Thanks

**Comment by fritzsedlazeck** [comment]
Hi,
sure sorry for that. 
So Unresolved are insertions where the reads agree that there is an insertion but they cannot resolve the length of an insertions.
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
I just added a comment:
https://github.com/fritzsedlazeck/Sniffles/wiki/Output#vcf-format

Thanks for pointing it out.
Fritz
