### ISSUE TITLE
--thread parameter

### ISSUE THREAD

**Issue by eldariont** [fritzsedlazeck/Sniffles#85]
Hi Fritz,

I observed a strange behavior when I use the --threads parameter of Sniffles on a small dataset of mine:

--threads 1: 15s user time / 16s wall clock time
--threads 3: 38s user time / 15s wall clock time
--threads 10: 125s user time / 16s wall clock time

I observe the same on a much larger dataset and wondered whether I'm doing something wrong. My machine has 128 cores and the jobs get 251% and 792% of CPU for 3 and 10 threads, respectively.

Best regards
David

**Comment by fritzsedlazeck** [comment]
Hi David, 

no everything is right. Sniffles is IO bound, which means that most time is consumed over reading in reads. This cannot be speed up. Also I did not put much time in the multithreading since it is running quite fast. 

Sorry for the confusion. 
Fritz

**Comment by eldariont** [comment]
Yes, I see. I had the same problem and Sniffles is indeed quite fast already.

Thanks for clearing this up :)
David
