### ISSUE TITLE
Help to summarize vcf output

### ISSUE THREAD

**Issue by ramcn** [fritzsedlazeck/Sniffles#88]
Hello,

I have generated VCF file using  ngmlr+sniffles was wanted to get the statistics of variants by size and type. (del, dups, inv, ins, tra). I needed some help to figure out the recommended tool and method. 

Below is the set of commands I am using.

1. ngmlr --match 3 --mismatch -7 --gap-decay 0.1 -t 28 -r hs37d5.fa -q rel5-guppy-0.3.0-chunk10k.fastq.gz  -o rel5-guppy-0.3.0-chunk10k.sam

2. sniffles --genotype --cluster -s 10 -d 1000 -m rel5-guppy-0.3.0-chunk10k.bam -v output.vcf

**Comment by fritzsedlazeck** [comment]
Hi,
Survivor is a tool that you could try out. Includes a summary method for SVs VCf files.
Best
Fritz

**Comment by ramcn** [comment]
Thanks Fritz for the quick reply. I had a look at Survivor wiki
<https://github.com/fritzsedlazeck/SURVIVOR/wiki>, but was not able to
figure out the right way to use it

I am trying to generate a summary as below. Could you please share some
more pointers about how to use survivor and the recommended bed file for
the rel5 nanopore dataset and generate below kind of summary.

Summary of variants by size and type
===================================================
Len Del Dup Inv INS TRA
30-50bp 14846 0 0 408 0
50-100bp 6784 1 4 1118 0
100-1000bp 4921 21 266 3191 0
1000-10000bp 546 26 47 92 0
10000+bp 50 39 6 0 43

**Comment by fritzsedlazeck** [comment]
Look at the readme.
Which bed file ?

**Comment by ramcn** [comment]
Hi Fritz,

I am trying to use the below command syntax on the vcf file generated by
sniffles.

SURVIVOR eval caller.vcf simulated.bed 10 eval_res

And was not sure which bed file and max BP to use.

Regards,
Ram

**Comment by ramcn** [comment]
Got it! Thanks. (somehow I missed stats command and was trying eval)
