### ISSUE TITLE
 VCF output - ZMW field

### ISSUE THREAD

**Issue by gbdias** [fritzsedlazeck/Sniffles#89]
Hi Fritz,

- After running ngmlr+sniffles with the exact same parameters in two samples, I noticed that the info field in the VCF file had variable lengths between these samples.
- The difference is caused by the presence/absence of the Zero Mode Waveguide field (**ZMW=**).
- I suppose this information comes from the original Pacbio read headers. Since one of my samples comes from NCBI-SRA, this information was lost and therefore the resulting VCF file is a bit shorter.

I do not have any particular need for the ZMW field, just thought I'd report this issue since other people might struggle if using downstream pipelines that expect a certain number of fields in the SV VCF. 

Sniffles has worked consistently and reproducibly on my datasets. Thanks for this amazing tool!

Guilherme Dias

**Comment by fritzsedlazeck** [comment]
Dear Guiherme,
thanks for reaching out. Yes if we cannot parse the ZMW ID out of the reads we will not provide the information. Therefore the tag is not included e.g. in ONT reads or in these SRA reads.  

Thanks so much for the last comment. Its always great not just to see bug reports ;)

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Ps. Feel free to tweet that. Its always great to get some advertisement ;). 
Just add me @sedlazeck
Thanks
Fritz
