### ISSUE TITLE
Coordinates of unresolved insertions

### ISSUE THREAD

**Issue by gbdias** [fritzsedlazeck/Sniffles#91]
Hi,

- I noticed that most unresolved INS (length 999999999), have start and end positions in 1bp intervals.
- However, some of these unresolved INS have coordinates in 0bp or even negative intervals (mostly -1 but some have other negative values).
- Can you provide any info on what is the standard behavior of Sniffles to deal with these INS?

Thanks!

**Comment by fritzsedlazeck** [comment]
Hi,
unresolved INS are insertions that are indicated by clipped reads, but where I cannot say something about the length. 

I did not sanity check the reported start - stop coordinates. They are derived from the underlying reads trying to make an estimate based on their clipping positions. Thus they can be greater than 0, but negative should not really happen. 

I hope that helps
Fritz

**Comment by gbdias** [comment]
Hi Fritz,

Thank you for the info.
- Based on what you said I now understand that the variation in read clipping would produce variable sized positive intervals.
- I still do not understand the negative ones though. My sample has >100 INS with negative intervals.
- Here are a few examples with -1 intervals:
```
chr2R	544847	1974	N	<INS>	.	UNRESOLVED	PRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr2R;END=544846;ZMW=18;STD_quant_start=0.707107;STD_quant_st
op=2.213594;Kurtosis_quant_start=3.759875;Kurtosis_quant_stop=-1.710007;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=999999999;STRANDS=+-;RE=20;AF=1	GT:DR:DV	1/1:0:20
chr2R	1349956	1990	N	<INS>	.	UNRESOLVED	PRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr2R;END=1349955;ZMW=30;STD_quant_start=0.840168;STD_quant_stop=1.111438;Kurtosis_quant_start=5.022497;Kurtosis_quant_stop=-1.233443;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=999999999;STRANDS=+-;RE=34;AF=0.971429	GT:DR:DV	1/1:1:34
chr3L	6975332	4304	N	<INS>	.	UNRESOLVED	PRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr3L;END=6975331;ZMW=32;STD_quant_start=0.816497;STD_quant_stop=1.471960;Kurtosis_quant_start=14.975543;Kurtosis_quant_stop=-1.863609;SVTYPE=INS;SUPTYPE=AL,SR;SVLEN=999999999;STRANDS=+-;RE=37;AF=0.711538	GT:DR:DV	0/1:15:37
```

- I can definitely get around this with some editing, just wanted to make sure that I could still use the start coordinates as the anchor points for INS positioning.

Thanks,
Guilherme

**Comment by fritzsedlazeck** [comment]
Hi Guilherme,
Yes that should not be. As I said I never checked these, but I will implement a check. 
You probably know that, but just to be safe. Ins are always just pointing at the coordinate where they should occure. Not indicating their lenght. That is reported over svlen.

Thanks for reaching out. I will take that into account for the next release.
Thanks
Fritz

**Comment by gbdias** [comment]
Hi Fritz,

Yes, thanks for clarifying that. I am only using the INS coordinates to `bedtools intersect` INS from different samples. And actually for this purpose 1bp intervals ar not very great either. I think I should probably give an arbitrary length for unresolved INS or maybe just exclude them from the analysis altogether.

Thank you for explaining this.
Best,
Guilherme

**Comment by fritzsedlazeck** [comment]
You could give SURVIVOR a try. Something that I implemented and more and more people are picking it up. It gives you more control over wobble parameters to merge 2 SVs. we are using it within samples and among samples. 
Cheers
Fritz
