### ISSUE TITLE
Dose Sniffles consider information of supplementary alignments(records) in a BAM file?

### ISSUE THREAD

**Issue by Archieyoung** [fritzsedlazeck/Sniffles#92]
Hi,
I am using Sniffles for SV calling on my Pacbio data. I am using picard to downsample the BAM file generated by NGMLR. But picard will keep the alignment marked as primary only. ["Reads marked as not primary alignments are all discarded. "](https://broadinstitute.github.io/picard/command-line-overview.html#PositionBasedDownsampleSam). Dose Sniffles using information of supplementary alignments(records) in a BAM file? Or Sniffles just use information of primary alignments?

**Comment by fritzsedlazeck** [comment]
Sniffles is using the supplement alignments, but only that information that is provided with the primary alignments.
Each Sam entry has a flag with information about it's supplement alignments.
Cheers
Fritz

**Comment by Archieyoung** [comment]
OK，that is great， thank you very much.

**Comment by fritzsedlazeck** [comment]
Hey,
longer reads make it algorithmically more challenging. It is true that the longer the read the more accurate you can place it, but this is just with respect of the region itself. 

Sniffles mainly uses the primary reads and then reads out the information from the supplementary flags per entry. without looking at the data you are running in the same issue. The IGV screenshot you show does not reassemble Pacbio or ONT data and thus Sniffles gets confused. It tries first to do a parameter estimation to see how many breaks, sequencing variation it can expect by chance from the giving data. Here I would assume that these reads are flagged as being too far outside of the spectrum. 

I hope that helps.
Cheers
Fritz
