### ISSUE TITLE
no distinction between equal to reference and missing when genotyping

### ISSUE THREAD

**Issue by webbchen** [fritzsedlazeck/Sniffles#94]
Dear Fritz
I've followed your wiki's instructions for genotyping a population of fungi with sniffles.  The aligned reads are Nanopore reads which have been aligned with bwa-mem.
I've called structural variants in all isolates, filtered the "precise" ones with > 20x coverage, merged them with survivor and used the resulting set for genotyping with sniffles again.
I've observed 2 odd things:
a) all calls are labelled as "imprecise".
b) there seems to be no distinction between "missing" and "equal to reference".  Anything that isn't called with majority of aligned reads equalling the variant is labelled " RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	0/0:0:0" , e.g. for some lines in this bit, which is from well inside a core chromosome:

`chr1.1	1365658	360	N	<INS>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=1365658;SVTYPE=INS;SUPTYPE=input;SVLEN=70;STRANDS=+-;SEQ=;RE=16;REF_strand=0,1;AF=0.941176	GT:DR:DV	1/1:1:16
chr1.1	1372852	363	N	<TRA>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=1427205;SVTYPE=TRA;SUPTYPE=input;SVLEN=100000;STRANDS=+-;SEQ=;RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	0/0:0:0
chr1.1	1375177	364	N	<INV>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=1375222;SVTYPE=INV;SUPTYPE=input;SVLEN=38;STRANDS=-+;SEQ=;RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	0/0:0:0
chr1.1	1375222	365	N	<INS>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=1375223;SVTYPE=INS;SUPTYPE=input;SVLEN=407;STRANDS=+-;SEQ=;RE=15;REF_strand=0,0;AF=1	GT:DR:DV	1/1:0:15
chr1.1	1379541	367	N	<DEL>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=4193890;SVTYPE=DEL;SUPTYPE=input;SVLEN=2814350;STRANDS=+-;SEQ=;RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	0/0:0:0
chr1.1	1406233	369	N	<DEL>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=1406951;SVTYPE=DEL;SUPTYPE=input;SVLEN=720;STRANDS=+-;SEQ=;RE=37;REF_strand=0,0;AF=1	GT:DR:DV	1/1:0:37
chr1.1	1431644	372	N	<DEL>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=1438819;SVTYPE=DEL;SUPTYPE=input;SVLEN=7186;STRANDS=+-;SEQ=;RE=31;REF_strand=0,0;AF=1	GT:DR:DV	1/1:0:31
chr1.1	1451503	375	N	<TRA>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr3.1;END=2440678;SVTYPE=TRA;SUPTYPE=input;SVLEN=100000;STRANDS=++;SEQ=;RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	0/0:0:0
chr1.1	1451504	376	N	<INS>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr1.1;END=1451504;SVTYPE=INS;SUPTYPE=input;SVLEN=1717;STRANDS=+-;SEQ=;RE=21;REF_strand=0,0;AF=1	GT:DR:DV	1/1:0:21
chr1.1	1457679	378	N	<TRA>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr20.1;END=377066;SVTYPE=TRA;SUPTYPE=input;SVLEN=100000;STRANDS=++;SEQ=;RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	0/0:0:0
chr1.1	1473689	380	N	<TRA>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=chr20.1;END=369177;SVTYPE=TRA;SUPTYPE=input;SVLEN=100000;STRANDS=+-;SEQ=;RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	0/0:0:0
` etc.
The fungus in question is prone to dropping accessory chromosomes and the odd bit from a core chromosome, but I don't believe that to be  always the case here as I've found no calls so far in several of my vcf-files which have been called as having coverage > 0 and being equal to the reference.

Many thanks and kind regards,

A. Webb

**Comment by fritzsedlazeck** [comment]
Hi Anne,
sorry for that and thanks for reaching out. Based on what you describes is that Sniffles for some reasons do not parse the reads in the second iteration. Therefore all entries have 0 support and thus are labeled as imprecise. This indeed is not what it is supposed to do. 

Can you maybe share
1. one of the initial calls (or just the first 100 lines) 
2. The first 100 lines of the input VCF for Sniffles forced calling. 

Thanks
Fritz

**Comment by webbchen** [comment]
Hi Fritz

Many thanks for your fast reply! I've grabbed the first 150 lines of the input file (snifflevars.vcf and the output resp. (the other one).
[sniffles_debug.zip](https://github.com/fritzsedlazeck/Sniffles/files/2328667/sniffles_debug.zip)
Thanks for looking into that!

Kind regards,
A.Webb

**Comment by fritzsedlazeck** [comment]
Dear Anne,
would it be possible to also share a part or a full bam file?
I was thinking that the problem is in reading in the CHR names, but as far as I can tell this works. 

I can open a dropbox folder or maybe you can open a ftp. Feel free to email me directly: fritz.sedlazeck@gmail.com
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
I also pushed just a check that should report if the chr names are for whatever reasons not corresponding from the input VCF vs. input bam file. 
Thanks
Fritz

**Comment by webbchen** [comment]
Dear Fritz

I genotyped with a sniffles version I downloaded last Friday and verified that it's the one in my path variable. Therefore it should have the bugfixes in them. In that context it'd be handy to have a --version parameter available, actually.
Bam file: Would a subset of a full bam file covering one chromosome helpful?

Regards,

A. Webb

**Comment by fritzsedlazeck** [comment]
Hi Anna,
I recently changed the interface and must have forgotten to include the version again. I just fixed that. 
Thx
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Anne, 
thanks again for reaching out. It was my misunderstanding and I just put up a fix for the genotype to be ./. when there is no coverage. 

Thanks
Fritz

**Comment by webbchen** [comment]
Hi Fritz
I'm getting the right output now, thanks for the repair, much appreciated!

A. Webb
