### ISSUE TITLE
BAM file and inversion

### ISSUE THREAD

**Issue by ptranvan** [fritzsedlazeck/Sniffles#95]
Hi,

I am trying to find concordances between the VCF output from Sniffles and the bam file used to run it.

I am studying inversions mainly. 

Do you have a figure of how does an inversion look like on a bam file (I am using Tablet to visualize a bam file).

Thanks for your help.

**Comment by ptranvan** [comment]
Thanks @fritzsedlazeck.

Do you have a light bam file that you can share with position of INV that I can look and make comparison with Tablet ?. 

Because my alignement is too heavy and it is not supported by IGV (not enough memory).

**Comment by fritzsedlazeck** [comment]
I will have to dig around a bit. I dont have one at hand right now (just switched laptops ) 

Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
Please see the answer in #87 . 
![image](https://user-images.githubusercontent.com/2081951/45515056-b83a9c80-b76c-11e8-96f6-ea8fb7963669.png)
