### ISSUE TITLE
Number of Copy Number Variants

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/Sniffles#96]
Hi Fritz,

Is there any possibility to get counts of specific tandem duplications? I m interested in a few genes where I find Tandem Duplications but I would like to know how many times that duplication has happed roughly.

Something like that (for : gene A ) : sample1 (2 copies), sample2 (3 copies) etc 

Best,
Mehmet

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
sorry this is currently not supported. You may be able to infer this by the number of supporting reads. 
Alternatively, you can use e.g. samtools depth to obtain the coverage level within the SV and outside of the event. Here a simple division of e.g. the median / mean value should do the trick. 

I will leave this open and consider it as feature request for a future version. 
Thanks
Fritz

**Comment by MehmetGoktay** [comment]
Thank you very much fritz!
