### ISSUE TITLE
colon absent after missing (./. call

### ISSUE THREAD

**Issue by webbchen** [fritzsedlazeck/Sniffles#97]
Dear Fritz

After the missing genotype call the colon is missing:

`ENA|CM001196|CM001196.1	51452	3	N	<TRA>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=ENA|CM001197|CM001197.1;END=2008373;SVTYPE=TRA;SUPTYPE=input;SVLEN=100000;STRANDS=--;SEQ=;RE=64;REF_strand=0,0;AF=1	GT:DR:DV	1/1:0:64
ENA|CM001196|CM001196.1	51453	4	N	<TRA>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=ENA|CM001203|CM001203.1;END=347810;SVTYPE=TRA;SUPTYPE=input;SVLEN=100000;STRANDS=--;SEQ=;RE=0;REF_strand=0,76;AF=0	GT:DR:DV	0/0:76:0
ENA|CM001196|CM001196.1	51454	5	N	<TRA>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.9;CHR2=ENA|CM001216|CM001216.1;END=318559;SVTYPE=TRA;SUPTYPE=input;SVLEN=100000;STRANDS=-+;SEQ=;RE=0;REF_strand=0,0;AF=-nan	GT:DR:DV	./.0:0
`
unlike in the 0/0 and 1/1 calls.
BCFtools took exception to that. ;-)

Kind regards,

A. Webb

**Comment by fritzsedlazeck** [comment]
Dear Anne,
thanks for letting me know. I just uploaded the fix.
thanks
Fritz
