### ISSUE TITLE
Global install

### ISSUE THREAD

**Issue by alnf** [fritzsedlazeck/Sniffles#99]
What should I expect from "sudo make install"? I'm not sure it's putting binaries somewhere in /usr/bin.

**Comment by fritzsedlazeck** [comment]
Where do you need this?
This can be answered over Google and is unrelated to this project.

**Comment by fritzsedlazeck** [comment]
You can easily make a ln -s sniffles /usr/bin/sniffles 
from the binary directory.

**Comment by alnf** [comment]
Yes, I understand it. I just didn't know if the particular behavior is expected or smth went wrong. I looked in the make config, I believe it only copies libz.a, so I will make a soft link. Thanks.

**Comment by fritzsedlazeck** [comment]
Np. Sorry if my first answer was a bit direct. See you soon
Fritz

**Comment by alnf** [comment]
I was not very explicit as well. See you!
